//This File Is Auto Generated By Process Control
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cysharp.Threading.Tasks;
using System.Threading;
using System;

public enum EGamePhase
{
	Default,
	BattleStart,
	PlayerStart,
}

public class JoeyGameControl : YViewControl
{
	private JoeyGameView m_View;
	public static JoeyGameControl Instance { get; private set; }

	private EGamePhase m_CurrentGamePhase = EGamePhase.Default;
	private EGamePhase m_LastGamePhase = EGamePhase.Default;
	private UIGamePhaseControl m_GamePhaseControl;
	private DataJoeyPlayer m_DataJoeyPlayer;
	private UIPauseControl m_PauseControl;
	private Dictionary<int, MonoBehaviourPool<Transform>> VFXPoolDict = new Dictionary<int, MonoBehaviourPool<Transform>>();
	private Dictionary<Transform, CancellationTokenSource> CancelTokenDict = new Dictionary<Transform, CancellationTokenSource>();
	private SingleDelayAction m_GlobalDelayAction = new SingleDelayAction();

	public static EResType GetResType()
	{
		return EResType.None;
	}

	protected override void OnInit()
	{
		Instance = this;
		base.OnInit();
		m_View = CreateView<JoeyGameView>();
		m_DataJoeyPlayer = DataSystem.Instance.GetDataJoeyPlayer();
		DataSystem.Instance.SaveDataJoeyPlayer();
	}

	void Start()
	{
		m_GamePhaseControl = Asset.OpenUI<UIGamePhaseControl>();
		if (m_DataJoeyPlayer.currentLevel <= 0)
		{
			m_DataJoeyPlayer.currentLevel = 1;
		}
		SetGamePhase(EGamePhase.BattleStart);
	}

	void Update()
	{
		CheckButtonInput();

		if (m_CurrentGamePhase != m_LastGamePhase)
		{
			m_LastGamePhase = m_CurrentGamePhase;
			switch (m_CurrentGamePhase)
			{
				case EGamePhase.Default:
					Default();
					break;
				case EGamePhase.BattleStart:
					BattleStart();
					break;
				case EGamePhase.PlayerStart:
					PlayerStart();
					break;
				default:
					break;
			}
		}
	}

	void CheckButtonInput()
	{
		if (Input.GetKeyDown(KeyCode.Escape))
		{
			if (m_PauseControl == null)
			{
				m_PauseControl = Asset.OpenUI<UIPauseControl>();
			}
			else
			{
				bool isActive = m_PauseControl.gameObject.activeSelf;
				m_PauseControl.gameObject.SetActive(!isActive);
			}
		}
	}

	private void Default()
	{
	}

	private void BattleStart()
	{
		SetLevelData();
		SetGamePhase(EGamePhase.PlayerStart);
	}

	private void PlayerStart()
	{
	}

	public void SetGamePhase(EGamePhase gamePhase)
	{
		m_CurrentGamePhase = gamePhase;
	}

	public void SetLevelData()
	{
		GData.Instance.LoadAll();
		StartCoroutine(SFX.PlayAudioCoroutine(audioPath: "Audio/SFX/shuffle_cards", startTime: 0f));

		if (m_DataJoeyPlayer.currentLevel >= 1 && m_DataJoeyPlayer.currentLevel <= 5)
		{
			var playerData = GData.Instance.GetTutorialPlayerData(m_DataJoeyPlayer.currentLevel);
			m_DataJoeyPlayer.lastPlayerHealth = m_DataJoeyPlayer.playerHealth;
			m_DataJoeyPlayer.playerHealth = playerData.Value.health;
			m_DataJoeyPlayer.playerMaxHealth = playerData.Value.maxHealth;
		}

		m_GamePhaseControl.SetData();

		List<List<string>> cardIdListEnv = CardDraw.Instance.DrawCardEnv(m_DataJoeyPlayer.currentLevel);
		for (int i = 0; i < cardIdListEnv.Count; i++)
		{
			List<string> cardIdList = cardIdListEnv[i];
			m_GamePhaseControl.AddEnvCardList(cardIds: cardIdList, index: i);
		}

		Dictionary<string, List<string>> equipmentDeck;
		if (m_DataJoeyPlayer.currentLevel >= 1 && m_DataJoeyPlayer.currentLevel <= 5)
		{
			equipmentDeck = GData.Instance.GetTutorialEquipmentDeck(m_DataJoeyPlayer.currentLevel);
		}
		else
		{
			equipmentDeck = GData.Instance.DeckItemDict;
		}

		foreach (var kv in equipmentDeck)
		{
			string cardTypeStr = kv.Key;
			List<string> cardIds = kv.Value;

			ECardType cardType = (ECardType)System.Enum.Parse(typeof(ECardType), cardTypeStr);
			Debug.Log("cardType: " + cardTypeStr + " " + cardType.ToString());

			m_GamePhaseControl.AddCardList(cardType: cardType, cardIds: cardIds);
		}
	}

	public async void LoadNextLevel()
	{
		m_DataJoeyPlayer.currentLevel++;

		m_GamePhaseControl.ClearCardQueue();
		await UniTask.WaitForSeconds(0.5f);


		SetGamePhase(EGamePhase.BattleStart);
	}

	public void EnterBattleStart()
	{
		SetGamePhase(EGamePhase.BattleStart);
	}

	public void ReturnToMainMenu()
	{
		SceneLoader.Instance.LoadScene("Start");
	}

	public void SetData()
	{
		;
	}

	public void PlayVFX(EVFXName vfxName, Transform parent, float delayTime)
	{
		int key = (int)vfxName;

		if (!VFXPoolDict.TryGetValue(key, out MonoBehaviourPool<Transform> pool))
		{
			string prefabPath = "VFX/" + vfxName.ToString();
			GameObject prefab = Resources.Load<GameObject>(prefabPath);
			pool = new MonoBehaviourPool<Transform>(() =>
			{
				GameObject instance = Instantiate(prefab, parent);
				instance.gameObject.name = vfxName.ToString();

				return instance.transform;
			});
			VFXPoolDict[key] = pool;
		}

		Transform vfxTransform = pool.Get();
		vfxTransform.SetParent(parent);
		vfxTransform.localPosition = Vector3.zero;

		var cts = new CancellationTokenSource();
		CancelTokenDict[vfxTransform] = cts;

		DelayHideVFX(vfxTransform, delayTime, cts, key).Forget();
	}

	public Transform GetVFX(EVFXName vfxName, Transform parent)
	{
		int key = (int)vfxName;

		if (!VFXPoolDict.TryGetValue(key, out MonoBehaviourPool<Transform> pool))
		{
			string prefabPath = "VFX/" + vfxName.ToString();
			GameObject prefab = Resources.Load<GameObject>(prefabPath);
			pool = new MonoBehaviourPool<Transform>(() =>
			{
				GameObject instance = Instantiate(prefab, parent);
				instance.gameObject.name = vfxName.ToString();
				instance.transform.localPosition = Vector3.zero;

				return instance.transform;
			});
			VFXPoolDict[key] = pool;
		}

		Transform vfxTransform = pool.Get();
		vfxTransform.SetParent(parent);
		vfxTransform.localPosition = Vector3.zero;
		vfxTransform.gameObject.SetActive(true);

		return vfxTransform;
	}

	public void PlayEnvVFX(EVFXName vfxName, int envIndex, float delayTime)
	{
		if (m_GamePhaseControl != null)
		{
			Transform effectRoot = m_GamePhaseControl.GetEffectRoot(envIndex);
			if (effectRoot != null)
			{
				PlayVFX(vfxName, effectRoot, delayTime);
			}
		}
	}

	public void ReturnVFXPool(Transform vfxTransform, int envIndex)
	{
		Transform effectRoot = m_GamePhaseControl.GetEffectRoot(envIndex);
		vfxTransform.SetParent(effectRoot);
		vfxTransform.localPosition = Vector3.zero;
	}

	private async UniTaskVoid DelayHideVFX(Transform vfxTransform, float delayTime, CancellationTokenSource cts, int key)
	{
		await UniTask.WaitForSeconds(delayTime, cancellationToken: cts.Token);
		if (vfxTransform != null && vfxTransform.gameObject != null && VFXPoolDict.TryGetValue(key, out MonoBehaviourPool<Transform> pool))
		{
			pool.Release(vfxTransform);
		}
		if (CancelTokenDict.TryGetValue(vfxTransform, out CancellationTokenSource tokenSource))
		{
			CancelTokenDict.Remove(vfxTransform);
			tokenSource.Dispose();
		}
	}

	public void AddGlobalDelayCall(Action action, float delayTime)
	{
		m_GlobalDelayAction.AddDelayCall(action, delayTime);
	}

	public bool HasBagCard(ECardType cardType)
	{
		if (m_GamePhaseControl != null)
		{
			return m_GamePhaseControl.HasBagCard(cardType);
		}
		return false;
	}

	protected override void OnReturn()
	{
		m_GlobalDelayAction.Cancel();

		foreach (var kvp in CancelTokenDict)
		{
			var cts = kvp.Value;
			if (cts != null && !cts.IsCancellationRequested)
			{
				cts.Cancel();
				cts.Dispose();
			}
		}
		CancelTokenDict.Clear();
		base.OnReturn();
	}
}