//This File Is Auto Generated By Process View
using UnityEngine;

public class JoeyGameView : YBaseView
{
	public Transform LevelRoot;
	public AssetSystem Asset;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		LevelRoot = viewItemList[0].Target;
		Asset = viewItemList[1].Target.GetComponent<AssetSystem>();
	}
}