//This File Is Auto Generated By Process Control
using UnityEngine;

public class JoeyTestGameControl : YViewControl
{
    private JoeyGameView m_View;
    public int TestNew = 0;
    public bool isNew = false;
    public static JoeyTestGameControl Instance { get; private set; }
    private DataJoeyPlayer m_PlayerData;

    protected override void OnInit()
    {
        Instance = this;
        base.OnInit();
        m_View = CreateView<JoeyGameView>();
        m_PlayerData = DataSystem.Instance.GetDataJoeyPlayer();
    }

    void Start()
    {
        InitTestCards();
        if (TestNew == 1)
        {
            UIBuildNewControl buildNewControl = m_View.Asset.OpenUI<UIBuildNewControl>();
            buildNewControl.SetShopData();
        }
        else
        {
            UILobbyControl buildControl = m_View.Asset.OpenUI<UILobbyControl>();
            buildControl.SetData();
        }
    }

    void InitTestCards()
    {
        GData.Instance.LoadAll();

        m_PlayerData.SelfCardDict.Clear();
        m_PlayerData.EquipedAttackList.Clear();
        m_PlayerData.EquipedDefenceList.Clear();
        m_PlayerData.EquipedItemList.Clear();
        m_PlayerData.EquipedSkillList.Clear();
        m_PlayerData.MaxEquipedAttackNum = 3;
        m_PlayerData.MaxEquipedDefenceNum = 3;
        m_PlayerData.MaxEquipedItemNum = 3;
        m_PlayerData.MaxEquipedSkillNum = 3;

        Card card1 = AddTestCard("1001");
        Card card2 = AddTestCard("1002");
        Card card3 = AddTestCard("1003");

        Card card4 = AddTestCard("2001");
        Card card5 = AddTestCard("2002");

        Card card6 = AddTestCard("3001");
        Card card7 = AddTestCard("4001");

        m_PlayerData.EquipedAttackList.Add(card1.UniqueId);
        m_PlayerData.EquipedDefenceList.Add(card4.UniqueId);
        m_PlayerData.EquipedItemList.Add(card6.UniqueId);
        m_PlayerData.EquipedSkillList.Add(card7.UniqueId);

        m_PlayerData.TempAttackList.Add(card2.UniqueId);
        m_PlayerData.TempAttackList.Add(card3.UniqueId);
        m_PlayerData.TempDefenceList.Add(card5.UniqueId);

        //m_PlayerData.UniqueIdGen = 5000;
        Debug.Log("InitTestCards");
    }

    Card AddTestCard(string cardId)
    {
        Card card = DataSystem.Instance.CreateCard(cardId);
        m_PlayerData.AddSelfCardDictData(card);
        return card;
    }
}

