//This File Is Auto Generated By Process Control
using UnityEngine;

public class JoeyStartGameControl : YViewControl
{
	private JoeyGameView m_View;
	public static JoeyStartGameControl Instance { get; private set; }

	public static EResType GetResType()
	{
		return EResType.None;
	}

	protected override void OnInit()
	{
		Instance = this;
		base.OnInit();
		m_View = CreateView<JoeyGameView>();
	}

	void Start()
	{
		UIStartControl startControl = Asset.OpenUI<UIStartControl>();
		startControl.SetData();
	}
}

