//This File Is Auto Generated By Process Control
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cysharp.Threading.Tasks;
using System.Threading;
using System;

public enum EGamePhase
{
	Default,
	BattleStart,
	PlayerStart,
}

public enum EGameMode
{
	Battle,
	Guide,
	Debug,
}

public class JoeyGameControl : YViewControl
{
	private JoeyGameView m_View;
	public static JoeyGameControl Instance { get; private set; }

	private EGamePhase m_CurrentGamePhase = EGamePhase.Default;
	private EGamePhase m_LastGamePhase = EGamePhase.Default;
	private UIGamePhaseControl m_GamePhaseControl;
	private DataJoeyPlayer m_DataJoeyPlayer;
	private UIPauseControl m_PauseControl;
	private UIGameOverControl m_GameOverControl;
	private Dictionary<int, MonoBehaviourPool<Transform>> VFXPoolDict = new Dictionary<int, MonoBehaviourPool<Transform>>();
	private Dictionary<Transform, CancellationTokenSource> CancelTokenDict = new Dictionary<Transform, CancellationTokenSource>();
	private SingleDelayAction m_GlobalDelayAction = new SingleDelayAction();
	private bool m_IsLobbyEnter = false;

	public EGameMode GameMode = EGameMode.Battle;
	public string[] DebugEnvCardIds = new string[0];
	public string[] DebugBagCardIds = new string[0];
	public int DebugLevelId = 1;

	public static EResType GetResType()
	{
		return EResType.None;
	}

	protected override void OnInit()
	{
		Instance = this;
		base.OnInit();
		m_View = CreateView<JoeyGameView>();
		m_DataJoeyPlayer = DataSystem.Instance.GetDataJoeyPlayer();
		DataSystem.Instance.SaveDataJoeyPlayer();
		GData.Instance.LoadAll();

	}

	void Start()
	{
		m_GamePhaseControl = Asset.OpenUI<UIGamePhaseControl>();
		if (m_DataJoeyPlayer.currentLevel <= 0)
		{
			m_DataJoeyPlayer.currentLevel = 1;
		}
		Asset.OpenUI<UILobbyControl>();
		SetGamePhase(EGamePhase.Default);
	}

	void Update()
	{
		CheckButtonInput();

		if (m_CurrentGamePhase != m_LastGamePhase)
		{
			m_LastGamePhase = m_CurrentGamePhase;
			switch (m_CurrentGamePhase)
			{
				case EGamePhase.Default:
					Default();
					break;
				case EGamePhase.BattleStart:
					BattleStart();
					break;
				case EGamePhase.PlayerStart:
					PlayerStart();
					break;
				default:
					break;
			}
		}
	}

	void CheckButtonInput()
	{
		if (Input.GetKeyDown(KeyCode.Escape))
		{
			if (m_GameOverControl != null && m_GameOverControl.gameObject.activeSelf)
			{
				return;
			}
			if (m_PauseControl == null)
			{
				m_PauseControl = Asset.OpenUI<UIPauseControl>();
			}
			else
			{
				bool isActive = m_PauseControl.gameObject.activeSelf;
				m_PauseControl.gameObject.SetActive(!isActive);
			}
		}
	}

	private void Default()
	{
	}

	private void BattleStart()
	{
		SetLevelData();
		SetGamePhase(EGamePhase.PlayerStart);
	}

	private void PlayerStart()
	{
	}

	public void SetGamePhase(EGamePhase gamePhase)
	{
		m_CurrentGamePhase = gamePhase;
	}

	public void SetLevelData()
	{
		StartCoroutine(SFX.PlayAudioCoroutine(audioPath: "Audio/SFX/shuffle_cards", startTime: 0f));

		int levelId = GameMode == EGameMode.Debug ? DebugLevelId : m_DataJoeyPlayer.currentLevel;

		if (GameMode == EGameMode.Battle && m_DataJoeyPlayer.SelfCardDict.Count == 0)
		{
			m_DataJoeyPlayer.StageId = 0;
			RoguelikeCharacter characterData = GData.Instance.GetRoguelikeCharacter();
			if (characterData != null)
			{
				DataSystem.Instance.InitRoguelikeCharacterData(characterData);
			}
			levelId = m_DataJoeyPlayer.currentLevel;
		}
		if (GameMode != EGameMode.Battle)
		{
			(int health, int maxHealth)? playerData = GData.Instance.GetTutorialPlayerData(levelId);
			if (playerData.HasValue)
			{
				m_DataJoeyPlayer.lastPlayerHealth = m_DataJoeyPlayer.playerHealth;
				m_DataJoeyPlayer.playerHealth = playerData.Value.health;
				m_DataJoeyPlayer.playerMaxHealth = playerData.Value.maxHealth;
			}
			else
			{
				Debug.LogError($"无法获取关卡 {levelId} 的玩家数据！");
			}
		}


		if (GameMode == EGameMode.Battle)
		{
			if (m_IsLobbyEnter == false)
			{
				m_GamePhaseControl.SetDataWithoutBagClear();

			}
			else
			{
				m_GamePhaseControl.SetData();
			}
		}
		else
		{
			m_GamePhaseControl.SetData();
		}

		if (m_IsLobbyEnter)
		{
			m_GamePhaseControl.AddSelfCardList();
			m_IsLobbyEnter = false;
		}

		List<List<string>> cardIdListEnv = CardDraw.Instance.DrawCardEnv(levelId);
		for (int i = 0; i < cardIdListEnv.Count; i++)
		{
			List<string> cardIdList = cardIdListEnv[i];
			m_GamePhaseControl.AddEnvCardList(cardIds: cardIdList, index: i);
		}

		if (GameMode != EGameMode.Battle)
		{
			Dictionary<string, List<string>> equipmentDeck;

			equipmentDeck = GData.Instance.GetTutorialEquipmentDeck(levelId);


			foreach (var kv in equipmentDeck)
			{
				string cardTypeStr = kv.Key;
				List<string> cardIds = kv.Value;

				ECardType cardType = (ECardType)System.Enum.Parse(typeof(ECardType), cardTypeStr);
				Debug.Log("cardType: " + cardTypeStr + " " + cardType.ToString());

				m_GamePhaseControl.AddCardList(cardType: cardType, cardIds: cardIds);
			}
		}

		if (GameMode == EGameMode.Debug)
		{
			if (DebugEnvCardIds != null && DebugEnvCardIds.Length > 0)
			{
				List<string> debugEnvCardList = new List<string>(DebugEnvCardIds);
				m_GamePhaseControl.AddEnvCardList(cardIds: debugEnvCardList, index: 0);
			}

			if (DebugBagCardIds != null && DebugBagCardIds.Length > 0)
			{
				Dictionary<ECardType, List<string>> bagCardDict = new Dictionary<ECardType, List<string>>();
				for (int i = 0; i < DebugBagCardIds.Length; i++)
				{
					string cardId = DebugBagCardIds[i];
					if (string.IsNullOrEmpty(cardId))
					{
						continue;
					}
					Card card = m_GamePhaseControl.CreateCard(cardId);
					ECardType cardType = card.GetCardType();
					if (!bagCardDict.ContainsKey(cardType))
					{
						bagCardDict[cardType] = new List<string>();
					}
					bagCardDict[cardType].Add(cardId);
				}

				foreach (var kv in bagCardDict)
				{
					m_GamePhaseControl.AddCardList(cardType: kv.Key, cardIds: kv.Value);
				}
			}
		}
	}

	public async void LoadNextLevel(bool IsLobbyEnter = false)
	{
		m_IsLobbyEnter = IsLobbyEnter;
		if (GameMode != EGameMode.Guide)
		{
			DataSystem.Instance.LoadNextRoguelikeStage();
		}
		else
		{
			m_DataJoeyPlayer.currentLevel++;
			DataSystem.Instance.SaveDataJoeyPlayer();
		}
		m_GamePhaseControl.ClearCardQueue();
		await UniTask.WaitForSeconds(0.5f);


		SetGamePhase(EGamePhase.BattleStart);
	}

	public void EnterBattleStart()
	{
		SetGamePhase(EGamePhase.BattleStart);
	}

	public void EndGamePhase()
	{
		if (GameMode == EGameMode.Battle)
		{
			RoguelikeStage currentStage = GData.Instance.GetRoguelikeStage(m_DataJoeyPlayer.StageId);
			if (currentStage != null && currentStage.type == EStageType.boss)
			{
				UISelectControl selectControl = Asset.OpenUI<UISelectControl>();
				selectControl.SetRelicData();
				selectControl.OnSelectComplete = () => Asset.OpenUI<UILobbyControl>();
			}
			else
			{
				UISelectControl selectControl = Asset.OpenUI<UISelectControl>();
				selectControl.SetData();
				selectControl.OnSelectComplete = () => LoadNextLevel();
			}

			m_DataJoeyPlayer.StageId++;
		}
		else
		{
			LoadNextLevel();
		}
	}

	public void ReturnToMainMenu()
	{
		SceneLoader.Instance.LoadScene("Start");
	}

	public void SetData()
	{
		;
	}

	public void PlayVFX(EVFXName vfxName, Transform parent, float delayTime)
	{
		int key = (int)vfxName;

		if (!VFXPoolDict.TryGetValue(key, out MonoBehaviourPool<Transform> pool))
		{
			string prefabPath = "VFX/" + vfxName.ToString();
			GameObject prefab = Resources.Load<GameObject>(prefabPath);
			pool = new MonoBehaviourPool<Transform>(() =>
			{
				GameObject instance = Instantiate(prefab, parent);
				instance.gameObject.name = vfxName.ToString();

				return instance.transform;
			});
			VFXPoolDict[key] = pool;
		}

		Transform vfxTransform = pool.Get();
		vfxTransform.SetParent(parent);
		vfxTransform.localPosition = Vector3.zero;

		var cts = new CancellationTokenSource();
		CancelTokenDict[vfxTransform] = cts;

		DelayHideVFX(vfxTransform, delayTime, cts, key).Forget();
	}

	public Transform GetVFX(EVFXName vfxName, Transform parent)
	{
		int key = (int)vfxName;

		if (!VFXPoolDict.TryGetValue(key, out MonoBehaviourPool<Transform> pool))
		{
			string prefabPath = "VFX/" + vfxName.ToString();
			GameObject prefab = Resources.Load<GameObject>(prefabPath);
			pool = new MonoBehaviourPool<Transform>(() =>
			{
				GameObject instance = Instantiate(prefab, parent);
				instance.gameObject.name = vfxName.ToString();
				instance.transform.localPosition = Vector3.zero;

				return instance.transform;
			});
			VFXPoolDict[key] = pool;
		}

		Transform vfxTransform = pool.Get();
		vfxTransform.SetParent(parent);
		vfxTransform.localPosition = Vector3.zero;
		vfxTransform.gameObject.SetActive(true);

		return vfxTransform;
	}

	public void PlayEnvVFX(EVFXName vfxName, int envIndex, float delayTime)
	{
		if (m_GamePhaseControl != null)
		{
			Transform effectRoot = m_GamePhaseControl.GetEffectRoot(envIndex);
			if (effectRoot != null)
			{
				PlayVFX(vfxName, effectRoot, delayTime);
			}
		}
	}

	public void ReturnVFXPool(Transform vfxTransform, int envIndex)
	{
		vfxTransform.gameObject.SetActive(false);
		Transform effectRoot = m_GamePhaseControl.GetEffectRoot(envIndex);
		vfxTransform.SetParent(effectRoot);
		vfxTransform.localPosition = Vector3.zero;
	}

	private async UniTaskVoid DelayHideVFX(Transform vfxTransform, float delayTime, CancellationTokenSource cts, int key)
	{
		await UniTask.WaitForSeconds(delayTime, cancellationToken: cts.Token);
		if (vfxTransform != null && vfxTransform.gameObject != null && VFXPoolDict.TryGetValue(key, out MonoBehaviourPool<Transform> pool))
		{
			pool.Release(vfxTransform);
		}
		if (CancelTokenDict.TryGetValue(vfxTransform, out CancellationTokenSource tokenSource))
		{
			CancelTokenDict.Remove(vfxTransform);
			tokenSource.Dispose();
		}
	}

	public void AddGlobalDelayCall(Action action, float delayTime)
	{
		m_GlobalDelayAction.AddDelayCall(action, delayTime);
	}

	public bool HasBagCard(ECardType cardType)
	{
		if (m_GamePhaseControl != null)
		{
			return m_GamePhaseControl.HasBagCard(cardType);
		}
		return false;
	}

	public bool IsPlayerHalfHealth()
	{
		return m_DataJoeyPlayer.playerHealth < m_DataJoeyPlayer.playerMaxHealth / 2;
	}

	public void ShowGameOver()
	{
		if (m_GameOverControl == null)
		{
			m_GameOverControl = Asset.OpenUI<UIGameOverControl>();
		}
		else
		{
			m_GameOverControl.gameObject.SetActive(true);
		}
	}


	protected override void OnReturn()
	{
		m_GlobalDelayAction.Cancel();

		foreach (var kvp in CancelTokenDict)
		{
			var cts = kvp.Value;
			if (cts != null && !cts.IsCancellationRequested)
			{
				cts.Cancel();
				cts.Dispose();
			}
		}
		CancelTokenDict.Clear();
		base.OnReturn();
	}
}