//This File Is Auto Generated By Process Control
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cysharp.Threading.Tasks;

public enum EGamePhase
{
	Default,
	battleStart,
	playerStart,
	playerAction,
	playerEnd,
	enemyStart,
	enemyAction,
	enemyEnd,
	battleEnd
}

public class JoeyGameControl : YViewControl
{
	private JoeyGameView m_View;
	public static JoeyGameControl Instance { get; private set; }

	private EGamePhase m_CurrentGamePhase = EGamePhase.Default;
	private EGamePhase m_LastGamePhase = EGamePhase.Default;
	private UIGamePhaseControl m_GamePhaseControl;
	private DataJoeyPlayer m_DataJoeyPlayer;
	private UIPauseControl m_PauseControl;

	public static EResType GetResType()
	{
		return EResType.None;
	}

	protected override void OnInit()
	{
		Instance = this;
		base.OnInit();
		m_View = CreateView<JoeyGameView>();
		m_DataJoeyPlayer = DataSystem.Instance.GetDataJoeyPlayer();
		DataSystem.Instance.SaveDataJoeyPlayer();
	}

	void Start()
	{
		m_GamePhaseControl = Asset.OpenUI<UIGamePhaseControl>();
		if (m_DataJoeyPlayer.currentLevel <= 0)
		{
			m_DataJoeyPlayer.currentLevel = 1;
		}
		SetGamePhase(EGamePhase.battleStart);
	}

	void Update()
	{
		CheckButtonInput();

		if (m_CurrentGamePhase != m_LastGamePhase)
		{
			m_LastGamePhase = m_CurrentGamePhase;
			switch (m_CurrentGamePhase)
			{
				case EGamePhase.Default:
					Default();
					break;
				case EGamePhase.battleStart:
					BattleStart();
					break;
				case EGamePhase.playerStart:
					PlayerStart();
					break;
				case EGamePhase.playerAction:
					PlayerAction();
					break;
				case EGamePhase.playerEnd:
					PlayerEnd();
					break;
				case EGamePhase.enemyStart:
					EnemyStart();
					break;
				case EGamePhase.enemyAction:
					EnemyAction();
					break;
				case EGamePhase.enemyEnd:
					EnemyEnd();
					break;
				case EGamePhase.battleEnd:
					BattleEnd();
					break;
				default:
					break;
			}
		}
	}

	void CheckButtonInput()
	{
		if (Input.GetKeyDown(KeyCode.Escape))
		{
			if (m_PauseControl == null)
			{
				m_PauseControl = Asset.OpenUI<UIPauseControl>();
			}
			else
			{
				bool isActive = m_PauseControl.gameObject.activeSelf;
				m_PauseControl.gameObject.SetActive(!isActive);
			}
		}
	}

	private void Default()
	{
	}

	private void BattleStart()
	{
		SetLevelData();
		SetGamePhase(EGamePhase.playerStart);
	}

	private void PlayerStart()
	{
		SetGamePhase(EGamePhase.playerAction);
	}

	private void PlayerAction()
	{
	}

	private void PlayerEnd()
	{
		SetGamePhase(EGamePhase.enemyStart);
	}

	private void EnemyStart()
	{
		SetGamePhase(EGamePhase.enemyAction);
	}

	private void EnemyAction()
	{
		SetGamePhase(EGamePhase.enemyEnd);
	}

	private void EnemyEnd()
	{
		SetGamePhase(EGamePhase.battleEnd);
	}

	private void BattleEnd()
	{
		SetGamePhase(EGamePhase.Default);
	}

	public void SetGamePhase(EGamePhase gamePhase)
	{
		m_CurrentGamePhase = gamePhase;
	}

	public void SetLevelData()
	{
		GData.Instance.LoadAll();
		StartCoroutine(SFX.PlayAudioCoroutine(audioPath: "Audio/SFX/shuffle_cards", startTime: 0f));

		if (m_DataJoeyPlayer.currentLevel >= 1 && m_DataJoeyPlayer.currentLevel <= 5)
		{
			var playerData = GData.Instance.GetTutorialPlayerData(m_DataJoeyPlayer.currentLevel);
			m_DataJoeyPlayer.lastPlayerHealth = m_DataJoeyPlayer.playerHealth;
			m_DataJoeyPlayer.playerHealth = playerData.Value.health;
			m_DataJoeyPlayer.playerMaxHealth = playerData.Value.maxHealth;
		}

		m_GamePhaseControl.SetData();

		List<List<string>> cardIdListEnv = CardDraw.Instance.DrawCardEnv(m_DataJoeyPlayer.currentLevel);
		for (int i = 0; i < cardIdListEnv.Count; i++)
		{
			List<string> cardIdList = cardIdListEnv[i];
			m_GamePhaseControl.AddEnvCardList(cardIds: cardIdList, index: i);
		}

		Dictionary<string, List<string>> equipmentDeck;
		if (m_DataJoeyPlayer.currentLevel >= 1 && m_DataJoeyPlayer.currentLevel <= 5)
		{
			equipmentDeck = GData.Instance.GetTutorialEquipmentDeck(m_DataJoeyPlayer.currentLevel);
		}
		else
		{
			equipmentDeck = GData.Instance.DeckItemDict;
		}

		foreach (var kv in equipmentDeck)
		{
			string cardTypeStr = kv.Key;
			List<string> cardIds = kv.Value;

			ECardType cardType = (ECardType)System.Enum.Parse(typeof(ECardType), cardTypeStr);
			Debug.Log("cardType: " + cardTypeStr + " " + cardType.ToString());

			m_GamePhaseControl.AddCardList(cardType: cardType, cardIds: cardIds);
		}
	}

	public async void LoadNextLevel()
	{
		m_DataJoeyPlayer.currentLevel++;
		await UniTask.WaitForSeconds(0.5f);
		SetGamePhase(EGamePhase.battleStart);
	}

	public void EnterBattleStart()
	{
		SetGamePhase(EGamePhase.battleStart);
	}

	public void ReturnToMainMenu()
	{
		SceneLoader.Instance.LoadScene("Start");
	}

	public void SetData()
	{
		;
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}