//This File Is Auto Generated By Process Control
using UnityEngine;

public class SoundEffectControl : YViewControl
{
	private SoundEffectView m_View;

	public static EResType GetResType()
	{
		return EResType.SoundEffect;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<SoundEffectView>();
	}

	public void SetData()
	{
		//m_View.Audio.spatialBlend = 0f;
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}

	public void PlayOneShot(AudioClip clip)
	{
		m_View.Audio.Stop();
		m_View.Audio.clip = clip;
		m_View.Audio.Play();
	}

	public void PlayOneShot(string soundName)
	{
		AudioClip clip = Resources.Load<AudioClip>("Audio/" + soundName);
		PlayOneShot(clip);
	}
}