//This File Is Auto Generated By Process View
using UnityEngine;

public class SoundEffectView : YBaseView
{
	public AudioSource Audio;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		Audio = viewItemList[0].Target.GetComponent<AudioSource>();
	}
}