//This File Is Auto Generated By Process Control
using UnityEngine;

public class UIAchievementControl : YViewControl
{
	private UIAchievementView m_View;

	public static EResType GetResType()
	{
		return EResType.UIAchievement;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIAchievementView>();
		m_View.BtnSkip.onClick.AddListener(OnBtnSkipClick);
	}

	void OnBtnSkipClick()
	{
		gameObject.SetActive(false);
	}

	public void SetData()
	{
		gameObject.SetActive(true);
		DataAchievement achievement = DataSystem.Instance.GetDataAchievement();

		m_View.TxtFistNum.text = achievement.FistUseNum.ToString();
		m_View.TxtCoinNum.text = achievement.MaxCoinNum.ToString();
		m_View.TxtDamage.text = achievement.MaxDamageNum.ToString();
		m_View.TxtDeadNum.text = achievement.DeadNum.ToString();
		m_View.TxtPassTime.text = achievement.PassGameNum.ToString();
		m_View.TxtMonsterNum.text = achievement.KillMonsterNum.ToString();
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}