//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIAchievementView : YBaseView
{
	public Button BtnSkip;
	public Text TxtFistNum;
	public Text TxtCoinNum;
	public Text TxtDamage;
	public Text TxtDeadNum;
	public Text TxtPassTime;
	public Text TxtMonsterNum;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		BtnSkip = viewItemList[0].Target.GetComponent<Button>();
		TxtFistNum = viewItemList[1].Target.GetComponent<Text>();
		TxtCoinNum = viewItemList[2].Target.GetComponent<Text>();
		TxtDamage = viewItemList[3].Target.GetComponent<Text>();
		TxtDeadNum = viewItemList[4].Target.GetComponent<Text>();
		TxtPassTime = viewItemList[5].Target.GetComponent<Text>();
		TxtMonsterNum = viewItemList[6].Target.GetComponent<Text>();
	}
}