//This File Is Auto Generated By Process Control
using UnityEngine;
using UnityEngine.UI;
using System;

public class UIBtnControl : YViewControl
{
	private UIBtnView m_View;
	private Action<int> m_OnClick;
	private int m_Index;

	public static EResType GetResType()
	{
		return EResType.UIBtn;
	}

	protected override void OnInit()
	{
		base.OnInit();
		// 此方法通常由 AssetSystem 调用，但在我们手动管理时可能不会自动调用
		// 我们将在 InitWithTransform 中手动处理
	}

	public void InitWithTransform(Transform trs, int index, Action<int> onClick)
	{
		m_Index = index;
		m_OnClick = onClick;
		
		m_View = new UIBtnView();
		m_View.OnInit(trs);

		// Fallback logic
		if (m_View.UIBtn == null)
		{
			m_View.UIBtn = trs.GetComponent<Button>();
		}
		if (m_View.Sold == null)
		{
			Transform soldTr = trs.Find("Sold");
			if (soldTr != null) m_View.Sold = soldTr.gameObject;
		}

		if (m_View.UIBtn != null)
		{
			// Ensure disabled buttons are still visible (grayed out)
			var colors = m_View.UIBtn.colors;
			// Set disabled color to gray with full alpha if it was transparent
			if (colors.disabledColor.a < 0.1f)
			{
				colors.disabledColor = new Color(0.5f, 0.5f, 0.5f, 1f);
				m_View.UIBtn.colors = colors;
			}
			
			m_View.UIBtn.onClick.RemoveAllListeners();
			m_View.UIBtn.onClick.AddListener(OnUIBtnClick);
		}
	}

	void OnUIBtnClick()
	{
		m_OnClick?.Invoke(m_Index);
	}

	public void SetData(bool isUnlocked, bool interactable)
	{
		if (m_View == null) return;

		if (isUnlocked)
		{
			if (m_View.Sold != null) m_View.Sold.SetActive(true);
			if (m_View.UIBtn != null) m_View.UIBtn.interactable = false;
		}
		else
		{
			if (m_View.Sold != null) m_View.Sold.SetActive(false);
			if (m_View.UIBtn != null) m_View.UIBtn.interactable = interactable;
		}
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}