//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIBtnView : YBaseView
{
	public Button UIBtn;
	public Image Lock;
	public Image Start;
	public Image IconStart;
	public Image UnLock;
	public Image IconUnlock;
	public Image IconLock;
	public Image Unknow;
	public Image IconUnknow;
	public RectTransform Rotation;
	public Image LineLock;
	public Image LineUnlock;
	public Text Text;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		UIBtn = viewItemList[0].Target.GetComponent<Button>();
		Lock = viewItemList[1].Target.GetComponent<Image>();
		Start = viewItemList[2].Target.GetComponent<Image>();
		IconStart = viewItemList[3].Target.GetComponent<Image>();
		UnLock = viewItemList[4].Target.GetComponent<Image>();
		IconUnlock = viewItemList[5].Target.GetComponent<Image>();
		IconLock = viewItemList[6].Target.GetComponent<Image>();
		Unknow = viewItemList[7].Target.GetComponent<Image>();
		IconUnknow = viewItemList[8].Target.GetComponent<Image>();
		Rotation = viewItemList[9].Target.GetComponent<RectTransform>();
		LineLock = viewItemList[10].Target.GetComponent<Image>();
		LineUnlock = viewItemList[11].Target.GetComponent<Image>();
		Text = viewItemList[12].Target.GetComponent<Text>();
	}
}