//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIBtnView : YBaseView
{
	public Button UIBtn;
	public GameObject Sold;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		UIBtn = viewItemList[0].Target.GetComponent<Button>();
		Sold = viewItemList[1].Target.gameObject;
	}
}