//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;


public class UIBuildControl : YViewControl
{
	private UIBuildView m_View;
	private List<UIBuildCardControl> EquipedCardList = new List<UIBuildCardControl>();
	private RectTransform[] m_EquipedItemArray;
	private RectTransform[] m_TempItemArray;
	private Image[] m_EmptyArray;
	private Button[] m_ButtonArray;
	private DataJoeyPlayer m_PlayerData;
	public ECardType m_CurrentCardType;


	public static EResType GetResType()
	{
		return EResType.UIBuild;
	}


	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIBuildView>();
		//m_View.BtnClose.onClick.AddListener(OnBtnCloseClick);
		m_View.BtnAttack.onClick.AddListener(OnBtnAttackClick);
		m_View.BtnDefence.onClick.AddListener(OnBtnDefenceClick);
		m_View.BtnItem.onClick.AddListener(OnBtnItemClick);
		m_View.BtnSkill.onClick.AddListener(OnBtnSkillClick);
		m_EquipedItemArray = new RectTransform[] { m_View.Item1, m_View.Item2, m_View.Item3, m_View.Item4, m_View.Item5, m_View.Item6 };
		m_TempItemArray = new RectTransform[] { m_View.Item7, m_View.Item8, m_View.Item9 };
		m_EmptyArray = new Image[] { m_View.Empty1, m_View.Empty2, m_View.Empty3, m_View.Empty4, m_View.Empty5, m_View.Empty6 };
		m_ButtonArray = new Button[m_EmptyArray.Length];
		for (int i = 0; i < m_EmptyArray.Length; i++)
		{
			Button button = m_EmptyArray[i].gameObject.GetComponent<Button>();
			if (button == null)
			{
				button = m_EmptyArray[i].gameObject.AddComponent<Button>();
			}
			int index = i;
			button.onClick.AddListener(() => OnEmptyButtonClick(index));
			m_ButtonArray[i] = button;
		}
		m_PlayerData = DataSystem.Instance.GetDataJoeyPlayer();
		m_CurrentCardType = ECardType.other;
	}



	void OnBtnCloseClick()
	{
		Close();
	}

	void OnBtnAttackClick()
	{
		RefreshEquipedCardsByType(ECardType.attack);
	}
	void OnBtnDefenceClick()
	{
		RefreshEquipedCardsByType(ECardType.defence);
	}
	void OnBtnItemClick()
	{
		RefreshEquipedCardsByType(ECardType.item);
	}
	void OnBtnSkillClick()
	{
		RefreshEquipedCardsByType(ECardType.skill);
	}




	public void RefreshEquipedCardsByType(ECardType cardType, bool isSaveBuild = true)
	{
		if (isSaveBuild && m_CurrentCardType != ECardType.other)
		{
			SaveBuild(m_CurrentCardType);
		}
		m_CurrentCardType = cardType;

		m_View.SelectAttack.SetActive(false);
		m_View.SelectDefence.SetActive(false);
		m_View.SelectItem.SetActive(false);
		m_View.SelectSkill.SetActive(false);

		List<int> equipList = null;
		List<int> tempList = null;
		int maxEquipedNum = 0;
		switch (cardType)
		{
			case ECardType.attack:
				equipList = m_PlayerData.EquipedAttackList;
				tempList = m_PlayerData.TempAttackList;
				maxEquipedNum = m_PlayerData.MaxEquipedAttackNum;
				m_View.SelectAttack.SetActive(true);
				break;
			case ECardType.defence:
				equipList = m_PlayerData.EquipedDefenceList;
				tempList = m_PlayerData.TempDefenceList;
				maxEquipedNum = m_PlayerData.MaxEquipedDefenceNum;
				m_View.SelectDefence.SetActive(true);
				break;
			case ECardType.item:
				equipList = m_PlayerData.EquipedItemList;
				tempList = m_PlayerData.TempItemList;
				maxEquipedNum = m_PlayerData.MaxEquipedItemNum;
				m_View.SelectItem.SetActive(true);
				break;
			case ECardType.skill:
				equipList = m_PlayerData.EquipedSkillList;
				tempList = m_PlayerData.TempSkillList;
				maxEquipedNum = m_PlayerData.MaxEquipedSkillNum;
				m_View.SelectSkill.SetActive(true);
				break;
			default:
				return;
		}

		for (int i = 0; i < m_EquipedItemArray.Length; i++)
		{
			if (i >= maxEquipedNum)
			{
				m_EquipedItemArray[i].gameObject.SetActive(false);
				if (i < m_EmptyArray.Length)
				{
					m_EmptyArray[i].color = Color.grey;
				}
				if (i < m_ButtonArray.Length && m_ButtonArray[i] != null)
				{
					m_ButtonArray[i].enabled = true;
				}
			}
			else
			{
				m_EquipedItemArray[i].gameObject.SetActive(true);
				if (i < m_EmptyArray.Length)
				{
					m_EmptyArray[i].color = Color.white;
				}
				if (i < m_ButtonArray.Length && m_ButtonArray[i] != null)
				{
					m_ButtonArray[i].enabled = false;
				}
			}

			UIBuildCardControl cardControl = EquipedCardList[i];
			if (i < equipList.Count)
			{
				int cardUniqueId = equipList[i];
				Card card = m_PlayerData.GetSelfCardDictData(cardUniqueId);
				if (card != null)
				{
					cardControl.gameObject.SetActive(true);
					cardControl.SetData(card);
				}
				else
				{
					cardControl.gameObject.SetActive(false);
				}
			}
			else
			{
				cardControl.gameObject.SetActive(false);
			}
		}

		for (int i = 0; i < m_TempItemArray.Length; i++)
		{
			int equipIndex = m_EquipedItemArray.Length + i;
			UIBuildCardControl cardControl = EquipedCardList[equipIndex];
			if (i < tempList.Count)
			{
				int cardUniqueId = tempList[i];
				Card card = m_PlayerData.GetSelfCardDictData(cardUniqueId);
				if (card != null)
				{
					cardControl.gameObject.SetActive(true);
					cardControl.SetData(card);
				}
				else
				{
					cardControl.gameObject.SetActive(false);
				}
			}
			else
			{
				cardControl.gameObject.SetActive(false);
			}
		}
	}

	private void OnEmptyButtonClick(int index)
	{
		if (index < 0 || index >= m_EquipedItemArray.Length)
		{
			return;
		}

		int cardTypeInt = (int)m_CurrentCardType;
		EquipmentUnlock equipmentUnlock = GData.Instance.GetEquipmentUnlock(cardTypeInt, index);
		if (equipmentUnlock == null)
		{
			return;
		}

		if (m_PlayerData.Coin < equipmentUnlock.cost)
		{
			return;
		}

		DataSystem.Instance.AddCoin(-equipmentUnlock.cost);

		switch (m_CurrentCardType)
		{
			case ECardType.attack:
				m_PlayerData.MaxEquipedAttackNum++;
				break;
			case ECardType.defence:
				m_PlayerData.MaxEquipedDefenceNum++;
				break;
			case ECardType.item:
				m_PlayerData.MaxEquipedItemNum++;
				break;
			case ECardType.skill:
				m_PlayerData.MaxEquipedSkillNum++;
				break;
			default:
				return;
		}

		m_EquipedItemArray[index].gameObject.SetActive(true);
		if (index < m_EmptyArray.Length)
		{
			m_EmptyArray[index].color = Color.white;
		}
		if (index < m_ButtonArray.Length && m_ButtonArray[index] != null)
		{
			m_ButtonArray[index].enabled = false;
		}

		DataSystem.Instance.SaveDataJoeyPlayer();
	}

	public void SetShopData()
	{
		for (int i = 0; i < m_EquipedItemArray.Length; i++)
		{
			UIBuildCardControl cardControl = Asset.OpenUI<UIBuildCardControl>(m_View.Content);
			RectTransform itemRect = m_EquipedItemArray[i];
			cardControl.CacheTrans.localPosition = itemRect.localPosition;
			cardControl.CacheTrans.localScale = Vector3.one * 0.6f;
			cardControl.EquipIndex = i;
			cardControl.OnDragEndHandler = OnCardDragEnd;
			EquipedCardList.Add(cardControl);
		}

		for (int i = 0; i < m_TempItemArray.Length; i++)
		{
			UIBuildCardControl cardControl = Asset.OpenUI<UIBuildCardControl>(m_View.Content);
			RectTransform itemRect = m_TempItemArray[i];
			cardControl.CacheTrans.localPosition = itemRect.localPosition;
			cardControl.CacheTrans.localScale = Vector3.one * 0.6f;
			cardControl.EquipIndex = m_EquipedItemArray.Length + i;
			cardControl.OnDragEndHandler = OnCardDragEnd;
			EquipedCardList.Add(cardControl);
		}

		RefreshEquipedCardsByType(ECardType.attack);
	}

	public void SaveBuild(ECardType cardType)
	{
		List<int> equipList = null;
		List<int> tempList = null;
		switch (cardType)
		{
			case ECardType.attack:
				equipList = m_PlayerData.EquipedAttackList;
				tempList = m_PlayerData.TempAttackList;
				break;
			case ECardType.defence:
				equipList = m_PlayerData.EquipedDefenceList;
				tempList = m_PlayerData.TempDefenceList;
				break;
			case ECardType.item:
				equipList = m_PlayerData.EquipedItemList;
				tempList = m_PlayerData.TempItemList;
				break;
			case ECardType.skill:
				equipList = m_PlayerData.EquipedSkillList;
				tempList = m_PlayerData.TempSkillList;
				break;
			default:
				return;
		}

		equipList.Clear();
		tempList.Clear();

		for (int i = 0; i < EquipedCardList.Count; i++)
		{
			UIBuildCardControl cardControl = EquipedCardList[i];
			if (cardControl.gameObject.activeSelf && cardControl.CardData != null)
			{
				ECardType cardControlType = cardControl.CardData.GetCardType();
				if (cardControlType == cardType)
				{
					if (cardControl.EquipIndex < 6)
					{
						equipList.Add(cardControl.CardData.UniqueId);
					}
					else
					{
						tempList.Add(cardControl.CardData.UniqueId);
					}
				}
			}
		}
	}

	private void OnCardDragEnd(UIBuildCardControl draggedCard, PointerEventData eventData)
	{
		if (CheckCardInDeleteArea(draggedCard, eventData))
		{
			DeleteCard(draggedCard);
			return;
		}

		for (int i = 0; i < m_EquipedItemArray.Length; i++)
		{
			if (m_EquipedItemArray[i] != null && m_EquipedItemArray[i].gameObject.activeSelf)
			{
				RectTransform itemRect = m_EquipedItemArray[i];
				if (RectTransformUtility.RectangleContainsScreenPoint(
					itemRect,
					eventData.position,
					eventData.pressEventCamera))
				{
					OnCardDragEndSwap(draggedCard, i);
					return;
				}
			}
		}

		for (int i = 0; i < m_TempItemArray.Length; i++)
		{
			if (m_TempItemArray[i] != null)
			{
				RectTransform itemRect = m_TempItemArray[i];
				if (RectTransformUtility.RectangleContainsScreenPoint(
					itemRect,
					eventData.position,
					eventData.pressEventCamera))
				{
					OnCardDragEndSwap(draggedCard, m_EquipedItemArray.Length + i);
					return;
				}
			}
		}

		RectTransform rectTransform = draggedCard.CacheTrans as RectTransform;
		if (rectTransform != null)
		{
			if (draggedCard.EquipIndex < m_EquipedItemArray.Length)
			{
				rectTransform.localPosition = m_EquipedItemArray[draggedCard.EquipIndex].localPosition;
			}
			else
			{
				int tempIndex = draggedCard.EquipIndex - m_EquipedItemArray.Length;
				rectTransform.localPosition = m_TempItemArray[tempIndex].localPosition;
			}
		}
	}

	private bool CheckCardInDeleteArea(UIBuildCardControl draggedCard, PointerEventData eventData)
	{
		if (m_View.BtnDelete == null || draggedCard.CardData == null)
		{
			return false;
		}

		RectTransform deleteRect = m_View.BtnDelete.rectTransform;
		RectTransform cardRect = draggedCard.CacheTrans as RectTransform;

		if (deleteRect == null || cardRect == null)
		{
			return false;
		}

		Vector3[] deleteCorners = new Vector3[4];
		Vector3[] cardCorners = new Vector3[4];
		deleteRect.GetWorldCorners(deleteCorners);
		cardRect.GetWorldCorners(cardCorners);

		Rect deleteRectWorld = new Rect(deleteCorners[0].x, deleteCorners[0].y,
			deleteCorners[2].x - deleteCorners[0].x,
			deleteCorners[2].y - deleteCorners[0].y);

		Rect cardRectWorld = new Rect(cardCorners[0].x, cardCorners[0].y,
			cardCorners[2].x - cardCorners[0].x,
			cardCorners[2].y - cardCorners[0].y);

		return deleteRectWorld.Overlaps(cardRectWorld);
	}

	private void DeleteCard(UIBuildCardControl draggedCard)
	{
		if (draggedCard.CardData == null)
		{
			return;
		}

		Card card = draggedCard.CardData;

		// Cannot sell curse cards (1025: Pain Blade, 2016: Pain Shield)
		if (card.id == "1025" || card.id == "2016")
		{
			Debug.Log("诅咒卡牌无法出售！");
			RectTransform curseCardRect = draggedCard.CacheTrans as RectTransform;
			if (curseCardRect != null)
			{
				if (draggedCard.EquipIndex < m_EquipedItemArray.Length)
				{
					curseCardRect.localPosition = m_EquipedItemArray[draggedCard.EquipIndex].localPosition;
				}
				else
				{
					int tempIndex = draggedCard.EquipIndex - m_EquipedItemArray.Length;
					curseCardRect.localPosition = m_TempItemArray[tempIndex].localPosition;
				}
			}
			return;
		}

		ECardType cardType = card.GetCardType();
		int uniqueId = card.UniqueId;

		List<int> equipList = null;
		List<int> tempList = null;

		switch (cardType)
		{
			case ECardType.attack:
				equipList = m_PlayerData.EquipedAttackList;
				tempList = m_PlayerData.TempAttackList;
				break;
			case ECardType.defence:
				equipList = m_PlayerData.EquipedDefenceList;
				tempList = m_PlayerData.TempDefenceList;
				break;
			case ECardType.item:
				equipList = m_PlayerData.EquipedItemList;
				tempList = m_PlayerData.TempItemList;
				break;
			case ECardType.skill:
				equipList = m_PlayerData.EquipedSkillList;
				tempList = m_PlayerData.TempSkillList;
				break;
			default:
				return;
		}

		equipList.Remove(uniqueId);
		tempList.Remove(uniqueId);
		m_PlayerData.RemoveSelfCardDictData(uniqueId);

		int halfPrice = Mathf.RoundToInt(card.price / 2f);
		DataSystem.Instance.AddCoin(halfPrice);

		DataSystem.Instance.SaveDataJoeyPlayer();

		RectTransform rectTransform = draggedCard.CacheTrans as RectTransform;
		if (rectTransform != null)
		{
			if (draggedCard.EquipIndex < m_EquipedItemArray.Length)
			{
				rectTransform.localPosition = m_EquipedItemArray[draggedCard.EquipIndex].localPosition;
			}
			else
			{
				int tempIndex = draggedCard.EquipIndex - m_EquipedItemArray.Length;
				rectTransform.localPosition = m_TempItemArray[tempIndex].localPosition;
			}
		}

		draggedCard.gameObject.SetActive(false);

		//SaveBuild(cardType);
		//RefreshEquipedCardsByType(m_CurrentCardType);
	}

	private void OnCardDragEndSwap(UIBuildCardControl draggedCard, int targetItemIndex)
	{
		UIBuildCardControl targetCard = null;
		int draggedIndex = -1;
		int targetIndex = -1;

		for (int i = 0; i < EquipedCardList.Count; i++)
		{
			if (EquipedCardList[i] == draggedCard)
			{
				draggedIndex = i;
			}
			if (EquipedCardList[i].EquipIndex == targetItemIndex && EquipedCardList[i] != draggedCard)
			{
				targetCard = EquipedCardList[i];
				targetIndex = i;
			}
		}

		if (targetCard != null)
		{
			UIBuildCardControl tempCard = EquipedCardList[draggedIndex];
			EquipedCardList[draggedIndex] = EquipedCardList[targetIndex];
			EquipedCardList[targetIndex] = tempCard;

			int tempEquipIndex = draggedCard.EquipIndex;
			draggedCard.EquipIndex = targetCard.EquipIndex;
			targetCard.EquipIndex = tempEquipIndex;

			if (draggedCard.EquipIndex < m_EquipedItemArray.Length)
			{
				draggedCard.CacheTrans.localPosition = m_EquipedItemArray[draggedCard.EquipIndex].localPosition;
			}
			else
			{
				int tempIndex = draggedCard.EquipIndex - m_EquipedItemArray.Length;
				draggedCard.CacheTrans.localPosition = m_TempItemArray[tempIndex].localPosition;
			}

			if (targetCard.EquipIndex < m_EquipedItemArray.Length)
			{
				targetCard.CacheTrans.localPosition = m_EquipedItemArray[targetCard.EquipIndex].localPosition;
			}
			else
			{
				int tempIndex = targetCard.EquipIndex - m_EquipedItemArray.Length;
				targetCard.CacheTrans.localPosition = m_TempItemArray[tempIndex].localPosition;
			}
		}
		else
		{
			draggedCard.EquipIndex = targetItemIndex;
			if (targetItemIndex < m_EquipedItemArray.Length)
			{
				draggedCard.CacheTrans.localPosition = m_EquipedItemArray[targetItemIndex].localPosition;
			}
			else
			{
				int tempIndex = targetItemIndex - m_EquipedItemArray.Length;
				draggedCard.CacheTrans.localPosition = m_TempItemArray[tempIndex].localPosition;
			}
		}

		SaveBuild(m_CurrentCardType);
	}

	protected override void OnReturn()
	{
		EquipedCardList.Clear();

		base.OnReturn();
	}
}