//This File Is Auto Generated By Process Control
using UnityEngine;

public class UIBuildNewControl : YViewControl
{
	private UIBuildNewView m_View;

	public static EResType GetResType()
	{
		return EResType.UIBuildNew;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIBuildNewView>();
		m_View.BtnAttack.onClick.AddListener(OnBtnAttackClick);
		m_View.BtnDefence.onClick.AddListener(OnBtnDefenceClick);
		m_View.BtnItem.onClick.AddListener(OnBtnItemClick);
		m_View.BtnSkill.onClick.AddListener(OnBtnSkillClick);
		m_View.BtnSell.onClick.AddListener(OnBtnSellClick);
	}

	void OnBtnAttackClick()
	{
	}

	void OnBtnDefenceClick()
	{
	}

	void OnBtnItemClick()
	{
	}

	void OnBtnSkillClick()
	{
	}

	void OnBtnSellClick()
	{
	}

	public void SetData()
	{
		;
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}