//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;


public class UIBuildControl : YViewControl
{
	private UIBuildView m_View;
	private List<UIBuildCardControl> TempCardList = new List<UIBuildCardControl>();
	private List<UIBuildCardControl> EquipedCardList = new List<UIBuildCardControl>();
	DataJoeyPlayer m_PlayerData;

	private List<int> TempCardUniqueIdList = new List<int>();
	private List<int> EquipedCardUniqueIdList = new List<int>();
	private ECardType m_CurrentCardType = ECardType.attack;

	private Canvas m_RootCanvas;
	private UIBuildCardControl m_CurrentDraggingCard;
	private RectTransform m_DraggingRect;
	private RectTransform[] m_EquipedSlots;
	private RectTransform[] m_TempSlots;


	public static EResType GetResType()
	{
		return EResType.UIBuild;
	}


	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIBuildView>();
		m_View.BtnClose.onClick.AddListener(OnBtnCloseClick);
		m_View.BtnAttack.onClick.AddListener(OnBtnAttackClick);
		m_View.BtnDefence.onClick.AddListener(OnBtnDefenceClick);
		m_View.BtnItem.onClick.AddListener(OnBtnItemClick);
		m_View.BtnSkill.onClick.AddListener(OnBtnSkillClick);
		m_PlayerData = DataSystem.Instance.GetDataJoeyPlayer();
		m_RootCanvas = GetComponentInParent<Canvas>();
		m_EquipedSlots = new[] { m_View.Item1, m_View.Item2, m_View.Item3, m_View.Item4, m_View.Item5, m_View.Item6 };
		m_TempSlots = new[] { m_View.Item7, m_View.Item8, m_View.Item9 };
	}



	void OnBtnCloseClick()
	{
		Close();
	}

	void OnBtnAttackClick()
	{
		SetTempAndEquipedCardId(ECardType.attack);
	}
	void OnBtnDefenceClick()
	{
		SetTempAndEquipedCardId(ECardType.defence);
	}
	void OnBtnItemClick()
	{
		SetTempAndEquipedCardId(ECardType.item);
	}
	void OnBtnSkillClick()
	{
		SetTempAndEquipedCardId(ECardType.skill);
	}


	void SetTempAndEquipedCardId(ECardType cardType = ECardType.attack)
	{
		m_CurrentCardType = cardType;
		TempCardUniqueIdList.Clear();
		EquipedCardUniqueIdList.Clear();
		foreach (var kvp in m_PlayerData.SelfCardDict)
		{
			int cardUniqueId = kvp.Key;
			var card = kvp.Value;
			ECardType cardECardType = card.GetCardType();
			if (cardECardType != cardType)
			{
				continue;
			}

			if (cardType == ECardType.attack)
			{
				if (m_PlayerData.EquipedAttackList.Contains(cardUniqueId))
				{
					EquipedCardUniqueIdList.Add(cardUniqueId);
				}
				if (m_PlayerData.TempAttackList.Contains(cardUniqueId))
				{
					TempCardUniqueIdList.Add(cardUniqueId);
				}
			}
			else if (cardType == ECardType.defence)
			{
				if (m_PlayerData.EquipedDefenceList.Contains(cardUniqueId))
				{
					EquipedCardUniqueIdList.Add(cardUniqueId);
				}
				if (m_PlayerData.TempDefenceList.Contains(cardUniqueId))
				{
					TempCardUniqueIdList.Add(cardUniqueId);
				}
			}
			else if (cardType == ECardType.item)
			{
				if (m_PlayerData.EquipedItemList.Contains(cardUniqueId))
				{
					EquipedCardUniqueIdList.Add(cardUniqueId);
				}
				if (m_PlayerData.TempItemList.Contains(cardUniqueId))
				{
					TempCardUniqueIdList.Add(cardUniqueId);
				}
			}
			else if (cardType == ECardType.skill)
			{
				if (m_PlayerData.EquipedSkillList.Contains(cardUniqueId))
				{
					EquipedCardUniqueIdList.Add(cardUniqueId);
				}
				if (m_PlayerData.TempSkillList.Contains(cardUniqueId))
				{
					TempCardUniqueIdList.Add(cardUniqueId);
				}
			}
		}
		RefreshEquipedCards();
		Debug.Log("count of TempCardUniqueIdList: " + TempCardUniqueIdList.Count);
		Debug.Log("count of EquipedCardUniqueIdList: " + EquipedCardUniqueIdList.Count);
	}


	void RefreshEquipedCards()
	{
		for (int i = 0; i < EquipedCardList.Count; i++)
		{
			var control = EquipedCardList[i];
			if (i < EquipedCardUniqueIdList.Count &&
				m_PlayerData.SelfCardDict.TryGetValue(EquipedCardUniqueIdList[i], out var card))
			{
				control.gameObject.SetActive(true);
				control.SetData(card, false, true);
				control.BeginDragHandler = null;
				control.DragHandler = null;
				control.EndDragHandler = null;
				control.ResetScale();
			}
			else
			{
				control.gameObject.SetActive(false);
				control.BuildClickHandler = null;
			}
		}


		for (int i = 0; i < TempCardList.Count; i++)
		{
			var control = TempCardList[i];
			if (i < TempCardUniqueIdList.Count &&
				m_PlayerData.SelfCardDict.TryGetValue(TempCardUniqueIdList[i], out var card))
			{
				control.gameObject.SetActive(true);
				control.SetData(card, false, true);
				control.BeginDragHandler = OnCardBeginDrag;
				control.DragHandler = OnCardDrag;
				control.EndDragHandler = OnCardEndDrag;
				control.ResetScale();
			}
			else
			{
				control.gameObject.SetActive(false);
				control.BeginDragHandler = null;
				control.DragHandler = null;
				control.EndDragHandler = null;
			}
		}
	}


	// void OnBuildCardClick(UIBuildCardControl control)
	// {
	// 	int uniqueId = control.CardData.UniqueId;
	// 	bool changed = control.m_IsDeckSlot
	// 		? TryMoveFromDeckToEquiped(uniqueId)
	// 		: TryMoveFromEquipedToDeck(uniqueId);

	// 	if (changed)
	// 	{
	// 		RefreshDeckCards();
	// 		RefreshEquipedCards();
	// 		DataSystem.Instance.SaveDataJoeyPlayer();
	// 	}
	// }

	List<int> GetEquipedListByType(ECardType cardType, out int maxNum)
	{
		switch (cardType)
		{
			case ECardType.attack: maxNum = m_PlayerData.MaxEquipedAttackNum; return m_PlayerData.EquipedAttackList;
			case ECardType.defence: maxNum = m_PlayerData.MaxEquipedDefenceNum; return m_PlayerData.EquipedDefenceList;
			case ECardType.item: maxNum = m_PlayerData.MaxEquipedItemNum; return m_PlayerData.EquipedItemList;
			case ECardType.skill: maxNum = m_PlayerData.MaxEquipedSkillNum; return m_PlayerData.EquipedSkillList;
			default: maxNum = 0; return new List<int>();
		}
	}

	public void SetData()
	{
		RectTransform[] itemArray = new RectTransform[] { m_View.Item1, m_View.Item2, m_View.Item3, m_View.Item4, m_View.Item5, m_View.Item6 ,m_View.Item7, m_View.Item8, m_View.Item9};

		for (int i = 0; i < 9; i++)
		{
			UIBuildCardControl cardControl = Asset.OpenUI<UIBuildCardControl>(null);
			cardControl.CacheTrans.SetParent(itemArray[i]);
			cardControl.CacheTrans.localScale = Vector3.one;
			cardControl.CacheTrans.localPosition = Vector3.zero;
			cardControl.CacheTrans.localEulerAngles = Vector3.zero;
			cardControl.BeginDragHandler = OnCardBeginDrag;
			cardControl.DragHandler = OnCardDrag;
			cardControl.EndDragHandler = OnCardEndDrag;
			if (i < 6)
			{
				EquipedCardList.Add(cardControl);
			}
			else
			{
				TempCardList.Add(cardControl);
			}
			

		}

		OnBtnAttackClick();
	}

	public void SetShopData()
	{
		RectTransform[] itemArray = new RectTransform[] { m_View.Item1, m_View.Item2, m_View.Item3, m_View.Item4, m_View.Item5, m_View.Item6, m_View.Item7, m_View.Item8, m_View.Item9 };

		for (int i = 0; i < 9; i++)
		{
			UIBuildCardControl cardControl = Asset.OpenUI<UIBuildCardControl>(null);
			cardControl.CacheTrans.SetParent(itemArray[i]);
			cardControl.CacheTrans.localScale = Vector3.one;
			cardControl.CacheTrans.localPosition = Vector3.zero;
			cardControl.CacheTrans.localEulerAngles = Vector3.zero;
			EquipedCardList.Add(cardControl);
		}
	}
	void OnCardBeginDrag(UIBuildCardControl control, PointerEventData eventData)
	{
		m_CurrentDraggingCard = control;
		m_DraggingRect = control.CacheTrans as RectTransform;
		control.CacheTrans.SetParent(m_RootCanvas.transform, true);
		UpdateDraggingPosition(eventData);
	}

	void OnCardDrag(UIBuildCardControl control, PointerEventData eventData)
	{
		if (control != m_CurrentDraggingCard) return;
		UpdateDraggingPosition(eventData);
	}

	void OnCardEndDrag(UIBuildCardControl control, PointerEventData eventData)
	{
		if (control != m_CurrentDraggingCard) return;

		bool moved = false;
		control.RestoreDragState();
		m_CurrentDraggingCard = null;
		m_DraggingRect = null;

		if (moved)
		{
			RefreshEquipedCards();
			DataSystem.Instance.SaveDataJoeyPlayer();
		}
	}

	void UpdateDraggingPosition(PointerEventData eventData)
	{
		if (m_DraggingRect == null || m_RootCanvas == null) return;
		if (RectTransformUtility.ScreenPointToWorldPointInRectangle(
			m_RootCanvas.transform as RectTransform,
			eventData.position,
			eventData.pressEventCamera,
			out var worldPos))
		{
			m_DraggingRect.position = worldPos;
		}
	}

	protected override void OnReturn()
	{
		TempCardList.Clear();
		EquipedCardList.Clear();

		base.OnReturn();
	}
}