//This File Is Auto Generated By Process Control
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;


public class UIBuildCardControl : YViewControl
{
    private UICardSimpleView m_View;
    private Card cachedCard;
    private ECardType cachedCardType;
    public Transform CacheTrans;
    private Vector3 m_OriginalScale = Vector3.zero;
    private bool m_IsMoving;
    public bool m_IsEquipedSlot;
    public System.Action<UIBuildCardControl> BuildClickHandler;

    public ECardType CardType => cachedCardType;
    public Card CardData => cachedCard;

    private Transform m_Transform = null;
    private CanvasGroup m_CanvasGroup;
    private Transform m_OriginalParent;
    private int m_OriginalSiblingIndex;

    public System.Action<UIBuildCardControl, PointerEventData> BeginDragHandler;
    public System.Action<UIBuildCardControl, PointerEventData> DragHandler;
    public System.Action<UIBuildCardControl, PointerEventData> EndDragHandler;




    public static EResType GetResType()
    {
        return EResType.UICardSimple;
    }

    protected override void OnInit()
    {
        base.OnInit();
        if (m_Transform == null)
        {
            m_Transform = transform ;
        }
        
        CacheTrans = m_Transform;
        if (m_OriginalScale == Vector3.zero)
        {
            m_OriginalScale = CacheTrans.localScale;
        }
        m_View = CreateView<UICardSimpleView>();
        m_View.BtnCard.onClick.AddListener(OnBtnCardClick);
        // 添加这行：初始化 CanvasGroup
        m_CanvasGroup = GetComponent<CanvasGroup>();
        if (m_CanvasGroup == null)
        {
            m_CanvasGroup = gameObject.AddComponent<CanvasGroup>();
        }
        if (m_View.Trigger != null)
        {
            m_View.Trigger.onEnter = OnPointerEnter;
            m_View.Trigger.onExit = OnPointerExit;
            m_View.Trigger.onBeginDrag = OnBeginDrag;
            m_View.Trigger.onDrag = OnDrag;
            m_View.Trigger.onEndDrag = OnEndDrag;
        }

        SetRaycastTargetFalse();
        CacheTrans.localScale = m_OriginalScale;


    }

    private void OnPointerEnter(GameObject go, UnityEngine.EventSystems.PointerEventData eventData)
    {
        if (m_IsMoving) return;
        CacheTrans.localScale = m_OriginalScale * 1.05f;
    }

    private void OnPointerExit(GameObject go, UnityEngine.EventSystems.PointerEventData eventData)
    {
        if (m_IsMoving) return;
        CacheTrans.localScale = m_OriginalScale;
    }

    private void OnBeginDrag(GameObject go, PointerEventData eventData)
    {
        if (!m_IsEquipedSlot) return;
        m_IsMoving = true;
        m_OriginalParent = CacheTrans.parent;
        m_OriginalSiblingIndex = CacheTrans.GetSiblingIndex();
        m_CanvasGroup.blocksRaycasts = false;
        BeginDragHandler?.Invoke(this, eventData);
    }
    private void OnDrag(GameObject go, PointerEventData eventData)
    {
        if (!m_IsMoving) return;
        DragHandler?.Invoke(this, eventData);
    }

    private void OnEndDrag(GameObject go, PointerEventData eventData)
    {
        if (!m_IsMoving) return;
        m_IsMoving = false;
        m_CanvasGroup.blocksRaycasts = true;
        EndDragHandler?.Invoke(this, eventData);
    }
    public void ResetScale()
    {
        CacheTrans.localScale = m_OriginalScale;
    }

    public void RestoreDragState()
    {
        CacheTrans.SetParent(m_OriginalParent, false);
        CacheTrans.SetSiblingIndex(m_OriginalSiblingIndex);
        CacheTrans.localScale = m_OriginalScale;
    }

    public void SetMoving(bool isMoving)
    {
        m_IsMoving = isMoving;
    }

    private void SetRaycastTargetFalse()
    {
        // 获取 Trigger 所在的 GameObject，保持它能接收事件
        GameObject triggerObj = m_View.Trigger != null ? m_View.Trigger.gameObject : null;
        
        Image[] images = GetComponentsInChildren<Image>(true);
        for (int i = 0; i < images.Length; i++)
        {
            // 排除当前对象和 Trigger 所在对象
            if (images[i].gameObject != gameObject && images[i].gameObject != triggerObj)
            {
                images[i].raycastTarget = false;
            }
        }

        Text[] texts = GetComponentsInChildren<Text>(true);
        for (int i = 0; i < texts.Length; i++)
        {
            if (texts[i].gameObject != gameObject && texts[i].gameObject != triggerObj)
            {
                texts[i].raycastTarget = false;
            }
        }
    }

    void OnBtnCardClick()
    {
        if (m_IsEquipedSlot)
        {
            BuildClickHandler?.Invoke(this);
            return;
        }
    }

    public void SetData(Card card, bool isEquipedSlot = true)
    {
        RectTransform animRect = m_View.Anim.transform as RectTransform;
        if (animRect != null)
        {
            animRect.anchoredPosition = Vector2.zero;
        }
        m_View.Anim.Play(ECardAnimName.Idle.ToString(), 0, 0);
        cachedCard = card;
        cachedCardType = (ECardType)System.Enum.Parse(typeof(ECardType), card.type);
        m_IsMoving = false;
        m_IsEquipedSlot = isEquipedSlot;

        m_View.CardName.text = card.cardName;
        m_View.CardImg.sprite = LoadSprite(card.cardImage);
        m_View.Description.text = card.description;
        m_View.IconType.sprite = LoadSprite(card.iconType);
        m_View.CardFrame.sprite = LoadSprite(card.cardFrame);

        SetTypeUI(card);
        SetStars(card.stars);
    }

    private void SetTypeUI(Card card)
    {
        m_View.Attack.SetActive(false);
        m_View.Defence.SetActive(false);
        m_View.Moster.SetActive(false);

        switch (cachedCardType)
        {
            case ECardType.attack:
                m_View.Attack.SetActive(true);
                m_View.TxtAttack.text = card.attack.ToString();
                break;

            case ECardType.defence:
                m_View.Defence.SetActive(true);
                m_View.TxtDefence.text = card.defence.ToString();
                break;

            case ECardType.monster:
                m_View.Attack.SetActive(true);
                m_View.TxtAttack.text = card.attack.ToString();
                m_View.Moster.SetActive(true);
                m_View.TextHeart.text = card.currentHealth.ToString();
                break;

            case ECardType.skill:
                break;

            case ECardType.item:
                break;

            case ECardType.other:
                m_View.IconType.gameObject.SetActive(false);
                break;

            default:
                break;
        }

        SetStars(cachedCard.stars);
    }

    private void SetStars(int stars)
    {
        stars = Mathf.Clamp(stars, 0, 3);
        int childCount = m_View.StarLayout.transform.childCount;
        for (int i = 0; i < childCount; i++)
        {
            var starObj = m_View.StarLayout.transform.GetChild(i).gameObject;
            starObj.SetActive(i < stars);
        }
    }

    private Sprite LoadSprite(string path)
    {
        return Resources.Load<Sprite>(path);
    }
}

