//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIBuildView : YBaseView
{
	public RectTransform Item1;
	public RectTransform Item2;
	public RectTransform Item3;
	public RectTransform Item4;
	public RectTransform Item5;
	public RectTransform Item6;
	public RectTransform Item7;
	public RectTransform Item8;
	public RectTransform Item9;
	public Button BtnAttack;
	public Button BtnDefence;
	public Button BtnItem;
	public Button BtnSkill;
	public RectTransform Content;
	public Image BtnDelete;
	public Image Empty1;
	public Image Empty2;
	public Image Empty3;
	public Image Empty4;
	public Image Empty5;
	public Image Empty6;
	public Image Empty7;
	public Image Empty8;
	public Image Empty9;
	public GameObject SelectAttack;
	public GameObject SelectDefence;
	public GameObject SelectItem;
	public GameObject SelectSkill;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		Item1 = viewItemList[0].Target.GetComponent<RectTransform>();
		Item2 = viewItemList[1].Target.GetComponent<RectTransform>();
		Item3 = viewItemList[2].Target.GetComponent<RectTransform>();
		Item4 = viewItemList[3].Target.GetComponent<RectTransform>();
		Item5 = viewItemList[4].Target.GetComponent<RectTransform>();
		Item6 = viewItemList[5].Target.GetComponent<RectTransform>();
		Item7 = viewItemList[6].Target.GetComponent<RectTransform>();
		Item8 = viewItemList[7].Target.GetComponent<RectTransform>();
		Item9 = viewItemList[8].Target.GetComponent<RectTransform>();
		BtnAttack = viewItemList[9].Target.GetComponent<Button>();
		BtnDefence = viewItemList[10].Target.GetComponent<Button>();
		BtnItem = viewItemList[11].Target.GetComponent<Button>();
		BtnSkill = viewItemList[12].Target.GetComponent<Button>();
		Content = viewItemList[13].Target.GetComponent<RectTransform>();
		BtnDelete = viewItemList[14].Target.GetComponent<Image>();
		Empty1 = viewItemList[15].Target.GetComponent<Image>();
		Empty2 = viewItemList[16].Target.GetComponent<Image>();
		Empty3 = viewItemList[17].Target.GetComponent<Image>();
		Empty4 = viewItemList[18].Target.GetComponent<Image>();
		Empty5 = viewItemList[19].Target.GetComponent<Image>();
		Empty6 = viewItemList[20].Target.GetComponent<Image>();
		Empty7 = viewItemList[21].Target.GetComponent<Image>();
		Empty8 = viewItemList[22].Target.GetComponent<Image>();
		Empty9 = viewItemList[23].Target.GetComponent<Image>();
		SelectAttack = viewItemList[24].Target.gameObject;
		SelectDefence = viewItemList[25].Target.gameObject;
		SelectItem = viewItemList[26].Target.gameObject;
		SelectSkill = viewItemList[27].Target.gameObject;
	}
}