//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIBuildNewView : YBaseView
{
	public Button BtnAttack;
	public Button BtnDefence;
	public Button BtnItem;
	public Button BtnSkill;
	public Button BtnSell;
	public RectTransform Content;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		BtnAttack = viewItemList[0].Target.GetComponent<Button>();
		BtnDefence = viewItemList[1].Target.GetComponent<Button>();
		BtnItem = viewItemList[2].Target.GetComponent<Button>();
		BtnSkill = viewItemList[3].Target.GetComponent<Button>();
		BtnSell = viewItemList[4].Target.GetComponent<Button>();
		Content = viewItemList[5].Target.GetComponent<RectTransform>();
	}
}