//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;



public class UIBuildControl : YViewControl
{
	private UIBuildView m_View;
	private List<UICardSimpleControl> DeckCardList = new List<UICardSimpleControl>();
	private List<UICardSimpleControl> EquipedCardList = new List<UICardSimpleControl>();
	DataJoeyPlayer m_PlayerData;

	private List<int> DeckCardUniqueIdList = new List<int>();
	private List<int> EquipedCardUniqueIdList = new List<int>();
	private string m_CurrentCardType = "attack";




	public static EResType GetResType()
	{
		return EResType.UIBuild;
	}




	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIBuildView>();
		m_View.BtnClose.onClick.AddListener(OnBtnCloseClick);
		m_View.BtnAttack.onClick.AddListener(OnBtnAttackClick);
		m_View.BtnDefence.onClick.AddListener(OnBtnDefenceClick);
		m_View.BtnItem.onClick.AddListener(OnBtnItemClick);
		m_View.BtnSkill.onClick.AddListener(OnBtnSkillClick);
		m_PlayerData = DataSystem.Instance.GetDataJoeyPlayer();
		InitTestCards();      // ← 仅测试时调用
		SetData();
		OnBtnAttackClick();
	}
	void InitTestCards()
	{
		m_PlayerData.SelfCardDict.Clear();
		m_PlayerData.EquipedAttackList.Clear();
		m_PlayerData.EquipedDefenceList.Clear();
		m_PlayerData.EquipedItemList.Clear();
		m_PlayerData.EquipedSkillList.Clear();
		m_PlayerData.MaxEquipedAttackNum = 3;
		m_PlayerData.MaxEquipedDefenceNum = 3;
		m_PlayerData.MaxEquipedItemNum = 3;
		m_PlayerData.MaxEquipedSkillNum = 3;

		AddTestCard(1001, "attack", "测试剑-1", 5, 0, 0);
		AddTestCard(1002, "attack", "测试剑-2", 7, 0, 0);
		AddTestCard(1003, "attack", "测试剑-3", 9, 0, 0);

		AddTestCard(2001, "defence", "测试盾-1", 0, 4, 0);
		AddTestCard(2002, "defence", "测试盾-2", 0, 6, 0);

		AddTestCard(3001, "item", "治疗药水", 0, 0, 0);
		AddTestCard(4001, "skill", "火球术", 10, 0, 0);

		m_PlayerData.EquipedAttackList.Add(1001);
		m_PlayerData.EquipedDefenceList.Add(2001);
		m_PlayerData.EquipedItemList.Add(3001);
		m_PlayerData.EquipedSkillList.Add(4001);

		m_PlayerData.UniqueIdGen = 5000;
		Debug.Log("InitTestCards");
	}

	void AddTestCard(int uniqueId, string type, string name, int attack, int defence, int health)
	{
		var card = new Card
		{
			id = $"test_{uniqueId}",
			type = type,
			iconType = $"Art/UI/icon_{type}",
			cardImage = "Art/UI/card_icon_test",
			cardFrame = "Art/UI/card_bg_normal",
			cardName = name,
			description = "测试用卡牌",
			attack = attack,
			currentAttack = attack,
			defence = defence,
			currentDefence = defence,
			health = health,
			currentHealth = health,
			price = 0,
			currentPrice = 0,
			stars = 1,
			effectId = string.Empty,
			UniqueId = uniqueId
		};

		m_PlayerData.SelfCardDict[uniqueId] = card;
	}



	void OnBtnCloseClick()
	{
		Close();
	}

	void OnBtnAttackClick()
	{
		SetDeckAndEquipedCardId("attack");
	}
	void OnBtnDefenceClick()
	{
		SetDeckAndEquipedCardId("defence");
	}
	void OnBtnItemClick()
	{
		SetDeckAndEquipedCardId("item");
	}
	void OnBtnSkillClick()
	{
		SetDeckAndEquipedCardId("skill");
	}


	void SetDeckAndEquipedCardId(string cardType = "attack")
	{
		m_CurrentCardType = cardType;
		DeckCardUniqueIdList.Clear();
		EquipedCardUniqueIdList.Clear();
		foreach (var kvp in m_PlayerData.SelfCardDict)
		{
			int cardUniqueId = kvp.Key;
			var card = kvp.Value;
			if (card.type != cardType)
			{
				continue;
			}

			if (cardType == "attack")
			{
				if (m_PlayerData.EquipedAttackList.Contains(cardUniqueId))
				{
					EquipedCardUniqueIdList.Add(cardUniqueId);
				}
				else
				{
					DeckCardUniqueIdList.Add(cardUniqueId);
				}
			}
			else if (cardType == "defence")
			{
				if (m_PlayerData.EquipedDefenceList.Contains(cardUniqueId))
				{
					EquipedCardUniqueIdList.Add(cardUniqueId);
				}
				else
				{
					DeckCardUniqueIdList.Add(cardUniqueId);
				}
			}
			else if (cardType == "item")
			{
				if (m_PlayerData.EquipedItemList.Contains(cardUniqueId))
				{
					EquipedCardUniqueIdList.Add(cardUniqueId);
				}
				else
				{
					DeckCardUniqueIdList.Add(cardUniqueId);
				}
			}
			else if (cardType == "skill")
			{
				if (m_PlayerData.EquipedSkillList.Contains(cardUniqueId))
				{
					EquipedCardUniqueIdList.Add(cardUniqueId);
				}
				else
				{
					DeckCardUniqueIdList.Add(cardUniqueId);
				}
			}
		}
		RefreshDeckCards();
		RefreshEquipedCards();
		Debug.Log("count of DeckCardUniqueIdList: " + DeckCardUniqueIdList.Count);
		Debug.Log("count of EquipedCardUniqueIdList: " + EquipedCardUniqueIdList.Count);
	}



	void RefreshDeckCards()
	{
		for (int i = 0; i < DeckCardList.Count; i++)
		{
			var control = DeckCardList[i];
			if (i < DeckCardUniqueIdList.Count &&
				m_PlayerData.SelfCardDict.TryGetValue(DeckCardUniqueIdList[i], out var card))
			{
				control.gameObject.SetActive(true);
				control.SetData(card);
				control.BindBuildClick(OnBuildCardClick, true, false);
			}
			else
			{
				control.gameObject.SetActive(false);
				control.BindBuildClick(null, false, false);
			}
		}
	}

	void RefreshEquipedCards()
	{
		for (int i = 0; i < EquipedCardList.Count; i++)
		{
			var control = EquipedCardList[i];
			if (i < EquipedCardUniqueIdList.Count &&
				m_PlayerData.SelfCardDict.TryGetValue(EquipedCardUniqueIdList[i], out var card))
			{
				control.gameObject.SetActive(true);
				control.SetData(card);
				control.BindBuildClick(OnBuildCardClick, false, true);
			}
			else
			{
				control.gameObject.SetActive(false);
				control.BindBuildClick(null, false, false);
			}
		}
	}


	void OnBuildCardClick(UICardSimpleControl control)
	{
		int uniqueId = control.CardData.UniqueId;
		bool changed = control.IsBuildDeck
			? TryMoveFromDeckToEquiped(uniqueId)
			: TryMoveFromEquipedToDeck(uniqueId);

		if (changed)
		{
			RefreshDeckCards();
			RefreshEquipedCards();
			DataSystem.Instance.SaveDataJoeyPlayer();
		}
	}


	bool TryMoveFromDeckToEquiped(int uniqueId)
	{
		var equipedList = GetEquipedListByType(m_CurrentCardType, out int maxNum);
		if (equipedList.Count >= maxNum) return false;

		DeckCardUniqueIdList.Remove(uniqueId);
		EquipedCardUniqueIdList.Add(uniqueId);
		equipedList.Add(uniqueId);
		return true;
	}

	bool TryMoveFromEquipedToDeck(int uniqueId)
	{
		var equipedList = GetEquipedListByType(m_CurrentCardType, out _);
		if (!equipedList.Remove(uniqueId)) return false;

		EquipedCardUniqueIdList.Remove(uniqueId);
		DeckCardUniqueIdList.Add(uniqueId);
		return true;
	}

	List<int> GetEquipedListByType(string cardType, out int maxNum)
	{
		switch (cardType)
		{
			case "attack": maxNum = m_PlayerData.MaxEquipedAttackNum; return m_PlayerData.EquipedAttackList;
			case "defence": maxNum = m_PlayerData.MaxEquipedDefenceNum; return m_PlayerData.EquipedDefenceList;
			case "item": maxNum = m_PlayerData.MaxEquipedItemNum; return m_PlayerData.EquipedItemList;
			case "skill": maxNum = m_PlayerData.MaxEquipedSkillNum; return m_PlayerData.EquipedSkillList;
			default: maxNum = 0; return DeckCardUniqueIdList;
		}
	}

	public void SetData()
	{
		RectTransform[] itemArray = new RectTransform[] { m_View.Item1, m_View.Item2, m_View.Item3, m_View.Item4, m_View.Item5, m_View.Item6 };

		for (int i = 0; i < 18; i++)
		{
			UICardSimpleControl cardControl = Asset.OpenUI<UICardSimpleControl>(null);
			cardControl.CacheTrans.SetParent(m_View.Content);
			cardControl.CacheTrans.localScale = Vector3.one;
			cardControl.CacheTrans.localPosition = Vector3.zero;
			cardControl.CacheTrans.localEulerAngles = Vector3.zero;
			//cardControl.CacheTrans.SetAsLastSibling();
			DeckCardList.Add(cardControl);
		}

		for (int i = 0; i < 6; i++)
		{
			UICardSimpleControl cardControl = Asset.OpenUI<UICardSimpleControl>(null);
			cardControl.CacheTrans.SetParent(itemArray[i]);
			cardControl.CacheTrans.localScale = Vector3.one;
			cardControl.CacheTrans.localPosition = Vector3.zero;
			cardControl.CacheTrans.localEulerAngles = Vector3.zero;
			//cardControl.CacheTrans.SetAsLastSibling();
			EquipedCardList.Add(cardControl);
		}

	}

	protected override void OnReturn()
	{
		DeckCardList.Clear();
		EquipedCardList.Clear();

		base.OnReturn();
	}
}