//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIBuildCardNewView : YBaseView
{
	public Image CardImg;
	public Text CardName;
	public GameObject Attack;
	public Text TxtAttack;
	public GameObject Defence;
	public Text TxtDefence;
	public GameObject StarLayout;
	public Button BtnCard;
	public EventTriggerListener Trigger;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		CardImg = viewItemList[0].Target.GetComponent<Image>();
		CardName = viewItemList[1].Target.GetComponent<Text>();
		Attack = viewItemList[2].Target.gameObject;
		TxtAttack = viewItemList[3].Target.GetComponent<Text>();
		Defence = viewItemList[4].Target.gameObject;
		TxtDefence = viewItemList[5].Target.GetComponent<Text>();
		StarLayout = viewItemList[6].Target.gameObject;
		BtnCard = viewItemList[8].Target.GetComponent<Button>();
		Trigger = viewItemList[8].Target.GetComponent<EventTriggerListener>();
	}
}