//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIBuildNewView : YBaseView
{
	public Button BtnAttack;
	public Button BtnDefence;
	public Button BtnItem;
	public Button BtnSkill;
	public Image BtnDelete;
	public RectTransform Content;
	public RectTransform item1;
	public RectTransform item2;
	public RectTransform item3;
	public RectTransform item4;
	public RectTransform item5;
	public RectTransform item6;
	public RectTransform item7;
	public Button BtnClose;
	public GameObject SelectAttack;
	public GameObject SelectDefence;
	public GameObject SelectItem;
	public GameObject SelectSkill;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		BtnAttack = viewItemList[0].Target.GetComponent<Button>();
		BtnDefence = viewItemList[1].Target.GetComponent<Button>();
		BtnItem = viewItemList[2].Target.GetComponent<Button>();
		BtnSkill = viewItemList[3].Target.GetComponent<Button>();
		BtnDelete = viewItemList[4].Target.GetComponent<Image>();
		Content = viewItemList[5].Target.GetComponent<RectTransform>();
		item1 = viewItemList[6].Target.GetComponent<RectTransform>();
		item2 = viewItemList[7].Target.GetComponent<RectTransform>();
		item3 = viewItemList[8].Target.GetComponent<RectTransform>();
		item4 = viewItemList[9].Target.GetComponent<RectTransform>();
		item5 = viewItemList[10].Target.GetComponent<RectTransform>();
		item6 = viewItemList[11].Target.GetComponent<RectTransform>();
		item7 = viewItemList[12].Target.GetComponent<RectTransform>();
		BtnClose = viewItemList[13].Target.GetComponent<Button>();
		SelectAttack = viewItemList[14].Target.gameObject;
		SelectDefence = viewItemList[15].Target.gameObject;
		SelectItem = viewItemList[16].Target.gameObject;
		SelectSkill = viewItemList[17].Target.gameObject;
	}
}