//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.EventSystems;


public class UIBuildNewControl : YViewControl
{
	private UIBuildNewView m_View;
	private List<UIBuildCardNewControl> EquipedCardList = new List<UIBuildCardNewControl>();
	private RectTransform[] m_EquipedItemArray;
	private DataJoeyPlayer m_PlayerData;
	public ECardType m_CurrentCardType;


	public static EResType GetResType()
	{
		return EResType.UIBuildNew;
	}


	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIBuildNewView>();
		// m_View.BtnClose.onClick.AddListener(OnBtnCloseClick);
		m_View.BtnAttack.onClick.AddListener(OnBtnAttackClick);
		m_View.BtnDefence.onClick.AddListener(OnBtnDefenceClick);
		m_View.BtnItem.onClick.AddListener(OnBtnItemClick);
		m_View.BtnSkill.onClick.AddListener(OnBtnSkillClick);
		m_EquipedItemArray = new RectTransform[] { m_View.item1, m_View.item2, m_View.item3, m_View.item4, m_View.item5, m_View.item6 ,m_View.item7};
		m_PlayerData = DataSystem.Instance.GetDataJoeyPlayer();
		m_CurrentCardType = ECardType.other;
	}



	void OnBtnCloseClick()
	{
		Close();
	}

	void OnBtnAttackClick()
	{
		RefreshEquipedCardsByType(ECardType.attack);
	}
	void OnBtnDefenceClick()
	{
		RefreshEquipedCardsByType(ECardType.defence);
	}
	void OnBtnItemClick()
	{
		RefreshEquipedCardsByType(ECardType.item);
	}
	void OnBtnSkillClick()
	{
		RefreshEquipedCardsByType(ECardType.skill);
	}




	public void RefreshEquipedCardsByType(ECardType cardType)
	{
		SaveBuild(m_CurrentCardType);
		m_CurrentCardType = cardType;
		List<int> equipList = null;
		switch (cardType)
		{
			case ECardType.attack:
				equipList = m_PlayerData.EquipedAttackList;
				break;
			case ECardType.defence:
				equipList = m_PlayerData.EquipedDefenceList;
				break;
			case ECardType.item:
				equipList = m_PlayerData.EquipedItemList;
				break;
			case ECardType.skill:
				equipList = m_PlayerData.EquipedSkillList;
				break;
			default:
				return;
		}

		for (int i = 0; i < m_EquipedItemArray.Length; i++)
		{
			UIBuildCardNewControl cardControl = EquipedCardList[i];
			if (i < equipList.Count)
			{
				int cardUniqueId = equipList[i];
				Card card = m_PlayerData.GetSelfCardDictData(cardUniqueId);
				if (card != null && card.GetCardType() == cardType)
				{
					cardControl.gameObject.SetActive(true);
					cardControl.SetData(card);
				}
				else
				{
					cardControl.gameObject.SetActive(false);
				}
			}
			else
			{
				cardControl.gameObject.SetActive(false);
			}
		}

	}

	public void SetShopData()
	{
		for (int i = 0; i < m_EquipedItemArray.Length; i++)
		{
			UIBuildCardNewControl cardControl = Asset.OpenUI<UIBuildCardNewControl>(m_View.Content);
			RectTransform itemRect = m_EquipedItemArray[i];
			cardControl.CacheTrans.localPosition = itemRect.localPosition;
			cardControl.CacheTrans.localScale = Vector3.one;
			cardControl.EquipIndex = i;
			cardControl.OnDragEndHandler = OnCardDragEnd;
			EquipedCardList.Add(cardControl);
		}

		RefreshEquipedCardsByType(ECardType.attack);
	}

	public void SaveBuild(ECardType cardType)
	{
		List<int> equipList = null;
		switch (cardType)
		{
			case ECardType.attack:
				equipList = m_PlayerData.EquipedAttackList;
				break;
			case ECardType.defence:
				equipList = m_PlayerData.EquipedDefenceList;
				break;
			case ECardType.item:
				equipList = m_PlayerData.EquipedItemList;
				break;
			case ECardType.skill:
				equipList = m_PlayerData.EquipedSkillList;
				break;
			default:
				return;
		}

		equipList.Clear();

		for (int i = 0; i < EquipedCardList.Count; i++)
		{
			UIBuildCardNewControl cardControl = EquipedCardList[i];
			if (cardControl.gameObject.activeSelf && cardControl.CardData != null)
			{
				if (cardControl.EquipIndex < 6)
				{
					equipList.Add(cardControl.CardData.UniqueId);
				}
			}
		}
	}

	private void OnCardDragEnd(UIBuildCardNewControl draggedCard, PointerEventData eventData)
	{
		if (CheckCardInDeleteArea(draggedCard, eventData))
		{
			DeleteCard(draggedCard);
			return;
		}

		for (int i = 0; i < m_EquipedItemArray.Length; i++)
		{
			if (m_EquipedItemArray[i] != null)
			{
				RectTransform itemRect = m_EquipedItemArray[i];
				if (RectTransformUtility.RectangleContainsScreenPoint(
					itemRect,
					eventData.position,
					eventData.pressEventCamera))
				{
					OnCardDragEndSwap(draggedCard, i);
					return;
				}
			}
		}

		RectTransform rectTransform = draggedCard.CacheTrans as RectTransform;
		if (rectTransform != null)
		{
			if (draggedCard.EquipIndex < m_EquipedItemArray.Length)
			{
				rectTransform.localPosition = m_EquipedItemArray[draggedCard.EquipIndex].localPosition;
			}
		}
	}

	private bool CheckCardInDeleteArea(UIBuildCardNewControl draggedCard, PointerEventData eventData)
	{
		if (m_View.BtnDelete == null || draggedCard.CardData == null)
		{
			return false;
		}

		RectTransform deleteRect = m_View.BtnDelete.rectTransform;
		RectTransform cardRect = draggedCard.CacheTrans as RectTransform;

		if (deleteRect == null || cardRect == null)
		{
			return false;
		}

		Vector3[] deleteCorners = new Vector3[4];
		Vector3[] cardCorners = new Vector3[4];
		deleteRect.GetWorldCorners(deleteCorners);
		cardRect.GetWorldCorners(cardCorners);

		Rect deleteRectWorld = new Rect(deleteCorners[0].x, deleteCorners[0].y,
			deleteCorners[2].x - deleteCorners[0].x,
			deleteCorners[2].y - deleteCorners[0].y);

		Rect cardRectWorld = new Rect(cardCorners[0].x, cardCorners[0].y,
			cardCorners[2].x - cardCorners[0].x,
			cardCorners[2].y - cardCorners[0].y);

		return deleteRectWorld.Overlaps(cardRectWorld);
	}

	private void DeleteCard(UIBuildCardNewControl draggedCard)
	{
		if (draggedCard.CardData == null)
		{
			return;
		}

		Card card = draggedCard.CardData;
		ECardType cardType = card.GetCardType();
		int uniqueId = card.UniqueId;

		List<int> equipList = null;

		switch (cardType)
		{
			case ECardType.attack:
				equipList = m_PlayerData.EquipedAttackList;
				break;
			case ECardType.defence:
				equipList = m_PlayerData.EquipedDefenceList;
				break;
			case ECardType.item:
				equipList = m_PlayerData.EquipedItemList;
				break;
			case ECardType.skill:
				equipList = m_PlayerData.EquipedSkillList;
				break;
			default:
				return;
		}

		equipList.Remove(uniqueId);
		m_PlayerData.RemoveSelfCardDictData(uniqueId);

		int halfPrice = Mathf.RoundToInt(card.price / 2f);
		DataSystem.Instance.AddCoin(halfPrice);

		DataSystem.Instance.SaveDataJoeyPlayer();

		RectTransform rectTransform = draggedCard.CacheTrans as RectTransform;
		if (rectTransform != null)
		{
			if (draggedCard.EquipIndex < m_EquipedItemArray.Length)
			{
				rectTransform.localPosition = m_EquipedItemArray[draggedCard.EquipIndex].localPosition;
			}

		}

		draggedCard.gameObject.SetActive(false);

		RefreshEquipedCardsByType(m_CurrentCardType);
	}

	private void OnCardDragEndSwap(UIBuildCardNewControl draggedCard, int targetItemIndex)
	{
		UIBuildCardNewControl targetCard = null;
		int draggedIndex = -1;
		int targetIndex = -1;

		for (int i = 0; i < EquipedCardList.Count; i++)
		{
			if (EquipedCardList[i] == draggedCard)
			{
				draggedIndex = i;
			}
			if (EquipedCardList[i].EquipIndex == targetItemIndex && EquipedCardList[i] != draggedCard)
			{
				targetCard = EquipedCardList[i];
				targetIndex = i;
			}
		}

		if (targetCard != null)
		{
			UIBuildCardNewControl tempCard = EquipedCardList[draggedIndex];
			EquipedCardList[draggedIndex] = EquipedCardList[targetIndex];
			EquipedCardList[targetIndex] = tempCard;

			int tempEquipIndex = draggedCard.EquipIndex;
			draggedCard.EquipIndex = targetCard.EquipIndex;
			targetCard.EquipIndex = tempEquipIndex;

			if (draggedCard.EquipIndex < m_EquipedItemArray.Length)
			{
				draggedCard.CacheTrans.localPosition = m_EquipedItemArray[draggedCard.EquipIndex].localPosition;
			}

			if (targetCard.EquipIndex < m_EquipedItemArray.Length)
			{
				targetCard.CacheTrans.localPosition = m_EquipedItemArray[targetCard.EquipIndex].localPosition;
			}
		}
		else
		{
			draggedCard.EquipIndex = targetItemIndex;
			if (targetItemIndex < m_EquipedItemArray.Length)
			{
				draggedCard.CacheTrans.localPosition = m_EquipedItemArray[targetItemIndex].localPosition;
			}
		}
	}

	protected override void OnReturn()
	{
		EquipedCardList.Clear();

		base.OnReturn();
	}
}