//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;


public class UIBuildSuperControl : YViewControl
{
    private UIBuildView m_View;
    private List<UIBuildCardControl> CardList = new List<UIBuildCardControl>();
    private RectTransform[] m_ItemArray;
    private DataJoeyPlayer m_PlayerData;
    public ECardType m_CurrentCardType;


    public static EResType GetResType()
    {
        return EResType.UIBuild;
    }


    protected override void OnInit()
    {
        base.OnInit();
        m_View = CreateView<UIBuildView>();
        m_View.BtnAttack.onClick.AddListener(OnBtnAttackClick);
        m_View.BtnDefence.onClick.AddListener(OnBtnDefenceClick);
        m_View.BtnItem.onClick.AddListener(OnBtnItemClick);
        m_View.BtnSkill.onClick.AddListener(OnBtnSkillClick);
        m_ItemArray = new RectTransform[] { m_View.Item1, m_View.Item2, m_View.Item3, m_View.Item4, m_View.Item5, m_View.Item6, m_View.Item7, m_View.Item8, m_View.Item9 };
        m_PlayerData = DataSystem.Instance.GetDataJoeyPlayer();
        m_CurrentCardType = ECardType.other;
    }



    void OnBtnCloseClick()
    {
        Close();
    }

    void OnBtnAttackClick()
    {
        RefreshCardsByType(ECardType.attack);
    }
    void OnBtnDefenceClick()
    {
        RefreshCardsByType(ECardType.defence);
    }
    void OnBtnItemClick()
    {
        RefreshCardsByType(ECardType.item);
    }
    void OnBtnSkillClick()
    {
        RefreshCardsByType(ECardType.skill);
    }




    public void RefreshCardsByType(ECardType cardType, bool isSaveBuild = true)
    {
        if (isSaveBuild && m_CurrentCardType != ECardType.other)
        {
            SaveBuild(m_CurrentCardType);
        }
        m_CurrentCardType = cardType;

        m_View.SelectAttack.SetActive(false);
        m_View.SelectDefence.SetActive(false);
        m_View.SelectItem.SetActive(false);
        m_View.SelectSkill.SetActive(false);

        switch (cardType)
        {
            case ECardType.attack:
                m_View.SelectAttack.SetActive(true);
                break;
            case ECardType.defence:
                m_View.SelectDefence.SetActive(true);
                break;
            case ECardType.item:
                m_View.SelectItem.SetActive(true);
                break;
            case ECardType.skill:
                m_View.SelectSkill.SetActive(true);
                break;
            default:
                return;
        }

        List<string> cardIds = new List<string>();
        for (int i = 0; i < m_PlayerData.EnvCardPool.Count; i++)
        {
            string cardId = m_PlayerData.EnvCardPool[i];
            Card cardConfig = GData.Instance.GetCardConfigById(cardId);
            if (cardConfig != null && cardConfig.GetCardType() == cardType)
            {
                cardIds.Add(cardId);
            }
        }

        while (CardList.Count < cardIds.Count)
        {
            UIBuildCardControl cardControl = Asset.OpenUI<UIBuildCardControl>(m_View.Content);
            int index = CardList.Count;
            if (index < m_ItemArray.Length)
            {
                cardControl.CacheTrans.localPosition = m_ItemArray[index].localPosition;
            }
            else
            {
                cardControl.CacheTrans.localPosition = Vector3.zero;
            }
            cardControl.CacheTrans.localScale = Vector3.one * 0.6f;
            cardControl.EquipIndex = index;
            cardControl.OnDragEndHandler = OnCardDragEnd;
            CardList.Add(cardControl);
        }

        for (int i = 0; i < CardList.Count; i++)
        {
            UIBuildCardControl cardControl = CardList[i];
            if (i < cardIds.Count)
            {
                string cardId = cardIds[i];
                Card cardConfig = GData.Instance.GetCardConfigById(cardId);
                if (cardConfig != null)
                {
                    cardControl.gameObject.SetActive(true);
                    cardControl.SetData(cardConfig);
                }
                else
                {
                    cardControl.gameObject.SetActive(false);
                }
            }
            else
            {
                cardControl.gameObject.SetActive(false);
            }
        }
    }

    public void SetShopData()
    {
        RefreshCardsByType(ECardType.attack);
    }

    public void SaveBuild(ECardType cardType)
    {
    }

    private void OnCardDragEnd(UIBuildCardControl draggedCard, PointerEventData eventData)
    {
        if (CheckCardInDeleteArea(draggedCard, eventData))
        {
            DeleteCard(draggedCard);
            return;
        }

        int index = draggedCard.EquipIndex;
        if (index < m_ItemArray.Length)
        {
            RectTransform rectTransform = draggedCard.CacheTrans as RectTransform;
            if (rectTransform != null)
            {
                rectTransform.localPosition = m_ItemArray[index].localPosition;
            }
        }
    }

    private bool CheckCardInDeleteArea(UIBuildCardControl draggedCard, PointerEventData eventData)
    {
        if (m_View.BtnDelete == null || draggedCard.CardData == null)
        {
            return false;
        }

        RectTransform deleteRect = m_View.BtnDelete.rectTransform;
        RectTransform cardRect = draggedCard.CacheTrans as RectTransform;

        if (deleteRect == null || cardRect == null)
        {
            return false;
        }

        Vector3[] deleteCorners = new Vector3[4];
        Vector3[] cardCorners = new Vector3[4];
        deleteRect.GetWorldCorners(deleteCorners);
        cardRect.GetWorldCorners(cardCorners);

        Rect deleteRectWorld = new Rect(deleteCorners[0].x, deleteCorners[0].y,
            deleteCorners[2].x - deleteCorners[0].x,
            deleteCorners[2].y - deleteCorners[0].y);

        Rect cardRectWorld = new Rect(cardCorners[0].x, cardCorners[0].y,
            cardCorners[2].x - cardCorners[0].x,
            cardCorners[2].y - cardCorners[0].y);

        return deleteRectWorld.Overlaps(cardRectWorld);
    }

    private void DeleteCard(UIBuildCardControl draggedCard)
    {
        if (draggedCard.CardData == null)
        {
            return;
        }

        Card card = draggedCard.CardData;
        string cardId = card.id;

        m_PlayerData.RemoveEnvCardPoolData(cardId);

        int halfPrice = Mathf.RoundToInt(card.price / 2f);
        DataSystem.Instance.AddCoin(halfPrice);

        DataSystem.Instance.SaveDataJoeyPlayer();

        int index = draggedCard.EquipIndex;
        if (index < m_ItemArray.Length)
        {
            RectTransform rectTransform = draggedCard.CacheTrans as RectTransform;
            if (rectTransform != null)
            {
                rectTransform.localPosition = m_ItemArray[index].localPosition;
            }
        }

        draggedCard.gameObject.SetActive(false);

        RefreshCardsByType(m_CurrentCardType, false);
    }

    protected override void OnReturn()
    {
        CardList.Clear();

        base.OnReturn();
    }
}

