//This File Is Auto Generated By Process Control
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class UIBuildCardNewControl : YViewControl
{
	private UIBuildCardNewView m_View;

    private Card m_CachedCard;
    private ECardType m_CachedCardType;
    public Transform CacheTrans;
    private Vector3 m_OriginalScale = Vector3.zero;
    public int EquipIndex;
    public System.Action<UIBuildCardNewControl> BuildClickHandler;
    public System.Action<UIBuildCardNewControl, PointerEventData> OnDragEndHandler;

    public ECardType CardType => m_CachedCardType;
    public Card CardData => m_CachedCard;

    public static EResType GetResType()
    {
        return EResType.UIBuildCardNew;
    }

    protected override void OnInit()
    {
        base.OnInit();
        CacheTrans = transform;
        if (m_OriginalScale == Vector3.zero)
        {
            m_OriginalScale = CacheTrans.localScale;
        }
        m_View = CreateView<UIBuildCardNewView>();
        m_View.BtnCard.onClick.AddListener(OnBtnCardClick);

        m_View.Trigger.onBeginDrag = OnBeginDrag;
        m_View.Trigger.onDrag = OnDrag;
        m_View.Trigger.onEndDrag = OnEndDrag;
        SetRaycastTargetFalse();
        CacheTrans.localScale = m_OriginalScale;
    }

    private void OnBeginDrag(GameObject go, PointerEventData eventData)
    {
    }

    private void OnDrag(GameObject go, PointerEventData eventData)
    {
        RectTransform rectTransform = CacheTrans as RectTransform;
        if (rectTransform != null)
        {
            rectTransform.SetAsLastSibling();

            RectTransform parentRect = rectTransform.parent as RectTransform;
            if (parentRect != null && RectTransformUtility.ScreenPointToLocalPointInRectangle(
                parentRect,
                eventData.position,
                eventData.pressEventCamera,
                out Vector2 localPos))
            {
                rectTransform.localPosition = localPos;
            }
        }
    }

    private void OnEndDrag(GameObject go, PointerEventData eventData)
    {
        if (OnDragEndHandler != null)
        {
            OnDragEndHandler(this, eventData);
        }
    }

    public void ResetScale()
    {
        CacheTrans.localScale = m_OriginalScale;
    }

    private void SetRaycastTargetFalse()
    {
        GameObject triggerObj = m_View.Trigger.gameObject;

        Image[] images = GetComponentsInChildren<Image>(true);
        for (int i = 0; i < images.Length; i++)
        {
            if (images[i].gameObject != gameObject && images[i].gameObject != triggerObj)
            {
                images[i].raycastTarget = false;
            }
        }

        Text[] texts = GetComponentsInChildren<Text>(true);
        for (int i = 0; i < texts.Length; i++)
        {
            if (texts[i].gameObject != gameObject && texts[i].gameObject != triggerObj)
            {
                texts[i].raycastTarget = false;
            }
        }
    }

    private void OnBtnCardClick()
    {
        BuildClickHandler?.Invoke(this);
    }

    public void SetData(Card card, bool isEquipedSlot = true)
    {
        m_CachedCard = card;
        m_CachedCardType = (ECardType)System.Enum.Parse(typeof(ECardType), card.type);

        m_View.CardName.text = card.cardName;
        m_View.CardImg.sprite = LoadSprite(card.cardImage);

        SetTypeUI(card);
        SetStars(card.stars);
    }

    private void SetTypeUI(Card card)
    {
        m_View.Attack.SetActive(false);
        m_View.Defence.SetActive(false);

        switch (m_CachedCardType)
        {
            case ECardType.attack:
                m_View.Attack.SetActive(true);
                m_View.TxtAttack.text = card.attack.ToString();
                break;

            case ECardType.defence:
                m_View.Defence.SetActive(true);
                m_View.TxtDefence.text = card.defence.ToString();
                break;

            default:
                break;
        }

        SetStars(m_CachedCard.stars);
    }

    private void SetStars(int stars)
    {
        stars = Mathf.Clamp(stars, 0, 3);
        int childCount = m_View.StarLayout.transform.childCount;
        for (int i = 0; i < childCount; i++)
        {
            GameObject starObj = m_View.StarLayout.transform.GetChild(i).gameObject;
            starObj.SetActive(i < stars);
        }
    }

    private Sprite LoadSprite(string path)
    {
        return Resources.Load<Sprite>(path);
    }
}
