//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using UnityEngine;

public class UICardProgressControl : YViewControl
{
	private UICardProgressView m_View;
	private List<UIPreviewCardControl> m_PreviewCardList = new List<UIPreviewCardControl>();

	public static EResType GetResType()
	{
		return EResType.UICardProgress;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UICardProgressView>();
		m_View.BtnClose.onClick.AddListener(OnBtnCloseClick);
	}

	void OnBtnCloseClick()
	{
		Close();
	}

	public void SetData()
	{
		GData.Instance.LoadCards();
		Dictionary<string, Card> cardDict = GData.Instance.CardDict;
		DataCardProgress cardProgress = DataSystem.Instance.GetDataCardProgress();

		foreach (Card card in cardDict.Values)
		{
			UIPreviewCardControl cardControl = Asset.OpenUI<UIPreviewCardControl>(m_View.Content);
			cardControl.CacheTrans.localScale = Vector3.one * 0.7f;
			cardControl.CacheTrans.localPosition = Vector3.zero;
			cardControl.CacheTrans.localEulerAngles = Vector3.zero;
			cardControl.SetData(card);
			m_PreviewCardList.Add(cardControl);
		}

		m_PreviewCardList.Sort((a, b) =>
		{
			bool aExists = cardProgress.GetCardIdDictData(a.CardData.id) > 0;
			bool bExists = cardProgress.GetCardIdDictData(b.CardData.id) > 0;

			if (aExists && !bExists)
			{
				return -1;
			}
			else if (!aExists && bExists)
			{
				return 1;
			}
			return 0;
		});

		for (int i = 0; i < m_PreviewCardList.Count; i++)
		{
			m_PreviewCardList[i].CacheTrans.SetSiblingIndex(i);
		}
	}

	protected override void OnClose()
	{
		for (int i = 0; i < m_PreviewCardList.Count; i++)
		{
			if (m_PreviewCardList[i] != null)
			{
				m_PreviewCardList[i].CleanupDescExt();
				m_PreviewCardList[i].Close();
			}
		}
		m_PreviewCardList.Clear();
		base.OnClose();
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}