//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UICardSimpleView : YBaseView
{
	public Animator Anim;
	public Image CardImg;
	public Image CardFrame;
	public Text CardName;
	public Image IconType;
	public Text Description;
	public Text TxtAttack;
	public Text TextHeart;
	public Text TxtDefence;
	public GameObject Attack;
	public GameObject Moster;
	public GameObject Defence;
	public GameObject StarLayout;
	public Button BtnCard;
	public EventTriggerListener Trigger;
	public Text Text;
	public GameObject Price;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		Anim = viewItemList[0].Target.GetComponent<Animator>();
		CardImg = viewItemList[1].Target.GetComponent<Image>();
		CardFrame = viewItemList[2].Target.GetComponent<Image>();
		CardName = viewItemList[3].Target.GetComponent<Text>();
		IconType = viewItemList[4].Target.GetComponent<Image>();
		Description = viewItemList[5].Target.GetComponent<Text>();
		TxtAttack = viewItemList[6].Target.GetComponent<Text>();
		TextHeart = viewItemList[7].Target.GetComponent<Text>();
		TxtDefence = viewItemList[8].Target.GetComponent<Text>();
		Attack = viewItemList[9].Target.gameObject;
		Moster = viewItemList[10].Target.gameObject;
		Defence = viewItemList[11].Target.gameObject;
		StarLayout = viewItemList[12].Target.gameObject;
		BtnCard = viewItemList[13].Target.GetComponent<Button>();
		Trigger = viewItemList[13].Target.GetComponent<EventTriggerListener>();
		Text = viewItemList[14].Target.GetComponent<Text>();
		Price = viewItemList[15].Target.gameObject;
	}
}