//This File Is Auto Generated By Process Control
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public enum ECardType
{
	attack,
	defence,
	monster,
	skill,
	item,
	other
}

public class UICardSimpleControl : YViewControl
{
	private UICardSimpleView m_View;
	private Card cachedCard;
	private ECardType cachedCardType;
	public bool IsEnv;
	private int m_EnvIndex = -1;
	public Transform CacheTrans;


	public ECardType CardType => cachedCardType;
	public Card CardData => cachedCard;
	public int EnvIndex => m_EnvIndex;
	private List<GameObject> EffectEntityList = new List<GameObject>();

	public YCardEffect CardEffect;

	public static EResType GetResType()
	{
		return EResType.UICardSimple;
	}

	protected override void OnInit()
	{
		base.OnInit();
		CacheTrans = transform;
		m_View = CreateView<UICardSimpleView>();
		m_View.BtnCard.onClick.AddListener(OnBtnCardClick);

		SetRaycastTargetFalse();
	}

	private void SetRaycastTargetFalse()
	{
		Image[] images = GetComponentsInChildren<Image>(true);
		for (int i = 0; i < images.Length; i++)
		{
			if (images[i].gameObject != gameObject)
			{
				images[i].raycastTarget = false;
			}
		}

		Text[] texts = GetComponentsInChildren<Text>(true);
		for (int i = 0; i < texts.Length; i++)
		{
			if (texts[i].gameObject != gameObject)
			{
				texts[i].raycastTarget = false;
			}
		}
	}

	void OnBtnCardClick()
	{
		if (IsEnv)
		{
			if (cachedCardType == ECardType.monster)
			{
				YActionSystem.Instance.DispatchAction(EActionId.TakeEnemyDamage, this, 1, m_EnvIndex);
			}
			else if (cachedCardType == ECardType.other)
			{
				JoeyGameControl.Instance.LoadNextLevel();
			}
			else
			{
				YActionSystem.Instance.DispatchAction(EActionId.MoveCard, IsEnv, this);
			}
		}
		else
		{
			switch (cachedCardType)
			{
				case ECardType.skill:
					CardEffect?.UseSkill();
					break;
				case ECardType.item:
					CardEffect?.UseItem();
					break;
			}
		}
	}

	public void CallCardTakeDamage(int damage)
	{
		Debug.Log(CardData.cardName);
		cachedCard.TakeDamage(damage);
		CardEffect?.OnTakeDamage();
		RefreshCard();
	}

	public void RefreshCard()
	{
		m_View.CardName.text = cachedCard.cardName;
		m_View.Description.text = cachedCard.description;

		switch (cachedCardType)
		{
			case ECardType.attack:
				m_View.TxtAttack.text = cachedCard.currentAttack.ToString();
				break;

			case ECardType.defence:
				m_View.TxtDefence.text = cachedCard.currentDefence.ToString();
				break;

			case ECardType.monster:
				m_View.TxtAttack.text = cachedCard.currentAttack.ToString();
				m_View.TextHeart.text = cachedCard.currentHealth.ToString();
				break;

			case ECardType.skill:
				break;

			case ECardType.item:
				break;

			case ECardType.other:
				break;

			default:
				break;
		}

		SetStars(cachedCard.stars);
	}

	public YCardEffect GetCardEffect()
	{
		if (cachedCard.effectIds == null || cachedCard.effectIds.Count == 0)
		{
			return GetDefaultEffect();
		}

		string effectIdStr = cachedCard.effectIds[0];
		string effectId;
		int effectValue;
		cachedCard.ParseEffectId(effectIdStr, out effectId, out effectValue);

		ECardEffectId effectIdEnum;
		if (!System.Enum.TryParse<ECardEffectId>(effectId, out effectIdEnum))
		{
			return GetDefaultEffect();
		}

		YCardEffect effect = null;
		switch (effectIdEnum)
		{
			case ECardEffectId.BounceToRandomEnemy_OnDealDamage:
				effect = new YBounceToRandomEnemy_OnDealDamage(effectValue);
				break;
			case ECardEffectId.ExtraDamage_OnDealDamage:
				effect = new YExtraDamage_OnDealDamage(effectValue);
				break;
			case ECardEffectId.Boom_OnKill:
				effect = new YBoom_OnKill(effectValue);
				break;
			case ECardEffectId.DealRandomEnemyEqualToAttack_OnTop:
				effect = new YDealRandomEnemyEqualToAttack_OnTop();
				break;
			case ECardEffectId.DealDamage_UseDefence:
				effect = new YDealDamage_UseDefence(effectValue);
				break;
			case ECardEffectId.Boom_OnPlay:
				effect = new YBoom_OnPlay(effectValue);
				break;
			case ECardEffectId.DoubleAttack_OnDealDamage:
				effect = new YDoubleAttack_OnDealDamage();
				break;
			case ECardEffectId.ExtraDamage_NoDefence:
				effect = new YExtraDamage_NoDefence(effectValue);
				break;
			case ECardEffectId.Electric:
				effect = new YElectric(effectValue);
				break;
			case ECardEffectId.DoubleAttack_OnPlay:
				effect = new YDoubleAttack_OnPlay();
				break;
			case ECardEffectId.HookEquipWeaponFromDiscard_OnDefence:
				effect = new YHookEquipWeaponFromDiscard_OnDefence();
				break;
			case ECardEffectId.HookEquipWeaponFromDiscard_OnPlay:
				effect = new YHookEquipWeaponFromDiscard_OnPlay();
				break;
			case ECardEffectId.LifeSteal_OnDealDamage:
				effect = new YLifeSteal_OnDealDamage(effectValue);
				break;
			case ECardEffectId.HealPlayer_OnPlay:
				effect = new YHealPlayer_OnPlay(effectValue);
				break;
			default:
				return GetDefaultEffect();
		}

		effect.SetData(this);
		return effect;
	}

	private YCardEffect GetDefaultEffect()
	{
		YDefaultEffect effect = new YDefaultEffect();
		effect.SetData(this);
		return effect;
	}

	public void SetData(Card card, bool isEnv = false, int envIndex = -1)
	{
		cachedCard = card;
		cachedCardType = (ECardType)System.Enum.Parse(typeof(ECardType), card.type);
		IsEnv = isEnv;
		m_EnvIndex = envIndex;

		m_View.CardName.text = card.cardName;
		m_View.CardImg.sprite = LoadSprite(card.cardImage);
		m_View.Description.text = card.description;
		m_View.IconType.sprite = LoadSprite(card.iconType);
		m_View.CardFrame.sprite = LoadSprite(card.cardFrame);

		SetTypeUI(card);
		SetStars(card.stars);
		CardEffect = GetCardEffect();
	}

	private void SetTypeUI(Card card)
	{
		m_View.Attack.SetActive(false);
		m_View.Defence.SetActive(false);
		m_View.Moster.SetActive(false);

		switch (cachedCardType)
		{
			case ECardType.attack:
				m_View.Attack.SetActive(true);
				m_View.TxtAttack.text = card.attack.ToString();
				break;

			case ECardType.defence:
				m_View.Defence.SetActive(true);
				m_View.TxtDefence.text = card.defence.ToString();
				break;

			case ECardType.monster:
				m_View.Attack.SetActive(true);
				m_View.TxtAttack.text = card.attack.ToString();
				m_View.Moster.SetActive(true);
				m_View.TextHeart.text = card.currentHealth.ToString();
				break;

			case ECardType.skill:
				break;

			case ECardType.item:
				break;

			case ECardType.other:
				m_View.IconType.gameObject.SetActive(false);
				break;

			default:
				break;
		}
	}

	private void SetStars(int stars)
	{
		stars = Mathf.Clamp(stars, 0, 3);
		int childCount = m_View.StarLayout.transform.childCount;
		for (int i = 0; i < childCount; i++)
		{
			var starObj = m_View.StarLayout.transform.GetChild(i).gameObject;
			starObj.SetActive(i < stars);
		}
	}

	private Sprite LoadSprite(string path)
	{
		return Resources.Load<Sprite>(path);
	}

	public void PlayVFX(List<string> cardEffects = null, string animName = null)
	{
		if (!string.IsNullOrEmpty(animName))
		{
			m_View.Anim.CrossFade(animName, 0, 0);
		}

		if (cardEffects != null && cardEffects.Count > 0)
		{
			for (int i = 0; i < cardEffects.Count; i++)
			{
				string effectName = cardEffects[i];
				var vfxPrefab = Resources.Load<GameObject>("VFX/" + effectName);
				var instance = Instantiate(vfxPrefab, CacheTrans);

				EffectEntityList.Add(instance);
			}
		}
	}

	public void StopVFX()
	{
		m_View.Anim.CrossFade("idle", 0, 0);

		for (int i = 0; i < EffectEntityList.Count; i++)
		{
			var go = EffectEntityList[i];
			if (go != null)
			{
				Destroy(go);
			}
		}
		EffectEntityList.Clear();
	}

	protected override void OnReturn()
	{

		CardEffect.StopAllEffects();

		for (int i = 0; i < EffectEntityList.Count; i++)
		{
			var go = EffectEntityList[i];
			if (go != null)
			{
				Destroy(go);
			}
		}
		gameObject.SetActive(false);
		EffectEntityList.Clear();
		base.OnReturn();
	}
}