//This File Is Auto Generated By Process Control
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public enum ECardType
{
	attack,
	defence,
	monster,
	skill,
	item,
	other
}

public class UICardSimpleControl : YViewControl
{
	private UICardSimpleView m_View;
	private Card cachedCard;
	private ECardType cachedCardType;
	private bool IsEnv;


	public ECardType CardType => cachedCardType;
	public Card Card => cachedCard;
	private Dictionary<string, List<GameObject>> TriggerEffectDict = new Dictionary<string, List<GameObject>>();

	public static EResType GetResType()
	{
		return EResType.UICardSimple;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UICardSimpleView>();
		m_View.BtnCard.onClick.AddListener(OnBtnCardClick);

		SetRaycastTargetFalse();
	}

	private void SetRaycastTargetFalse()
	{
		Image[] images = GetComponentsInChildren<Image>(true);
		for (int i = 0; i < images.Length; i++)
		{
			if (images[i].gameObject != gameObject)
			{
				images[i].raycastTarget = false;
			}
		}

		Text[] texts = GetComponentsInChildren<Text>(true);
		for (int i = 0; i < texts.Length; i++)
		{
			if (texts[i].gameObject != gameObject)
			{
				texts[i].raycastTarget = false;
			}
		}
	}

	void OnBtnCardClick()
	{
		if (IsEnv)
		{
			if (cachedCardType == ECardType.monster)
			{
				YActionSystem.Instance.DispatchAction(EActionId.TakeEnemy, this);
			}
			else if (cachedCardType == ECardType.other)
			{
				JoeyGameControl.Instance.LoadNextLevel();
			}
			else
			{
				YActionSystem.Instance.DispatchAction(EActionId.MoveCard, IsEnv, this);
			}
		}
	}

	public void CallCardTakeDamage(int damage)
	{
		Debug.Log("CallCardTakeDamage");
		cachedCard.TakeDamage(damage);
		RefreshCard();
	}

	public void RefreshCard()
	{
		m_View.CardName.text = cachedCard.cardName;
		m_View.Description.text = cachedCard.description;

		switch (cachedCardType)
		{
			case ECardType.attack:
				m_View.TxtAttack.text = cachedCard.currentAttack.ToString();
				break;

			case ECardType.defence:
				m_View.TxtDefence.text = cachedCard.currentDefence.ToString();
				break;

			case ECardType.monster:
				m_View.TxtAttack.text = cachedCard.currentAttack.ToString();
				m_View.TextHeart.text = cachedCard.currentHealth.ToString();
				break;

			case ECardType.skill:
				break;

			case ECardType.item:
				break;

			case ECardType.other:
				break;

			default:
				break;
		}

		SetStars(cachedCard.stars);
	}

	public void SetData(Card card, bool isEnv = false)
	{
		cachedCard = card;
		cachedCardType = (ECardType)System.Enum.Parse(typeof(ECardType), card.type);
		IsEnv = isEnv;

		m_View.CardName.text = card.cardName;
		m_View.CardImg.sprite = LoadSprite(card.cardImage);
		m_View.Description.text = card.description;
		m_View.IconType.sprite = LoadSprite(card.iconType);
		m_View.CardFrame.sprite = LoadSprite(card.cardFrame);

		SetTypeUI(card);
		SetStars(card.stars);
	}

	private void SetTypeUI(Card card)
	{
		m_View.Attack.SetActive(false);
		m_View.Defence.SetActive(false);
		m_View.Moster.SetActive(false);

		switch (cachedCardType)
		{
			case ECardType.attack:
				m_View.Attack.SetActive(true);
				m_View.TxtAttack.text = card.attack.ToString();
				break;

			case ECardType.defence:
				m_View.Defence.SetActive(true);
				m_View.TxtDefence.text = card.defence.ToString();
				break;

			case ECardType.monster:
				m_View.Attack.SetActive(true);
				m_View.TxtAttack.text = card.attack.ToString();
				m_View.Moster.SetActive(true);
				m_View.TextHeart.text = card.currentHealth.ToString();
				break;

			case ECardType.skill:
				break;

			case ECardType.item:
				break;

			case ECardType.other:
				m_View.IconType.gameObject.SetActive(false);
				break;

			default:
				break;
		}
	}

	private void SetStars(int stars)
	{
		stars = Mathf.Clamp(stars, 0, 3);
		int childCount = m_View.StarLayout.transform.childCount;
		for (int i = 0; i < childCount; i++)
		{
			var starObj = m_View.StarLayout.transform.GetChild(i).gameObject;
			starObj.SetActive(i < stars);
		}
	}

	private Sprite LoadSprite(string path)
	{
		return Resources.Load<Sprite>(path);
	}

	public void PlayVFX(string cardTrigger = null, List<string> cardEffects = null, string animName = null)
	{
		if (!string.IsNullOrEmpty(animName))
		{
			m_View.Anim.CrossFade(animName, 0.1f, 0);
		}

		if (cardEffects != null && cardEffects.Count > 0)
		{
			if (!TriggerEffectDict.ContainsKey(cardTrigger))
			{
				TriggerEffectDict[cardTrigger] = new List<GameObject>();
			}
			var list = TriggerEffectDict[cardTrigger];

			for (int i = 0; i < cardEffects.Count; i++)
			{
				string effectName = cardEffects[i];
				var vfxPrefab = Resources.Load<GameObject>("VFX/" + effectName);
				var instance = Instantiate(vfxPrefab);
				instance.transform.SetParent(transform);
				instance.transform.localPosition = Vector3.zero;
				instance.transform.localRotation = Quaternion.identity;
				list.Add(instance);
			}
		}
	}

	public void StopVFX(string cardTrigger)
	{
		m_View.Anim.CrossFade("Idle", 0.1f, 0);

		if (TriggerEffectDict.TryGetValue(cardTrigger, out var list))
		{
			for (int i = 0; i < list.Count; i++)
			{
				var go = list[i];
				Destroy(go);
			}
			list.Clear();
		}
	}

	protected override void OnReturn()
	{
		YActionSystem.Instance.DispatchAction(EActionId.RemoveCard, cachedCard.UniqueId);

		foreach (var kv in TriggerEffectDict)
		{
			var list = kv.Value;
			for (int i = 0; i < list.Count; i++)
			{
				Destroy(list[i]);
			}
			list.Clear();
		}
		TriggerEffectDict.Clear();
		base.OnReturn();
	}
}