//This File Is Auto Generated By Process Control
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using Cysharp.Threading.Tasks;
using System.Threading;

public enum ECardType
{
	attack,
	defence,
	monster,
	skill,
	item,
	other
}

public class UICardSimpleControl : YViewControl
{
	private UICardSimpleView m_View;
	private Card cachedCard;
	private ECardType cachedCardType;
	public bool IsEnv;
	private int m_EnvIndex = -1;
	public Transform CacheTrans;


	public ECardType CardType => cachedCardType;
	public Card CardData => cachedCard;
	public int EnvIndex => m_EnvIndex;
	private List<Transform> EffectEntityList = new List<Transform>();
	private List<CancellationTokenSource> CancelTokenList = new List<CancellationTokenSource>();
	private Vector3 m_OriginalScale;
	private bool m_IsMoving;

	public YCardEffect CardEffect;

	public static EResType GetResType()
	{
		return EResType.UICardSimple;
	}

	protected override void OnInit()
	{
		base.OnInit();
		CacheTrans = transform;
		m_View = CreateView<UICardSimpleView>();
		m_View.BtnCard.onClick.AddListener(OnBtnCardClick);

		if (m_View.Trigger != null)
		{
			m_View.Trigger.onEnter = OnPointerEnter;
			m_View.Trigger.onExit = OnPointerExit;
		}

		SetRaycastTargetFalse();
	}

	private void OnPointerEnter(GameObject go, UnityEngine.EventSystems.PointerEventData eventData)
	{
		if (m_IsMoving) return;
		m_OriginalScale = CacheTrans.localScale;
		CacheTrans.localScale = m_OriginalScale * 1.1f;
	}

	private void OnPointerExit(GameObject go, UnityEngine.EventSystems.PointerEventData eventData)
	{
		if (m_IsMoving) return;
		CacheTrans.localScale = m_OriginalScale;
	}

	public void SetMoving(bool isMoving)
	{
		m_IsMoving = isMoving;
	}

	private void SetRaycastTargetFalse()
	{
		Image[] images = GetComponentsInChildren<Image>(true);
		for (int i = 0; i < images.Length; i++)
		{
			if (images[i].gameObject != gameObject)
			{
				images[i].raycastTarget = false;
			}
		}

		Text[] texts = GetComponentsInChildren<Text>(true);
		for (int i = 0; i < texts.Length; i++)
		{
			if (texts[i].gameObject != gameObject)
			{
				texts[i].raycastTarget = false;
			}
		}
	}

	void OnBtnCardClick()
	{
		if (IsEnv)
		{
			if (cachedCardType == ECardType.monster)
			{
				YActionSystem.Instance.DispatchAction(EActionId.TakeEnemyDamage, this, 1, m_EnvIndex);
			}
			else if (cachedCardType == ECardType.other)
			{
				JoeyGameControl.Instance.LoadNextLevel();
			}
			else
			{
				YActionSystem.Instance.DispatchAction(EActionId.MoveCard, IsEnv, this);
			}
		}
		else
		{
			switch (cachedCardType)
			{
				case ECardType.skill:
				case ECardType.item:
					YActionSystem.Instance.DispatchAction(EActionId.UseBagCard, this);
					break;
			}
		}
	}

	public void CallCardTakeDamage(int damage, EEffectType effectType = EEffectType.Damage)
	{
		Debug.Log(CardData.cardName);
		cachedCard.TakeDamage(damage);
		CardEffect?.OnTakeDamage(effectType);
		RefreshCard();
	}

	public void RefreshCard()
	{
		m_View.CardName.text = cachedCard.cardName;
		m_View.Description.text = cachedCard.description;

		switch (cachedCardType)
		{
			case ECardType.attack:
				m_View.TxtAttack.text = cachedCard.currentAttack.ToString();
				break;

			case ECardType.defence:
				m_View.TxtDefence.text = cachedCard.currentDefence.ToString();
				break;

			case ECardType.monster:
				m_View.TxtAttack.text = cachedCard.currentAttack.ToString();
				m_View.TextHeart.text = cachedCard.currentHealth.ToString();
				break;

			case ECardType.skill:
				break;

			case ECardType.item:
				break;

			case ECardType.other:
				break;

			default:
				break;
		}

		SetStars(cachedCard.stars);
	}

	public YCardEffect GetCardEffect()
	{
		if (cachedCard.effectIds == null || cachedCard.effectIds.Count == 0)
		{
			return GetDefaultEffect();
		}

		string effectIdStr = cachedCard.effectIds[0];
		string effectId;
		int effectValue;
		cachedCard.ParseEffectId(effectIdStr, out effectId, out effectValue);

		ECardEffectId effectIdEnum;
		if (!System.Enum.TryParse<ECardEffectId>(effectId, out effectIdEnum))
		{
			return GetDefaultEffect();
		}

		YCardEffect effect = null;
		switch (effectIdEnum)
		{
			case ECardEffectId.BounceToRandomEnemy_OnDealDamage:
				effect = new YBounceToRandomEnemy_OnDealDamage(effectValue);
				break;
			case ECardEffectId.ExtraDamage_OnDealDamage:
				effect = new YExtraDamage_OnDealDamage(effectValue);
				break;
			case ECardEffectId.Boom_OnDead:
				effect = new YBoom_OnDead(effectValue);
				break;
			case ECardEffectId.DealRandomEnemyEqualToAttack_OnTop:
				effect = new YDealRandomEnemyEqualToAttack_OnTop();
				break;
			case ECardEffectId.DealDamage_UseDefence:
				effect = new YDealDamage_UseDefence(effectValue);
				break;
			case ECardEffectId.Boom_OnPlay:
				effect = new YBoom_OnPlay(effectValue);
				break;
			case ECardEffectId.DoubleAttack_OnDealDamage:
				effect = new YDoubleAttack_OnDealDamage();
				break;
			case ECardEffectId.ExtraDamage_NoDefence:
				effect = new YExtraDamage_NoDefence(effectValue);
				break;
			case ECardEffectId.Electric:
				effect = new YElectric(effectValue);
				break;
			case ECardEffectId.DoubleAttack_OnPlay:
				effect = new YDoubleAttack_OnPlay();
				break;
			case ECardEffectId.HookEquipWeaponFromDiscard_OnDefence:
				effect = new YHookEquipWeaponFromDiscard_OnDefence();
				break;
			case ECardEffectId.HookEquipWeaponFromDiscard_OnPlay:
				effect = new YHookEquipWeaponFromDiscard_OnPlay();
				break;
			case ECardEffectId.LifeSteal_OnDealDamage:
				effect = new YLifeSteal_OnDealDamage(effectValue);
				break;
			case ECardEffectId.HealPlayer_OnPlay:
				effect = new YHealPlayer_OnPlay(effectValue);
				break;
			default:
				return GetDefaultEffect();
		}

		effect.SetData(this);
		return effect;
	}

	private YCardEffect GetDefaultEffect()
	{
		YDefaultEffect effect = new YDefaultEffect();
		effect.SetData(this);
		return effect;
	}

	public void SetData(Card card, bool isEnv = false, int envIndex = -1)
	{
		cachedCard = card;
		cachedCardType = (ECardType)System.Enum.Parse(typeof(ECardType), card.type);
		IsEnv = isEnv;
		m_EnvIndex = envIndex;

		m_View.CardName.text = card.cardName;
		m_View.CardImg.sprite = LoadSprite(card.cardImage);
		m_View.Description.text = card.description;
		m_View.IconType.sprite = LoadSprite(card.iconType);
		m_View.CardFrame.sprite = LoadSprite(card.cardFrame);

		SetTypeUI(card);
		SetStars(card.stars);
		CardEffect = GetCardEffect();
	}

	private void SetTypeUI(Card card)
	{
		m_View.Attack.SetActive(false);
		m_View.Defence.SetActive(false);
		m_View.Moster.SetActive(false);

		switch (cachedCardType)
		{
			case ECardType.attack:
				m_View.Attack.SetActive(true);
				m_View.TxtAttack.text = card.attack.ToString();
				break;

			case ECardType.defence:
				m_View.Defence.SetActive(true);
				m_View.TxtDefence.text = card.defence.ToString();
				break;

			case ECardType.monster:
				m_View.Attack.SetActive(true);
				m_View.TxtAttack.text = card.attack.ToString();
				m_View.Moster.SetActive(true);
				m_View.TextHeart.text = card.currentHealth.ToString();
				break;

			case ECardType.skill:
				break;

			case ECardType.item:
				break;

			case ECardType.other:
				m_View.IconType.gameObject.SetActive(false);
				break;

			default:
				break;
		}
	}

	private void SetStars(int stars)
	{
		stars = Mathf.Clamp(stars, 0, 3);
		int childCount = m_View.StarLayout.transform.childCount;
		for (int i = 0; i < childCount; i++)
		{
			var starObj = m_View.StarLayout.transform.GetChild(i).gameObject;
			starObj.SetActive(i < stars);
		}
	}

	private Sprite LoadSprite(string path)
	{
		return Resources.Load<Sprite>(path);
	}

	public void PlayVFX(List<EVFXName> vfxNames, ECardAnimName animName = ECardAnimName.None, EVFXLife vfxLife = EVFXLife.CardLife, float delayTime = .5f)
	{
		if (animName != ECardAnimName.None)
		{
			m_View.Anim.CrossFade(animName.ToString(), 0, 0);
		}

		if (vfxNames != null && vfxNames.Count > 0)
		{
			for (int i = 0; i < vfxNames.Count; i++)
			{
				EVFXName vfxName = vfxNames[i];
				if (vfxLife == EVFXLife.SelfLife)
				{
					JoeyGameControl.Instance.PlayEnvVFX(vfxName, m_EnvIndex, delayTime);
				}
				else if (vfxLife == EVFXLife.CardLife)
				{
					Transform vfxTransform = JoeyGameControl.Instance.GetVFX(vfxName, CacheTrans);
					EffectEntityList.Add(vfxTransform);

					DelayHideCardLifeVFX(vfxTransform, delayTime).Forget();

				}
			}
		}
	}


	public async UniTaskVoid DelayHideCardLifeVFX(Transform vfxTransform, float delayTime)
	{
		var cts = new CancellationTokenSource();
		CancelTokenList.Add(cts);
		await UniTask.WaitForSeconds(delayTime, cancellationToken: cts.Token);
		if (vfxTransform != null && vfxTransform.gameObject != null)
		{
			JoeyGameControl.Instance.ReturnVFXPool(vfxTransform, m_EnvIndex);
			EffectEntityList.Remove(vfxTransform);
		}
		CancelTokenList.Remove(cts);
		cts.Dispose();
	}



	public void StopAllEffects()
	{
		for (int i = 0; i < CancelTokenList.Count; i++)
		{
			var cts = CancelTokenList[i];
			if (cts != null && !cts.IsCancellationRequested)
			{
				cts.Cancel();
				cts.Dispose();
			}
		}
		CancelTokenList.Clear();
	}

	protected override void OnReturn()
	{
		StopAllEffects();

		for (int i = 0; i < EffectEntityList.Count; i++)
		{
			var go = EffectEntityList[i];
			if (go != null)
			{
				JoeyGameControl.Instance.ReturnVFXPool(go, m_EnvIndex);
			}
		}
		gameObject.SetActive(false);
		EffectEntityList.Clear();
		base.OnReturn();
	}
}