//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UICardProgressView : YBaseView
{
	public RectTransform Content;
	public Button BtnClose;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		Content = viewItemList[0].Target.GetComponent<RectTransform>();
		BtnClose = viewItemList[1].Target.GetComponent<Button>();
	}
}