//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using UnityEngine;

public enum ECardSchool
{
	None,
	Shuriken,
	Magic,
	Blood,
	Knight,
	Growth,
}

public class UICardProgressControl : YViewControl
{
	private UICardProgressView m_View;
	private List<UIPreviewCardControl> m_PreviewCardList = new List<UIPreviewCardControl>();
	private Dictionary<int, List<UIPreviewCardControl>> m_CardTypeDict = new Dictionary<int, List<UIPreviewCardControl>>();
	private ECardType m_CurrentCardType = ECardType.attack;
	private ECardSchool m_CurrentCardSchool = ECardSchool.None;

	private List<string> m_ShurikenSchoolCards = new List<string>
	{
		"1003", "1013", "1024", "3006", "1018", "2007", "4007", "4008", "2004", "2005"
	};

	private List<string> m_MagicSchoolCards = new List<string>
	{
		"1021", "1022", "2014", "4006", "4013", "4014", "4015", "4016"
	};

	private List<string> m_BloodSchoolCards = new List<string>
	{
		"1008", "1020", "2006", "2012", "3012", "3013", "4010", "4011", "4012"
	};

	private List<string> m_KnightSchoolCards = new List<string>
	{
		"1023", "2015", "2008", "1016", "2011", "2003", "2009", "2010", "2013", "4001", "4003", "4005"
	};

	private List<string> m_GrowthSchoolCards = new List<string>
	{
		"1012", "1013", "2008", "3007", "3008", "3009", "3010"
	};

	public static EResType GetResType()
	{
		return EResType.UICardProgress;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UICardProgressView>();
		m_View.BtnClose.onClick.AddListener(OnBtnCloseClick);
		m_View.BtnAll.onClick.AddListener(() => OnTabClick(ECardType.other));
		m_View.BtnAttack.onClick.AddListener(() => OnTabClick(ECardType.attack));
		m_View.BtnDefence.onClick.AddListener(() => OnTabClick(ECardType.defence));
		m_View.BtnItem.onClick.AddListener(() => OnTabClick(ECardType.item));
		m_View.BtnSkill.onClick.AddListener(() => OnTabClick(ECardType.skill));
		m_View.BtnCardFree.onClick.AddListener(() => OnSchoolClick(ECardSchool.None));
		m_View.BtnCardShuriken.onClick.AddListener(() => OnSchoolClick(ECardSchool.Shuriken));
		m_View.BtnCardMagic.onClick.AddListener(() => OnSchoolClick(ECardSchool.Magic));
		m_View.BtnCardBlood.onClick.AddListener(() => OnSchoolClick(ECardSchool.Blood));
		m_View.BtnCardKnight.onClick.AddListener(() => OnSchoolClick(ECardSchool.Knight));
		m_View.BtnCardGrowth.onClick.AddListener(() => OnSchoolClick(ECardSchool.Growth));
	}

	void OnBtnCloseClick()
	{
		Close();
	}

	void OnTabClick(ECardType cardType)
	{
		m_CurrentCardType = cardType;
		RefreshTabDisplay();
	}

	void OnSchoolClick(ECardSchool cardSchool)
	{
		m_CurrentCardSchool = cardSchool;
		RefreshTabDisplay();
	}

	void RefreshTabDisplay()
	{
		m_View.SelectAll.gameObject.SetActive(m_CurrentCardType == ECardType.other);
		m_View.SelectAttack.gameObject.SetActive(m_CurrentCardType == ECardType.attack);
		m_View.SelectDefence.gameObject.SetActive(m_CurrentCardType == ECardType.defence);
		m_View.SelectItem.gameObject.SetActive(m_CurrentCardType == ECardType.item);
		m_View.SelectSkill.gameObject.SetActive(m_CurrentCardType == ECardType.skill);

		bool showAll = m_CurrentCardType == ECardType.other;
		bool filterBySchool = m_CurrentCardSchool != ECardSchool.None;

		foreach (var kvp in m_CardTypeDict)
		{
			ECardType cardType = (ECardType)kvp.Key;
			bool shouldShowByType = showAll || cardType == m_CurrentCardType;
			foreach (var cardControl in kvp.Value)
			{
				if (cardControl != null)
				{
					bool shouldShow = shouldShowByType;
					if (shouldShow && filterBySchool)
					{
						shouldShow = IsCardInSchool(cardControl.CardData.id, m_CurrentCardSchool);
					}
					cardControl.gameObject.SetActive(shouldShow);
				}
			}
		}
	}

	bool IsCardInSchool(string cardId, ECardSchool school)
	{
		switch (school)
		{
			case ECardSchool.Shuriken:
				return m_ShurikenSchoolCards.Contains(cardId);
			case ECardSchool.Magic:
				return m_MagicSchoolCards.Contains(cardId);
			case ECardSchool.Blood:
				return m_BloodSchoolCards.Contains(cardId);
			case ECardSchool.Knight:
				return m_KnightSchoolCards.Contains(cardId);
			case ECardSchool.Growth:
				return m_GrowthSchoolCards.Contains(cardId);
			case ECardSchool.None:
				return true;
			default:
				return false;
		}
	}

	public void SetData()
	{
		GData.Instance.LoadCards();
		Dictionary<string, Card> cardDict = GData.Instance.CardDict;
		DataCardProgress cardProgress = DataSystem.Instance.GetDataCardProgress();

		HashSet<string> filteredCardIds = new HashSet<string>
		{
			"1000", "1001", "1011", "1019", "2000", "3000",
			"4000", "4002", "4003", "4004", "4005", "4009",
			"5000", "5001", "5007", "5008", "5030", "5031", "5038", "5039"
		};



		foreach (Card card in cardDict.Values)
		{
			if (filteredCardIds.Contains(card.id))
			{
				continue;
			}
			UIPreviewCardControl cardControl = Asset.OpenUI<UIPreviewCardControl>(m_View.Content);
			cardControl.CacheTrans.localScale = Vector3.one * 0.7f;
			cardControl.CacheTrans.localPosition = Vector3.zero;
			cardControl.CacheTrans.localEulerAngles = Vector3.zero;
			cardControl.SetData(card);

			ECardType cardType = card.GetCardType();
			int cardTypeInt = (int)cardType;
			if (!m_CardTypeDict.ContainsKey(cardTypeInt))
			{
				m_CardTypeDict[cardTypeInt] = new List<UIPreviewCardControl>();
			}
			m_CardTypeDict[cardTypeInt].Add(cardControl);
			m_PreviewCardList.Add(cardControl);
		}

		foreach (var kvp in m_CardTypeDict)
		{
			DataCardProgress cardProgressData = DataSystem.Instance.GetDataCardProgress();
			kvp.Value.Sort((a, b) =>
			{
				bool aExists = cardProgressData.GetCardIdDictData(a.CardData.id) > 0;
				bool bExists = cardProgressData.GetCardIdDictData(b.CardData.id) > 0;

				if (aExists && !bExists)
				{
					return -1;
				}
				else if (!aExists && bExists)
				{
					return 1;
				}
				return 0;
			});

			for (int i = 0; i < kvp.Value.Count; i++)
			{
				kvp.Value[i].CacheTrans.SetSiblingIndex(i);
			}
		}

		m_CurrentCardType = ECardType.other;
		m_CurrentCardSchool = ECardSchool.None;
		RefreshTabDisplay();
	}

	protected override void OnClose()
	{
		for (int i = 0; i < m_PreviewCardList.Count; i++)
		{
			if (m_PreviewCardList[i] != null)
			{
				m_PreviewCardList[i].CleanupDescExt();
				m_PreviewCardList[i].Close();
			}
		}
		m_PreviewCardList.Clear();
		m_CardTypeDict.Clear();
		base.OnClose();
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}