//This File Is Auto Generated By Process Control
using UnityEngine;
using UnityEngine.UI;
using System;

public class UICounterControl : YViewControl
{
	private UICounterView m_View;
	private Image[] m_Images;
	private System.Action m_Callback;
	private int m_CurrentIndex = 0;
	private float NextPlayMoment;
	private SoundEffectControl m_SoundEffectControl;

	public static EResType GetResType()
	{
		return EResType.UICounter;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UICounterView>();
	}

	public void SetData(System.Action callback, SoundEffectControl soundEffectControl)
	{
		m_Callback = callback;
		m_SoundEffectControl = soundEffectControl;
		m_Images = new Image[]
		{
			m_View.Four,
			m_View.Three,
			m_View.Two,
			m_View.One,
		};

		m_View.Five.gameObject.SetActive(false);
		m_View.Four.gameObject.SetActive(false);

		for (int i = 0; i < m_Images.Length; i++)
		{
			if (m_Images[i] != null)
			{
				m_Images[i].gameObject.SetActive(false);
			}
		}

		m_CurrentIndex = 0;

		if (m_Images.Length > 0 && m_Images[0] != null)
		{
			m_Images[0].gameObject.SetActive(true);
			int audioIndex = m_Images.Length - m_CurrentIndex;
			string audioName = "Voice_girl_0" + audioIndex;
			if (m_SoundEffectControl != null)
			{
				m_SoundEffectControl.PlayOneShot(audioName);
			}
			m_CurrentIndex++;
			NextPlayMoment = Time.time + 1f;
		}
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}

	private void Update()
	{
		if (m_Images == null) return;

		if (Time.time > NextPlayMoment)
		{
			if (m_CurrentIndex == m_Images.Length)
			{
				if (m_Callback != null)
				{
					m_Callback();
				}
				Destroy(gameObject);
			}
			else
			{
				if (m_CurrentIndex > 0)
				{
					m_Images[m_CurrentIndex - 1].gameObject.SetActive(false);
				}

				m_Images[m_CurrentIndex].gameObject.SetActive(true);

				int audioIndex = m_Images.Length - m_CurrentIndex;
				string audioName = "Voice_girl_0" + audioIndex;
				if (m_SoundEffectControl != null)
				{
					m_SoundEffectControl.PlayOneShot(audioName);
				}

				m_CurrentIndex++;
				NextPlayMoment = Time.time + 1f;
			}
		}
	}
}