//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UICounterView : YBaseView
{
	public Image One;
	public Image Two;
	public Image Three;
	public Image Five;
	public Image Four;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		One = viewItemList[0].Target.GetComponent<Image>();
		Two = viewItemList[1].Target.GetComponent<Image>();
		Three = viewItemList[2].Target.GetComponent<Image>();
		Five = viewItemList[3].Target.GetComponent<Image>();
		Four = viewItemList[4].Target.GetComponent<Image>();
	}
}