//This File Is Auto Generated By Process Control
using UnityEngine;
using Cysharp.Threading.Tasks;

public class UIDamageTextControl : YViewControl
{
	private UIDamageTextView m_View;
	private Animator m_Animator;
	public Transform CacheTrans;

	public static EResType GetResType()
	{
		return EResType.UIDamageText;
	}

	protected override void OnInit()
	{
		base.OnInit();
		CacheTrans = transform;
		m_View = CreateView<UIDamageTextView>();
		m_Animator = GetComponent<Animator>();
	}

	public void SetData(int damage, Transform parent, Vector3 localPositionShift)
	{
		CacheTrans.SetParent(parent);
		CacheTrans.localPosition = localPositionShift;

		if (damage > 0)
		{
			if (m_View.Damage != null)
			{
				m_View.Damage.text = "-" + damage.ToString();
				m_View.Damage.gameObject.SetActive(true);
			}
			if (m_View.Add != null)
			{
				m_View.Add.gameObject.SetActive(false);
			}
		}
		else if (damage < 0)
		{
			if (m_View.Add != null)
			{
				m_View.Add.text = "+" + (-damage).ToString();
				m_View.Add.gameObject.SetActive(true);
			}
			if (m_View.Damage != null)
			{
				m_View.Damage.gameObject.SetActive(false);
			}
		}

		if (m_Animator != null)
		{
			m_Animator.Play("UIDamage_kouxue");
		}

		DelayReturn().Forget();
	}

	private async UniTaskVoid DelayReturn()
	{
		await UniTask.WaitForSeconds(0.8f);
		Return();
	}

	protected override void OnReturn()
	{
		if (m_View.Damage != null)
		{
			m_View.Damage.gameObject.SetActive(false);
		}
		if (m_View.Add != null)
		{
			m_View.Add.gameObject.SetActive(false);
		}
		base.OnReturn();
	}
}