//This File Is Auto Generated By Process Control
using UnityEngine;
using Cysharp.Threading.Tasks;

public class UIDamageTextControl : YViewControl
{
	private UIDamageTextView m_View;
	private Animator m_Animator;
	public Transform CacheTrans;

	public static EResType GetResType()
	{
		return EResType.UIDamageText;
	}

	protected override void OnInit()
	{
		base.OnInit();
		CacheTrans = transform;
		m_View = CreateView<UIDamageTextView>();
		m_Animator = GetComponent<Animator>();
	}

	public void SetData(int value, Transform parent, Vector3 localPositionShift, bool isDamage = true)
	{
		CacheTrans.SetParent(parent);
		CacheTrans.localPosition = localPositionShift;
		CacheTrans.localScale = Vector3.one;

		if (isDamage)
		{
			m_View.Damage.text = "-" + value.ToString();
			m_View.Damage.gameObject.SetActive(true);
			m_View.Add.gameObject.SetActive(false);
		}
		else
		{
			m_View.Add.text = "+" + value.ToString();
			m_View.Add.gameObject.SetActive(true);
			m_View.Damage.gameObject.SetActive(false);
		}

		if (m_Animator != null)
		{
			string animName = isDamage ? "UIDamage_kouxue" : "UIDamage_huixue";
			m_Animator.Play(animName);
		}

		DelayReturn().Forget();
	}

	private async UniTaskVoid DelayReturn()
	{
		await UniTask.WaitForSeconds(0.8f);
		Return();
	}

	protected override void OnReturn()
	{
		m_View.Damage.gameObject.SetActive(false);
		m_View.Add.gameObject.SetActive(false);
		gameObject.SetActive(false);
		CacheTrans.localScale = Vector3.one;
		base.OnReturn();
	}
}