//This File Is Auto Generated By Process Control
using System;
using UnityEngine;
using Cysharp.Threading.Tasks;
using System.Threading;

public class UIDamageTextControl : YViewControl
{
	private UIDamageTextView m_View;
	public Transform CacheTrans;
	private CancellationTokenSource m_DestroyCts;

	public static EResType GetResType()
	{
		return EResType.UIDamageText;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_DestroyCts = new CancellationTokenSource();
		CacheTrans = transform;
		m_View = CreateView<UIDamageTextView>();
	}

	public void SetData(int value, Transform parent, Vector3 localPositionShift, bool isDamage = true)
	{
		m_View.Coin.gameObject.SetActive(false);
		CacheTrans.SetParent(parent);
		CacheTrans.localPosition = localPositionShift;
		CacheTrans.localScale = Vector3.one;

		if (isDamage)
		{
			m_View.Damage.text = "-" + value.ToString();
		}
		else
		{
			m_View.Add.text = "+" + value.ToString();
		}

		string animName = isDamage ? "UIDamage_kouxue" : "UIDamage_huixue";
		m_View.Anim.Play(animName);

		DelayReturn(m_DestroyCts.Token).Forget();
	}

	public void SetCoinData(int value, Transform parent, Vector3 localPositionShift)
	{
		CacheTrans.SetParent(parent);
		CacheTrans.localPosition = localPositionShift;
		CacheTrans.localScale = Vector3.one;

		m_View.Coin.text = "+" + value.ToString();
		m_View.Anim.Play("UIDamage_Coin");

		DelayReturn(m_DestroyCts.Token).Forget();
	}

	private async UniTaskVoid DelayReturn(CancellationToken cancellationToken)
	{
		try
		{
			await UniTask.WaitForSeconds(0.8f, cancellationToken: cancellationToken);
			Return();
		}
		catch (OperationCanceledException)
		{
		}
	}

	protected override void OnReturn()
	{
		m_View.Damage.gameObject.SetActive(false);
		m_View.Add.gameObject.SetActive(false);
		m_View.Coin.gameObject.SetActive(false);
		gameObject.SetActive(false);
		CacheTrans.localScale = Vector3.one;
		base.OnReturn();
	}

	private void OnDestroy()
	{
		if (m_DestroyCts != null && !m_DestroyCts.IsCancellationRequested)
		{
			m_DestroyCts.Cancel();
			m_DestroyCts.Dispose();
			m_DestroyCts = null;
		}
	}
}