//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIDamageTextView : YBaseView
{
	public Text Damage;
	public Text Add;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		Damage = viewItemList[0].Target.GetComponent<Text>();
		Add = viewItemList[1].Target.GetComponent<Text>();
	}
}