//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class UIDescExtControl : YViewControl
{
	private UIDescExtView m_View;
	private RectTransform m_RectTransform;
	private float m_Spacing = 50f;

	public static EResType GetResType()
	{
		return EResType.UIDescExt;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIDescExtView>();
		m_RectTransform = transform as RectTransform;
	}

	public void SetData(string description)
	{
		if (m_View != null && m_View.Txt != null)
		{
			m_View.Txt.text = description;
		}
	}

	public void SetData(List<string> descriptions)
	{
		if (m_View != null && m_View.Txt != null)
		{
			m_View.Txt.text = string.Join("\n", descriptions);
		}
	}

	public void SetPositionRelativeTo(RectTransform targetRect)
	{
		Debug.Log("SetPositionRelativeTo: " + targetRect.name);


		Camera uiCamera = Camera.main;


		Vector2 targetScreenPos = RectTransformUtility.WorldToScreenPoint(uiCamera, targetRect.position);
		float screenCenterX = Screen.width * 0.5f;
		bool isTargetOnLeft = targetScreenPos.x < screenCenterX;

		this.transform.SetParent(targetRect);

		Rect targetRectLocal = targetRect.rect;
		Rect descRect = m_RectTransform.rect;

		float targetWidth = targetRectLocal.width;
		float descWidth = descRect.width;
		float x;
		if (isTargetOnLeft)
		{
			x = targetWidth * 0.5f + descWidth * 0.5f + m_Spacing;
		}
		else
		{
			x = -targetWidth * 0.5f - descWidth * 0.5f - m_Spacing;
		}
		float y = targetRectLocal.yMax - descRect.yMax;

		m_RectTransform.localPosition = new Vector2(x, y);
		this.transform.SetParent(targetRect.parent.parent);

	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}