//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIGamePhaseView : YBaseView
{
	public RectTransform EnvPanels;
	public Text TextHeart;
	public Text AttackNum;
	public Text DefenceNum;
	public Text TxtCoin;
	public VerticalLayoutGroup SkillPanel;
	public VerticalLayoutGroup ItemPanel;
	public VerticalLayoutGroup DefencePanel;
	public VerticalLayoutGroup AttackPanel;
	public Image JoeyImage;
	public RectTransform EffectRoot0;
	public RectTransform EffectRoot1;
	public RectTransform EffectRoot2;
	public RectTransform EffectRoot3;
	public RectTransform EffectRoot4;
	public Text TxtStage;
	public RectTransform RelicContent;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		EnvPanels = viewItemList[0].Target.GetComponent<RectTransform>();
		TextHeart = viewItemList[1].Target.GetComponent<Text>();
		AttackNum = viewItemList[2].Target.GetComponent<Text>();
		DefenceNum = viewItemList[3].Target.GetComponent<Text>();
		TxtCoin = viewItemList[4].Target.GetComponent<Text>();
		SkillPanel = viewItemList[5].Target.GetComponent<VerticalLayoutGroup>();
		ItemPanel = viewItemList[6].Target.GetComponent<VerticalLayoutGroup>();
		DefencePanel = viewItemList[7].Target.GetComponent<VerticalLayoutGroup>();
		AttackPanel = viewItemList[8].Target.GetComponent<VerticalLayoutGroup>();
		JoeyImage = viewItemList[9].Target.GetComponent<Image>();
		EffectRoot0 = viewItemList[10].Target.GetComponent<RectTransform>();
		EffectRoot1 = viewItemList[11].Target.GetComponent<RectTransform>();
		EffectRoot2 = viewItemList[12].Target.GetComponent<RectTransform>();
		EffectRoot3 = viewItemList[13].Target.GetComponent<RectTransform>();
		EffectRoot4 = viewItemList[14].Target.GetComponent<RectTransform>();
		TxtStage = viewItemList[15].Target.GetComponent<Text>();
		RelicContent = viewItemList[16].Target.GetComponent<RectTransform>();
	}
}