//This File Is Auto Generated By Process Control
using UnityEngine;

public class UIGameOverControl : YViewControl
{
	private UIGameOverView m_View;

	public static EResType GetResType()
	{
		return EResType.UIGameOver;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIGameOverView>();
		m_View.Restart.onClick.AddListener(OnRestartClick);
		m_View.ReturnToMainMenu.onClick.AddListener(OnReturnToMainMenuClick);
	}

	void OnRestartClick()
	{
		JoeyGameControl.Instance.EnterBattleStart();
		gameObject.SetActive(false);
	}

	void OnReturnToMainMenuClick()
	{
		JoeyGameControl.Instance.ReturnToMainMenu();
		gameObject.SetActive(false);
	}

	public void SetData()
	{
		;
	}

	protected override void OnReturn()
	{
		gameObject.SetActive(false);
	}
}