//This File Is Auto Generated By Process Control
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Cysharp.Threading.Tasks;
using DG.Tweening;
using UnityEngine;
using UnityEngine.UI;
using Random = UnityEngine.Random;

public partial class UIGamePhaseControl : YViewControl
{
	private UIGamePhaseView m_View;
	private SingleDelayAction m_MoveCardDelayAction = new SingleDelayAction();

	private List<VerticalLayoutGroup> m_EnvPanels = new List<VerticalLayoutGroup>();
	private MonoBehaviourPool<UICardSimpleControl> m_CardSimplePool;
	private MonoBehaviourPool<UIDamageTextControl> m_DamageTextPool;
	private Dictionary<int, Card> m_CardDict = new Dictionary<int, Card>();
	private List<UIRelicControl> m_RelicList = new List<UIRelicControl>();
	private Dictionary<int, List<UICardSimpleControl>> m_EnvCardDict = new Dictionary<int, List<UICardSimpleControl>>();
	private Dictionary<int, List<UICardSimpleControl>> m_BagCardDict = new Dictionary<int, List<UICardSimpleControl>>();
	private DataJoeyPlayer m_DataJoeyPlayer;
	private List<Card> UsedCardList = new List<Card>();
	private Transform[] m_EffectRoots;
	private Queue<UICardSimpleControl> m_CardActionQueue = new Queue<UICardSimpleControl>();
	public UICardSimpleControl CurrentEffectCard;
	public List<UICardSimpleControl> CardActionQueueDebug = new List<UICardSimpleControl>();
	private Dictionary<UICardSimpleControl, CancellationTokenSource> m_CardCtsDict = new Dictionary<UICardSimpleControl, CancellationTokenSource>();
	public List<UICardSimpleControl> CardCtsDictDebug = new List<UICardSimpleControl>();
	private CancellationTokenSource m_ShakeScreenCts;
	private CancellationTokenSource m_MoveBagCardsCts;
	private bool IsEnvDirty = false;
	private int currentMonsterAttack = 0;
	public List<UICardSimpleControl> m_YGrimReaperList = new List<UICardSimpleControl>();
	private int m_RealGrimReaperEnvIndex = -1;
	private bool m_HasCreatedGrimReaper = false;
	private UICardSimpleControl m_FistCardCache;
	private UICardSimpleControl m_KeyPathCardCache;
	private const string EXIT_CARD_ID = "6001";
	private bool m_KeyPathSpawned = false;
	private int m_CurrentAttackTargetEnvIndex = -1;
	private int PhaseCounter = 0;
	private UIDescExtControl m_BlockFatalDescExtControl;
	private bool m_IsBlockFatalActive = false;

	private UIRelicControl m_CardLimitDebuffControl;

	// ArcaneOrb relic: 每施放三次技能获得一张技能牌
	private int m_ArcaneOrbSkillCounter = 0;

	public static EResType GetResType()
	{
		return EResType.UIGamePhase;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIGamePhaseView>();
		m_DataJoeyPlayer = DataSystem.Instance.GetDataJoeyPlayer();
		RegistAction(EActionId.AddHp, AddHp);
		RegistAction(EActionId.AppAttack, AppAttack);
		RegistAction(EActionId.AppDefence, AppDefence);
		RegistAction(EActionId.MoveCard, MoveCard);
		RegistAction(EActionId.TakeEnemyDamage, TakeEnemyDamage);
		RegistAction(EActionId.TakePlayerDamage, TakePlayerDamage);
		RegistAction(EActionId.TakePlayerBoomDamage, TakePlayerBoomDamage);
		RegistAction(EActionId.TakePlayerNoDefenceDamage, TakePlayerNoDefenceDamage);
		RegistAction(EActionId.BoomEnvCard, BoomEnvCard);
		RegistAction(EActionId.UseBagCard, UseBagCard);
		RegistAction(EActionId.AddCardFromDiscard, AddCardFromDiscard);
		RegistAction(EActionId.AttackRandomEnemy, AttackRandomEnemy);
		RegistAction(EActionId.TakeAllEnemyDamage, TakeAllEnemyDamage);
		RegistAction(EActionId.AddCardToQueue, AddCardToQueue);
		RegistAction(EActionId.AddEffectValueToBagCard, AddEffectValueToBagCard);
		RegistAction(EActionId.SwapEnvCard, SwapEnvCard);
		RegistAction(EActionId.RomeoMonkeyDead, RomeoMonkeyDead);
		RegistAction(EActionId.JulietMonkeyDead, JulietMonkeyDead);
		RegistAction(EActionId.BananaMonkeyDead, BananaMonkeyDead);
		RegistAction(EActionId.AddEnvCardFromBag, AddEnvCardFromBag);
		RegistAction(EActionId.ThrowWeaponToEnv, ThrowWeaponToEnv);
		RegistAction(EActionId.ThrowWeaponDefenceToEnv, ThrowWeaponDefenceToEnv);

		RegistAction(EActionId.HealPlayerOnDefense, HealPlayerOnDefense);
		RegistAction(EActionId.AddCardToEnv, AddCardToEnv);
		RegistAction(EActionId.AddCardToSpecifiedEnv, AddCardToSpecifiedEnv);
		RegistAction(EActionId.DoubleLastWeaponAttack, DoubleLastWeaponAttack);
		RegistAction(EActionId.AddCardsToEnv, AddCardsToEnv);
		RegistAction(EActionId.AddCardsToEnvByCardId, AddCardsToEnvByCardId);
		RegistAction(EActionId.OnCoinChange, OnCoinChange);
		RegistAction(EActionId.MonsterHealOnDealDamage, MonsterHealOnDealDamage);
		RegistAction(EActionId.AddCardToBagFromSelect, AddCardToBagFromSelect);
		RegistAction(EActionId.SwapTopTwoEnvCards, SwapTopTwoEnvCards);
		RegistAction(EActionId.UpdateRelic, UpdateRelic);
		RegistAction(EActionId.OnCardPointerEnter, OnCardPointerEnter);
		RegistAction(EActionId.PermanentBoostAttack, PermanentBoostAttack);
		RegistAction(EActionId.PermanentBoostDefence, PermanentBoostDefence);
		RegistAction(EActionId.MoveEnvCardLeft, MoveEnvCardLeft);
		RegistAction(EActionId.SwapEnvCardWithRandom, SwapEnvCardWithRandom);
		RegistAction(EActionId.KillSkeletonMonster, KillSkeletonMonster);
		RegistAction(EActionId.DealSplashDamage, DealSplashDamage);
		RegistAction(EActionId.KingShieldSwitchToShield, KingShieldSwitchToShield);
		RegistAction(EActionId.KingShieldSwitchToSword, KingShieldSwitchToSword);
		RegistAction(EActionId.BloodStorageActivate, BloodStorageActivate);
		RegistAction(EActionId.RefreshCardLimitDebuff, OnRefreshCardLimitDebuff);
		RegistAction(EActionId.BloodStorageDeduct, BloodStorageDeduct);
		RegistAction(EActionId.ShamanDonkeyBuff, ShamanDonkeyBuff);
		RegistAction(EActionId.UnyieldingActivate, UnyieldingActivate);
		RegistAction(EActionId.BeastBloodBoilingActivate, BeastBloodBoilingActivate);
		RegistAction(EActionId.FreshBloodGuardActivate, FreshBloodGuardActivate);
		RegistAction(EActionId.BloodyBattleActivate, BloodyBattleActivate);
		RegistAction(EActionId.AddBlockDamagePhase, AddBlockDamagePhase);
		RegistAction(EActionId.LifeShareSetPlayerHealth, LifeShareSetPlayerHealth);
		RegistAction(EActionId.FireBallDamage, FireBallDamage);
		RegistAction(EActionId.IceMagicDamage, IceMagicDamage);
		RegistAction(EActionId.SkillPowerUpActivate, SkillPowerUpActivate);
		RegistAction(EActionId.OnSkillCast, OnSkillCast);
		RegistAction(EActionId.DualWieldActivate, DualWieldActivate);
		RegistAction(EActionId.ShieldBashActivate, ShieldBashActivate);
		RegistAction(EActionId.FortressActivate, FortressActivate);
		RegistAction(EActionId.StrikeActivate, StrikeActivate);

		for (int i = 0; i < m_View.EnvPanels.childCount; i++)
		{
			Transform child = m_View.EnvPanels.GetChild(i);
			VerticalLayoutGroup vlg = child.GetComponent<VerticalLayoutGroup>();
			m_EnvPanels.Add(vlg);
		}

		m_EffectRoots = new Transform[] { m_View.EffectRoot0, m_View.EffectRoot1, m_View.EffectRoot2, m_View.EffectRoot3, m_View.EffectRoot4 };

		m_CardSimplePool = new MonoBehaviourPool<UICardSimpleControl>(() =>
		{
			return this.Asset.OpenUI<UICardSimpleControl>(null);
		});

		m_DamageTextPool = new MonoBehaviourPool<UIDamageTextControl>(() =>
		{
			return this.Asset.OpenUI<UIDamageTextControl>(null);
		});

		m_View.TipBlickDamage.onEnter = OnBlockFatalPointerEnter;
		m_View.TipBlickDamage.onExit = OnBlockFatalPointerExit;

		m_View.BlockFatal.SetActive(false);
	}

	public Transform GetEffectRoot(int envIndex)
	{
		if (envIndex >= 0 && envIndex < m_EffectRoots.Length)
		{
			return m_EffectRoots[envIndex];
		}
		return null;
	}


	void OnHPChanged(int hp)
	{
		m_View.TextHeart.text = hp.ToString();
		if (m_DataJoeyPlayer.playerMaxHealth > 0)
		{
			float ratio = (float)hp / m_DataJoeyPlayer.playerMaxHealth;
			m_View.Heart.fillAmount = ratio;
		}

		RunActionForEachLastBagCard((x) =>
		{
			if (x.GetBuffValue(EBuffType.UpdateByHpChange) > 0)
			{
				x.UpdateBuffValue();
			}

		});

	}

	void OnAttackChanged(int attack)
	{
	}

	void OnDefenceChanged(int defence)
	{
	}

	private void ApplyPlayerHealthChange(int delta, bool isHeal = false)
	{
		m_DataJoeyPlayer.lastPlayerHealth = m_DataJoeyPlayer.playerHealth;
		m_DataJoeyPlayer.playerHealth += delta;
		if (m_DataJoeyPlayer.playerHealth < 0)
		{
			m_DataJoeyPlayer.playerHealth = 0;
		}
		if (isHeal && m_DataJoeyPlayer.playerHealth > m_DataJoeyPlayer.playerMaxHealth)
		{
			m_DataJoeyPlayer.playerHealth = m_DataJoeyPlayer.playerMaxHealth;
		}
		if (delta != 0)
		{
			int actualChange = isHeal ? (m_DataJoeyPlayer.playerHealth - m_DataJoeyPlayer.lastPlayerHealth) : Mathf.Abs(delta);
			{
				ShowDamageText(actualChange, m_View.Joey, new Vector3(100f, 190f, 0), !isHeal);
			}
			if (isHeal)
			{
				JoeyGameControl.Instance.PlayVFX(EVFXName.VFX_HuiXue, transform, 2f);
				m_View.JoeyAnim.Play("happy");
			}
			else
			{
				JoeyGameControl.Instance.PlayVFX(EVFXName.VFX_joey_souji, transform, DataSystem.Instance.GetVFXDelayTime(EVFXName.VFX_joey_souji));
				m_View.JoeyAnim.Play("fear");
			}
		}
		if (delta < 0 && !isHeal)
		{
			if (m_ShakeScreenCts != null && !m_ShakeScreenCts.IsCancellationRequested)
			{
				m_ShakeScreenCts.Cancel();
				m_ShakeScreenCts.Dispose();
			}
			m_ShakeScreenCts = new CancellationTokenSource();
			ShakeScreen(0.2f, 20f, m_ShakeScreenCts.Token).Forget();
		}
		OnHPChanged(m_DataJoeyPlayer.playerHealth);
		CheckGameOver();
	}

	private void CheckGameOver()
	{
		if (m_DataJoeyPlayer.playerHealth <= 0)
		{
			DataAchievement achievement = DataSystem.Instance.GetDataAchievement();
			achievement.DeadNum++;
			DataSystem.Instance.SaveDataAchievement();
			JoeyGameControl.Instance.ShowGameOver();
		}
	}

	void AddHp(object[] paraArray)
	{
		int delta = (int)paraArray[0];
		AddHp(delta);
	}

	void AppAttack(object[] paraArray)
	{
		int delta = (int)paraArray[0];
		m_DataJoeyPlayer.playerAttack += delta;
		OnAttackChanged(m_DataJoeyPlayer.playerAttack);
	}

	void AppDefence(object[] paraArray)
	{
		int delta = (int)paraArray[0];
		m_DataJoeyPlayer.playerDefence += delta;
		OnDefenceChanged(m_DataJoeyPlayer.playerDefence);
	}

	public void SetData()
	{
		RefreshView();
		ClearAllCard();
		CreateFistCardCache();
		CreateKeyPathCardCache();
		if (m_KeyPathCardCache != null)
		{
			m_KeyPathCardCache.gameObject.SetActive(false);
		}
		m_KeyPathSpawned = false;

		ResetUnyieldingState();
		ResetBloodStorageState();
		ResetCounterInsightState();
		ResetDualWieldState();
		ResetShieldBashState();
		ResetFortressState();
		ResetStrikeState();
	}

	public void SetBackgroundByStageId(int stageId)
	{
		if (JoeyGameControl.Instance.GameMode == EGameMode.Guide)
		{
			m_View.MonkeyBg.SetActive(false);
			m_View.TurkeyBg.SetActive(false);
			m_View.DonkeyBg.SetActive(false);
			m_View.DeadkeyBg.SetActive(false);
			m_View.GuideBg.SetActive(true);
		}
		else if (JoeyGameControl.Instance.GameMode == EGameMode.Env)
		{
			EnvStage envStage = GData.Instance.GetEnvStage(stageId);
			if (envStage != null)
			{
				SetBackgroundByTheme(envStage.theme);
			}
		}
		else
		{
			RoguelikeStage roguelikeStage = GData.Instance.GetRoguelikeStage(stageId);
			if (roguelikeStage != null)
			{
				SetBackgroundByTheme(roguelikeStage.theme);
			}
		}
	}

	private void SetBackgroundByTheme(ETheme theme)
	{
		m_View.MonkeyBg.SetActive(false);
		m_View.TurkeyBg.SetActive(false);
		m_View.DonkeyBg.SetActive(false);
		m_View.DeadkeyBg.SetActive(false);
		m_View.GuideBg.SetActive(false);

		switch (theme)
		{
			case ETheme.monkey:
				m_View.MonkeyBg.SetActive(true);
				break;
			case ETheme.turkey:
				m_View.TurkeyBg.SetActive(true);
				break;
			case ETheme.donkey:
				m_View.DonkeyBg.SetActive(true);
				break;
			case ETheme.deadkey:
				m_View.DeadkeyBg.SetActive(true);
				break;
		}
	}

	private void CreateFistCardCache()
	{
		// Only skip creation if fist card exists and is active, unless it needs to be replaced
		if (m_FistCardCache != null && m_FistCardCache.gameObject.activeSelf)
		{
			// Check if we need to replace the current fist card
			bool hasHighArtRelic = DataSystem.Instance.HasRelic(ERelicType.HighArt);
			bool hasGlovesRelic = DataSystem.Instance.HasRelic(ERelicType.BareHandsMaster);
			bool isBareHands = m_FistCardCache.CardData != null && m_FistCardCache.CardData.id == "1011";
			bool isMagicWand = m_FistCardCache.CardData != null && m_FistCardCache.CardData.id == "1022";

			// 判断是否需要替换当前的拳头卡:
			// 1. 有 HighArt 遗物但当前不是魔杖 → 需要替换为魔杖
			// 2. 有 BareHandsMaster 遗物但当前还是赤手空拳 → 需要替换为拳套
			bool needReplace = (hasHighArtRelic && !isMagicWand) || (hasGlovesRelic && isBareHands);

			if (!needReplace)
			{
				return;
			}

			// 需要替换时，先回收旧的卡片
			m_FistCardCache.Return();
			m_FistCardCache = null;
		}

		// Determine which card to use:
		// HighArt relic takes priority - use Magic Wand (1022)
		// BareHandsMaster relic - use Boxing Gloves (1019)
		// Default - use Bare Hands (1011)
		string cardId;
		if (DataSystem.Instance.HasRelic(ERelicType.HighArt))
		{
			cardId = "1022"; // Magic Wand
		}
		else if (DataSystem.Instance.HasRelic(ERelicType.BareHandsMaster))
		{
			cardId = "1019"; // Boxing Gloves
		}
		else
		{
			cardId = "1011"; // Bare Hands
		}

		Card card = DataSystem.Instance.CreateCard(cardId);
		Transform attackPanelTransform = m_View.AttackPanel.transform;
		UICardSimpleControl cardControl = m_CardSimplePool.Get();
		cardControl.CacheTrans.SetParent(m_View.EmptyAttack);
		cardControl.CacheTrans.position = attackPanelTransform.position;
		cardControl.CacheTrans.localScale = Vector3.one * .8f;
		cardControl.CacheTrans.localEulerAngles = Vector3.zero;
		cardControl.IsEnv = false;
		cardControl.SetData(card);
		m_FistCardCache = cardControl;
	}

	private void CreateKeyPathCardCache()
	{
		if (m_KeyPathCardCache != null)
		{
			return;
		}
		Card card = CreateCard(EXIT_CARD_ID);
		Transform effectRoot2 = GetEffectRoot(2);
		UICardSimpleControl cardControl = Asset.OpenUI<UICardSimpleControl>(effectRoot2);
		cardControl.CacheTrans.localPosition = Vector3.zero;
		cardControl.CacheTrans.localScale = Vector3.one;
		cardControl.CacheTrans.localEulerAngles = Vector3.zero;
		cardControl.IsEnv = true;
		cardControl.SetData(card, isEnv: true, envIndex: 2);
		cardControl.gameObject.SetActive(false);
		m_KeyPathCardCache = cardControl;
	}

	public void ClearEnvCardList()
	{
		for (int i = 0; i < m_EnvPanels.Count; i++)
		{
			if (m_EnvCardDict.TryGetValue(i, out List<UICardSimpleControl> envCardList))
			{
				for (int j = 0; j < envCardList.Count; j++)
				{
					UICardSimpleControl cardControl = envCardList[j];
					if (cardControl != null && cardControl.gameObject.activeSelf)
					{
						m_CardDict.Remove(cardControl.CardData.UniqueId);
						RemoveCardCts(cardControl);
						cardControl.Return();
					}
				}
			}
		}
		m_EnvCardDict.Clear();
	}

	public void ClearBagCardList()
	{
		foreach (var kvp in m_BagCardDict)
		{
			List<UICardSimpleControl> bagCardList = kvp.Value;
			if (bagCardList != null)
			{
				for (int i = 0; i < bagCardList.Count; i++)
				{
					UICardSimpleControl cardControl = bagCardList[i];
					if (cardControl != null && cardControl.gameObject.activeSelf)
					{
						m_CardDict.Remove(cardControl.CardData.UniqueId);
						RemoveCardCts(cardControl);
						cardControl.Return();
					}
				}
			}
		}
		m_BagCardDict.Clear();
	}

	public void SetDataWithoutBagClear()
	{
		RefreshView();
		ClearEnvCardList();
		UsedCardList.Clear();
		CreateFistCardCache();
		CreateKeyPathCardCache();
		if (m_KeyPathCardCache != null)
		{
			m_KeyPathCardCache.gameObject.SetActive(false);
		}
		m_KeyPathSpawned = false;

		ResetUnyieldingState();
		ResetBloodStorageState();
	}

	private void RefreshView()
	{
		m_View.TextHeart.text = m_DataJoeyPlayer.playerHealth.ToString();
		if (m_DataJoeyPlayer.playerMaxHealth > 0)
		{
			float ratio = (float)m_DataJoeyPlayer.playerHealth / m_DataJoeyPlayer.playerMaxHealth;
			m_View.Heart.fillAmount = ratio;
		}
		m_View.TxtCoin.text = m_DataJoeyPlayer.Coin.ToString();
		if (JoeyGameControl.Instance.GameMode == EGameMode.Env)
		{
			EnvStage envStage = GData.Instance.GetEnvStage(m_DataJoeyPlayer.StageId);
			if (envStage != null)
			{
				int totalStages = 20;
				m_View.TxtStage.text = envStage.level.ToString() + "/" + totalStages.ToString();
			}
		}
		else if (JoeyGameControl.Instance.GameMode == EGameMode.Guide)
		{
			int totalLevels = 3;
			m_View.TxtStage.text = $"{m_DataJoeyPlayer.currentLevel}/{totalLevels}";
		}
		else
		{
			RoguelikeStage currentStage = GData.Instance.GetRoguelikeStage(m_DataJoeyPlayer.StageId);
			if (currentStage != null && !string.IsNullOrEmpty(currentStage.stages))
			{
				m_View.TxtStage.text = currentStage.stages;
			}
		}

		// 设置 Description 文本
		if (JoeyGameControl.Instance.GameMode == EGameMode.Env)
		{
			EnvStage envStage = GData.Instance.GetEnvStage(m_DataJoeyPlayer.StageId);
			if (envStage != null)
			{

				// 根据 theme 设置 BattleEnv 模式的 Description
				switch (envStage.theme)
				{
					case ETheme.monkey:
						m_View.Description.text = "加油,打败坏monkey";
						break;
					case ETheme.donkey:
						m_View.Description.text = "努力,战胜坏donkey";
						break;
					case ETheme.turkey:
						m_View.Description.text = "冲鸭,击溃坏turkey";
						break;
					case ETheme.deadkey:
						m_View.Description.text = "打败死神!";
						break;
					case ETheme.tutorial:
						m_View.Description.text = "终极挑战,击败最强敌人!";
						break;
					default:
						m_View.Description.text = "还是我们A*Studio，再Dream一次吧！";
						break;
				}
			}
		}
		else if (JoeyGameControl.Instance.GameMode == EGameMode.Guide)
		{

			// 教学关卡的三关文本
			switch (m_DataJoeyPlayer.currentLevel)
			{
				case 1:
					m_View.Description.text = "点击堆叠卡牌/攻击敌人";
					break;
				case 2:
					m_View.Description.text = "喝药回血,用技能打败敌人";
					break;
				case 3:
					m_View.Description.text = "多次触发手里剑获胜哟";
					break;
				default:
					m_View.Description.text = "还是我们A*Studio，再Dream一次吧！";
					break;
			}
		}
		else
		{
			RoguelikeStage currentStage = GData.Instance.GetRoguelikeStage(m_DataJoeyPlayer.StageId);
			if (currentStage != null && !string.IsNullOrEmpty(currentStage.stages))
			{
				m_View.TxtStage.text = currentStage.stages;
			}

			// 普通关卡默认文本
			m_View.Description.text = "还是我们A*Studio，再Dream一次吧！";
		}


		RefreshRelicDisplay();
		RefreshCardLimitDebuff();
	}

	private void OnCoinChanged(int coin)
	{
		m_DataJoeyPlayer.Coin = coin;
		m_View.TxtCoin.text = coin.ToString();
	}

	private UICardSimpleControl GetCardSimple(Transform parent, bool IsEnv)
	{
		UICardSimpleControl cardControl = m_CardSimplePool.Get();
		cardControl.CacheTrans.SetParent(parent);
		cardControl.CacheTrans.localScale = Vector3.one;
		cardControl.CacheTrans.localPosition = Vector3.zero;
		cardControl.CacheTrans.localEulerAngles = Vector3.zero;
		cardControl.CacheTrans.SetAsLastSibling();
		cardControl.IsEnv = IsEnv;
		return cardControl;
	}

	private void ShowDamageText(int damage, Transform parent, Vector3 localPositionShift, bool isDamage = true)
	{
		UIDamageTextControl damageTextControl = m_DamageTextPool.Get();
		damageTextControl.SetData(damage, parent, localPositionShift, isDamage);
	}

	private async UniTask ShakeScreen(float duration = 0.2f, float intensity = 10f, CancellationToken cancellationToken = default)
	{
		RectTransform rectTransform = transform as RectTransform;
		Vector2 originalPosition = rectTransform.anchoredPosition;
		float elapsed = 0f;

		while (elapsed < duration)
		{
			cancellationToken.ThrowIfCancellationRequested();
			float progress = elapsed / duration;
			float currentIntensity = intensity * (1f - progress);
			Vector2 randomOffset = Random.insideUnitCircle * currentIntensity;
			rectTransform.anchoredPosition = originalPosition + randomOffset;

			elapsed += Time.deltaTime;
			await UniTask.Yield(cancellationToken);
		}

		rectTransform.anchoredPosition = Vector2.zero;
	}

	public Card CreateCard(string cardId)
	{
		Card card = DataSystem.Instance.CreateCard(cardId);
		m_CardDict[card.UniqueId] = card;
		return card;
	}

	private Transform GetParentByCardType(ECardType cardType)
	{
		switch (cardType)
		{
			case ECardType.attack:
				return m_View.AttackPanel.transform;
			case ECardType.defence:
				return m_View.DefencePanel.transform;
			case ECardType.skill:
				return m_View.SkillPanel.transform;
			case ECardType.item:
				return m_View.ItemPanel.transform;
			case ECardType.monster:
			case ECardType.other:
				return m_View.EnvPanels.transform;
			default:
				return null;
		}
	}

	private void AddCardToBag(string cardId)
	{
		Card card = CreateCard(cardId);
		AddCardToBag(card);
	}

	private void AddCardToBag(Card card)
	{
		if (card == null)
		{
			return;
		}
		ECardType cardType = card.GetCardType();
		Transform parent = GetParentByCardType(cardType);
		if (parent == null)
		{
			return;
		}
		m_CardDict[card.UniqueId] = card;
		UICardSimpleControl cardControl = GetCardSimple(parent, false);
		cardControl.SetData(card);
		AddBagCard(cardType, cardControl);
		cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
	}


	public void AddCardList(ECardType cardType, List<string> cardIds)
	{
		Debug.Log("AddCardList: " + cardType + " " + cardIds.Count);

		Transform parent = GetParentByCardType(cardType);
		if (parent == null)
		{
			return;
		}

		for (int i = cardIds.Count - 1; i >= 0; i--)
		{
			string cardId = cardIds[i];
			Card card = CreateCard(cardId);
			UICardSimpleControl cardControl = GetCardSimple(parent, false);
			cardControl.SetData(card);
			AddBagCard(cardType, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
		}
	}

	public void AddEnvCardList(List<string> cardIds, int index)
	{
		VerticalLayoutGroup parent = m_EnvPanels[index];

		for (int i = cardIds.Count - 1; i >= 0; i--)
		{
			string cardId = cardIds[i];
			Card card = CreateCard(cardId);

			if (DataSystem.Instance.IsHardGame && card.GetCardType() == ECardType.monster)
			{
				card.currentHealth *= 2;
				card.health *= 2;
			}

			if (DataSystem.Instance.HasRelic(ERelicType.DecayAura) && card.GetCardType() == ECardType.monster)
			{
				if (card.currentAttack > 0) card.currentAttack = Mathf.Max(1, card.currentAttack - 1);
				if (card.currentHealth > 0) card.currentHealth = Mathf.Max(1, card.currentHealth - 1);
			}

			UICardSimpleControl cardControl = GetCardSimple(parent.transform, true);
			cardControl.SetData(card, isEnv: true, envIndex: index);
			AddEnvCard(index, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
		}
	}

	public Card GetCardDataById(int uniqueId)
	{
		return m_CardDict[uniqueId];
	}

	public Dictionary<int, List<UICardSimpleControl>> GetEnvCardDict()
	{
		return m_EnvCardDict;
	}

	public Dictionary<int, List<UICardSimpleControl>> GetBagCardDict()
	{
		return m_BagCardDict;
	}

	public void AddSelfCardList()
	{
		AddCardsFromEquipList(m_DataJoeyPlayer.EquipedAttackList);
		AddCardsFromEquipList(m_DataJoeyPlayer.EquipedDefenceList);
		AddCardsFromEquipList(m_DataJoeyPlayer.EquipedItemList);
		AddCardsFromEquipList(m_DataJoeyPlayer.EquipedSkillList);
	}

	private void AddCardsFromEquipList(List<int> equipList)
	{
		for (int i = 0; i < equipList.Count; i++)
		{
			int uniqueId = equipList[i];
			Card card = m_DataJoeyPlayer.GetSelfCardDictData(uniqueId);
			if (card == null) continue;

			// HighArt relic takes priority: Replace Bare Hands or Boxing Gloves with Magic Wand
			if (DataSystem.Instance.HasRelic(ERelicType.HighArt) && (card.id == "1011" || card.id == "1019"))
			{
				// Get the magic wand card template
				Card magicWandTemplate = GData.Instance.GetCardConfigById("1022");
				// Replace card data while keeping the unique ID
				card.cardImage = magicWandTemplate.cardImage;
				card.cardBackground = magicWandTemplate.cardBackground;
				card.cardName = magicWandTemplate.cardName;
				card.description = magicWandTemplate.description;
				card.id = magicWandTemplate.id;
				card.SetAttack(magicWandTemplate.currentAttack);
				card.effectId = magicWandTemplate.effectId;
			}
			// Replace Bare Hands with Boxing Gloves if player has BareHandsMaster relic (and not HighArt)
			else if (DataSystem.Instance.HasRelic(ERelicType.BareHandsMaster) && card.id == "1011")
			{
				// Get the boxing gloves card template
				Card boxingGlovesTemplate = GData.Instance.GetCardConfigById("1019");
				// Replace card data while keeping the unique ID
				card.cardImage = boxingGlovesTemplate.cardImage;
				card.cardBackground = boxingGlovesTemplate.cardBackground;
				card.cardName = boxingGlovesTemplate.cardName;
				card.description = boxingGlovesTemplate.description;
				card.id = boxingGlovesTemplate.id;
				card.SetAttack(boxingGlovesTemplate.currentAttack);
				card.effectId = boxingGlovesTemplate.effectId;
			}

			ECardType cardType = card.GetCardType();
			Transform parent = GetParentByCardType(cardType);
			if (parent == null)
			{
				continue;
			}
			m_CardDict[card.UniqueId] = card;
			UICardSimpleControl cardControl = GetCardSimple(parent, false);
			cardControl.SetData(card);
			AddBagCard(cardType, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
		}
	}

	private void AddBagCard(ECardType cardType, UICardSimpleControl cardControl, bool isMoveCard = false)
	{
		int cardTypeInt = (int)cardType;
		if (!m_BagCardDict.TryGetValue(cardTypeInt, out List<UICardSimpleControl> cardList))
		{
			m_BagCardDict[cardTypeInt] = new List<UICardSimpleControl>();
		}

		// Check if card will become top of pile (last in list)
		bool willBecomeTop = (m_BagCardDict[cardTypeInt].Count == 0);

		m_BagCardDict[cardTypeInt].Add(cardControl);
		cardControl.IsEnv = false;
		cardControl.EnvIndex = -1;
		if (!isMoveCard)
		{
			cardControl.CacheTrans.localScale = new Vector3(0.8f, 0.8f, 0.8f);
		}

	if (cardType == ECardType.defence)
	{
		// Apply Fortress bonus if available
		ApplyFortressBonus(cardControl);

		RunActionForEachLastBagCard((x) =>
		{
			if (x.GetBuffValue(EBuffType.UpdateByDefenceCardNum) > 0)
			{
				x.UpdateBuffValue();
			}

		});
		
		// DualWieldMastery relic: Refresh attack cards when defence is equipped
		if (DataSystem.Instance.HasRelic(ERelicType.DualWieldMastery))
		{
			RefreshAllAttackCards();
		}
	}

		// 螺旋手里剑：当任意攻击卡进入手牌时，检查并移动螺旋手里剑到环境
		// 注意：即使是从环境拿回来的卡（isMoveCard=true），也应该触发此逻辑
		if (cardType == ECardType.attack)
		{
			CheckAndMoveSpiralShurikenToEnv(cardControl);
		}

		// Trigger OnEnterBag if not from move animation (which calls it separately)
		if (!isMoveCard && cardControl.CardEffect != null)
		{
			Debug.Log($"[AddBagCard] Calling OnEnterBag for {cardControl.CardData.cardName} (UniqueId: {cardControl.CardData.UniqueId}, Type: {cardType})");
			cardControl.CardEffect.OnEnterBag();
		}

		// Trigger OnBecomeTopOfPile if card becomes top of pile
		// Skip if isMoveCard=true, as MoveCard callback will handle it
		if (!isMoveCard && willBecomeTop && cardControl.CardEffect != null)
		{
			Debug.Log($"[AddBagCard] Card becomes top of pile, calling OnBecomeTopOfPile for {cardControl.CardData.cardName} (UniqueId: {cardControl.CardData.UniqueId}, Type: {cardType})");
			cardControl.CardEffect.OnBecomeTopOfPile();
		}
	}


	private async UniTask RemoveBagCard(ECardType cardType, UICardSimpleControl cardControl)
	{
		int cardTypeInt = (int)cardType;
		if (m_BagCardDict.TryGetValue(cardTypeInt, out List<UICardSimpleControl> cardList))
		{
			Debug.Log($"[RemoveBagCard] Removing {cardControl.CardData.cardName} (UniqueId: {cardControl.CardData.UniqueId}, Type: {cardType})");
			cardList.Remove(cardControl);
			RemoveCardData(cardControl.CardData.UniqueId);
			cardControl.Return();

			UICardSimpleControl newLastBagCard = GetLastBagCard(cardType);
			if (newLastBagCard != null)
			{
				Debug.Log($"[RemoveBagCard] New top card: {newLastBagCard.CardData.cardName} (UniqueId: {newLastBagCard.CardData.UniqueId}), calling OnBecomeTopOfPile");
				float delayTime = newLastBagCard.CardEffect?.OnBecomeTopOfPile() ?? 0.5f;
				await UniTask.WaitForSeconds(delayTime);
			}
			else
			{
				Debug.Log($"[RemoveBagCard] No cards left in {cardType} pile");
			}
			
			// DualWieldMastery relic: Refresh attack cards when defence is removed
			if (cardType == ECardType.defence && DataSystem.Instance.HasRelic(ERelicType.DualWieldMastery))
			{
				RefreshAllAttackCards();
			}
		}
	}

	private List<UICardSimpleControl> GetBagCardList(ECardType cardType)
	{
		int cardTypeInt = (int)cardType;
		if (m_BagCardDict.TryGetValue(cardTypeInt, out List<UICardSimpleControl> cardList))
		{
			return cardList;
		}
		return null;
	}

	private UICardSimpleControl GetLastBagCard(ECardType cardType)
	{
		List<UICardSimpleControl> cardList = GetBagCardList(cardType);
		if (cardList != null && cardList.Count > 0)
		{
			return cardList[cardList.Count - 1];
		}
		return null;
	}

	public UICardSimpleControl GetLastEnvCard(int envIndex)
	{
		if (m_EnvCardDict.TryGetValue(envIndex, out List<UICardSimpleControl> cardList))
		{
			if (cardList != null && cardList.Count > 0)
			{
				return cardList[cardList.Count - 1];
			}
		}
		return null;
	}

	public void RunActionForEachLastEnvCard(Action<UICardSimpleControl> action)
	{
		if (action == null || m_EnvPanels == null)
		{
			return;
		}
		for (int i = 0; i < m_EnvPanels.Count; i++)
		{
			UICardSimpleControl lastCard = GetLastEnvCard(i);
			if (lastCard != null)
			{
				action(lastCard);
			}
		}
	}

	public void RunActionForEachLastBagCard(Action<UICardSimpleControl> action)
	{
		if (action == null)
		{
			return;
		}
		ECardType[] bagCardTypes = { ECardType.attack, ECardType.defence, ECardType.skill, ECardType.item };
		for (int i = 0; i < bagCardTypes.Length; i++)
		{
			UICardSimpleControl lastCard = GetLastBagCard(bagCardTypes[i]);
			if (lastCard != null)
			{
				action(lastCard);
			}
		}
	}

	public int GetEnvCardCount(int envIndex)
	{
		if (m_EnvCardDict.TryGetValue(envIndex, out List<UICardSimpleControl> cardList))
		{
			return cardList?.Count ?? 0;
		}
		return 0;
	}

	public bool HasBagCard(ECardType cardType)
	{
		List<UICardSimpleControl> cardList = GetBagCardList(cardType);
		return cardList != null && cardList.Count > 0;
	}

	public bool HasEnemy()
	{
		return FindRandomEnemy() != -1;
	}


	private UICardSimpleControl GetFistCard()
	{
		return m_FistCardCache;
	}

	private void AddEnvCard(int index, UICardSimpleControl cardControl)
	{
		if (!m_EnvCardDict.TryGetValue(index, out List<UICardSimpleControl> cardList))
		{
			m_EnvCardDict[index] = new List<UICardSimpleControl>();
		}
		m_EnvCardDict[index].Add(cardControl);
	}

	private void RemoveEnvCard(int index, UICardSimpleControl cardControl)
	{
		if (m_EnvCardDict.TryGetValue(index, out List<UICardSimpleControl> cardList))
		{
			cardList.Remove(cardControl);
			RemoveCardData(cardControl.CardData.UniqueId);
			cardControl.Return();
		}
	}

	private void RemoveEnvCardFromDict(int index, UICardSimpleControl cardControl)
	{
		if (m_EnvCardDict.TryGetValue(index, out List<UICardSimpleControl> cardList))
		{
			cardList.Remove(cardControl);
		}
	}

	private async UniTask<bool> DealDamageToEnvCard(UICardSimpleControl cardControl, int damage, int envIndex, EEffectType effectType = EEffectType.Damage, CancellationToken? cancellationToken = null)
	{
		CancellationToken token = cancellationToken ?? CancellationToken.None;

		// 应用技能伤害加成
		damage = ApplySkillDamageBonus(damage, effectType);

		if (cardControl.CardType == ECardType.monster)
		{
			// Apply vulnerable damage bonus (50% extra damage)
			int vulnerableTurns = cardControl.GetBuffValue(EBuffType.Vulnerable);
			if (vulnerableTurns > 0 && effectType == EEffectType.Damage)
			{
				int bonusDamage = Mathf.RoundToInt(damage * 0.5f);
				damage += bonusDamage;
				Debug.Log($"Vulnerable: {cardControl.CardData.cardName} takes +{bonusDamage} damage ({vulnerableTurns} turns remaining)");
			}

			float delayTime = cardControl.CallCardTakeDamage(damage, effectType);
			ShowDamageText(damage, cardControl.CacheTrans, new Vector3(0f, 180f, 0));
			{
				if (m_ShakeScreenCts != null && !m_ShakeScreenCts.IsCancellationRequested)
				{
					m_ShakeScreenCts.Cancel();
					m_ShakeScreenCts.Dispose();
				}
				m_ShakeScreenCts = new CancellationTokenSource();
				ShakeScreen(0.2f, 20f, m_ShakeScreenCts.Token).Forget();
			}
			if (delayTime > 0f)
			{
				await UniTask.WaitForSeconds(delayTime, cancellationToken: token);
			}

			// 火球攻击解除冰冻状态
			if (effectType == EEffectType.FireBall && cardControl.IsFrozen())
			{
				cardControl.RemoveBuff(EBuffType.Frozen);
				Debug.Log($"Monster at envIndex {envIndex} unfrozen by FireBall");
			}
		}



		if (cardControl.CardData.currentHealth <= 0 && cardControl.CardType == ECardType.monster)
		{
			Debug.Log("Monster dead: " + cardControl.CardData.id);
			string monsterId = cardControl.CardData.id;
			List<Card> dropCards = GetMonsterDropCard(monsterId, envIndex);

			float delayTime = cardControl.CardEffect?.OnBeDying() ?? 0f;
			await UniTask.WaitForSeconds(delayTime, cancellationToken: token);

			Card configCard = GData.Instance.GetCardConfigById(monsterId);
			if (configCard != null && configCard.stars == 3)
			{
				DataSystem.Instance.AddGrowthPoints(10);
			}

			DataAchievement achievement = DataSystem.Instance.GetDataAchievement();
			if (configCard != null && configCard.price > 0)
			{
				DataSystem.Instance.AddCoin(configCard.price);
				if (m_DataJoeyPlayer.Coin > achievement.MaxCoinNum)
				{
					achievement.MaxCoinNum = m_DataJoeyPlayer.Coin;
				}
			}
			achievement.KillMonsterNum++;
			DataSystem.Instance.SaveDataAchievement();
			// 播放怪物离场音效
			SFX.PlayAudio("Audio/SFX/Battle/MonsterFly", 1.0f, 0.5f);


			RemoveEnvCard(envIndex, cardControl);
			delayTime = cardControl.CardEffect?.OnDead() ?? 0.5f;
			await UniTask.WaitForSeconds(delayTime, cancellationToken: token);
			RemoveCardCts(cardControl);

			if (dropCards != null && dropCards.Count > 0)
			{
				AddEnvDropCard(dropCards, envIndex);
			}

			CheckAndSpawnKeyPath();

			return true;
		}

		return false;
	}

	private List<Card> GetMonsterDropCard(string monsterId, int envIndex)
	{
		if (string.IsNullOrEmpty(monsterId))
		{
			return null;
		}

		// Get current level random seed for deterministic drop
		int levelRandomSeed = DataSystem.Instance.GetDataJoeyPlayer().levelRandomSeed;

		// Use deterministic drop with seed based on random seed and position
		if (!LootDropManager.Instance.TryGetDropCardsWithSeed(monsterId, levelRandomSeed, envIndex, out List<string> cardIds) || cardIds == null || cardIds.Count == 0)
		{
			return null;
		}

		List<Card> dropCards = new List<Card>();
		for (int i = 0; i < cardIds.Count; i++)
		{
			Card card = CreateCard(cardIds[i]);
			dropCards.Add(card);
		}

		return dropCards;
	}

	private void AddEnvDropCard(List<Card> dropCards, int centerIndex)
	{
		if (dropCards == null || dropCards.Count == 0)
		{
			return;
		}

		if (m_EnvPanels == null || m_EnvPanels.Count == 0)
		{
			return;
		}

		centerIndex = Mathf.Clamp(centerIndex, 0, m_EnvPanels.Count - 1);

		var usedIndices = new HashSet<int>();
		var offsetPattern = BuildOffsetPattern(m_EnvPanels.Count);

		for (int i = 0; i < dropCards.Count; i++)
		{
			int panelIndex = FindPanelIndex(centerIndex, usedIndices, offsetPattern, m_EnvPanels.Count);
			if (panelIndex < 0)
			{
				panelIndex = centerIndex;
			}

			panelIndex = Mathf.Clamp(panelIndex, 0, m_EnvPanels.Count - 1);
			VerticalLayoutGroup parent = m_EnvPanels[panelIndex];
			UICardSimpleControl cardControl = GetCardSimple(parent.transform, true);
			cardControl.SetData(dropCards[i], isEnv: true, envIndex: panelIndex);
			AddEnvCard(panelIndex, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);

			usedIndices.Add(panelIndex);
		}
	}

	private List<int> BuildOffsetPattern(int panelCount)
	{
		var offsets = new List<int>();
		offsets.Add(0);
		int step = 1;
		while (offsets.Count < panelCount * 2)
		{
			offsets.Add(-step);
			offsets.Add(step);
			step++;
		}
		return offsets;
	}

	private int FindPanelIndex(int centerIndex, HashSet<int> usedIndices, List<int> offsetPattern, int panelCount)
	{
		for (int i = 0; i < offsetPattern.Count; i++)
		{
			int candidate = centerIndex + offsetPattern[i];
			if (candidate < 0 || candidate >= panelCount) continue;
			if (usedIndices.Contains(candidate)) continue;
			return candidate;
		}

		return Mathf.Clamp(centerIndex, 0, panelCount - 1);
	}

	void BoomEnvCard(object[] paraArray)
	{
		int envIndex = (int)paraArray[0];
		int damage = (int)paraArray[1];
		bool excludeSelf = paraArray.Length > 2 && paraArray[2] is bool && (bool)paraArray[2];

		if (envIndex == -1)
		{
			BoomEnvCardRandom(damage);
		}
		else
		{
			BoomEnvCardAtPosition(envIndex, damage, excludeSelf);
		}

	}

	private int FindRandomEnemy()
	{
		List<int> enemyIndices = new List<int>();
		for (int i = 0; i < m_EnvPanels.Count; i++)
		{
			UICardSimpleControl lastCard = GetLastEnvCard(i);
			if (lastCard != null && lastCard.gameObject.activeSelf && lastCard.CardType == ECardType.monster && lastCard.CardData.currentHealth > 0)
			{
				enemyIndices.Add(i);
			}
		}
		if (enemyIndices.Count == 0)
		{
			return -1;
		}
		if (enemyIndices.Count == 1)
		{
			return enemyIndices[0];
		}
		return enemyIndices[Random.Range(0, enemyIndices.Count)];
	}

	void AddEnvCardFromBag(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		AddEnvCardFromBag(cardControl);
	}

	void ThrowWeaponToEnv(object[] paraArray)
	{
		ThrowWeaponToEnv();
	}
	void ThrowWeaponDefenceToEnv(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		ThrowWeaponDefenceToEnv(cardControl);
	}

	void AddCardToSpecifiedEnv(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		string cardId = (string)paraArray[1];
		int envIndex = (int)paraArray[2];
		AddCardToEnv(cardControl, cardId, envIndex);
	}

	void AddCardToEnv(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		string cardId = (string)paraArray[1];
		AddCardToEnv(cardControl, cardId);
	}
	void AddCardsToEnv(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		List<Card> cards = (List<Card>)paraArray[1];
		int envIndex = Random.Range(0, m_EnvPanels.Count - 1);
		AddEnvDropCard(cards, envIndex);
	}

	void AddCardsToEnvByCardId(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		string cardId = (string)paraArray[1];
		int count = (int)paraArray[2];
		AddCardsToEnvByCardId(cardControl, cardId, count);
	}

	void SwapTopTwoEnvCards(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		SwapTopTwoEnvCards(cardControl);
	}

	void MonsterHealOnDealDamage(object[] paraArray)
	{
		UICardSimpleControl monsterCardControl = (UICardSimpleControl)paraArray[0];
		if (monsterCardControl != null && monsterCardControl.CardType == ECardType.monster)
		{
			VampireMonkeyDealDamage(monsterCardControl);
		}
	}
	void DoubleLastWeaponAttack(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		if (cardControl == null)
		{
			return;
		}
		UICardSimpleControl lastAttackCard = GetLastBagCard(ECardType.attack);

		if (lastAttackCard == null)
		{
			lastAttackCard = GetFistCard();

		}

		if (lastAttackCard != null)
		{
			int attackValue = lastAttackCard.CardData.currentAttack;
			Debug.Log($"Before DoubleLastWeaponAttack: {attackValue}");
			lastAttackCard.AddEffectValue(EEffectType.Damage, attackValue);
			Debug.Log($"After DoubleLastWeaponAttack: {lastAttackCard.CardData.currentAttack + lastAttackCard.CardEffect.GetEffectValue(EEffectType.Damage)}");
		}
	}

	void HealPlayerOnDefense(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		Debug.Log($"currentMonsterAttack: {currentMonsterAttack}");
		if (currentMonsterAttack > 0 && cardControl != null)
		{
			int defenceValue = cardControl.CardData.currentDefence;
			int healAmount = Mathf.Min(currentMonsterAttack, defenceValue);
			ApplyPlayerHealthChange(healAmount, true);
		}
		currentMonsterAttack = 0;
	}

	// 王之盾: 剑(1016)切换到盾(2011)
	void KingShieldSwitchToShield(object[] paraArray)
	{
		UICardSimpleControl cardControl = paraArray.Length > 0 && paraArray[0] is UICardSimpleControl ? (UICardSimpleControl)paraArray[0] : null;
		int currentSwitchCount = paraArray.Length > 1 && paraArray[1] is int ? (int)paraArray[1] : 0;

		if (cardControl == null)
		{
			return;
		}

		// 创建新的盾牌卡(2011)并加入防御牌堆
		string shieldCardId = "2011";
		Card newCard = CreateCard(shieldCardId);
		var description = newCard.description;
		newCard.description = description.Substring(0, description.Length - 1) + (1 - currentSwitchCount);
		ECardType cardType = newCard.GetCardType();
		Transform parent = GetParentByCardType(cardType);
		if (parent == null)
		{
			return;
		}
		m_CardDict[newCard.UniqueId] = newCard;
		UICardSimpleControl newCardControl = GetCardSimple(parent, false);
		newCardControl.SetData(newCard);
		AddBagCard(cardType, newCardControl);
		newCardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);

		// 传递切换计数到新卡的 CardEffect
		if (newCardControl.CardEffect is YKingShield_OnDefense shieldEffect)
		{
			shieldEffect.SwitchCount = currentSwitchCount + 1;
		}

		Debug.Log($"KingShield: 剑切换到盾，当前计数: {currentSwitchCount + 1}");
	}

	// 王之盾: 盾(2011)切换到剑(1016)
	void KingShieldSwitchToSword(object[] paraArray)
	{
		UICardSimpleControl cardControl = paraArray.Length > 0 && paraArray[0] is UICardSimpleControl ? (UICardSimpleControl)paraArray[0] : null;
		int currentSwitchCount = paraArray.Length > 1 && paraArray[1] is int ? (int)paraArray[1] : 0;

		if (cardControl == null)
		{
			return;
		}

		// 创建新的剑卡(1016)并加入攻击牌堆
		string swordCardId = "1016";
		Card newCard = CreateCard(swordCardId);
		var description = newCard.description;
		newCard.description = description.Substring(0, description.Length - 1) + (1 - currentSwitchCount);
		ECardType cardType = newCard.GetCardType();
		Transform parent = GetParentByCardType(cardType);
		if (parent == null)
		{
			return;
		}
		m_CardDict[newCard.UniqueId] = newCard;
		UICardSimpleControl newCardControl = GetCardSimple(parent, false);
		newCardControl.SetData(newCard);
		AddBagCard(cardType, newCardControl);
		newCardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);

		// 传递切换计数到新卡的 CardEffect
		if (newCardControl.CardEffect is YKingShield_OnAttack swordEffect)
		{
			swordEffect.SwitchCount = currentSwitchCount + 1;
		}

		Debug.Log($"KingShield: 盾切换到剑，当前计数: {currentSwitchCount + 1}");
	}

	void RemoveCardData(int uniqueId)
	{
		if (m_CardDict.TryGetValue(uniqueId, out Card card))
		{
			UsedCardList.Add(card);
			m_CardDict.Remove(uniqueId);
		}
	}

	public void ClearAllCard()
	{
		m_CardSimplePool.ForEach(cardControl =>
		{
			if (cardControl != null && cardControl.gameObject.activeSelf && cardControl != m_FistCardCache)
			{
				cardControl.Return();
			}
		});

		m_CardDict.Clear();
		m_EnvCardDict.Clear();
		m_BagCardDict.Clear();
		UsedCardList.Clear();
		ClearAllCardCts();
	}

	private CancellationToken GetOrCreateCardToken(UICardSimpleControl cardControl)
	{
		if (cardControl == null)
		{
			return CancellationToken.None;
		}

		if (!m_CardCtsDict.TryGetValue(cardControl, out CancellationTokenSource cts) || cts == null || cts.IsCancellationRequested)
		{
			if (cts != null)
			{
				cts.Dispose();
				m_CardCtsDict.Remove(cardControl);
			}
			cts = new CancellationTokenSource();
			m_CardCtsDict[cardControl] = cts;
			string cardId = cardControl?.CardData?.id ?? "null";
			string cardName = cardControl?.CardData?.cardName ?? "null";
			Debug.Log($"[AddCardCts] CardId: {cardId}, CardName: {cardName}, DictCount: {m_CardCtsDict.Count}");
		}

		return cts.Token;
	}

	private void RemoveCardCts(UICardSimpleControl cardControl)
	{
		if (cardControl == null)
		{
			return;
		}



		if (!m_CardCtsDict.TryGetValue(cardControl, out CancellationTokenSource cts))
		{
			string cardId = cardControl?.CardData?.id ?? "null";
			string cardName = cardControl?.CardData?.cardName ?? "null";
			Debug.LogWarning($"[RemoveCardCts] CardId: {cardId}, CardName: {cardName} not found in dict, DictCount: {m_CardCtsDict.Count}");
			return;
		}

		if (cts != null)
		{
			cts.Cancel();
			cts.Dispose();
		}
		m_CardCtsDict.Remove(cardControl);
		string cardId2 = cardControl?.CardData?.id ?? "null";
		string cardName2 = cardControl?.CardData?.cardName ?? "null";
		Debug.Log($"[RemoveCardCts] CardId: {cardId2}, CardName: {cardName2}, DictCount: {m_CardCtsDict.Count}");
	}

	private void ClearAllCardCts()
	{
		foreach (var kvp in m_CardCtsDict)
		{
			if (kvp.Value != null)
			{
				kvp.Value.Cancel();
				kvp.Value.Dispose();
			}
		}
		m_CardCtsDict.Clear();
	}

	public void ClearAllUniTasks()
	{
		ClearAllCardCts();
		m_MoveCardDelayAction.Cancel();
		if (m_ShakeScreenCts != null && !m_ShakeScreenCts.IsCancellationRequested)
		{
			m_ShakeScreenCts.Cancel();
			m_ShakeScreenCts.Dispose();
		}
		m_ShakeScreenCts = null;
		if (m_MoveBagCardsCts != null && !m_MoveBagCardsCts.IsCancellationRequested)
		{
			m_MoveBagCardsCts.Cancel();
			m_MoveBagCardsCts.Dispose();
		}
		m_MoveBagCardsCts = null;
	}

	async void MoveCard(object[] paraArray)
	{
		bool isEnv = (bool)paraArray[0];
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[1];
		cardControl.SetMoving(true);
		if (isEnv)
		{
			// 播放拿牌音效
			SFX.PlayAudio("Audio/SFX/deal_cards", 1.9f, 0.5f);

			// 魔剑士指环效果：加入手牌时转换武器牌/防御牌
			TryApplyMagicSwordsmanRing(cardControl);

			ECardType cardType = cardControl.CardType;

			Vector3 startWorldPos = cardControl.CacheTrans.parent.position;
			Vector3 startScale = Vector3.one;

			RemoveEnvCardFromDict(cardControl.EnvIndex, cardControl);
			AddBagCard(cardType, cardControl, true);

			VerticalLayoutGroup layout = null;
			switch (cardType)
			{
				case ECardType.attack:
					layout = m_View.AttackPanel;
					break;
				case ECardType.defence:
					layout = m_View.DefencePanel;
					break;
				case ECardType.skill:
					layout = m_View.SkillPanel;
					break;
				case ECardType.item:
					layout = m_View.ItemPanel;
					break;
				default:
					return;
			}

			Vector3 endScale = new Vector3(0.8f, 0.8f, 1.0f);
			float duration = .2f;
			Vector3 endPos = layout.transform.position;

			m_MoveCardDelayAction.AddAnimDelayAction(
				(cancellationToken) => MoveCardAnimation(cardControl, startWorldPos, endPos, startScale, endScale, duration, layout, cancellationToken),
				() =>
				{
					cardControl.CacheTrans.position = endPos;
					cardControl.CacheTrans.localScale = endScale;
					cardControl.CacheTrans.localEulerAngles = Vector3.zero;
					layout.enabled = true;
					cardControl.SetMoving(false);
					
					// Trigger OnEnterBag for the moved card
					if (cardControl.CardEffect != null)
					{
						Debug.Log($"[MoveCard] Calling OnEnterBag for moved card: {cardControl.CardData.cardName} (UniqueId: {cardControl.CardData.UniqueId}, Type: {cardType})");
						cardControl.CardEffect.OnEnterBag();
					}
					
					// Check if the moved card becomes top of pile
					UICardSimpleControl lastBagCard = GetLastBagCard(cardType);
					if (lastBagCard == cardControl && cardControl.CardEffect != null)
					{
						Debug.Log($"[MoveCard] Moved card becomes top of pile, calling OnBecomeTopOfPile for {cardControl.CardData.cardName} (UniqueId: {cardControl.CardData.UniqueId}, Type: {cardType})");
						cardControl.CardEffect.OnBecomeTopOfPile();
					}
					
					// Also trigger OnEnterBag for CurrentEffectCard (the item/skill that caused the move)
					if (CurrentEffectCard != null)
					{
						CurrentEffectCard.CardEffect?.OnEnterBag();

						CurrentEffectCard.IsEffecting = false;
						RemoveCardCts(CurrentEffectCard);
					}

				}
			);
		}
	}

	private async UniTask MoveCardAnimation(UICardSimpleControl cardControl, Vector3 startPos, Vector3 endPos, Vector3 startScale, Vector3 endScale, float duration, VerticalLayoutGroup layout, CancellationToken cancellationToken)
	{
		if (layout != null)
		{
			layout.enabled = false;
			cardControl.CacheTrans.SetParent(layout.transform);
		}

		float elapsed = 0f;
		while (elapsed < duration)
		{
			cancellationToken.ThrowIfCancellationRequested();
			elapsed += Time.deltaTime;
			float t = elapsed / duration;

			cardControl.CacheTrans.position = Vector3.Lerp(startPos, endPos, t);
			cardControl.CacheTrans.localScale = Vector3.Lerp(startScale, endScale, t);

			//Debug.Log($"MoveCard Animation - Position: {cardControl.CacheTrans.position}, Scale: {cardControl.CacheTrans.localScale}, t: {t}");

			await UniTask.Yield(cancellationToken);
		}
	}

	public void MoveBagCardsToCoinAndShowReward()
	{
		if (m_MoveBagCardsCts != null && !m_MoveBagCardsCts.IsCancellationRequested)
		{
			m_MoveBagCardsCts.Cancel();
			m_MoveBagCardsCts.Dispose();
		}
		m_MoveBagCardsCts = new CancellationTokenSource();
		MoveBagCardsToCoinAndShowRewardAsync(m_MoveBagCardsCts.Token).Forget();
	}

	private async UniTaskVoid MoveBagCardsToCoinAndShowRewardAsync(CancellationToken cancellationToken)
	{
		List<UICardSimpleControl> bagCards = new List<UICardSimpleControl>();
		foreach (var kvp in m_BagCardDict)
		{
			List<UICardSimpleControl> cardList = kvp.Value;
			for (int i = 0; i < cardList.Count; i++)
			{
				UICardSimpleControl cardControl = cardList[i];
				if (cardControl != m_FistCardCache)
				{
					bagCards.Add(cardControl);
				}
			}
		}

		Vector3 targetPos = m_View.TxtCoin.transform.position;
		float duration = 0.5f;

		List<UniTask> animationTasks = new List<UniTask>();
		for (int i = 0; i < bagCards.Count; i++)
		{
			UICardSimpleControl cardControl = bagCards[i];
			cardControl.transform.SetParent(Asset.UIRoot);
			Vector3 startPos = cardControl.CacheTrans.position;
			Vector3 startScale = cardControl.CacheTrans.localScale;
			Vector3 endScale = Vector3.zero;

			animationTasks.Add(MoveCardAnimation(cardControl, startPos, targetPos, startScale, endScale, duration, null, CancellationToken.None));
		}

		await UniTask.WhenAll(animationTasks);

		for (int i = 0; i < bagCards.Count; i++)
		{
			UICardSimpleControl cardControl = bagCards[i];
			RemoveCardData(cardControl.CardData.UniqueId);
			RemoveCardCts(cardControl);
			cardControl.Return();
		}


		int coinReward = bagCards.Count * 5;
		if (coinReward > 0)
		{
			DataSystem.Instance.AddCoin(coinReward);
			OnCoinChanged(m_DataJoeyPlayer.Coin);
			DataAchievement achievement = DataSystem.Instance.GetDataAchievement();
			if (m_DataJoeyPlayer.Coin > achievement.MaxCoinNum)
			{
				achievement.MaxCoinNum = m_DataJoeyPlayer.Coin;
				DataSystem.Instance.SaveDataAchievement();
			}
			UIDamageTextControl damageTextControl = m_DamageTextPool.Get();
			damageTextControl.SetCoinData(coinReward, Asset.UIRoot, Vector3.zero);
			damageTextControl.transform.position = m_View.TxtCoin.transform.position - new Vector3(1f, 1f, 0f);
		}
	}

	async void TakeEnemyDamage(object[] paraArray)
	{
		UICardSimpleControl enemyCardControl = (UICardSimpleControl)paraArray[0];
		int attackCount = (int)paraArray[1];
		int envIndex = (int)paraArray[2];
		m_CurrentAttackTargetEnvIndex = envIndex;  // 记录当前攻击目标位置，供溅射效果使用
		UICardSimpleControl attackCardControl = GetLastBagCard(ECardType.attack);
		if (attackCardControl == null)
		{
			attackCardControl = GetFistCard();
		}
		bool useFistCard = attackCardControl == m_FistCardCache;


		attackCount += attackCardControl.CardEffect?.GetEffectValue(EEffectType.ExtraAttackCnt) ?? 0;

		// DoublePunch relic: bare hands can attack twice
		if (DataSystem.Instance.HasRelic(ERelicType.DoublePunch))
		{
			if (attackCardControl.CardEffect != null && attackCardControl.CardEffect.Id == ECardEffectId.BareHands)
			{
				attackCount += 1;
			}
		}

		Card attackCard = attackCardControl.CardData;
		int damage = attackCard.currentAttack;
		float delayTime;
		delayTime = attackCardControl.CardEffect?.UseAttack() ?? 0f;
		await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(attackCardControl));

		if (useFistCard)
		{
			DataAchievement achievement = DataSystem.Instance.GetDataAchievement();
			achievement.FistUseNum++;
			DataSystem.Instance.SaveDataAchievement();
		}



		if (DataSystem.Instance.HasRelic(ERelicType.GetSpecialCardByAttack))
		{
			if (ControlUtil.IsRandomSucceed(5))
			{
				AddCardToBag("3009");
			}
		}

	bool hasSlowAttack = attackCardControl.CardEffect?.GetEffectValue(EEffectType.SlowAttack) > 0;
	bool enemyCounteredFirst = false;
	if (hasSlowAttack && enemyCardControl != null && enemyCardControl.gameObject.activeSelf && enemyCardControl.CardData.currentHealth > 0)
	{
		int enemyAttack = enemyCardControl.CardData.currentAttack;
		if (enemyAttack > 0)
		{
			CancellationToken enemyToken = GetOrCreateCardToken(enemyCardControl);
			await TakePlayerDamageAsync(enemyAttack, enemyCardControl, envIndex, enemyToken, attackCardControl);
			enemyCounteredFirst = true;
		}
	}

	// Cache NoCounterAttack flag before dealing damage, because enemy's OnTakeDamage may remove the weapon (e.g. BigDumbDonkey kicks weapon away)
	bool hasNoCounterAttack = attackCardControl.CardEffect?.GetEffectValue(EEffectType.NoCounterAttack) > 0;

	bool enemyKilled = false;
		for (int i = 0; i < attackCount; i++)
		{
			// Reset damage to base attack for each attack iteration
			damage = attackCard.currentAttack;
			
			if (DataSystem.Instance.HasRelic(ERelicType.LifeSteal))
			{
				YActionSystem.Instance.DispatchAction(EActionId.AddHp, 1);
			}
			delayTime = attackCardControl.CardEffect?.OnDealDamage() ?? 0.5f;

			damage += attackCardControl.CardEffect.GetEffectValue(EEffectType.Damage);
			// 染血拳套relic效果：血量低于50%时，赤手空拳/拳套的伤害+5
			if (DataSystem.Instance.HasRelic(ERelicType.BloodyGloves))
			{
				if (attackCardControl.CardEffect != null && attackCardControl.CardEffect.Id == ECardEffectId.BareHands)
				{
					if (JoeyGameControl.Instance.IsPlayerHalfHealth())
					{
						damage += 5;
					}
				}
			}
			// 双持精通relic效果：没有装备防具时，所有伤害+5
			if (DataSystem.Instance.HasRelic(ERelicType.DualWieldMastery))
			{
				if (!HasBagCard(ECardType.defence))
				{
					damage += 5;
				}
			}
			await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(attackCardControl));

			bool isKilled = await DealDamageToEnvCard(enemyCardControl, damage, envIndex, EEffectType.Damage, GetOrCreateCardToken(attackCardControl));

			// Apply Strike vulnerable effect after damage is dealt (but before checking if killed)
			if (!isKilled)
			{
				ApplyStrikeVulnerable(enemyCardControl);
			}

			if (damage > 0)
			{
				DataAchievement achievement = DataSystem.Instance.GetDataAchievement();
				if (damage > achievement.MaxDamageNum)
				{
					achievement.MaxDamageNum = damage;
					DataSystem.Instance.SaveDataAchievement();
				}
			}
			if (isKilled)
			{
				enemyKilled = true;

				delayTime = attackCardControl.CardEffect?.OnKill() ?? 0.5f;
				await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(attackCardControl));

				if (DataSystem.Instance.HasRelic(ERelicType.HealOnKill))
				{
					AddHp(3);
				}

			break;
		}
	}

	// 检查怪物是否被冰冻
		bool isEnemyFrozen = enemyCardControl != null && enemyCardControl.IsFrozen();
		if (isEnemyFrozen)
		{
			// 被冰冻的怪物受到武器攻击后解冻，不进行反击
			enemyCardControl.RemoveBuff(EBuffType.Frozen);
			Debug.Log($"Monster at envIndex {envIndex} unfrozen after weapon attack");
		}

		if (!enemyKilled && !hasNoCounterAttack && !enemyCounteredFirst && !isEnemyFrozen && enemyCardControl != null && enemyCardControl.gameObject.activeSelf && enemyCardControl.CardData.currentHealth > 0)
		{
			int enemyAttack = enemyCardControl.CardData.currentAttack;
			CancellationToken enemyToken = GetOrCreateCardToken(enemyCardControl);
			await TakePlayerDamageAsync(enemyAttack, enemyCardControl, envIndex, enemyToken, attackCardControl);
		}

		// Play card consumption animation after enemy counter-attack (if any)
		// This ensures counter-insight parry/counter animations complete before the card disappears
		bool isSkip = IsUseAttackFinishAnim();
		float finishDelayTime = attackCardControl.CardEffect?.OnUseFinished(isSkip) ?? 0f;
		if (finishDelayTime > 0f)
		{
			await UniTask.WaitForSeconds(finishDelayTime, cancellationToken: GetOrCreateCardToken(attackCardControl));
		}


		if (!useFistCard)
		{
			// Check if card should be kept in bag (durability mechanic)
			bool shouldKeep = attackCardControl.CardEffect?.ShouldKeepInBag() ?? false;

			if (!shouldKeep)
			{
				await RemoveBagCard(ECardType.attack, attackCardControl);
				float removeDelayTime = attackCardControl.CardEffect?.OnRemoveCard() ?? 0f;
				if (removeDelayTime > 0f)
				{
					await UniTask.WaitForSeconds(removeDelayTime, cancellationToken: GetOrCreateCardToken(attackCardControl));
				}

				// Check if attack bag is empty, if so trigger fist card's OnBecomeTopOfPile
				UICardSimpleControl nextAttackCard = GetLastBagCard(ECardType.attack);
				if (nextAttackCard == null && m_FistCardCache != null)
				{
					float fistDelayTime = m_FistCardCache.CardEffect?.OnBecomeTopOfPile() ?? 0f;
					if (fistDelayTime > 0f)
					{
						await UniTask.WaitForSeconds(fistDelayTime);
					}
				}
			}
		}
		else
		{
			m_FistCardCache.ClearEffectVlaue();

		}




		RemoveCardCts(attackCardControl);

		// Consume DualWield buff after attack
		ConsumeDualWieldBuff();
		// Consume ShieldBash buff after attack
		ConsumeShieldBashBuff();

		// Clean up enemy card's CTS if it wasn't already removed during counter-attack
		if (m_CardCtsDict.ContainsKey(enemyCardControl))
		{
			RemoveCardCts(enemyCardControl);
		}

		enemyCardControl.IsEffecting = false;
	}

	async void TakePlayerDamage(object[] paraArray)
	{
		int enemyAttack = (int)paraArray[0];
		UICardSimpleControl enemyCardControl = (UICardSimpleControl)paraArray[1];
		int envIndex = (int)paraArray[2];
		CancellationToken enemyToken = GetOrCreateCardToken(enemyCardControl);
		await TakePlayerDamageAsync(enemyAttack, enemyCardControl, envIndex, enemyToken, null);
	}

	async UniTask TakePlayerDamageAsync(int enemyAttack, UICardSimpleControl enemyCardControl, int envIndex, CancellationToken cancellationToken = default, UICardSimpleControl attackCardControl = null)
	{
		if (!m_CardCtsDict.TryGetValue(enemyCardControl, out CancellationTokenSource _))
		{
			return;
		}

		// Play enemy attack animation first
		currentMonsterAttack = enemyAttack;
		float delayTime = enemyCardControl.CardEffect?.OnDealDamage() ?? 0.5f;
		await UniTask.WaitForSeconds(delayTime, cancellationToken: cancellationToken);

		// Check CounterInsight relic for dodge and counter-attack (after enemy animation)
		bool dodgedWithCounterInsight = await TryCounterInsightDodge(enemyCardControl, enemyAttack, envIndex, cancellationToken);
		if (dodgedWithCounterInsight)
		{
			// Attack was dodged and countered, skip damage processing
			RemoveCardCts(enemyCardControl);
			currentMonsterAttack = 0;
			return;
		}

		// Increment CounterInsight counter (if relic is equipped)
		IncrementCounterInsight();

		int defenceValue = 0;
		UICardSimpleControl defenceCardControl = GetLastBagCard(ECardType.defence);
		bool usedWeaponParry = false;

		// Check if DualWield is active - if so, cannot use defence cards
		if (m_DualWieldActive && defenceCardControl != null)
		{
			Debug.Log("DualWield active: Cannot use defence cards!");
			defenceCardControl = null; // Disable defence card usage
		}

		// If no defence card, check for WeaponParry relic to use weapon as defence
		if (defenceCardControl == null && DataSystem.Instance.HasRelic(ERelicType.WeaponParry))
		{
			UICardSimpleControl weaponCard = GetLastBagCard(ECardType.attack);
			if (weaponCard != null && weaponCard != m_FistCardCache)
			{
				// Calculate current weapon attack including all bonuses
				int currentWeaponAttack = weaponCard.CardData.currentAttack;
				currentWeaponAttack += weaponCard.CardEffect?.GetEffectValue(EEffectType.Damage) ?? 0;
				
				// Add BloodyGloves relic bonus if applicable
				if (DataSystem.Instance.HasRelic(ERelicType.BloodyGloves))
				{
					if (weaponCard.CardEffect != null && weaponCard.CardEffect.Id == ECardEffectId.BareHands)
					{
						if (JoeyGameControl.Instance.IsPlayerHalfHealth())
						{
							currentWeaponAttack += 5;
						}
					}
				}
				
				// Add DualWieldMastery relic bonus if applicable
				if (DataSystem.Instance.HasRelic(ERelicType.DualWieldMastery))
				{
					if (!HasBagCard(ECardType.defence))
					{
						currentWeaponAttack += 5;
					}
				}
				
				// Use weapon as defence (defence value = 20% of current weapon attack)
				defenceCardControl = weaponCard;
				defenceValue = Mathf.RoundToInt(currentWeaponAttack * 0.2f);
				usedWeaponParry = true;

				bool isOverflow = defenceValue < enemyAttack;
				// Play defence animation
				var vfxNames = new List<EVFXName> { EVFXName.VFX_Dun };
				float vfxDelay = defenceCardControl.PlayVFX(vfxNames, ECardAnimName.UI_Carditem_dunpai, EVFXLife.SelfLife);
				SFX.PlayAudio("Audio/SFX/Battle/Defence", 1.0f, 0f);
				delayTime = vfxDelay > 0f ? vfxDelay : 0.5f;
				await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(defenceCardControl));
			}
		}
		else if (defenceCardControl != null)
		{
			defenceValue = defenceCardControl.CardData.currentDefence + (defenceCardControl.CardEffect?.GetEffectValue(EEffectType.Defence) ?? 0);
			bool isOverflow = defenceValue < enemyAttack;
			delayTime = defenceCardControl.CardEffect?.UseDefence(isOverflow) ?? 0.5f;
			await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(defenceCardControl));

			if (DataSystem.Instance.HasRelic(ERelicType.GetSpecialCardByDefence))
			{
				if (ControlUtil.IsRandomSucceed(10))
				{
					AddCardToBag("3010");
				}
			}
		}
		int damage = 0;
		if (defenceValue < enemyAttack)
		{
			damage = enemyAttack - defenceValue;
			if (DataSystem.Instance.HasRelic(ERelicType.Callus) && damage > 0 && damage < 3)
			{
				damage = 0;
			}
		}

		// BareHandParry relic: Block half damage when no weapon and no defence equipped
		if (DataSystem.Instance.HasRelic(ERelicType.BareHandParry) && damage > 0)
		{
			bool hasNoWeapon = !HasBagCard(ECardType.attack);
			bool hasNoDefence = !HasBagCard(ECardType.defence);

			if (hasNoWeapon && hasNoDefence)
			{
				int blockedDamage = damage / 2;
				damage = damage - blockedDamage;
				Debug.Log($"BareHandParry: Blocked {blockedDamage} damage, remaining damage: {damage}");

				// Play defence animation on fist card (bare hands weapon)
				if (m_FistCardCache != null)
				{
					var vfxNames = new List<EVFXName> { EVFXName.VFX_Dun };
					float vfxDelay = m_FistCardCache.PlayVFX(vfxNames, ECardAnimName.UI_Carditem_dunpai, EVFXLife.SelfLife);
					SFX.PlayAudio("Audio/SFX/Battle/Defence", 1.0f, 0f);
					delayTime = vfxDelay > 0f ? vfxDelay : 0.3f;
					await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(m_FistCardCache));
				}
				else
				{
					// Fallback to player visual effect if fist card not available
					JoeyGameControl.Instance.PlayVFX(EVFXName.VFX_Dun, m_View.Joey, 0.3f);
				}
			}
		}

		if (damage > 0 && TryBlockFatalDamage(damage))
		{
			damage = m_DataJoeyPlayer.playerHealth - 1;
		}

		// Only play hit sound if actually taking damage
		if (damage > 0)
		{
			SFX.PlayAudio("Audio/SFX/Battle/MonsterOnAttack", 1.0f, 0f);
		}
		ApplyPlayerHealthChange(-damage);
		OnAttackChanged(m_DataJoeyPlayer.playerAttack);
		OnDefenceChanged(m_DataJoeyPlayer.playerDefence);

		if (damage > 0)
		{
			DataAchievement achievement = DataSystem.Instance.GetDataAchievement();
			if (damage > achievement.MaxTakeDamageNum)
			{
				achievement.MaxTakeDamageNum = damage;
				DataSystem.Instance.SaveDataAchievement();
			}
		}

		if (defenceCardControl != null)
		{
			// Handle weapon parry or normal defence card
			int reflectDamage = defenceCardControl.CardEffect?.GetEffectValue(EEffectType.ReflectDamage) ?? 0;

			if (DataSystem.Instance.HasRelic(ERelicType.ShieldReflect) && !usedWeaponParry)
			{
				int shieldDefence = defenceValue;
				int relicReflectDamage = shieldDefence / 2;
				if (relicReflectDamage > 0)
				{
					reflectDamage += relicReflectDamage;
				}
			}

			if (reflectDamage > 0)
			{
				await AttackSpecialEnemy(enemyCardControl, reflectDamage, envIndex, GetOrCreateCardToken(defenceCardControl));
			}
			
			// Call OnUseFinished for both weapon parry and normal defence cards
			// This handles durability reduction for cards like Knight Sword
			float finishDelayTime = defenceCardControl.CardEffect?.OnUseFinished(false) ?? 0f;
			if (finishDelayTime > 0f)
			{
				await UniTask.WaitForSeconds(finishDelayTime, cancellationToken: GetOrCreateCardToken(defenceCardControl));
			}

			// Check if card should be kept in bag (durability mechanic)
			bool shouldKeep = defenceCardControl.CardEffect?.ShouldKeepInBag() ?? false;

			if (!shouldKeep)
			{
				// Remove from appropriate bag type (attack for weapon parry, defence for normal)
				ECardType cardType = usedWeaponParry ? ECardType.attack : ECardType.defence;
				await RemoveBagCard(cardType, defenceCardControl);
				float removeDelayTime = defenceCardControl.CardEffect?.OnRemoveCard() ?? 0f;
				if (removeDelayTime > 0f)
				{
					await UniTask.WaitForSeconds(removeDelayTime, cancellationToken: GetOrCreateCardToken(defenceCardControl));
				}
			}

			// Always remove card token (cleanup) regardless of whether card is kept
			RemoveCardCts(defenceCardControl);
		}
		if (DataSystem.Instance.HasRelic(ERelicType.ThornBlessing))
		{
			await AttackSpecialEnemy(enemyCardControl, 3, envIndex, cancellationToken);
		}

		RemoveCardCts(enemyCardControl);
		currentMonsterAttack = 0;
	}

	void TakePlayerBoomDamage(object[] paraArray)
	{
		int damage = (int)paraArray[0];
		EVFXName vfxName = paraArray.Length > 1 && paraArray[1] is EVFXName ? (EVFXName)paraArray[1] : EVFXName.VFX_boom;
		if (damage > 0)
		{
			JoeyGameControl.Instance.PlayVFX(vfxName, m_View.Joey, 0.4f);
			SFX.PlayAudio("Audio/SFX/Battle/boom", 1.0f, 0f);
		}

		if (damage > 0 && TryBlockFatalDamage(damage))
		{
			damage = m_DataJoeyPlayer.playerHealth - 1;
		}

		ApplyPlayerHealthChange(-damage);
	}

	void TakePlayerNoDefenceDamage(object[] paraArray)
	{
		int damage = (int)paraArray[0];
		EVFXName vfxName = paraArray.Length > 1 && paraArray[1] is EVFXName ? (EVFXName)paraArray[1] : EVFXName.VFX_boom;
		if (damage > 0)
		{
			JoeyGameControl.Instance.PlayVFX(vfxName, m_View.Joey, 0.4f);
			SFX.PlayAudio("Audio/SFX/Battle/MonsterOnAttack", 1.0f, 0f);
		}

		if (damage > 0 && TryBlockFatalDamage(damage))
		{
			damage = m_DataJoeyPlayer.playerHealth - 1;
		}

		ApplyPlayerHealthChange(-damage);
	}


	async void UseBagCard(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		ECardType cardType = cardControl.CardType;
		float delayTime = 0f;

		if (cardType == ECardType.skill)
		{
			delayTime = cardControl.CardEffect?.UseSkill() ?? 0.5f;
			// 魔法剑效果：技能牌使用后增加手牌顶部武器牌攻击力
			MagicSwordOnSkillUsed();
			// 魔法盾效果：技能牌使用后增加手牌顶部防御牌防御力
			MagicShieldOnSkillUsed();
			if (DataSystem.Instance.HasRelic(ERelicType.GetSpecialCardBySkill))
			{
				if (ControlUtil.IsRandomSucceed(10))
				{
					AddCardToBag("3008");
				}
			}
			// 奥术宝珠效果：每施放三次技能获得一张技能牌4013
			TryArcaneOrbTrigger();
		}
		else if (cardType == ECardType.item)
		{
			delayTime = cardControl.CardEffect?.UseItem() ?? 0.5f;
			if (DataSystem.Instance.HasRelic(ERelicType.GetSpecialCardByItem))
			{
				if (ControlUtil.IsRandomSucceed(10))
				{
					AddCardToBag("3007");
				}
			}
		}

		await UniTask.WaitForSeconds(delayTime);

		float finishDelayTime = cardControl.CardEffect?.OnUseFinished(false) ?? 0f;
		if (finishDelayTime > 0f)
		{
			await UniTask.WaitForSeconds(finishDelayTime);
		}

		// Check if card should be kept in bag (durability mechanic)
		bool shouldKeep = cardControl.CardEffect?.ShouldKeepInBag() ?? false;

		if (!shouldKeep)
		{
			await RemoveBagCard(cardType, cardControl);

			float removeDelayTime = cardControl.CardEffect?.OnRemoveCard() ?? 0f;
			if (removeDelayTime > 0f)
			{
				await UniTask.WaitForSeconds(removeDelayTime);
			}
		}

		// Always remove card token (cleanup) regardless of whether card is kept
		RemoveCardCts(cardControl);

		if (CurrentEffectCard != null)
		{
			CurrentEffectCard.IsEffecting = false;
		}
	}

	void AddCardFromDiscard(object[] paraArray)
	{
		ECardType specialCardType = paraArray.Length > 0 && paraArray[0] is ECardType ? (ECardType)paraArray[0] : ECardType.other;
		if (specialCardType == ECardType.attack)
		{
			AddCardFromDiscardAttack();
		}
		else
		{
			AddCardFromDiscardByType(specialCardType);
		}
	}

	void AddCardToBagFromSelect(object[] paraArray)
	{
		if (paraArray.Length > 0 && paraArray[0] is Card)
		{
			Card card = (Card)paraArray[0];
			AddCardToBag(card);
		}
	}

	async void AttackRandomEnemy(object[] paraArray)
	{
		int damage = paraArray[0] is int ? (int)paraArray[0] : 0;
		int attackTime = paraArray.Length > 1 && paraArray[1] is int ? (int)paraArray[1] : 1;
		await AttackRandomEnemy(damage, attackTime).SuppressCancellationThrow();
	}

	async UniTask AttackSpecialEnemy(UICardSimpleControl enemyCardControl, int damage, int envIndex, CancellationToken? cancellationToken = null)
	{
		if (enemyCardControl == null)
		{
			return;
		}

		await DealDamageToEnvCard(enemyCardControl, damage, envIndex, EEffectType.ReflectDamage, cancellationToken);
	}

	async void TakeAllEnemyDamage(object[] paraArray)
	{
		int damage = paraArray[0] is int ? (int)paraArray[0] : 0;
		await TakeAllEnemyDamage(damage);
	}

	void AddCardToQueue(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		if (cardControl != null && !cardControl.IsEffecting && !m_CardActionQueue.Contains(cardControl) && CurrentEffectCard != cardControl)
		{
			for (int i = 0; i < m_EnvPanels.Count; i++)
			{
				UICardSimpleControl lastCard = GetLastEnvCard(i);
				if (lastCard != null)
				{
					lastCard.UpdateBuffValue();
				}
			}
			if (cardControl.gameObject.activeSelf)
			{
				cardControl.IsEffecting = true;
				m_CardActionQueue.Enqueue(cardControl);
				CardActionQueueDebug = new List<UICardSimpleControl>(m_CardActionQueue);
				CardCtsDictDebug = new List<UICardSimpleControl>(m_CardCtsDict.Keys);
			}
			m_View.TxtPhaseCnt.text = PhaseCounter.ToString();
			CheckAndSpawnKeyPath();
		}
	}

	void AddEffectValueToBagCard(object[] paraArray)
	{
		ECardType targetCardType = (ECardType)paraArray[0];
		EEffectType effectType = (EEffectType)paraArray[1];
		int value = (int)paraArray[2];
		AddEffectValueToBagCard(targetCardType, effectType, value);
	}

	void FixedUpdate()
	{
		if (CurrentEffectCard == null && m_CardActionQueue.Count > 0)
		{
			CurrentEffectCard = m_CardActionQueue.Dequeue();
			CardActionQueueDebug = new List<UICardSimpleControl>(m_CardActionQueue);
			CardCtsDictDebug = new List<UICardSimpleControl>(m_CardCtsDict.Keys);
			if (CurrentEffectCard != null)
			{
				//Debug.Log($"[Update] New CurrentEffectCard:{CurrentEffectCard?.CardData?.cardName}, IsEffecting:{CurrentEffectCard?.IsEffecting}");
				GetOrCreateCardToken(CurrentEffectCard);
				CurrentEffectCard.OnBtnRealClick();
			}
		}

		if (CurrentEffectCard != null && !CurrentEffectCard.IsEffecting && m_CardCtsDict.Count == 0)
		{

			TryBloodStorageHeal();
			TryUnyieldingTurnUpdate();
			TryRegenerationHeal();
			TryHalfHealthAmulet();
			UpdateVulnerableDebuffs();
			CurrentEffectCard = null;
			PhaseCounter++;
			UpdateBlockFatalDisplay();

		}
		else if (CurrentEffectCard != null)
		{
			if (CurrentEffectCard.IsEffecting && m_CardCtsDict.Count == 0)
			{
				Debug.Log($"[Update] CurrentEffectCard stuck - card:{CurrentEffectCard?.CardData?.cardName}, IsEffecting:{CurrentEffectCard?.IsEffecting}, m_CardCtsDict.Count:{m_CardCtsDict.Count}");
			}
		}
	}

	void LateUpdate()
	{
	}

	private bool HasAnyMonsterInEnv()
	{
		foreach (var kvp in m_EnvCardDict)
		{
			if (kvp.Value != null)
			{
				foreach (var card in kvp.Value)
				{
					if (card != null && card.gameObject.activeSelf && card.CardType == ECardType.monster)
					{
						return true;
					}
				}
			}
		}
		return false;
	}

	private void CheckAndSpawnKeyPath()
	{
		if (m_KeyPathSpawned)
		{
			return;
		}

		if (!HasAnyMonsterInEnv())
		{
			SpawnKeyPath();
		}
	}

	private void SpawnKeyPath()
	{
		m_KeyPathSpawned = true;

		foreach (var kvp in m_EnvCardDict)
		{
			List<UICardSimpleControl> envCardList = kvp.Value;
			if (envCardList != null)
			{
				for (int i = 0; i < envCardList.Count; i++)
				{
					UICardSimpleControl cardControl = envCardList[i];
					if (cardControl != null && cardControl.gameObject.activeSelf)
					{
						cardControl.OnBtnRealClick();
					}
				}
			}
		}

		if (m_KeyPathCardCache != null)
		{
			m_KeyPathCardCache.gameObject.SetActive(true);
			int envIndex = m_KeyPathCardCache.EnvIndex;
			if (envIndex >= 0 && envIndex < m_EnvPanels.Count)
			{
				m_KeyPathCardCache.CacheTrans.SetParent(m_EnvPanels[envIndex].transform, false);
			}
			//m_KeyPathCardCache.CacheTrans.SetAsLastSibling();
			m_KeyPathCardCache.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
		}
	}

	public void ClearCardQueue()
	{
		if (CurrentEffectCard != null)
		{
			CurrentEffectCard.IsEffecting = false;
			RemoveCardCts(CurrentEffectCard);
			CurrentEffectCard.Return();
		}
		CurrentEffectCard = null;

		while (m_CardActionQueue.Count > 0)
		{
			UICardSimpleControl cardControl = m_CardActionQueue.Dequeue();
			cardControl.IsEffecting = false;
			RemoveCardCts(cardControl);
			cardControl.Return();
		}
		CardActionQueueDebug = null;
		CardCtsDictDebug = null;

	}


	void OnCoinChange(object[] paraArray)
	{
		int coin = (int)paraArray[0];
		int delta = paraArray.Length > 1 && paraArray[1] is int ? (int)paraArray[1] : 0;
		OnCoinChanged(coin);
		if (delta != 0)
		{
			UIDamageTextControl damageTextControl = m_DamageTextPool.Get();
			damageTextControl.SetCoinData(delta, Asset.UIRoot, Vector3.zero);
			damageTextControl.transform.position = m_View.TxtCoin.transform.position - new Vector3(1f, 1f, 0f);
		}
	}

	void SwapEnvCard(object[] paraArray)
	{
		SwapEnvCard();
	}

	void RomeoMonkeyDead(object[] paraArray)
	{
		this.OnRomeoMonkeyDead();
	}

	void JulietMonkeyDead(object[] paraArray)
	{
		this.OnJulietMonkeyDead();
	}

	void BananaMonkeyDead(object[] paraArray)
	{
		this.OnBananaMonkeyDead();
	}

	void UpdateRelic(object[] paraArray)
	{
		RefreshRelicDisplay();
		int relicId = (int)paraArray[0];
		UpdateAllCardsRelic(relicId);
		
		// DualWieldMastery relic: Refresh attack cards to show bonus
		if (relicId == (int)ERelicType.DualWieldMastery)
		{
			RefreshAllAttackCards();
		}
	}

	private void UpdateAllCardsRelic(int relicId)
	{
		foreach (var kvp in m_BagCardDict)
		{
			List<UICardSimpleControl> bagCardList = kvp.Value;
			for (int i = 0; i < bagCardList.Count; i++)
			{
				UICardSimpleControl cardControl = bagCardList[i];
				cardControl.AddRelic(relicId);
			}
		}

		// Special handling for BareHandsMaster or HighArt relic: recreate fist card cache
		if (relicId == (int)ERelicType.BareHandsMaster || relicId == (int)ERelicType.HighArt)
		{
			if (m_FistCardCache != null)
			{
				m_FistCardCache.Return();
				m_FistCardCache = null;
			}
			CreateFistCardCache();
		}
		else
		{
			m_FistCardCache.AddRelic(relicId);
		}

		foreach (var kvp in m_EnvCardDict)
		{
			List<UICardSimpleControl> envCardList = kvp.Value;
			for (int i = 0; i < envCardList.Count; i++)
			{
				UICardSimpleControl cardControl = envCardList[i];
				if (cardControl.CardType != ECardType.monster && cardControl.CardType != ECardType.other)
				{
					cardControl.AddRelic(relicId);
				}
			}
		}
	}
	
	private void RefreshAllAttackCards()
	{
		// Refresh all attack cards in bag
		List<UICardSimpleControl> attackCardList = GetBagCardList(ECardType.attack);
		if (attackCardList != null)
		{
			for (int i = 0; i < attackCardList.Count; i++)
			{
				attackCardList[i].RefreshCard();
			}
		}
		
		// Refresh fist card (bare hands)
		if (m_FistCardCache != null)
		{
			m_FistCardCache.RefreshCard();
		}
	}

	void OnCardPointerEnter(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		if (cardControl == null)
		{
			return;
		}

		bool shouldShow = false;
		if (cardControl.IsEnv)
		{
			UICardSimpleControl lastEnvCard = GetLastEnvCard(cardControl.EnvIndex);
			if (lastEnvCard == cardControl)
			{
				shouldShow = true;
			}
		}
		else
		{
			shouldShow = true;
		}

		if (shouldShow)
		{
			cardControl.ShowCardHoverEffect();
		}
	}

	private void OnBlockFatalPointerEnter(GameObject go, UnityEngine.EventSystems.PointerEventData eventData)
	{
		if (m_BlockDamagePhaseEnd > 0 && PhaseCounter <= m_BlockDamagePhaseEnd)
		{
			int remainingTurns = m_BlockDamagePhaseEnd - PhaseCounter + 1;
			m_BlockFatalDescExtControl = Asset.OpenUI<UIDescExtControl>(Asset.UIRoot);
			m_BlockFatalDescExtControl.SetData("无敌剩余回合数: " + remainingTurns);
			RectTransform blockFatalRect = m_View.BlockFatal.transform as RectTransform;
			m_BlockFatalDescExtControl.SetPositionRelativeTo(blockFatalRect);
		}
	}

	private void OnBlockFatalPointerExit(GameObject go, UnityEngine.EventSystems.PointerEventData eventData)
	{
		if (m_BlockFatalDescExtControl != null)
		{
			m_BlockFatalDescExtControl.Close();
			m_BlockFatalDescExtControl = null;
		}
	}

	private void UpdateBlockFatalDisplay()
	{
		bool shouldShowBlockFatal = m_BlockDamagePhaseEnd > 0 && PhaseCounter <= m_BlockDamagePhaseEnd;

		if (m_IsBlockFatalActive != shouldShowBlockFatal)
		{
			m_View.BlockFatal.SetActive(shouldShowBlockFatal);
			m_IsBlockFatalActive = shouldShowBlockFatal;
		}

		if (shouldShowBlockFatal)
		{
			int remainingTurns = m_BlockDamagePhaseEnd - PhaseCounter;
			m_View.TxtPhaseBlock.text = remainingTurns.ToString();
		}
	}

	void PermanentBoostAttack(object[] paraArray)
	{
		UICardSimpleControl cardControl = GetLastBagCard(ECardType.attack);
		if (cardControl != null && cardControl.CardData != null)
		{
			Card cardData = cardControl.CardData;
			cardData.currentAttack += 1;
			cardControl.RefreshCard();
		}
	}

	void PermanentBoostDefence(object[] paraArray)
	{
		UICardSimpleControl cardControl = GetLastBagCard(ECardType.defence);
		if (cardControl != null && cardControl.CardData != null)
		{
			Card cardData = cardControl.CardData;
			cardData.currentDefence += 1;
			cardControl.RefreshCard();
		}
	}

	private void RefreshRelicDisplay()
	{
		int needCount = 0;
		if (m_DataJoeyPlayer != null && m_DataJoeyPlayer.RelicList != null)
		{
			needCount = m_DataJoeyPlayer.RelicList.Count;
		}

		while (m_RelicList.Count < needCount)
		{
			UIRelicControl relicControl = Asset.OpenUI<UIRelicControl>(m_View.RelicContent);
			relicControl.CacheTrans.localScale = Vector3.one;
			relicControl.CacheTrans.localPosition = Vector3.zero;
			relicControl.CacheTrans.localEulerAngles = Vector3.zero;
			m_RelicList.Add(relicControl);
		}

		for (int i = 0; i < m_RelicList.Count; i++)
		{
			if (i < needCount)
			{
				int relicId = m_DataJoeyPlayer.RelicList[i];
				RelicInfo relicInfo = GData.Instance.GetRelicInfo((ERelicType)relicId);
				if (relicInfo != null)
				{
					m_RelicList[i].gameObject.SetActive(true);
					m_RelicList[i].SetGameData(relicInfo);
					m_RelicList[i].ImgRelicTransform.localScale = Vector3.one * 2f;

					// Initialize counter display for CounterInsight relic
					if (relicId == (int)ERelicType.CounterInsight)
					{
						UpdateCounterInsightDisplay();
					}
				}
				else
				{
					m_RelicList[i].gameObject.SetActive(false);
				}
			}
			else
			{
				m_RelicList[i].gameObject.SetActive(false);
			}
		}
	}

	void OnRefreshCardLimitDebuff(object[] paraArray)
	{
		RefreshCardLimitDebuff();
	}

	/// <summary>
	/// Check and display card limit debuff in Env mode
	/// </summary>
	private void RefreshCardLimitDebuff()
	{
		// Only apply in Env mode
		if (JoeyGameControl.Instance == null || JoeyGameControl.Instance.GameMode != EGameMode.Env)
		{
			if (m_CardLimitDebuffControl != null)
			{
				m_CardLimitDebuffControl.gameObject.SetActive(false);
			}
			return;
		}

		// Get card limit from character config
		RoguelikeCharacter characterData = GData.Instance.GetRoguelikeCharacter();
		int cardLimit = characterData != null ? characterData.envCardLimit : 0;

		// If no limit set, hide debuff
		if (cardLimit <= 0)
		{
			if (m_CardLimitDebuffControl != null)
			{
				m_CardLimitDebuffControl.gameObject.SetActive(false);
			}
			return;
		}

		// Check if player's card pool exceeds the limit
		int currentCardCount = m_DataJoeyPlayer != null ? m_DataJoeyPlayer.EnvCardPool.Count : 0;
		bool isOverLimit = currentCardCount > cardLimit;

		if (isOverLimit)
		{
			// Create debuff control if not exists
			if (m_CardLimitDebuffControl == null)
			{
				m_CardLimitDebuffControl = Asset.OpenUI<UIRelicControl>(m_View.RelicContent);
				m_CardLimitDebuffControl.CacheTrans.localScale = Vector3.one;
				m_CardLimitDebuffControl.CacheTrans.localPosition = Vector3.zero;
				m_CardLimitDebuffControl.CacheTrans.localEulerAngles = Vector3.zero;
			}

			// Get base debuff info from config and parse template placeholders
			RelicInfo baseInfo = GData.Instance.GetRelicInfo(ERelicType.CardLimitDebuff);
			if (baseInfo != null)
			{
				// Parse template placeholders: {cardLimit}, {currentCount}
				string dynamicDescription = baseInfo.description
					.Replace("{cardLimit}", cardLimit.ToString())
					.Replace("{currentCount}", currentCardCount.ToString());

				// Create a new RelicInfo with parsed description
				RelicInfo dynamicDebuffInfo = new RelicInfo(
					id: baseInfo.id,
					cardImage: baseInfo.cardImage,
					iconImage: baseInfo.iconImage,
					name: baseInfo.name,
					description: dynamicDescription,
					stars: baseInfo.stars
				);

				m_CardLimitDebuffControl.gameObject.SetActive(true);
				m_CardLimitDebuffControl.SetGameData(dynamicDebuffInfo);
				m_CardLimitDebuffControl.ImgRelicTransform.localScale = Vector3.one * 2f;
			}
		}
		else
		{
			// Hide debuff when under limit
			if (m_CardLimitDebuffControl != null)
			{
				m_CardLimitDebuffControl.gameObject.SetActive(false);
			}
		}
	}

	protected override void OnClose()
	{
		for (int i = 0; i < m_RelicList.Count; i++)
		{
			if (m_RelicList[i] != null)
			{
				m_RelicList[i].Close();
			}
		}
		if (m_CardLimitDebuffControl != null)
		{
			m_CardLimitDebuffControl.Close();
		}

		ClearAllUniTasks();
		CurrentEffectCard = null;
		m_CardActionQueue.Clear();

		foreach (var kvp in m_BagCardDict)
		{
			List<UICardSimpleControl> cardList = kvp.Value;
			if (cardList != null)
			{
				for (int i = 0; i < cardList.Count; i++)
				{
					UICardSimpleControl cardControl = cardList[i];
					if (cardControl != null && cardControl != m_FistCardCache)
					{
						cardControl.Close();
					}
				}
			}
		}

		foreach (var kvp in m_EnvCardDict)
		{
			List<UICardSimpleControl> cardList = kvp.Value;
			if (cardList != null)
			{
				for (int i = 0; i < cardList.Count; i++)
				{
					UICardSimpleControl cardControl = cardList[i];
					if (cardControl != null)
					{
						cardControl.Close();
					}
				}
			}
		}

		for (int i = 0; i < m_YGrimReaperList.Count; i++)
		{
			UICardSimpleControl cardControl = m_YGrimReaperList[i];
			if (cardControl != null)
			{
				cardControl.Close();
			}
		}

		if (m_FistCardCache != null)
		{
			m_FistCardCache.Close();
		}
		if (m_KeyPathCardCache != null)
		{
			m_KeyPathCardCache.Close();
		}

		if (m_CardSimplePool != null)
		{
			m_CardSimplePool.DestroyAll();
			m_CardSimplePool = null;
		}

		if (m_DamageTextPool != null)
		{
			m_DamageTextPool.DestroyAll();
			m_DamageTextPool = null;
		}

		m_EnvPanels.Clear();
		m_CardDict.Clear();
		m_RelicList.Clear();
		m_EnvCardDict.Clear();
		m_BagCardDict.Clear();
		UsedCardList.Clear();
		m_YGrimReaperList.Clear();
		m_CardCtsDict.Clear();

		m_View = null;
		m_DataJoeyPlayer = null;
		m_EffectRoots = null;
		m_FistCardCache = null;
		m_KeyPathCardCache = null;

		base.OnClose();
	}

	private void TryRegenerationHeal()
	{
		if (DataSystem.Instance.HasRelic(ERelicType.RegenerationAmulet))
		{
			if (PhaseCounter > 0 && PhaseCounter % 3 == 0)
			{
				ApplyPlayerHealthChange(1, true);
			}
		}
	}

	private void TryHalfHealthAmulet()
	{
		if (DataSystem.Instance.HasRelic(ERelicType.HalfHealthAmulet))
		{
			if (PhaseCounter > 0 && PhaseCounter % 2 == 0)
			{
				bool isHalfHealthOrBelow = JoeyGameControl.Instance.IsPlayerHalfHealth();
				if (isHalfHealthOrBelow)
				{
					// 血量小于等于50%，回复1HP
					ApplyPlayerHealthChange(1, true);
				}
				else
				{
					// 血量大于50%，扣除1HP
					ApplyPlayerHealthChange(-1, false);
				}
			}
		}
	}

	/// <summary>
	/// 处理技能施放事件（用于魔法杖等视作施放技能的效果）
	/// </summary>
	void OnSkillCast(object[] paraArray)
	{
		TryArcaneOrbTrigger();
	}

	/// <summary>
	/// 奥术宝珠效果：每施放三次技能获得一张技能牌4013
	/// </summary>
	private void TryArcaneOrbTrigger()
	{
		if (DataSystem.Instance.HasRelic(ERelicType.ArcaneOrb))
		{
			m_ArcaneOrbSkillCounter++;
			if (m_ArcaneOrbSkillCounter >= 5)
			{
				m_ArcaneOrbSkillCounter = 0;
				AddCardToBag("4013");
				Debug.Log("ArcaneOrb triggered: Added card 4013 to bag");
			}
		}
	}

	/// <summary>
	/// 魔剑士指环效果：加入手牌的武器牌变成魔力剑(1021)，防御牌变成魔力盾(2014)
	/// </summary>
	/// <param name="cardControl">要转换的卡牌控制器</param>
	/// <returns>转换后的卡牌类型</returns>
	private ECardType TryApplyMagicSwordsmanRing(UICardSimpleControl cardControl)
	{
		if (!DataSystem.Instance.HasRelic(ERelicType.MagicSwordsmanRing))
		{
			return cardControl.CardType;
		}

		Card card = cardControl.CardData;
		ECardType cardType = cardControl.CardType;

		// 武器牌变成魔力剑(1021)
		if (cardType == ECardType.attack && card.id != "1021" && card.id != "1011" && card.id != "1019")
		{
			Card magicSwordTemplate = GData.Instance.GetCardConfigById("1021");
			if (magicSwordTemplate != null)
			{
				card.cardImage = magicSwordTemplate.cardImage;
				card.cardBackground = magicSwordTemplate.cardBackground;
				card.cardName = magicSwordTemplate.cardName;
				card.description = magicSwordTemplate.description;
				card.id = magicSwordTemplate.id;
				card.SetAttack(magicSwordTemplate.currentAttack);
				card.effectId = magicSwordTemplate.effectId;
				cardControl.SetData(card);
				Debug.Log($"MagicSwordsmanRing: Converted attack card to Magic Sword (1021)");
			}
		}
		// 防御牌变成魔力盾(2014)
		else if (cardType == ECardType.defence && card.id != "2014")
		{
			Card magicShieldTemplate = GData.Instance.GetCardConfigById("2014");
			if (magicShieldTemplate != null)
			{
				card.cardImage = magicShieldTemplate.cardImage;
				card.cardBackground = magicShieldTemplate.cardBackground;
				card.cardName = magicShieldTemplate.cardName;
				card.description = magicShieldTemplate.description;
				card.id = magicShieldTemplate.id;
				card.currentDefence = magicShieldTemplate.currentDefence;
				card.effectId = magicShieldTemplate.effectId;
				cardControl.SetData(card);
				Debug.Log($"MagicSwordsmanRing: Converted defence card to Magic Shield (2014)");
			}
		}

		return cardType;
	}

}