//This File Is Auto Generated By Process Control
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using UnityEngine;
using UnityEngine.UI;
using DG.Tweening;
using Cysharp.Threading.Tasks;
using Random = UnityEngine.Random;

public partial class UIGamePhaseControl : YViewControl
{
	private UIGamePhaseView m_View;
	private SingleDelayAction m_MoveCardDelayAction = new SingleDelayAction();

	private Sprite sadSprite;
	private Sprite sleepSprite;
	private Sprite happySprite;
	private Sprite deathSprite;
	private List<VerticalLayoutGroup> m_EnvPanels = new List<VerticalLayoutGroup>();
	private MonoBehaviourPool<UICardSimpleControl> m_CardSimplePool;
	private MonoBehaviourPool<UIDamageTextControl> m_DamageTextPool;
	private Dictionary<int, Card> m_CardDict = new Dictionary<int, Card>();
	private Dictionary<int, List<UICardSimpleControl>> m_EnvCardDict = new Dictionary<int, List<UICardSimpleControl>>();
	private Dictionary<int, List<UICardSimpleControl>> m_BagCardDict = new Dictionary<int, List<UICardSimpleControl>>();
	private static int UniqueIdGen = 0;
	private DataJoeyPlayer m_DataJoeyPlayer;
	private List<Card> UsedCardList = new List<Card>();
	private UIGameOverControl m_GameOverControl;
	private Transform[] m_EffectRoots;
	private Queue<UICardSimpleControl> m_CardActionQueue = new Queue<UICardSimpleControl>();
	public UICardSimpleControl CurrentEffectCard;

	public static EResType GetResType()
	{
		return EResType.UIGamePhase;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIGamePhaseView>();
		m_DataJoeyPlayer = DataSystem.Instance.GetDataJoeyPlayer();
		RegistAction(EActionId.AppHp, AppHp);
		RegistAction(EActionId.AppAttack, AppAttack);
		RegistAction(EActionId.AppDefence, AppDefence);
		RegistAction(EActionId.MoveCard, MoveCard);
		RegistAction(EActionId.TakeEnemyDamage, TakeEnemyDamage);
		RegistAction(EActionId.TakePlayerDamage, TakePlayerDamage);
		RegistAction(EActionId.BoomEnvCard, BoomEnvCard);
		RegistAction(EActionId.UseBagCard, UseBagCard);
		RegistAction(EActionId.AddCardFromDiscard, AddCardFromDiscard);
		RegistAction(EActionId.AttackRandomEnemy, AttackRandomEnemy);
		RegistAction(EActionId.TakeAllEnemyDamage, TakeAllEnemyDamage);
		RegistAction(EActionId.AddCardToQueue, AddCardToQueue);
		RegistAction(EActionId.AddEffectValueToBagCard, AddEffectValueToBagCard);

		sadSprite = Resources.Load<Sprite>("Art/Img/joey/joey_sad");
		sleepSprite = Resources.Load<Sprite>("Art/Img/joey/img_sleep");
		happySprite = Resources.Load<Sprite>("Art/Img/joey/joey_happy");
		deathSprite = Resources.Load<Sprite>("Art/Img/joey/joey_weekup");

		for (int i = 0; i < m_View.EnvPanels.childCount; i++)
		{
			Transform child = m_View.EnvPanels.GetChild(i);
			VerticalLayoutGroup vlg = child.GetComponent<VerticalLayoutGroup>();
			m_EnvPanels.Add(vlg);
		}

		m_EffectRoots = new Transform[] { m_View.EffectRoot0, m_View.EffectRoot1, m_View.EffectRoot2, m_View.EffectRoot3, m_View.EffectRoot4 };

		m_CardSimplePool = new MonoBehaviourPool<UICardSimpleControl>(() =>
		{
			return this.Asset.OpenUI<UICardSimpleControl>(null);
		});

		m_DamageTextPool = new MonoBehaviourPool<UIDamageTextControl>(() =>
		{
			return this.Asset.OpenUI<UIDamageTextControl>(null);
		});
	}

	public Transform GetEffectRoot(int envIndex)
	{
		if (envIndex >= 0 && envIndex < m_EffectRoots.Length)
		{
			return m_EffectRoots[envIndex];
		}
		return null;
	}

	void OnHPChanged(int hp)
	{
		m_View.TextHeart.text = hp.ToString();
		ChangeJoeyImage();
	}

	void OnAttackChanged(int attack)
	{
		m_View.AttackNum.text = attack.ToString();
	}

	void OnDefenceChanged(int defence)
	{
		m_View.DefenceNum.text = defence.ToString();
	}

	void AppHp(object[] paraArray)
	{
		int delta = (int)paraArray[0];
		m_DataJoeyPlayer.lastPlayerHealth = m_DataJoeyPlayer.playerHealth;
		m_DataJoeyPlayer.playerHealth += delta;
		OnHPChanged(m_DataJoeyPlayer.playerHealth);
	}

	void AppAttack(object[] paraArray)
	{
		int delta = (int)paraArray[0];
		m_DataJoeyPlayer.playerAttack += delta;
		OnAttackChanged(m_DataJoeyPlayer.playerAttack);
	}

	void AppDefence(object[] paraArray)
	{
		int delta = (int)paraArray[0];
		m_DataJoeyPlayer.playerDefence += delta;
		OnDefenceChanged(m_DataJoeyPlayer.playerDefence);
	}

	public void SetData()
	{
		RefreshView();
		ClearAllCard();
	}

	private void RefreshView()
	{
		m_View.TextHeart.text = m_DataJoeyPlayer.playerHealth.ToString();
		m_View.AttackNum.text = m_DataJoeyPlayer.playerAttack.ToString();
		m_View.DefenceNum.text = m_DataJoeyPlayer.playerDefence.ToString();
		m_View.TxtCoin.text = "0";
	}

	public void ChangeJoeyImage()
	{
		StartCoroutine(ChangeJoeyImageCoroutine());
	}

	IEnumerator ChangeJoeyImageCoroutine()
	{
		if (m_DataJoeyPlayer.playerHealth < m_DataJoeyPlayer.lastPlayerHealth)
		{
			m_View.JoeyImage.sprite = sadSprite;
		}
		else if (m_DataJoeyPlayer.playerHealth > m_DataJoeyPlayer.lastPlayerHealth)
		{
			m_View.JoeyImage.sprite = happySprite;
		}
		else if (m_DataJoeyPlayer.playerHealth <= 0)
		{
			m_View.JoeyImage.sprite = deathSprite;
		}
		yield return new WaitForSeconds(0.5f);
		m_View.JoeyImage.sprite = sleepSprite;
	}

	private UICardSimpleControl GetCardSimple(Transform parent)
	{
		UICardSimpleControl cardControl = m_CardSimplePool.Get();
		cardControl.CacheTrans.SetParent(parent);
		cardControl.CacheTrans.localScale = Vector3.one;
		cardControl.CacheTrans.localPosition = Vector3.zero;
		cardControl.CacheTrans.localEulerAngles = Vector3.zero;
		return cardControl;
	}

	private void ShowDamageText(int damage, Transform parent, Vector3 localPositionShift)
	{
		UIDamageTextControl damageTextControl = m_DamageTextPool.Get();
		damageTextControl.SetData(damage, parent, localPositionShift);
	}

	private Card CreateCard(string cardId)
	{
		Card card = GData.Instance.GetCardConfigById(cardId).Clone();
		UniqueIdGen++;
		card.UniqueId = UniqueIdGen;
		m_CardDict[UniqueIdGen] = card;
		return card;
	}

	public void AddCardList(ECardType cardType, List<string> cardIds)
	{
		Debug.Log("AddCardList: " + cardType + " " + cardIds.Count);

		Transform parent = null;
		switch (cardType)
		{
			case ECardType.attack:
				parent = m_View.AttackPanel.transform;
				break;
			case ECardType.defence:
				parent = m_View.DefencePanel.transform;
				break;
			case ECardType.skill:
				parent = m_View.SkillPanel.transform;
				break;
			case ECardType.item:
				parent = m_View.ItemPanel.transform;
				break;
			case ECardType.monster:
			case ECardType.other:
				parent = m_View.EnvPanels.transform;
				break;
			default:
				return;
		}

		for (int i = cardIds.Count - 1; i >= 0; i--)
		{
			string cardId = cardIds[i];
			Card card = CreateCard(cardId);
			UICardSimpleControl cardControl = GetCardSimple(parent);
			cardControl.SetData(card);
			AddBagCard(cardType, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
		}
	}

	public void AddEnvCardList(List<string> cardIds, int index)
	{
		VerticalLayoutGroup parent = m_EnvPanels[index];

		for (int i = cardIds.Count - 1; i >= 0; i--)
		{
			string cardId = cardIds[i];
			Card card = CreateCard(cardId);
			UICardSimpleControl cardControl = GetCardSimple(parent.transform);
			cardControl.SetData(card, isEnv: true, envIndex: index);
			AddEnvCard(index, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
		}
	}

	public Card GetCardDataById(int uniqueId)
	{
		return m_CardDict[uniqueId];
	}

	private void AddBagCard(ECardType cardType, UICardSimpleControl cardControl, bool isMoveCard = false)
	{
		int cardTypeInt = (int)cardType;
		if (!m_BagCardDict.TryGetValue(cardTypeInt, out List<UICardSimpleControl> cardList))
		{
			m_BagCardDict[cardTypeInt] = new List<UICardSimpleControl>();
		}
		m_BagCardDict[cardTypeInt].Add(cardControl);
		cardControl.IsEnv = false;
		cardControl.EnvIndex = -1;
		if (!isMoveCard)
		{
			cardControl.CacheTrans.localScale = new Vector3(0.8f, 0.8f, 0.8f);
		}
	}

	private async UniTask RemoveBagCard(ECardType cardType, UICardSimpleControl cardControl)
	{
		int cardTypeInt = (int)cardType;
		if (m_BagCardDict.TryGetValue(cardTypeInt, out List<UICardSimpleControl> cardList))
		{
			cardList.Remove(cardControl);
			RemoveCardData(cardControl.CardData.UniqueId);
			cardControl.Return();

			UICardSimpleControl newLastBagCard = GetLastBagCard(cardType);
			if (newLastBagCard != null)
			{
				float delayTime = newLastBagCard.CardEffect?.OnBecomeTopOfPile() ?? 0.5f;
				await UniTask.WaitForSeconds(delayTime);
			}
		}
	}

	private List<UICardSimpleControl> GetBagCardList(ECardType cardType)
	{
		int cardTypeInt = (int)cardType;
		if (m_BagCardDict.TryGetValue(cardTypeInt, out List<UICardSimpleControl> cardList))
		{
			return cardList;
		}
		return null;
	}

	private UICardSimpleControl GetLastBagCard(ECardType cardType)
	{
		List<UICardSimpleControl> cardList = GetBagCardList(cardType);
		if (cardList != null && cardList.Count > 0)
		{
			return cardList[cardList.Count - 1];
		}
		return null;
	}

	private UICardSimpleControl GetLastEnvCard(int envIndex)
	{
		if (m_EnvCardDict.TryGetValue(envIndex, out List<UICardSimpleControl> cardList))
		{
			if (cardList != null && cardList.Count > 0)
			{
				return cardList[cardList.Count - 1];
			}
		}
		return null;
	}

	public bool HasBagCard(ECardType cardType)
	{
		List<UICardSimpleControl> cardList = GetBagCardList(cardType);
		return cardList != null && cardList.Count > 0;
	}

	private UICardSimpleControl GetFistCard()
	{
		Card card = GData.Instance.GetCardConfigById("1003").Clone();
		UniqueIdGen++;
		card.UniqueId = UniqueIdGen;
		m_CardDict[UniqueIdGen] = card;

		Transform parent = m_View.AttackPanel.transform;
		m_View.AttackPanel.enabled = false;
		UICardSimpleControl cardControl = GetCardSimple(parent);
		cardControl.SetData(card);
		AddBagCard(ECardType.attack, cardControl);
		//m_View.AttackPanel.enabled = true;
		return cardControl;
	}

	private void AddEnvCard(int index, UICardSimpleControl cardControl)
	{
		if (!m_EnvCardDict.TryGetValue(index, out List<UICardSimpleControl> cardList))
		{
			m_EnvCardDict[index] = new List<UICardSimpleControl>();
		}
		m_EnvCardDict[index].Add(cardControl);
	}

	private void RemoveEnvCard(int index, UICardSimpleControl cardControl)
	{
		if (m_EnvCardDict.TryGetValue(index, out List<UICardSimpleControl> cardList))
		{
			cardList.Remove(cardControl);
			RemoveCardData(cardControl.CardData.UniqueId);
			cardControl.Return();
		}
	}

	private void RemoveEnvCardFromDict(int index, UICardSimpleControl cardControl)
	{
		if (m_EnvCardDict.TryGetValue(index, out List<UICardSimpleControl> cardList))
		{
			cardList.Remove(cardControl);
		}
	}

	private async UniTask<bool> DealDamageToEnvCard(UICardSimpleControl cardControl, int damage, int envIndex, EEffectType effectType = EEffectType.Damage)
	{
		if (cardControl.CardType == ECardType.monster)
		{
			float delayTime = cardControl.CallCardTakeDamage(damage, effectType);
			ShowDamageText(damage, cardControl.CacheTrans, new Vector3(0f, 180f, 0));
			if (delayTime > 0f)
			{
				await UniTask.WaitForSeconds(delayTime);
			}
		}



		if (cardControl.CardData.currentHealth <= 0 && cardControl.CardType == ECardType.monster)
		{
			string monsterId = cardControl.CardData.id;
			List<Card> dropCards = GetMonsterDropCard(monsterId);

			float delayTime = cardControl.CardEffect?.OnBeDying() ?? 0.5f;
			await UniTask.WaitForSeconds(delayTime);

			RemoveEnvCard(envIndex, cardControl);
			delayTime = cardControl.CardEffect?.OnDead() ?? 0.5f;
			await UniTask.WaitForSeconds(delayTime);

			if (dropCards != null && dropCards.Count > 0)
			{
				AddEnvDropCard(dropCards, envIndex);
			}

			return true;
		}

		return false;
	}

	private List<Card> GetMonsterDropCard(string monsterId)
	{
		if (string.IsNullOrEmpty(monsterId))
		{
			return null;
		}

		if (!LootDropManager.Instance.TryGetDropCards(monsterId, out List<string> cardIds) || cardIds == null || cardIds.Count == 0)
		{
			return null;
		}

		List<Card> dropCards = new List<Card>();
		for (int i = 0; i < cardIds.Count; i++)
		{
			Card card = CreateCard(cardIds[i]);
			dropCards.Add(card);
		}

		return dropCards;
	}

	private void AddEnvDropCard(List<Card> dropCards, int centerIndex)
	{
		if (dropCards == null || dropCards.Count == 0)
		{
			return;
		}

		if (m_EnvPanels == null || m_EnvPanels.Count == 0)
		{
			return;
		}

		centerIndex = Mathf.Clamp(centerIndex, 0, m_EnvPanels.Count - 1);

		var usedIndices = new HashSet<int>();
		var offsetPattern = BuildOffsetPattern(m_EnvPanels.Count);

		for (int i = 0; i < dropCards.Count; i++)
		{
			int panelIndex = FindPanelIndex(centerIndex, usedIndices, offsetPattern, m_EnvPanels.Count);
			if (panelIndex < 0)
			{
				panelIndex = centerIndex;
			}

			panelIndex = Mathf.Clamp(panelIndex, 0, m_EnvPanels.Count - 1);
			VerticalLayoutGroup parent = m_EnvPanels[panelIndex];
			UICardSimpleControl cardControl = GetCardSimple(parent.transform);
			cardControl.SetData(dropCards[i], isEnv: true, envIndex: panelIndex);
			AddEnvCard(panelIndex, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);

			usedIndices.Add(panelIndex);
		}
	}

	private List<int> BuildOffsetPattern(int panelCount)
	{
		var offsets = new List<int>();
		offsets.Add(0);
		int step = 1;
		while (offsets.Count < panelCount * 2)
		{
			offsets.Add(-step);
			offsets.Add(step);
			step++;
		}
		return offsets;
	}

	private int FindPanelIndex(int centerIndex, HashSet<int> usedIndices, List<int> offsetPattern, int panelCount)
	{
		for (int i = 0; i < offsetPattern.Count; i++)
		{
			int candidate = centerIndex + offsetPattern[i];
			if (candidate < 0 || candidate >= panelCount) continue;
			if (usedIndices.Contains(candidate)) continue;
			return candidate;
		}

		return Mathf.Clamp(centerIndex, 0, panelCount - 1);
	}

	async void BoomEnvCard(object[] paraArray)
	{
		int envIndex = (int)paraArray[0];
		int damage = (int)paraArray[1];
		bool excludeSelf = paraArray.Length > 2 && paraArray[2] is bool && (bool)paraArray[2];

		if (envIndex == -1)
		{
			envIndex = FindRandomEnemy();
			if (envIndex == -1)
			{
				return;
			}
		}
		Debug.Log("BoomEnvCard: envIndex = " + envIndex);
		foreach (var kvp in m_EnvCardDict)
		{
			Debug.Log("BoomEnvCard: envIndex = " + kvp.Key + " " + kvp.Value.Count);
		}

		int[] indices;
		if (excludeSelf)
		{
			indices = new int[] { envIndex - 1, envIndex + 1 };
		}
		else
		{
			indices = new int[] { envIndex - 1, envIndex, envIndex + 1 };
		}

		for (int i = 0; i < indices.Length; i++)
		{
			int index = indices[i];
			if (m_EnvCardDict.TryGetValue(index, out List<UICardSimpleControl> cardList))
			{
				if (cardList != null && cardList.Count > 0)
				{
					UICardSimpleControl lastCard = cardList[cardList.Count - 1];
					await DealDamageToEnvCard(lastCard, damage, index, EEffectType.Boom);
				}
			}
		}
	}

	private int FindRandomEnemy()
	{
		List<int> enemyIndices = new List<int>();
		foreach (var kvp in m_EnvCardDict)
		{
			if (kvp.Value != null && kvp.Value.Count > 0)
			{
				UICardSimpleControl lastCard = kvp.Value[kvp.Value.Count - 1];
				if (lastCard != null && lastCard.gameObject.activeSelf && lastCard.CardType == ECardType.monster)
				{
					enemyIndices.Add(kvp.Key);
				}
			}
		}
		if (enemyIndices.Count == 0)
		{
			return -1;
		}
		return enemyIndices[Random.Range(0, enemyIndices.Count)];
	}

	void RemoveCardData(int uniqueId)
	{
		if (m_CardDict.TryGetValue(uniqueId, out Card card))
		{
			UsedCardList.Add(card);
			m_CardDict.Remove(uniqueId);
		}
	}

	public void ClearAllCard()
	{
		m_CardSimplePool.ForEach(cardControl =>
		{
			if (cardControl != null && cardControl.gameObject.activeSelf)
			{
				cardControl.Return();
			}
		});

		m_CardDict.Clear();
		m_EnvCardDict.Clear();
		m_BagCardDict.Clear();
		UsedCardList.Clear();
		UniqueIdGen = 0;
	}

	async void MoveCard(object[] paraArray)
	{
		bool isEnv = (bool)paraArray[0];
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[1];
		cardControl.SetMoving(true);
		if (isEnv)
		{
			ECardType cardType = cardControl.CardType;

			Vector3 startWorldPos = cardControl.CacheTrans.parent.position;
			Vector3 startScale = Vector3.one;

			RemoveEnvCardFromDict(cardControl.EnvIndex, cardControl);
			AddBagCard(cardType, cardControl, true);
			cardControl.CardEffect?.OnEnterBag();
			//await UniTask.WaitForSeconds(delayTime);

			VerticalLayoutGroup layout = null;
			switch (cardType)
			{
				case ECardType.attack:
					layout = m_View.AttackPanel;
					break;
				case ECardType.defence:
					layout = m_View.DefencePanel;
					break;
				case ECardType.skill:
					layout = m_View.SkillPanel;
					break;
				case ECardType.item:
					layout = m_View.ItemPanel;
					break;
				default:
					return;
			}

			Vector3 endScale = new Vector3(0.8f, 0.8f, 1.0f);
			float duration = .2f;
			Vector3 endPos = layout.transform.position;

			m_MoveCardDelayAction.AddAnimDelayAction(
				(cancellationToken) => MoveCardAnimation(cardControl, startWorldPos, endPos, startScale, endScale, duration, layout, cancellationToken),
				() =>
				{
					cardControl.CacheTrans.position = endPos;
					cardControl.CacheTrans.localScale = endScale;
					layout.enabled = true;
					cardControl.SetMoving(false);
					if (CurrentEffectCard != null)
					{
						CurrentEffectCard.IsEffecting = false;
					}
				}
			);
		}
	}

	private async UniTask MoveCardAnimation(UICardSimpleControl cardControl, Vector3 startPos, Vector3 endPos, Vector3 startScale, Vector3 endScale, float duration, VerticalLayoutGroup layout, CancellationToken cancellationToken)
	{
		layout.enabled = false;
		cardControl.CacheTrans.SetParent(layout.transform);

		//Debug.Log("MoveCardAnimation: startPos = " + startPos + ", endPos = " + endPos + ", startScale = " + startScale + ", endScale = " + endScale + ", duration = " + duration);
		float elapsed = 0f;
		while (elapsed < duration)
		{
			cancellationToken.ThrowIfCancellationRequested();
			elapsed += Time.deltaTime;
			float t = elapsed / duration;

			cardControl.CacheTrans.position = Vector3.Lerp(startPos, endPos, t);
			cardControl.CacheTrans.localScale = Vector3.Lerp(startScale, endScale, t);

			//Debug.Log($"MoveCard Animation - Position: {cardControl.CacheTrans.position}, Scale: {cardControl.CacheTrans.localScale}, t: {t}");

			await UniTask.Yield();
		}
	}

	async void TakeEnemyDamage(object[] paraArray)
	{
		UICardSimpleControl enemyCardControl = (UICardSimpleControl)paraArray[0];
		int attackCount = (int)paraArray[1];
		int envIndex = (int)paraArray[2];
		UICardSimpleControl attackCardControl = GetLastBagCard(ECardType.attack);
		bool useFistCard = false;
		if (attackCardControl == null)
		{
			attackCardControl = GetFistCard();
			useFistCard = true;
		}
		if (useFistCard)
		{
			await UniTask.WaitForSeconds(1f);
		}

		attackCount += attackCardControl.CardEffect?.GetEffectValue(EEffectType.ExtraAttackCnt) ?? 0;
		Card attackCard = attackCardControl.CardData;
		int damage = attackCard.currentAttack + attackCardControl.CardEffect?.GetEffectValue(EEffectType.Damage) ?? 0;

		float delayTime;
		delayTime = attackCardControl.CardEffect?.UseAttack() ?? 0.5f;
		await UniTask.WaitForSeconds(delayTime);

		for (int i = 0; i < attackCount; i++)
		{
			delayTime = attackCardControl.CardEffect?.OnDealDamage() ?? 0.5f;
			await UniTask.WaitForSeconds(delayTime);

			if (await DealDamageToEnvCard(enemyCardControl, damage, envIndex))
			{
				delayTime = attackCardControl.CardEffect?.OnKill() ?? 0.5f;
				await UniTask.WaitForSeconds(delayTime);
				break;
			}
			else
			{
				int enemyAttack = enemyCardControl.CardData.currentAttack;
				await TakePlayerDamageAsync(enemyAttack, enemyCardControl, envIndex);
			}
		}

		float finishDelayTime = attackCardControl.CardEffect?.OnUseFinished() ?? 0f;
		if (finishDelayTime > 0f)
		{
			await UniTask.WaitForSeconds(finishDelayTime);
		}
		await RemoveBagCard(ECardType.attack, attackCardControl);
		float removeDelayTime = attackCardControl.CardEffect?.OnRemoveCard() ?? 0f;
		if (removeDelayTime > 0f)
		{
			await UniTask.WaitForSeconds(removeDelayTime);
		}
		enemyCardControl.IsEffecting = false;
	}

	async void TakePlayerDamage(object[] paraArray)
	{
		int enemyAttack = (int)paraArray[0];
		UICardSimpleControl enemyCardControl = (UICardSimpleControl)paraArray[1];
		int envIndex = (int)paraArray[2];
		await TakePlayerDamageAsync(enemyAttack, enemyCardControl, envIndex);
	}

	async UniTask TakePlayerDamageAsync(int enemyAttack, UICardSimpleControl enemyCardControl, int envIndex)
	{
		float delayTime = enemyCardControl.CardEffect?.OnDealDamage() ?? 0.5f;
		await UniTask.WaitForSeconds(delayTime);

		int defenceValue = 0;
		UICardSimpleControl defenceCardControl = GetLastBagCard(ECardType.defence);
		if (defenceCardControl != null)
		{
			defenceValue = defenceCardControl.CardData.currentDefence;
			bool isOverflow = defenceValue < enemyAttack;
			delayTime = defenceCardControl.CardEffect?.UseDefence(isOverflow) ?? 0.5f;
			await UniTask.WaitForSeconds(delayTime);
		}
		int damage = 0;
		if (defenceValue < enemyAttack)
		{
			damage = enemyAttack - defenceValue;
		}
		m_DataJoeyPlayer.lastPlayerHealth = m_DataJoeyPlayer.playerHealth;
		m_DataJoeyPlayer.playerHealth -= damage;
		if (m_DataJoeyPlayer.playerHealth < 0)
		{
			m_DataJoeyPlayer.playerHealth = 0;
		}
		if (damage > 0)
		{
			ShowDamageText(damage, m_View.JoeyImage.transform, new Vector3(100f, 190f, 0));
		}
		OnHPChanged(m_DataJoeyPlayer.playerHealth);
		OnAttackChanged(m_DataJoeyPlayer.playerAttack);
		OnDefenceChanged(m_DataJoeyPlayer.playerDefence);

		if (defenceCardControl != null)
		{
			int reflectDamage = defenceCardControl.CardEffect?.GetEffectValue(EEffectType.ReflectDamage) ?? 0;
			if (reflectDamage > 0)
			{
				await AttackSpecialEnemy(enemyCardControl, reflectDamage, envIndex);
			}
			float finishDelayTime = defenceCardControl.CardEffect?.OnUseFinished() ?? 0f;
			if (finishDelayTime > 0f)
			{
				await UniTask.WaitForSeconds(finishDelayTime);
			}
			await RemoveBagCard(ECardType.defence, defenceCardControl);
			float removeDelayTime = defenceCardControl.CardEffect?.OnRemoveCard() ?? 0f;
			if (removeDelayTime > 0f)
			{
				await UniTask.WaitForSeconds(removeDelayTime);
			}
		}

		if (m_DataJoeyPlayer.playerHealth <= 0)
		{
			if (m_GameOverControl == null)
			{
				m_GameOverControl = this.Asset.OpenUI<UIGameOverControl>();
			}
			else
			{
				m_GameOverControl.gameObject.SetActive(true);
			}
		}
	}

	async void UseBagCard(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		ECardType cardType = cardControl.CardType;
		float delayTime = 0f;

		if (cardType == ECardType.skill)
		{
			delayTime = cardControl.CardEffect?.UseSkill() ?? 0.5f;
		}
		else if (cardType == ECardType.item)
		{
			delayTime = cardControl.CardEffect?.UseItem() ?? 0.5f;
		}

		await UniTask.WaitForSeconds(delayTime);
		float finishDelayTime = cardControl.CardEffect?.OnUseFinished() ?? 0f;
		if (finishDelayTime > 0f)
		{
			await UniTask.WaitForSeconds(finishDelayTime);
		}
		await RemoveBagCard(cardType, cardControl);
		float removeDelayTime = cardControl.CardEffect?.OnRemoveCard() ?? 0f;
		if (removeDelayTime > 0f)
		{
			await UniTask.WaitForSeconds(removeDelayTime);
		}
		if (CurrentEffectCard != null)
		{
			CurrentEffectCard.IsEffecting = false;
		}
	}

	void AddCardFromDiscard(object[] paraArray)
	{
		ECardType specialCardType = paraArray.Length > 0 && paraArray[0] is ECardType ? (ECardType)paraArray[0] : ECardType.other;

		List<Card> availableCards = new List<Card>();
		for (int i = UsedCardList.Count - 1; i >= 0; i--)
		{
			Card card = UsedCardList[i];
			ECardType cardType = (ECardType)System.Enum.Parse(typeof(ECardType), card.type);
			if (specialCardType != ECardType.other)
			{
				if (cardType == specialCardType)
				{
					availableCards.Add(card);
				}
			}
			else
			{
				if (cardType != ECardType.monster)
				{
					availableCards.Add(card);
				}
			}
		}

		if (availableCards.Count == 0)
		{
			return;
		}

		Card selectedCard = availableCards[Random.Range(0, availableCards.Count)];
		UsedCardList.Remove(selectedCard);
		m_CardDict[selectedCard.UniqueId] = selectedCard;

		ECardType selectedCardType = (ECardType)System.Enum.Parse(typeof(ECardType), selectedCard.type);
		Transform parent = null;
		switch (selectedCardType)
		{
			case ECardType.attack:
				parent = m_View.AttackPanel.transform;
				break;
			case ECardType.defence:
				parent = m_View.DefencePanel.transform;
				break;
			case ECardType.skill:
				parent = m_View.SkillPanel.transform;
				break;
			case ECardType.item:
				parent = m_View.ItemPanel.transform;
				break;
			default:
				return;
		}

		UICardSimpleControl cardControl = GetCardSimple(parent);
		cardControl.SetData(selectedCard);
		AddBagCard(selectedCardType, cardControl);
		cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
	}

	async void AttackRandomEnemy(object[] paraArray)
	{
		int damage = paraArray[0] is int ? (int)paraArray[0] : 0;
		int attackTime = paraArray.Length > 1 && paraArray[1] is int ? (int)paraArray[1] : 1;
		if (damage <= 0)
		{
			return;
		}

		int envIndex = FindRandomEnemy();
		if (envIndex == -1)
		{
			return;
		}

		UICardSimpleControl enemyCardControl = GetLastEnvCard(envIndex);
		if (enemyCardControl == null)
		{
			return;
		}

		for (int i = 0; i < attackTime; i++)
		{
			if (await DealDamageToEnvCard(enemyCardControl, damage, envIndex))
			{
				break;
			}
			enemyCardControl = GetLastEnvCard(envIndex);
			if (enemyCardControl == null)
			{
				break;
			}
		}
	}

	async UniTask AttackSpecialEnemy(UICardSimpleControl enemyCardControl, int damage, int envIndex)
	{
		if (enemyCardControl == null)
		{
			return;
		}

		await DealDamageToEnvCard(enemyCardControl, damage, envIndex);
	}

	async void TakeAllEnemyDamage(object[] paraArray)
	{
		int damage = paraArray[0] is int ? (int)paraArray[0] : 0;
		if (damage <= 0)
		{
			return;
		}

		List<int> enemyIndices = new List<int>();
		foreach (var kvp in m_EnvCardDict)
		{
			if (kvp.Value != null && kvp.Value.Count > 0)
			{
				UICardSimpleControl lastCard = kvp.Value[kvp.Value.Count - 1];
				if (lastCard != null && lastCard.gameObject.activeSelf && lastCard.CardType == ECardType.monster)
				{
					enemyIndices.Add(kvp.Key);
				}
			}
		}

		foreach (int envIndex in enemyIndices)
		{
			UICardSimpleControl enemyCardControl = GetLastEnvCard(envIndex);
			if (enemyCardControl != null)
			{
				await DealDamageToEnvCard(enemyCardControl, damage, envIndex, EEffectType.Electric);
			}
		}
	}

	void AddCardToQueue(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		if (cardControl != null && !m_CardActionQueue.Contains(cardControl))
		{
			m_CardActionQueue.Enqueue(cardControl);
		}
	}

	void AddEffectValueToBagCard(object[] paraArray)
	{
		ECardType targetCardType = paraArray.Length > 0 && paraArray[0] is ECardType ? (ECardType)paraArray[0] : ECardType.attack;
		EEffectType effectType = paraArray.Length > 1 && paraArray[1] is EEffectType ? (EEffectType)paraArray[1] : EEffectType.Other;
		int value = paraArray.Length > 2 && paraArray[2] is int ? (int)paraArray[2] : 0;

		UICardSimpleControl lastBagCard = GetLastBagCard(targetCardType);
		if (lastBagCard != null && lastBagCard.CardEffect != null)
		{
			lastBagCard.CardEffect.AddEffectValue(effectType, value);
		}
	}

	void Update()
	{
		if (CurrentEffectCard == null && m_CardActionQueue.Count > 0)
		{
			CurrentEffectCard = m_CardActionQueue.Dequeue();
			if (CurrentEffectCard != null)
			{
				CurrentEffectCard.OnBtnRealClick();
			}
		}

		if (CurrentEffectCard != null && !CurrentEffectCard.IsEffecting)
		{
			CurrentEffectCard = null;
		}
	}

	public void ClearCardQueue()
	{
		while (m_CardActionQueue.Count > 0)
		{
			UICardSimpleControl cardControl = m_CardActionQueue.Dequeue();
			cardControl.IsEffecting = false;
			cardControl.Return();
		}

		if (CurrentEffectCard != null)
		{
			CurrentEffectCard.IsEffecting = false;
			CurrentEffectCard.Return();
			CurrentEffectCard = null;
		}
	}

	protected override void OnReturn()
	{
		m_MoveCardDelayAction.Cancel();
		m_CardActionQueue.Clear();
		CurrentEffectCard = null;
		base.OnReturn();
	}
}