//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIGamePhaseView : YBaseView
{
	public RectTransform EnvPanels;
	public Text TextHeart;
	public Text TxtCoin;
	public VerticalLayoutGroup SkillPanel;
	public VerticalLayoutGroup ItemPanel;
	public VerticalLayoutGroup DefencePanel;
	public VerticalLayoutGroup AttackPanel;
	public RectTransform EffectRoot0;
	public RectTransform EffectRoot1;
	public RectTransform EffectRoot2;
	public RectTransform EffectRoot3;
	public RectTransform EffectRoot4;
	public Text TxtStage;
	public RectTransform RelicContent;
	public RectTransform UsedRoot;
	public Text UsedCradsNumber;
	public RectTransform EmptyAttack;
	public RectTransform Joey;
	public Animator JoeyAnim;
	public GameObject MonkeyBg;
	public GameObject TurkeyBg;
	public Image Heart;
	public GameObject DonkeyBg;
	public GameObject DeadkeyBg;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		EnvPanels = viewItemList[0].Target.GetComponent<RectTransform>();
		TextHeart = viewItemList[1].Target.GetComponent<Text>();
		TxtCoin = viewItemList[2].Target.GetComponent<Text>();
		SkillPanel = viewItemList[3].Target.GetComponent<VerticalLayoutGroup>();
		ItemPanel = viewItemList[4].Target.GetComponent<VerticalLayoutGroup>();
		DefencePanel = viewItemList[5].Target.GetComponent<VerticalLayoutGroup>();
		AttackPanel = viewItemList[6].Target.GetComponent<VerticalLayoutGroup>();
		EffectRoot0 = viewItemList[7].Target.GetComponent<RectTransform>();
		EffectRoot1 = viewItemList[8].Target.GetComponent<RectTransform>();
		EffectRoot2 = viewItemList[9].Target.GetComponent<RectTransform>();
		EffectRoot3 = viewItemList[10].Target.GetComponent<RectTransform>();
		EffectRoot4 = viewItemList[11].Target.GetComponent<RectTransform>();
		TxtStage = viewItemList[12].Target.GetComponent<Text>();
		RelicContent = viewItemList[13].Target.GetComponent<RectTransform>();
		UsedRoot = viewItemList[14].Target.GetComponent<RectTransform>();
		UsedCradsNumber = viewItemList[15].Target.GetComponent<Text>();
		EmptyAttack = viewItemList[16].Target.GetComponent<RectTransform>();
		Joey = viewItemList[17].Target.GetComponent<RectTransform>();
		JoeyAnim = viewItemList[17].Target.GetComponent<Animator>();
		MonkeyBg = viewItemList[18].Target.gameObject;
		TurkeyBg = viewItemList[19].Target.gameObject;
		Heart = viewItemList[20].Target.GetComponent<Image>();
		DonkeyBg = viewItemList[21].Target.gameObject;
		DeadkeyBg = viewItemList[22].Target.gameObject;
	}
}