//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIGamePhaseView : YBaseView
{
	public RectTransform EnvPanels;
	public Text TextHeart;
	public Text AttackNum;
	public Text DefenceNum;
	public Text TxtCoin;
	public VerticalLayoutGroup SkillPanel;
	public VerticalLayoutGroup ItemPanel;
	public VerticalLayoutGroup DefencePanel;
	public VerticalLayoutGroup AttackPanel;
	public Image JoeyImage;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		EnvPanels = viewItemList[0].Target.GetComponent<RectTransform>();
		TextHeart = viewItemList[1].Target.GetComponent<Text>();
		AttackNum = viewItemList[2].Target.GetComponent<Text>();
		DefenceNum = viewItemList[3].Target.GetComponent<Text>();
		TxtCoin = viewItemList[4].Target.GetComponent<Text>();
		SkillPanel = viewItemList[5].Target.GetComponent<VerticalLayoutGroup>();
		ItemPanel = viewItemList[6].Target.GetComponent<VerticalLayoutGroup>();
		DefencePanel = viewItemList[7].Target.GetComponent<VerticalLayoutGroup>();
		AttackPanel = viewItemList[8].Target.GetComponent<VerticalLayoutGroup>();
		JoeyImage = viewItemList[9].Target.GetComponent<Image>();
	}
}