//This File Is Auto Generated By Process Control
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using UnityEngine;
using UnityEngine.UI;
using DG.Tweening;
using Cysharp.Threading.Tasks;
using Random = UnityEngine.Random;

public partial class UIGamePhaseControl : YViewControl
{
	private UIGamePhaseView m_View;
	private SingleDelayAction m_MoveCardDelayAction = new SingleDelayAction();

	private List<VerticalLayoutGroup> m_EnvPanels = new List<VerticalLayoutGroup>();
	private MonoBehaviourPool<UICardSimpleControl> m_CardSimplePool;
	private MonoBehaviourPool<UIDamageTextControl> m_DamageTextPool;
	private Dictionary<int, Card> m_CardDict = new Dictionary<int, Card>();
	private List<UIRelicControl> m_RelicList = new List<UIRelicControl>();
	private Dictionary<int, List<UICardSimpleControl>> m_EnvCardDict = new Dictionary<int, List<UICardSimpleControl>>();
	private Dictionary<int, List<UICardSimpleControl>> m_BagCardDict = new Dictionary<int, List<UICardSimpleControl>>();
	private DataJoeyPlayer m_DataJoeyPlayer;
	private List<Card> UsedCardList = new List<Card>();
	private Transform[] m_EffectRoots;
	private Queue<UICardSimpleControl> m_CardActionQueue = new Queue<UICardSimpleControl>();
	public UICardSimpleControl CurrentEffectCard;
	private Dictionary<UICardSimpleControl, CancellationTokenSource> m_CardCtsDict = new Dictionary<UICardSimpleControl, CancellationTokenSource>();
	private bool IsEnvDirty = false;
	private int currentMonsterAttack = 0;
	private bool m_NextAttackDouble = false;
	private List<UICardSimpleControl> m_YGrimReaperList = new List<UICardSimpleControl>();
	private int m_RealGrimReaperEnvIndex = -1;
	private UICardSimpleControl m_FistCardCache;

	public static EResType GetResType()
	{
		return EResType.UIGamePhase;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIGamePhaseView>();
		m_DataJoeyPlayer = DataSystem.Instance.GetDataJoeyPlayer();
		RegistAction(EActionId.AppHp, AppHp);
		RegistAction(EActionId.AppAttack, AppAttack);
		RegistAction(EActionId.AppDefence, AppDefence);
		RegistAction(EActionId.MoveCard, MoveCard);
		RegistAction(EActionId.TakeEnemyDamage, TakeEnemyDamage);
		RegistAction(EActionId.TakePlayerDamage, TakePlayerDamage);
		RegistAction(EActionId.TakePlayerBoomDamage, TakePlayerBoomDamage);
		RegistAction(EActionId.BoomEnvCard, BoomEnvCard);
		RegistAction(EActionId.UseBagCard, UseBagCard);
		RegistAction(EActionId.AddCardFromDiscard, AddCardFromDiscard);
		RegistAction(EActionId.AttackRandomEnemy, AttackRandomEnemy);
		RegistAction(EActionId.TakeAllEnemyDamage, TakeAllEnemyDamage);
		RegistAction(EActionId.AddCardToQueue, AddCardToQueue);
		RegistAction(EActionId.AddEffectValueToBagCard, AddEffectValueToBagCard);
		RegistAction(EActionId.StealCoin, StealCoin);
		RegistAction(EActionId.ReturnCoin, ReturnCoin);
		RegistAction(EActionId.EscapeMonkey, EscapeMonkey);
		RegistAction(EActionId.SwapEnvCard, SwapEnvCard);
		RegistAction(EActionId.RomeoMonkeyDead, RomeoMonkeyDead);
		RegistAction(EActionId.JulietMonkeyDead, JulietMonkeyDead);
		RegistAction(EActionId.AddEnvCardFromBag, AddEnvCardFromBag);
		RegistAction(EActionId.CreateGrimReaperClone, CreateGrimReaperClone);
		RegistAction(EActionId.GrimReaperTakeDamage, GrimReaperTakeDamage);
		RegistAction(EActionId.ThrowWeaponToEnv, ThrowWeaponToEnv);
		RegistAction(EActionId.ThrowWeaponDefenceToEnv, ThrowWeaponDefenceToEnv);

		RegistAction(EActionId.HealPlayerOnDefense, HealPlayerOnDefense);
		RegistAction(EActionId.AddCardToEnv, AddCardToEnv);
		RegistAction(EActionId.AddCardToSpecifiedEnv, AddCardToSpecifiedEnv);
		RegistAction(EActionId.DoubleLastWeaponAttack, DoubleLastWeaponAttack);
		RegistAction(EActionId.AddCardsToEnv, AddCardsToEnv);
		RegistAction(EActionId.OnCoinChange, OnCoinChange);
		RegistAction(EActionId.MonsterHealOnDealDamage, MonsterHealOnDealDamage);
		RegistAction(EActionId.AddCardToBagFromSelect, AddCardToBagFromSelect);
		RegistAction(EActionId.SwapTopTwoEnvCards, SwapTopTwoEnvCards);
		RegistAction(EActionId.UpdateRelic, UpdateRelic);
		RegistAction(EActionId.OnCardPointerEnter, OnCardPointerEnter);
		RegistAction(EActionId.PermanentBoostAttack, PermanentBoostAttack);
		RegistAction(EActionId.PermanentBoostDefence, PermanentBoostDefence);

		for (int i = 0; i < m_View.EnvPanels.childCount; i++)
		{
			Transform child = m_View.EnvPanels.GetChild(i);
			VerticalLayoutGroup vlg = child.GetComponent<VerticalLayoutGroup>();
			m_EnvPanels.Add(vlg);
		}

		m_EffectRoots = new Transform[] { m_View.EffectRoot0, m_View.EffectRoot1, m_View.EffectRoot2, m_View.EffectRoot3, m_View.EffectRoot4 };

		m_CardSimplePool = new MonoBehaviourPool<UICardSimpleControl>(() =>
		{
			return this.Asset.OpenUI<UICardSimpleControl>(null);
		});

		m_DamageTextPool = new MonoBehaviourPool<UIDamageTextControl>(() =>
		{
			return this.Asset.OpenUI<UIDamageTextControl>(null);
		});
	}

	public Transform GetEffectRoot(int envIndex)
	{
		if (envIndex >= 0 && envIndex < m_EffectRoots.Length)
		{
			return m_EffectRoots[envIndex];
		}
		return null;
	}


	void OnHPChanged(int hp)
	{
		m_View.TextHeart.text = hp.ToString();
	}

	void OnAttackChanged(int attack)
	{
	}

	void OnDefenceChanged(int defence)
	{
	}

	private void ApplyPlayerHealthChange(int delta, bool isHeal = false)
	{
		m_DataJoeyPlayer.lastPlayerHealth = m_DataJoeyPlayer.playerHealth;
		m_DataJoeyPlayer.playerHealth += delta;
		if (m_DataJoeyPlayer.playerHealth < 0)
		{
			m_DataJoeyPlayer.playerHealth = 0;
		}
		if (isHeal && m_DataJoeyPlayer.playerHealth > m_DataJoeyPlayer.playerMaxHealth)
		{
			m_DataJoeyPlayer.playerHealth = m_DataJoeyPlayer.playerMaxHealth;
		}
		if (delta != 0)
		{
			int actualChange = isHeal ? (m_DataJoeyPlayer.playerHealth - m_DataJoeyPlayer.lastPlayerHealth) : Mathf.Abs(delta);
			//if (actualChange > 0)
			{
				ShowDamageText(actualChange, m_View.Joey, new Vector3(100f, 190f, 0), !isHeal);
			}
		}
		if (delta < 0 && !isHeal)
		{
			ShakeScreen(0.2f, 20f).Forget();
		}
		OnHPChanged(m_DataJoeyPlayer.playerHealth);
		CheckGameOver();
	}

	private void CheckGameOver()
	{
		if (m_DataJoeyPlayer.playerHealth <= 0)
		{
			JoeyGameControl.Instance.ShowGameOver();
		}
	}

	void AppHp(object[] paraArray)
	{
		int delta = (int)paraArray[0];
		AppHp(delta);
	}

	void AppAttack(object[] paraArray)
	{
		int delta = (int)paraArray[0];
		m_DataJoeyPlayer.playerAttack += delta;
		OnAttackChanged(m_DataJoeyPlayer.playerAttack);
	}

	void AppDefence(object[] paraArray)
	{
		int delta = (int)paraArray[0];
		m_DataJoeyPlayer.playerDefence += delta;
		OnDefenceChanged(m_DataJoeyPlayer.playerDefence);
	}

	public void SetData()
	{
		RefreshView();
		ClearAllCard();
		CreateFistCardCache();
	}

	private void CreateFistCardCache()
	{
		if (m_FistCardCache != null && m_FistCardCache.gameObject.activeSelf)
		{
			return;
		}
		Card card = DataSystem.Instance.CreateCard("1011");
		Transform attackPanelTransform = m_View.AttackPanel.transform;
		UICardSimpleControl cardControl = m_CardSimplePool.Get();
		cardControl.CacheTrans.SetParent(m_View.EmptyAttack);
		cardControl.CacheTrans.position = attackPanelTransform.position;
		cardControl.CacheTrans.localScale = Vector3.one * .8f;
		cardControl.CacheTrans.localEulerAngles = Vector3.zero;
		cardControl.IsEnv = false;
		cardControl.SetData(card);
		m_FistCardCache = cardControl;
	}

	public void ClearEnvCardList()
	{
		for (int i = 0; i < m_EnvPanels.Count; i++)
		{
			if (m_EnvCardDict.TryGetValue(i, out List<UICardSimpleControl> envCardList))
			{
				for (int j = 0; j < envCardList.Count; j++)
				{
					UICardSimpleControl cardControl = envCardList[j];
					if (cardControl != null && cardControl.gameObject.activeSelf)
					{
						m_CardDict.Remove(cardControl.CardData.UniqueId);
						RemoveCardCts(cardControl);
						cardControl.Return();
					}
				}
			}
		}
		m_EnvCardDict.Clear();
	}

	public void ClearBagCardList()
	{
		foreach (var kvp in m_BagCardDict)
		{
			List<UICardSimpleControl> bagCardList = kvp.Value;
			if (bagCardList != null)
			{
				for (int i = 0; i < bagCardList.Count; i++)
				{
					UICardSimpleControl cardControl = bagCardList[i];
					if (cardControl != null && cardControl.gameObject.activeSelf)
					{
						m_CardDict.Remove(cardControl.CardData.UniqueId);
						RemoveCardCts(cardControl);
						cardControl.Return();
					}
				}
			}
		}
		m_BagCardDict.Clear();
	}

	public void SetDataWithoutBagClear()
	{
		RefreshView();
		ClearEnvCardList();
		UsedCardList.Clear();
		ClearGrimReaperData();
	}

	private void RefreshView()
	{
		m_View.TextHeart.text = m_DataJoeyPlayer.playerHealth.ToString();
		m_View.TxtCoin.text = m_DataJoeyPlayer.Coin.ToString();
		RoguelikeStage currentStage = GData.Instance.GetRoguelikeStage(m_DataJoeyPlayer.StageId);
		if (currentStage != null && !string.IsNullOrEmpty(currentStage.stages))
		{
			m_View.TxtStage.text = currentStage.stages;
		}
		else
		{
			m_View.TxtStage.text = string.Empty;
		}
		RefreshRelicDisplay();
	}

	private void OnCoinChanged(int coin)
	{
		m_DataJoeyPlayer.Coin = coin;
		m_View.TxtCoin.text = coin.ToString();
	}

	private UICardSimpleControl GetCardSimple(Transform parent, bool IsEnv)
	{
		UICardSimpleControl cardControl = m_CardSimplePool.Get();
		cardControl.CacheTrans.SetParent(parent);
		cardControl.CacheTrans.localScale = Vector3.one;
		cardControl.CacheTrans.localPosition = Vector3.zero;
		cardControl.CacheTrans.localEulerAngles = Vector3.zero;
		cardControl.CacheTrans.SetAsLastSibling();
		cardControl.IsEnv = IsEnv;
		return cardControl;
	}

	private void ShowDamageText(int damage, Transform parent, Vector3 localPositionShift, bool isDamage = true)
	{
		UIDamageTextControl damageTextControl = m_DamageTextPool.Get();
		damageTextControl.SetData(damage, parent, localPositionShift, isDamage);
	}

	private async UniTask ShakeScreen(float duration = 0.2f, float intensity = 10f)
	{
		RectTransform rectTransform = transform as RectTransform;
		Vector2 originalPosition = rectTransform.anchoredPosition;
		float elapsed = 0f;

		while (elapsed < duration)
		{
			float progress = elapsed / duration;
			float currentIntensity = intensity * (1f - progress);
			Vector2 randomOffset = Random.insideUnitCircle * currentIntensity;
			rectTransform.anchoredPosition = originalPosition + randomOffset;

			elapsed += Time.deltaTime;
			await UniTask.Yield();
		}

		rectTransform.anchoredPosition = originalPosition;
	}

	public Card CreateCard(string cardId)
	{
		Card card = DataSystem.Instance.CreateCard(cardId);
		m_CardDict[card.UniqueId] = card;
		return card;
	}

	private Transform GetParentByCardType(ECardType cardType)
	{
		switch (cardType)
		{
			case ECardType.attack:
				return m_View.AttackPanel.transform;
			case ECardType.defence:
				return m_View.DefencePanel.transform;
			case ECardType.skill:
				return m_View.SkillPanel.transform;
			case ECardType.item:
				return m_View.ItemPanel.transform;
			case ECardType.monster:
			case ECardType.other:
				return m_View.EnvPanels.transform;
			default:
				return null;
		}
	}

	private void AddCardToBag(string cardId)
	{
		Card card = CreateCard(cardId);
		AddCardToBag(card);
	}

	private void AddCardToBag(Card card)
	{
		if (card == null)
		{
			return;
		}
		ECardType cardType = card.GetCardType();
		Transform parent = GetParentByCardType(cardType);
		if (parent == null)
		{
			return;
		}
		m_CardDict[card.UniqueId] = card;
		UICardSimpleControl cardControl = GetCardSimple(parent, false);
		cardControl.SetData(card);
		AddBagCard(cardType, cardControl);
		cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
	}


	public void AddCardList(ECardType cardType, List<string> cardIds)
	{
		Debug.Log("AddCardList: " + cardType + " " + cardIds.Count);

		Transform parent = GetParentByCardType(cardType);
		if (parent == null)
		{
			return;
		}

		for (int i = cardIds.Count - 1; i >= 0; i--)
		{
			string cardId = cardIds[i];
			Card card = CreateCard(cardId);
			UICardSimpleControl cardControl = GetCardSimple(parent, false);
			cardControl.SetData(card);
			AddBagCard(cardType, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
		}
	}

	public void AddEnvCardList(List<string> cardIds, int index)
	{
		VerticalLayoutGroup parent = m_EnvPanels[index];

		for (int i = cardIds.Count - 1; i >= 0; i--)
		{
			string cardId = cardIds[i];
			Card card = CreateCard(cardId);
			UICardSimpleControl cardControl = GetCardSimple(parent.transform, true);
			cardControl.SetData(card, isEnv: true, envIndex: index);
			AddEnvCard(index, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
		}
	}

	public Card GetCardDataById(int uniqueId)
	{
		return m_CardDict[uniqueId];
	}

	public void AddSelfCardList()
	{
		AddCardsFromEquipList(m_DataJoeyPlayer.EquipedAttackList);
		AddCardsFromEquipList(m_DataJoeyPlayer.EquipedDefenceList);
		AddCardsFromEquipList(m_DataJoeyPlayer.EquipedItemList);
		AddCardsFromEquipList(m_DataJoeyPlayer.EquipedSkillList);
	}

	private void AddCardsFromEquipList(List<int> equipList)
	{
		for (int i = 0; i < equipList.Count; i++)
		{
			int uniqueId = equipList[i];
			Card card = m_DataJoeyPlayer.GetSelfCardDictData(uniqueId);
			if (card == null) continue;

			ECardType cardType = card.GetCardType();
			Transform parent = GetParentByCardType(cardType);
			if (parent == null)
			{
				continue;
			}
			m_CardDict[card.UniqueId] = card;
			UICardSimpleControl cardControl = GetCardSimple(parent, false);
			cardControl.SetData(card);
			AddBagCard(cardType, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);
		}
	}

	private void AddBagCard(ECardType cardType, UICardSimpleControl cardControl, bool isMoveCard = false)
	{
		int cardTypeInt = (int)cardType;
		if (!m_BagCardDict.TryGetValue(cardTypeInt, out List<UICardSimpleControl> cardList))
		{
			m_BagCardDict[cardTypeInt] = new List<UICardSimpleControl>();
		}
		m_BagCardDict[cardTypeInt].Add(cardControl);
		cardControl.IsEnv = false;
		cardControl.EnvIndex = -1;
		if (!isMoveCard)
		{
			cardControl.CacheTrans.localScale = new Vector3(0.8f, 0.8f, 0.8f);
		}
	}


	private async UniTask RemoveBagCard(ECardType cardType, UICardSimpleControl cardControl)
	{
		int cardTypeInt = (int)cardType;
		if (m_BagCardDict.TryGetValue(cardTypeInt, out List<UICardSimpleControl> cardList))
		{
			cardList.Remove(cardControl);
			RemoveCardData(cardControl.CardData.UniqueId);
			cardControl.Return();

			UICardSimpleControl newLastBagCard = GetLastBagCard(cardType);
			if (newLastBagCard != null)
			{
				float delayTime = newLastBagCard.CardEffect?.OnBecomeTopOfPile() ?? 0.5f;
				await UniTask.WaitForSeconds(delayTime, cancellationToken: CancellationToken.None);
			}
		}
	}

	private List<UICardSimpleControl> GetBagCardList(ECardType cardType)
	{
		int cardTypeInt = (int)cardType;
		if (m_BagCardDict.TryGetValue(cardTypeInt, out List<UICardSimpleControl> cardList))
		{
			return cardList;
		}
		return null;
	}

	private UICardSimpleControl GetLastBagCard(ECardType cardType)
	{
		List<UICardSimpleControl> cardList = GetBagCardList(cardType);
		if (cardList != null && cardList.Count > 0)
		{
			return cardList[cardList.Count - 1];
		}
		return null;
	}

	private UICardSimpleControl GetLastEnvCard(int envIndex)
	{
		if (m_EnvCardDict.TryGetValue(envIndex, out List<UICardSimpleControl> cardList))
		{
			if (cardList != null && cardList.Count > 0)
			{
				return cardList[cardList.Count - 1];
			}
		}
		return null;
	}

	public bool HasBagCard(ECardType cardType)
	{
		List<UICardSimpleControl> cardList = GetBagCardList(cardType);
		return cardList != null && cardList.Count > 0;
	}


	private UICardSimpleControl GetFistCard()
	{
		return m_FistCardCache;
	}

	private void AddEnvCard(int index, UICardSimpleControl cardControl)
	{
		if (!m_EnvCardDict.TryGetValue(index, out List<UICardSimpleControl> cardList))
		{
			m_EnvCardDict[index] = new List<UICardSimpleControl>();
		}
		m_EnvCardDict[index].Add(cardControl);
		IsEnvDirty = true;
	}

	private void RemoveEnvCard(int index, UICardSimpleControl cardControl)
	{
		if (m_EnvCardDict.TryGetValue(index, out List<UICardSimpleControl> cardList))
		{
			cardList.Remove(cardControl);
			RemoveCardData(cardControl.CardData.UniqueId);
			cardControl.Return();
			IsEnvDirty = true;
		}
	}

	private void RemoveEnvCardFromDict(int index, UICardSimpleControl cardControl)
	{
		if (m_EnvCardDict.TryGetValue(index, out List<UICardSimpleControl> cardList))
		{
			cardList.Remove(cardControl);
		}
	}

	private async UniTask<bool> DealDamageToEnvCard(UICardSimpleControl cardControl, int damage, int envIndex, EEffectType effectType = EEffectType.Damage, CancellationToken? cancellationToken = null)
	{
		CancellationToken token = cancellationToken ?? GetOrCreateCardToken(CurrentEffectCard);

		if (cardControl.CardType == ECardType.monster)
		{
			float delayTime = cardControl.CallCardTakeDamage(damage, effectType);
			ShowDamageText(damage, cardControl.CacheTrans, new Vector3(0f, 180f, 0));
			//if (effectType == EEffectType.Damage)
			{
				ShakeScreen(0.2f, 20f).Forget();
			}
			if (delayTime > 0f)
			{
				await UniTask.WaitForSeconds(delayTime, cancellationToken: token);
			}
		}



		if (cardControl.CardData.currentHealth <= 0 && cardControl.CardType == ECardType.monster)
		{
			string monsterId = cardControl.CardData.id;
			List<Card> dropCards = GetMonsterDropCard(monsterId);

			float delayTime = cardControl.CardEffect?.OnBeDying() ?? 0.5f;
			await UniTask.WaitForSeconds(delayTime, cancellationToken: token);

			Card configCard = GData.Instance.GetCardConfigById(monsterId);
			if (configCard != null && configCard.price > 0)
			{
				DataSystem.Instance.AddCoin(configCard.price);
			}

			RemoveEnvCard(envIndex, cardControl);
			delayTime = cardControl.CardEffect?.OnDead() ?? 0.5f;
			await UniTask.WaitForSeconds(delayTime, cancellationToken: token);
			RemoveCardCts(cardControl);

			if (dropCards != null && dropCards.Count > 0)
			{
				AddEnvDropCard(dropCards, envIndex);
			}

			return true;
		}

		return false;
	}

	private List<Card> GetMonsterDropCard(string monsterId)
	{
		if (string.IsNullOrEmpty(monsterId))
		{
			return null;
		}

		if (!LootDropManager.Instance.TryGetDropCards(monsterId, out List<string> cardIds) || cardIds == null || cardIds.Count == 0)
		{
			return null;
		}

		List<Card> dropCards = new List<Card>();
		for (int i = 0; i < cardIds.Count; i++)
		{
			Card card = CreateCard(cardIds[i]);
			dropCards.Add(card);
		}

		return dropCards;
	}

	private void AddEnvDropCard(List<Card> dropCards, int centerIndex)
	{
		if (dropCards == null || dropCards.Count == 0)
		{
			return;
		}

		if (m_EnvPanels == null || m_EnvPanels.Count == 0)
		{
			return;
		}

		centerIndex = Mathf.Clamp(centerIndex, 0, m_EnvPanels.Count - 1);

		var usedIndices = new HashSet<int>();
		var offsetPattern = BuildOffsetPattern(m_EnvPanels.Count);

		for (int i = 0; i < dropCards.Count; i++)
		{
			int panelIndex = FindPanelIndex(centerIndex, usedIndices, offsetPattern, m_EnvPanels.Count);
			if (panelIndex < 0)
			{
				panelIndex = centerIndex;
			}

			panelIndex = Mathf.Clamp(panelIndex, 0, m_EnvPanels.Count - 1);
			VerticalLayoutGroup parent = m_EnvPanels[panelIndex];
			UICardSimpleControl cardControl = GetCardSimple(parent.transform, true);
			cardControl.SetData(dropCards[i], isEnv: true, envIndex: panelIndex);
			AddEnvCard(panelIndex, cardControl);
			cardControl.PlayVFX(new List<EVFXName>(), ECardAnimName.UI_Carditem_pailai, EVFXLife.CardLife);

			usedIndices.Add(panelIndex);
		}
	}

	private List<int> BuildOffsetPattern(int panelCount)
	{
		var offsets = new List<int>();
		offsets.Add(0);
		int step = 1;
		while (offsets.Count < panelCount * 2)
		{
			offsets.Add(-step);
			offsets.Add(step);
			step++;
		}
		return offsets;
	}

	private int FindPanelIndex(int centerIndex, HashSet<int> usedIndices, List<int> offsetPattern, int panelCount)
	{
		for (int i = 0; i < offsetPattern.Count; i++)
		{
			int candidate = centerIndex + offsetPattern[i];
			if (candidate < 0 || candidate >= panelCount) continue;
			if (usedIndices.Contains(candidate)) continue;
			return candidate;
		}

		return Mathf.Clamp(centerIndex, 0, panelCount - 1);
	}

	async void BoomEnvCard(object[] paraArray)
	{
		int envIndex = (int)paraArray[0];
		int damage = (int)paraArray[1];
		bool excludeSelf = paraArray.Length > 2 && paraArray[2] is bool && (bool)paraArray[2];

		if (envIndex == -1)
		{
			await BoomEnvCardRandom(damage);
		}
		else
		{
			await BoomEnvCardAtPosition(envIndex, damage, excludeSelf);
		}
	}

	private int FindRandomEnemy()
	{
		List<int> enemyIndices = new List<int>();
		foreach (var kvp in m_EnvCardDict)
		{
			if (kvp.Value != null && kvp.Value.Count > 0)
			{
				UICardSimpleControl lastCard = kvp.Value[kvp.Value.Count - 1];
				if (lastCard != null && lastCard.gameObject.activeSelf && lastCard.CardType == ECardType.monster && lastCard.CardData.currentHealth > 0)
				{
					enemyIndices.Add(kvp.Key);
				}
			}
		}
		if (enemyIndices.Count == 0)
		{
			return -1;
		}
		return enemyIndices[Random.Range(0, enemyIndices.Count)];
	}

	void AddEnvCardFromBag(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		AddEnvCardFromBag(cardControl);
	}

	void ThrowWeaponToEnv(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		ThrowWeaponToEnv(cardControl);
	}
	void ThrowWeaponDefenceToEnv(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		ThrowWeaponDefenceToEnv(cardControl);
	}

	void AddCardToSpecifiedEnv(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		string cardId = (string)paraArray[1];
		int envIndex = (int)paraArray[2];
		AddCardToEnv(cardControl, cardId, envIndex);
	}

	void AddCardToEnv(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		string cardId = (string)paraArray[1];
		AddCardToEnv(cardControl, cardId);
	}
	void AddCardsToEnv(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		List<Card> cards = (List<Card>)paraArray[1];
		int envIndex = Random.Range(0, m_EnvPanels.Count - 1);
		AddEnvDropCard(cards, envIndex);
	}

	void SwapTopTwoEnvCards(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		SwapTopTwoEnvCards(cardControl);
	}

	void MonsterHealOnDealDamage(object[] paraArray)
	{
		UICardSimpleControl monsterCardControl = (UICardSimpleControl)paraArray[0];
		if (monsterCardControl != null && monsterCardControl.CardType == ECardType.monster)
		{
			VampireMonkeyDealDamage(monsterCardControl);
			// monsterCardControl.CallCardTakeDamage(3, EEffectType.Heal);
		}
	}
	void DoubleLastWeaponAttack(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		if (cardControl == null)
		{
			return;
		}
		// 设置标记，表示下一次攻击翻倍
		m_NextAttackDouble = true;
	}

	void HealPlayerOnDefense(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		Debug.Log($"currentMonsterAttack: {currentMonsterAttack}");
		if (currentMonsterAttack > 0)
		{
			ApplyPlayerHealthChange(currentMonsterAttack, true);
		}
		currentMonsterAttack = 0;
	}

	void RemoveCardData(int uniqueId)
	{
		if (m_CardDict.TryGetValue(uniqueId, out Card card))
		{
			UsedCardList.Add(card);
			m_CardDict.Remove(uniqueId);
		}
	}

	public void ClearAllCard()
	{
		m_CardSimplePool.ForEach(cardControl =>
		{
			if (cardControl != null && cardControl.gameObject.activeSelf && cardControl != m_FistCardCache)
			{
				cardControl.Return();
			}
		});

		m_CardDict.Clear();
		m_EnvCardDict.Clear();
		m_BagCardDict.Clear();
		UsedCardList.Clear();
		ClearGrimReaperData();
		ClearAllCardCts();
	}

	private CancellationToken GetOrCreateCardToken(UICardSimpleControl cardControl)
	{
		if (cardControl == null)
		{
			return CancellationToken.None;
		}

		if (!m_CardCtsDict.TryGetValue(cardControl, out CancellationTokenSource cts) || cts == null || cts.IsCancellationRequested)
		{
			if (cts != null)
			{
				cts.Dispose();
				m_CardCtsDict.Remove(cardControl);
			}
			cts = new CancellationTokenSource();
			m_CardCtsDict[cardControl] = cts;
			string cardId = cardControl?.CardData?.id ?? "null";
			string cardName = cardControl?.CardData?.cardName ?? "null";
			Debug.Log($"[AddCardCts] CardId: {cardId}, CardName: {cardName}, DictCount: {m_CardCtsDict.Count}");
		}

		return cts.Token;
	}

	private void RemoveCardCts(UICardSimpleControl cardControl)
	{
		if (cardControl == null)
		{
			return;
		}

		if (!m_CardCtsDict.TryGetValue(cardControl, out CancellationTokenSource cts))
		{
			string cardId = cardControl?.CardData?.id ?? "null";
			string cardName = cardControl?.CardData?.cardName ?? "null";
			Debug.LogWarning($"[RemoveCardCts] CardId: {cardId}, CardName: {cardName} not found in dict, DictCount: {m_CardCtsDict.Count}");
			return;
		}

		if (cts != null)
		{
			cts.Cancel();
			cts.Dispose();
		}
		m_CardCtsDict.Remove(cardControl);
		string cardId2 = cardControl?.CardData?.id ?? "null";
		string cardName2 = cardControl?.CardData?.cardName ?? "null";
		Debug.Log($"[RemoveCardCts] CardId: {cardId2}, CardName: {cardName2}, DictCount: {m_CardCtsDict.Count}");
	}

	private void ClearAllCardCts()
	{
		foreach (var kvp in m_CardCtsDict)
		{
			if (kvp.Value != null)
			{
				kvp.Value.Cancel();
				kvp.Value.Dispose();
			}
		}
		m_CardCtsDict.Clear();
	}

	async void MoveCard(object[] paraArray)
	{
		bool isEnv = (bool)paraArray[0];
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[1];
		cardControl.SetMoving(true);
		if (isEnv)
		{
			ECardType cardType = cardControl.CardType;

			Vector3 startWorldPos = cardControl.CacheTrans.parent.position;
			Vector3 startScale = Vector3.one;

			RemoveEnvCardFromDict(cardControl.EnvIndex, cardControl);
			AddBagCard(cardType, cardControl, true);
			//await UniTask.WaitForSeconds(delayTime);

			VerticalLayoutGroup layout = null;
			switch (cardType)
			{
				case ECardType.attack:
					layout = m_View.AttackPanel;
					break;
				case ECardType.defence:
					layout = m_View.DefencePanel;
					break;
				case ECardType.skill:
					layout = m_View.SkillPanel;
					break;
				case ECardType.item:
					layout = m_View.ItemPanel;
					break;
				default:
					return;
			}

			Vector3 endScale = new Vector3(0.8f, 0.8f, 1.0f);
			float duration = .2f;
			Vector3 endPos = layout.transform.position;

			m_MoveCardDelayAction.AddAnimDelayAction(
				(cancellationToken) => MoveCardAnimation(cardControl, startWorldPos, endPos, startScale, endScale, duration, layout, cancellationToken),
				() =>
				{
					cardControl.CacheTrans.position = endPos;
					cardControl.CacheTrans.localScale = endScale;
					cardControl.CacheTrans.localEulerAngles = Vector3.zero;
					layout.enabled = true;
					cardControl.SetMoving(false);
					if (CurrentEffectCard != null)
					{
						CurrentEffectCard.CardEffect?.OnEnterBag();

						CurrentEffectCard.IsEffecting = false;
						RemoveCardCts(CurrentEffectCard);
					}

				}
			);
		}
	}

	private async UniTask MoveCardAnimation(UICardSimpleControl cardControl, Vector3 startPos, Vector3 endPos, Vector3 startScale, Vector3 endScale, float duration, VerticalLayoutGroup layout, CancellationToken cancellationToken)
	{
		layout.enabled = false;
		cardControl.CacheTrans.SetParent(layout.transform);

		//Debug.Log("MoveCardAnimation: startPos = " + startPos + ", endPos = " + endPos + ", startScale = " + startScale + ", endScale = " + endScale + ", duration = " + duration);
		float elapsed = 0f;
		while (elapsed < duration)
		{
			cancellationToken.ThrowIfCancellationRequested();
			elapsed += Time.deltaTime;
			float t = elapsed / duration;

			cardControl.CacheTrans.position = Vector3.Lerp(startPos, endPos, t);
			cardControl.CacheTrans.localScale = Vector3.Lerp(startScale, endScale, t);

			//Debug.Log($"MoveCard Animation - Position: {cardControl.CacheTrans.position}, Scale: {cardControl.CacheTrans.localScale}, t: {t}");

			await UniTask.Yield(GetOrCreateCardToken(cardControl));
		}
	}

	async void TakeEnemyDamage(object[] paraArray)
	{
		UICardSimpleControl enemyCardControl = (UICardSimpleControl)paraArray[0];
		int attackCount = (int)paraArray[1];
		int envIndex = (int)paraArray[2];
		UICardSimpleControl attackCardControl = GetLastBagCard(ECardType.attack);
		if (attackCardControl == null)
		{
			attackCardControl = GetFistCard();
		}
		bool useFistCard = attackCardControl == m_FistCardCache;
		if (useFistCard)
		{
			await UniTask.WaitForSeconds(1f, cancellationToken: GetOrCreateCardToken(attackCardControl));
		}

		attackCount += attackCardControl.CardEffect?.GetEffectValue(EEffectType.ExtraAttackCnt) ?? 0;
		Card attackCard = attackCardControl.CardData;
		int damage = attackCard.currentAttack + attackCardControl.CardEffect?.GetEffectValue(EEffectType.Damage) ?? 0;
		if (m_NextAttackDouble)
		{
			damage *= 2;
			m_NextAttackDouble = false;
		}
		float delayTime;
		delayTime = attackCardControl.CardEffect?.UseAttack() ?? 0.5f;
		await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(attackCardControl));

		if (DataSystem.Instance.HasRelic(ERelicType.GetSpecialCardByAttack))
		{
			if (ControlUtil.IsRandomSucceed(10))
			{
				AddCardToBag("4001");
			}
		}

		bool enemyKilled = false;
		for (int i = 0; i < attackCount; i++)
		{
			delayTime = attackCardControl.CardEffect?.OnDealDamage() ?? 0.5f;
			await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(attackCardControl));

			bool isKilled = await DealDamageToEnvCard(enemyCardControl, damage, envIndex, EEffectType.Damage, GetOrCreateCardToken(attackCardControl));
			if (isKilled)
			{
				enemyKilled = true;

				delayTime = attackCardControl.CardEffect?.OnKill() ?? 0.5f;
				await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(attackCardControl));

				if (DataSystem.Instance.HasRelic(ERelicType.HealOnKill))
				{
					AppHp(3);
				}

				break;
			}
		}

		// 延迟播放武器牌的掉落动画，直到防御牌使用后判断是否需要播放
		bool shouldPlayWeaponDropAnimation = true;

		if (!enemyKilled && enemyCardControl != null && enemyCardControl.gameObject.activeSelf && enemyCardControl.CardData.currentHealth > 0)
		{
			int enemyAttack = enemyCardControl.CardData.currentAttack;
			CancellationToken attackToken = GetOrCreateCardToken(attackCardControl);
			// 传递武器牌引用，以便在防御牌使用后判断是否需要播放掉落动画
			shouldPlayWeaponDropAnimation = await TakePlayerDamageAsync(enemyAttack, enemyCardControl, envIndex, attackToken, attackCardControl);
		}

		// 只有当武器牌不会被移动到环境卡时，才播放掉落动画
		if (shouldPlayWeaponDropAnimation)
		{
			float finishDelayTime = attackCardControl.CardEffect?.OnUseFinished() ?? 0f;
			if (finishDelayTime > 0f)
			{
				await UniTask.WaitForSeconds(finishDelayTime, cancellationToken: GetOrCreateCardToken(attackCardControl));
			}
		}

		if (!useFistCard)
		{
			await RemoveBagCard(ECardType.attack, attackCardControl);
			float removeDelayTime = attackCardControl.CardEffect?.OnRemoveCard() ?? 0f;
			if (removeDelayTime > 0f)
			{
				await UniTask.WaitForSeconds(removeDelayTime, cancellationToken: GetOrCreateCardToken(attackCardControl));
			}
		}
		RemoveCardCts(attackCardControl);

		enemyCardControl.IsEffecting = false;
	}

	async void TakePlayerDamage(object[] paraArray)
	{
		int enemyAttack = (int)paraArray[0];
		UICardSimpleControl enemyCardControl = (UICardSimpleControl)paraArray[1];
		int envIndex = (int)paraArray[2];
		CancellationToken enemyToken = GetOrCreateCardToken(enemyCardControl);
		// 这个调用不需要返回武器牌掉落动画的播放标志，因为不是从TakeEnemyDamage调用的
		await TakePlayerDamageAsync(enemyAttack, enemyCardControl, envIndex, enemyToken, null);
	}

	async UniTask<bool> TakePlayerDamageAsync(int enemyAttack, UICardSimpleControl enemyCardControl, int envIndex, CancellationToken cancellationToken = default, UICardSimpleControl attackCardControl = null)
	{
		currentMonsterAttack = enemyAttack;
		float delayTime = enemyCardControl.CardEffect?.OnDealDamage() ?? 0.5f;
		await UniTask.WaitForSeconds(delayTime, cancellationToken: cancellationToken);

		int defenceValue = 0;
		UICardSimpleControl defenceCardControl = GetLastBagCard(ECardType.defence);
		bool weaponWillMoveToEnv = false;
		if (defenceCardControl != null)
		{
			defenceValue = defenceCardControl.CardData.currentDefence + (defenceCardControl.CardEffect?.GetEffectValue(EEffectType.Defence) ?? 0);
			bool isOverflow = defenceValue < enemyAttack;
			delayTime = defenceCardControl.CardEffect?.UseDefence(isOverflow) ?? 0.5f;
			await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(defenceCardControl));

			// 检查防御牌是否有ThrowWeaponToStack_OnDefence效果，如果有，武器牌会被移动到环境卡，不应该播放掉落动画
			weaponWillMoveToEnv = defenceCardControl.CardEffect != null &&
				defenceCardControl.CardEffect.Id == ECardEffectId.ThrowWeaponToStack_OnDefence;

			if (DataSystem.Instance.HasRelic(ERelicType.GetSpecialCardByDefence))
			{
				if (ControlUtil.IsRandomSucceed(10))
				{
					AddCardToBag("4001");
				}
			}
		}
		int damage = 0;
		if (defenceValue < enemyAttack)
		{
			damage = enemyAttack - defenceValue;
		}
		ApplyPlayerHealthChange(-damage);
		OnAttackChanged(m_DataJoeyPlayer.playerAttack);
		OnDefenceChanged(m_DataJoeyPlayer.playerDefence);

		if (defenceCardControl != null)
		{
			int reflectDamage = defenceCardControl.CardEffect?.GetEffectValue(EEffectType.ReflectDamage) ?? 0;
			if (reflectDamage > 0)
			{
				await AttackSpecialEnemy(enemyCardControl, reflectDamage, envIndex, GetOrCreateCardToken(defenceCardControl));
			}
			float finishDelayTime = defenceCardControl.CardEffect?.OnUseFinished() ?? 0f;
			if (finishDelayTime > 0f)
			{
				await UniTask.WaitForSeconds(finishDelayTime, cancellationToken: GetOrCreateCardToken(defenceCardControl));
			}
			await RemoveBagCard(ECardType.defence, defenceCardControl);
			float removeDelayTime = defenceCardControl.CardEffect?.OnRemoveCard() ?? 0f;
			if (removeDelayTime > 0f)
			{
				await UniTask.WaitForSeconds(removeDelayTime, cancellationToken: GetOrCreateCardToken(defenceCardControl));
			}
			RemoveCardCts(defenceCardControl);
		}

		RemoveCardCts(enemyCardControl);
		currentMonsterAttack = 0;

		// 返回是否应该播放武器牌的掉落动画（如果武器牌会被移动到环境卡，则返回false）
		return !weaponWillMoveToEnv;
	}

	void TakePlayerBoomDamage(object[] paraArray)
	{
		int damage = (int)paraArray[0];
		if (damage > 0)
		{
			JoeyGameControl.Instance.PlayVFX(EVFXName.VFX_boom, m_View.Joey, 0f);
			SFX.PlayAudio("Audio/SFX/Battle/boom", 1.0f, 0f);
		}
		ApplyPlayerHealthChange(-damage);
	}

	async void UseBagCard(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		ECardType cardType = cardControl.CardType;
		float delayTime = 0f;

		if (cardType == ECardType.skill)
		{
			delayTime = cardControl.CardEffect?.UseSkill() ?? 0.5f;
		}
		else if (cardType == ECardType.item)
		{
			delayTime = cardControl.CardEffect?.UseItem() ?? 0.5f;
		}

		await UniTask.WaitForSeconds(delayTime, cancellationToken: GetOrCreateCardToken(cardControl));
		float finishDelayTime = cardControl.CardEffect?.OnUseFinished() ?? 0f;
		if (finishDelayTime > 0f)
		{
			await UniTask.WaitForSeconds(finishDelayTime, cancellationToken: GetOrCreateCardToken(cardControl));
		}
		await RemoveBagCard(cardType, cardControl);
		float removeDelayTime = cardControl.CardEffect?.OnRemoveCard() ?? 0f;
		if (removeDelayTime > 0f)
		{
			await UniTask.WaitForSeconds(removeDelayTime, cancellationToken: GetOrCreateCardToken(cardControl));
		}
		RemoveCardCts(cardControl);
		if (CurrentEffectCard != null)
		{
			CurrentEffectCard.IsEffecting = false;
		}
	}

	void AddCardFromDiscard(object[] paraArray)
	{
		ECardType specialCardType = paraArray.Length > 0 && paraArray[0] is ECardType ? (ECardType)paraArray[0] : ECardType.other;
		if (specialCardType == ECardType.attack)
		{
			AddCardFromDiscardAttack();
		}
		else
		{
			AddCardFromDiscardByType(specialCardType);
		}
	}

	void AddCardToBagFromSelect(object[] paraArray)
	{
		if (paraArray.Length > 0 && paraArray[0] is Card)
		{
			Card card = (Card)paraArray[0];
			AddCardToBag(card);
		}
	}

	async void AttackRandomEnemy(object[] paraArray)
	{
		try
		{
			int damage = paraArray[0] is int ? (int)paraArray[0] : 0;
			int attackTime = paraArray.Length > 1 && paraArray[1] is int ? (int)paraArray[1] : 1;
			await AttackRandomEnemy(damage, attackTime);
		}
		catch (OperationCanceledException)
		{
		}
	}

	async UniTask AttackSpecialEnemy(UICardSimpleControl enemyCardControl, int damage, int envIndex, CancellationToken? cancellationToken = null)
	{
		if (enemyCardControl == null)
		{
			return;
		}

		await DealDamageToEnvCard(enemyCardControl, damage, envIndex, EEffectType.Damage, cancellationToken);
	}

	async void TakeAllEnemyDamage(object[] paraArray)
	{
		int damage = paraArray[0] is int ? (int)paraArray[0] : 0;
		await TakeAllEnemyDamage(damage);
	}

	void AddCardToQueue(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		if (cardControl != null && !m_CardActionQueue.Contains(cardControl) && CurrentEffectCard != cardControl)
		{
			for (int i = 0; i < m_EnvPanels.Count; i++)
			{
				UICardSimpleControl lastCard = GetLastEnvCard(i);
				if (lastCard != null)
				{
					lastCard.UpdateBuffValue();
				}
			}
			m_CardActionQueue.Enqueue(cardControl);
		}
	}

	void AddEffectValueToBagCard(object[] paraArray)
	{
		ECardType targetCardType = paraArray.Length > 0 && paraArray[0] is ECardType ? (ECardType)paraArray[0] : ECardType.attack;
		EEffectType effectType = paraArray.Length > 1 && paraArray[1] is EEffectType ? (EEffectType)paraArray[1] : EEffectType.Other;
		int value = paraArray.Length > 2 && paraArray[2] is int ? (int)paraArray[2] : 0;
		AddEffectValueToBagCard(targetCardType, effectType, value);
	}

	void Update()
	{
		if (CurrentEffectCard == null && m_CardActionQueue.Count > 0)
		{
			CurrentEffectCard = m_CardActionQueue.Dequeue();
			if (CurrentEffectCard != null)
			{
				GetOrCreateCardToken(CurrentEffectCard);
				CurrentEffectCard.OnBtnRealClick();
			}
		}

		if (CurrentEffectCard != null && !CurrentEffectCard.IsEffecting && m_CardCtsDict.Count == 0)
		{
			CurrentEffectCard = null;
		}
	}

	void LateUpdate()
	{
		if (IsEnvDirty)
		{
			IsEnvDirty = false;
			UpdateBadMonkeyAttack();
		}
	}

	public void ClearCardQueue()
	{
		if (CurrentEffectCard != null)
		{
			CurrentEffectCard.IsEffecting = false;
			RemoveCardCts(CurrentEffectCard);
			CurrentEffectCard.Return();
		}
		CurrentEffectCard = null;

		while (m_CardActionQueue.Count > 0)
		{
			UICardSimpleControl cardControl = m_CardActionQueue.Dequeue();
			cardControl.IsEffecting = false;
			RemoveCardCts(cardControl);
			cardControl.Return();
		}

	}

	void CreateGrimReaperClone(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		CreateGrimReaperClone(cardControl);
	}

	void GrimReaperTakeDamage(object[] paraArray)
	{
		UICardSimpleControl grimReaperCard = (UICardSimpleControl)paraArray[0];
		bool isSuccess = paraArray.Length > 1 && paraArray[1] is bool ? (bool)paraArray[1] : false;
		GrimReaperTakeDamage(grimReaperCard, isSuccess);
	}

	private void ClearGrimReaperData()
	{
		m_YGrimReaperList.Clear();
		m_RealGrimReaperEnvIndex = -1;
	}

	void StealCoin(object[] paraArray)
	{
		YStealMoney stealMoneyEffect = (YStealMoney)paraArray[0];
		int amount = (int)paraArray[1];
		m_DataJoeyPlayer.Coin -= amount;
		if (m_DataJoeyPlayer.Coin < 0)
		{
			m_DataJoeyPlayer.Coin = 0;
		}
		stealMoneyEffect.AddStolenCoin(amount);
		OnCoinChanged(m_DataJoeyPlayer.Coin);
	}

	void ReturnCoin(object[] paraArray)
	{
		YStealMoney stealMoneyEffect = (YStealMoney)paraArray[0];
		int stolenAmount = stealMoneyEffect.GetStolenCoinAmount();
		if (stolenAmount > 0)
		{
			m_DataJoeyPlayer.Coin += stolenAmount;
			OnCoinChanged(m_DataJoeyPlayer.Coin);
		}
	}

	void OnCoinChange(object[] paraArray)
	{
		int coin = (int)paraArray[0];
		OnCoinChanged(coin);
	}

	void EscapeMonkey(object[] paraArray)
	{
		UICardSimpleControl monkeyCard = (UICardSimpleControl)paraArray[0];
		if (monkeyCard != null && monkeyCard.IsEnv)
		{
			int envIndex = monkeyCard.EnvIndex;
			RemoveEnvCard(envIndex, monkeyCard);
			RemoveCardCts(monkeyCard);
		}
	}

	void SwapEnvCard(object[] paraArray)
	{
		SwapEnvCard();
	}

	void RomeoMonkeyDead(object[] paraArray)
	{
		this.OnRomeoMonkeyDead();
	}

	void JulietMonkeyDead(object[] paraArray)
	{
		this.OnJulietMonkeyDead();
	}

	void UpdateRelic(object[] paraArray)
	{
		RefreshRelicDisplay();
		int relicId = (int)paraArray[0];
		UpdateAllCardsRelic(relicId);
	}

	private void UpdateAllCardsRelic(int relicId)
	{
		foreach (var kvp in m_BagCardDict)
		{
			List<UICardSimpleControl> bagCardList = kvp.Value;
			for (int i = 0; i < bagCardList.Count; i++)
			{
				UICardSimpleControl cardControl = bagCardList[i];
				cardControl.AddRelic(relicId);
			}
		}

		m_FistCardCache.AddRelic(relicId);

		foreach (var kvp in m_EnvCardDict)
		{
			List<UICardSimpleControl> envCardList = kvp.Value;
			for (int i = 0; i < envCardList.Count; i++)
			{
				UICardSimpleControl cardControl = envCardList[i];
				if (cardControl.CardType != ECardType.monster && cardControl.CardType != ECardType.other)
				{
					cardControl.AddRelic(relicId);
				}
			}
		}
	}

	void OnCardPointerEnter(object[] paraArray)
	{
		UICardSimpleControl cardControl = (UICardSimpleControl)paraArray[0];
		if (cardControl == null)
		{
			return;
		}

		bool shouldShow = false;
		if (cardControl.IsEnv)
		{
			UICardSimpleControl lastEnvCard = GetLastEnvCard(cardControl.EnvIndex);
			if (lastEnvCard == cardControl)
			{
				shouldShow = true;
			}
		}
		else
		{
			shouldShow = true;
		}

		if (shouldShow)
		{
			cardControl.ShowCardHoverEffect();
		}
	}

	void PermanentBoostAttack(object[] paraArray)
	{
		UICardSimpleControl cardControl = GetLastBagCard(ECardType.attack);
		if (cardControl != null && cardControl.CardData != null)
		{
			Card cardData = cardControl.CardData;
			cardData.attack += 1;
			cardData.currentAttack += 1;
			cardControl.RefreshCard();
		}
	}

	void PermanentBoostDefence(object[] paraArray)
	{
		UICardSimpleControl cardControl = GetLastBagCard(ECardType.defence);
		if (cardControl != null && cardControl.CardData != null)
		{
			Card cardData = cardControl.CardData;
			cardData.defence += 1;
			cardData.currentDefence += 1;
			cardControl.RefreshCard();
		}
	}

	private void RefreshRelicDisplay()
	{
		int needCount = 0;
		if (m_DataJoeyPlayer != null && m_DataJoeyPlayer.RelicList != null)
		{
			needCount = m_DataJoeyPlayer.RelicList.Count;
		}

		while (m_RelicList.Count < needCount)
		{
			UIRelicControl relicControl = Asset.OpenUI<UIRelicControl>(m_View.RelicContent);
			relicControl.CacheTrans.localScale = Vector3.one;
			relicControl.CacheTrans.localPosition = Vector3.zero;
			relicControl.CacheTrans.localEulerAngles = Vector3.zero;
			m_RelicList.Add(relicControl);
		}

		for (int i = 0; i < m_RelicList.Count; i++)
		{
			if (i < needCount)
			{
				int relicId = m_DataJoeyPlayer.RelicList[i];
				RelicInfo relicInfo = GData.Instance.GetRelicInfo((ERelicType)relicId);
				if (relicInfo != null)
				{
					m_RelicList[i].gameObject.SetActive(true);
					m_RelicList[i].SetGameData(relicInfo);
				}
				else
				{
					m_RelicList[i].gameObject.SetActive(false);
				}
			}
			else
			{
				m_RelicList[i].gameObject.SetActive(false);
			}
		}
	}

	protected override void OnReturn()
	{
		ClearAllCardCts();
		CurrentEffectCard = null;
		m_MoveCardDelayAction.Cancel();
		m_CardActionQueue.Clear();
		base.OnReturn();
	}
}