//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIGrowthWindowView : YBaseView
{
	public Text TxtDesc;
	public Button BtnClose;
	public Button BtnBuy;
	public Text TxtPrice;

	private static Transform FindDeepChild(Transform root, string name)
	{
		if (root == null) return null;
		var stack = new System.Collections.Generic.Stack<Transform>();
		stack.Push(root);
		while (stack.Count > 0)
		{
			var t = stack.Pop();
			if (t != null && t.name == name) return t;
			for (int i = 0; i < t.childCount; i++)
			{
				stack.Push(t.GetChild(i));
			}
		}
		return null;
	}

	private static Text FindText(Transform holder, string name)
	{
		var t = FindDeepChild(holder, name);
		return t != null ? t.GetComponent<Text>() : null;
	}

	private static Button FindButton(Transform holder, string name)
	{
		var t = FindDeepChild(holder, name);
		return t != null ? t.GetComponent<Button>() : null;
	}

	private void BindByIndex(System.Collections.Generic.List<YViewItem> viewItemList)
	{
		TxtDesc = viewItemList[0].Target.GetComponent<Text>();
		BtnClose = viewItemList[1].Target.GetComponent<Button>();
		BtnBuy = viewItemList[2].Target.GetComponent<Button>();
		TxtPrice = viewItemList[3].Target.GetComponent<Text>();
	}

	private void BindByNameFallback(Transform holder)
	{
		// 兜底：prefab 里名字就是 TxtDesc/BtnClose/BtnBuy/TxtPrice
		if (TxtDesc == null) TxtDesc = FindText(holder, "TxtDesc");
		if (BtnClose == null) BtnClose = FindButton(holder, "BtnClose");
		if (BtnBuy == null) BtnBuy = FindButton(holder, "BtnBuy");
		if (TxtPrice == null) TxtPrice = FindText(holder, "TxtPrice");
	}

	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef != null)
		{
			var viewItemList = itemRef.ViewItemList;
			if(viewItemList != null && viewItemList.Count >= 4)
			{
				BindByIndex(viewItemList);
			}
			else
			{
				Debug.LogWarning($"[UIGrowthWindowView] ViewItemList count not enough (need 4). Actual: {(viewItemList == null ? 0 : viewItemList.Count)}. Fallback to Find-by-name.");
			}
		}
		else
		{
			Debug.LogWarning("[UIGrowthWindowView] Missing YViewReference on holder. Fallback to Find-by-name.");
		}

		BindByNameFallback(holder);

		if (TxtPrice == null)
		{
			Debug.LogError("[UIGrowthWindowView] TxtPrice is null (not found by ViewItemList or name).");
		}
	}
}