//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIGrowthView : YBaseView
{
	public RectTransform Btn;
	public RectTransform Btn1;
	public RectTransform Btn2;
	public RectTransform Btn3;
	public RectTransform Btn4;
	public RectTransform Btn5;
	public RectTransform Btn6;
	public RectTransform Btn7;
	public RectTransform Btn8;
	public RectTransform Btn9;
	public RectTransform Btn10;
	public RectTransform Btn11;
	public RectTransform Btn12;
	public RectTransform Btn13;
	public RectTransform Btn14;
	public RectTransform Btn15;
	public RectTransform Btn16;
	public RectTransform Btn17;
	public RectTransform Btn18;
	public RectTransform Btn19;
	public RectTransform Btn20;
	public Button BtnSkip;
	public Text TextCoins;

	private static Transform FindDeepChild(Transform root, string name)
	{
		if (root == null) return null;
		var stack = new System.Collections.Generic.Stack<Transform>();
		stack.Push(root);
		while (stack.Count > 0)
		{
			var t = stack.Pop();
			if (t != null && t.name == name) return t;
			for (int i = 0; i < t.childCount; i++)
			{
				stack.Push(t.GetChild(i));
			}
		}
		return null;
	}

	private static RectTransform FindRect(Transform holder, string name)
	{
		var t = FindDeepChild(holder, name);
		return t != null ? t.GetComponent<RectTransform>() : null;
	}

	private static Button FindButton(Transform holder, string name)
	{
		var t = FindDeepChild(holder, name);
		return t != null ? t.GetComponent<Button>() : null;
	}

	private static Text FindText(Transform holder, string name)
	{
		var t = FindDeepChild(holder, name);
		return t != null ? t.GetComponent<Text>() : null;
	}

	private void BindByIndex(System.Collections.Generic.List<YViewItem> viewItemList)
	{
		Btn = viewItemList[0].Target.GetComponent<RectTransform>();
		Btn1 = viewItemList[1].Target.GetComponent<RectTransform>();
		Btn2 = viewItemList[2].Target.GetComponent<RectTransform>();
		Btn3 = viewItemList[3].Target.GetComponent<RectTransform>();
		Btn4 = viewItemList[4].Target.GetComponent<RectTransform>();
		Btn5 = viewItemList[5].Target.GetComponent<RectTransform>();
		Btn6 = viewItemList[6].Target.GetComponent<RectTransform>();
		Btn7 = viewItemList[7].Target.GetComponent<RectTransform>();
		Btn8 = viewItemList[8].Target.GetComponent<RectTransform>();
		Btn9 = viewItemList[9].Target.GetComponent<RectTransform>();
		Btn10 = viewItemList[10].Target.GetComponent<RectTransform>();
		Btn11 = viewItemList[11].Target.GetComponent<RectTransform>();
		Btn12 = viewItemList[12].Target.GetComponent<RectTransform>();
		Btn13 = viewItemList[13].Target.GetComponent<RectTransform>();
		Btn14 = viewItemList[14].Target.GetComponent<RectTransform>();
		Btn15 = viewItemList[15].Target.GetComponent<RectTransform>();
		Btn16 = viewItemList[16].Target.GetComponent<RectTransform>();
		Btn17 = viewItemList[17].Target.GetComponent<RectTransform>();
		Btn18 = viewItemList[18].Target.GetComponent<RectTransform>();
		Btn19 = viewItemList[19].Target.GetComponent<RectTransform>();
		Btn20 = viewItemList[20].Target.GetComponent<RectTransform>();
		BtnSkip = viewItemList[21].Target.GetComponent<Button>();
		TextCoins = viewItemList[22].Target.GetComponent<Text>();
	}

	private void BindByNameFallback(Transform holder)
	{
		if (Btn == null) Btn = FindRect(holder, "Btn");
		if (Btn1 == null) Btn1 = FindRect(holder, "Btn1");
		if (Btn2 == null) Btn2 = FindRect(holder, "Btn2");
		if (Btn3 == null) Btn3 = FindRect(holder, "Btn3");
		if (Btn4 == null) Btn4 = FindRect(holder, "Btn4");
		if (Btn5 == null) Btn5 = FindRect(holder, "Btn5");
		if (Btn6 == null) Btn6 = FindRect(holder, "Btn6");
		if (Btn7 == null) Btn7 = FindRect(holder, "Btn7");
		if (Btn8 == null) Btn8 = FindRect(holder, "Btn8");
		if (Btn9 == null) Btn9 = FindRect(holder, "Btn9");
		if (Btn10 == null) Btn10 = FindRect(holder, "Btn10");
		if (Btn11 == null) Btn11 = FindRect(holder, "Btn11");
		if (Btn12 == null) Btn12 = FindRect(holder, "Btn12");
		if (Btn13 == null) Btn13 = FindRect(holder, "Btn13");
		if (Btn14 == null) Btn14 = FindRect(holder, "Btn14");
		if (Btn15 == null) Btn15 = FindRect(holder, "Btn15");
		if (Btn16 == null) Btn16 = FindRect(holder, "Btn16");
		if (Btn17 == null) Btn17 = FindRect(holder, "Btn17");
		if (Btn18 == null) Btn18 = FindRect(holder, "Btn18");
		if (Btn19 == null) Btn19 = FindRect(holder, "Btn19");
		if (Btn20 == null) Btn20 = FindRect(holder, "Btn20");

		if (BtnSkip == null) BtnSkip = FindButton(holder, "BtnSkip");
		// 你新增的文本，如果 prefab 名字叫 TextCoin/Coins 都做个兼容
		if (TextCoins == null) TextCoins = FindText(holder, "TextCoins");
		if (TextCoins == null) TextCoins = FindText(holder, "TextCoin");
		if (TextCoins == null) TextCoins = FindText(holder, "TxtCoins");
	}

	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if (itemRef != null)
		{
			var viewItemList = itemRef.ViewItemList;
			if (viewItemList != null && viewItemList.Count >= 23)
			{
				BindByIndex(viewItemList);
			}
			else
			{
				Debug.LogWarning($"[UIGrowthView] ViewItemList count not enough (need 23). Actual: {(viewItemList == null ? 0 : viewItemList.Count)}. Fallback to Find-by-name.");
			}
		}
		else
		{
			Debug.LogWarning("[UIGrowthView] Missing YViewReference on holder. Fallback to Find-by-name.");
		}

		BindByNameFallback(holder);
	}
}