//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIGrowthView : YBaseView
{
	public RectTransform Btn;
	public RectTransform Btn1;
	public RectTransform Btn2;
	public RectTransform Btn3;
	public RectTransform Btn4;
	public RectTransform Btn5;
	public RectTransform Btn6;
	public RectTransform Btn7;
	public RectTransform Btn8;
	public RectTransform Btn9;
	public RectTransform Btn10;
	public RectTransform Btn12;
	public RectTransform Btn11;
	public RectTransform Btn13;
	public RectTransform Btn14;
	public RectTransform Btn15;
	public RectTransform Btn16;
	public RectTransform Btn17;
	public RectTransform Btn18;
	public RectTransform Btn19;
	public RectTransform Btn20;
	public Button BtnSkip;
	public ScrollRect Scroll;
	public RectTransform Viewport;
	public RectTransform Content;
	public Text TxtCoin;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		Btn = viewItemList[0].Target.GetComponent<RectTransform>();
		Btn1 = viewItemList[1].Target.GetComponent<RectTransform>();
		Btn2 = viewItemList[2].Target.GetComponent<RectTransform>();
		Btn3 = viewItemList[3].Target.GetComponent<RectTransform>();
		Btn4 = viewItemList[4].Target.GetComponent<RectTransform>();
		Btn5 = viewItemList[5].Target.GetComponent<RectTransform>();
		Btn6 = viewItemList[6].Target.GetComponent<RectTransform>();
		Btn7 = viewItemList[7].Target.GetComponent<RectTransform>();
		Btn8 = viewItemList[8].Target.GetComponent<RectTransform>();
		Btn9 = viewItemList[9].Target.GetComponent<RectTransform>();
		Btn10 = viewItemList[10].Target.GetComponent<RectTransform>();
		Btn12 = viewItemList[11].Target.GetComponent<RectTransform>();
		Btn11 = viewItemList[12].Target.GetComponent<RectTransform>();
		Btn13 = viewItemList[13].Target.GetComponent<RectTransform>();
		Btn14 = viewItemList[14].Target.GetComponent<RectTransform>();
		Btn15 = viewItemList[15].Target.GetComponent<RectTransform>();
		Btn16 = viewItemList[16].Target.GetComponent<RectTransform>();
		Btn17 = viewItemList[17].Target.GetComponent<RectTransform>();
		Btn18 = viewItemList[18].Target.GetComponent<RectTransform>();
		Btn19 = viewItemList[19].Target.GetComponent<RectTransform>();
		Btn20 = viewItemList[20].Target.GetComponent<RectTransform>();
		BtnSkip = viewItemList[21].Target.GetComponent<Button>();
		Scroll = viewItemList[22].Target.GetComponent<ScrollRect>();
		Viewport = viewItemList[23].Target.GetComponent<RectTransform>();
		Content = viewItemList[24].Target.GetComponent<RectTransform>();
		TxtCoin = viewItemList[25].Target.GetComponent<Text>();
	}
}