//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIGrowthWindowView : YBaseView
{
	public Text TxtDesc;
	public Button BtnClose;
	public Button BtnBuy;
	public Text TxtPrice;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		TxtDesc = viewItemList[0].Target.GetComponent<Text>();
		BtnClose = viewItemList[1].Target.GetComponent<Button>();
		BtnBuy = viewItemList[2].Target.GetComponent<Button>();
		TxtPrice = viewItemList[3].Target.GetComponent<Text>();
	}
}