//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIGuideTipView : YBaseView
{
	public GameObject Anim;
	public Text TxtTip;
	public RectTransform TipTrans;
	public RectTransform Left;
	public RectTransform Right;
	public RectTransform Top;
	public RectTransform Down;
	public RectTransform Pos;
	public GameObject Mask;
	public RectTransform CacheTrans;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		Anim = viewItemList[0].Target.gameObject;
		TxtTip = viewItemList[1].Target.GetComponent<Text>();
		TipTrans = viewItemList[1].Target.GetComponent<RectTransform>();
		Left = viewItemList[2].Target.GetComponent<RectTransform>();
		Right = viewItemList[3].Target.GetComponent<RectTransform>();
		Top = viewItemList[4].Target.GetComponent<RectTransform>();
		Down = viewItemList[5].Target.GetComponent<RectTransform>();
		Pos = viewItemList[6].Target.GetComponent<RectTransform>();
		Mask = viewItemList[7].Target.gameObject;
		CacheTrans = viewItemList[8].Target.GetComponent<RectTransform>();
	}
}