//This File Is Auto Generated By Process Control
using UnityEngine;

public class UILobbyControl : YViewControl
{
	private UILobbyView m_View;

	public static EResType GetResType()
	{
		return EResType.UILobby;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UILobbyView>();
		m_View.BtnBuild.onClick.AddListener(OnBtnBuildClick);
		m_View.BtnShop.onClick.AddListener(OnBtnShopClick);
		m_View.BtnGame.onClick.AddListener(OnBtnGameClick);
		m_View.BtnMerge.onClick.AddListener(OnBtnMergeClick);
	}

	void OnBtnBuildClick()
	{
		//Asset.OpenUI<UIBuildControl>(transform);
	}

	void OnBtnShopClick()
	{
	}

	void OnBtnGameClick()
	{
	}

	void OnBtnMergeClick()
	{
	}

	public void SetData()
	{
		;
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}