//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UILobbyView : YBaseView
{
	public Button BtnBuild;
	public Button BtnShop;
	public Button BtnGame;
	public Button BtnMerge;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		BtnBuild = viewItemList[0].Target.GetComponent<Button>();
		BtnShop = viewItemList[1].Target.GetComponent<Button>();
		BtnGame = viewItemList[2].Target.GetComponent<Button>();
		BtnMerge = viewItemList[3].Target.GetComponent<Button>();
	}
}