//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UILobbyView : YBaseView
{
	public Button BtnBuild;
	public Button BtnShop;
	public Button BtnGame;
	public Button BtnMerge;
	public Button BtnCardProgress;
	public Button BtnHardGame;
	public Button BtnSkip;
	public Button BtnGrowth;
	public Button BtnLeft;
	public Button BtnRight;
	public Text TextDiff;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		BtnBuild = viewItemList[0].Target.GetComponent<Button>();
		BtnShop = viewItemList[1].Target.GetComponent<Button>();
		BtnGame = viewItemList[2].Target.GetComponent<Button>();
		BtnMerge = viewItemList[3].Target.GetComponent<Button>();
		BtnCardProgress = viewItemList[4].Target.GetComponent<Button>();
		BtnHardGame = viewItemList[5].Target.GetComponent<Button>();
		BtnSkip = viewItemList[6].Target.GetComponent<Button>();
		BtnGrowth = viewItemList[7].Target.GetComponent<Button>();
		BtnLeft = viewItemList[8].Target.GetComponent<Button>();
		BtnRight = viewItemList[9].Target.GetComponent<Button>();
		TextDiff = viewItemList[10].Target.GetComponent<Text>();
	}
}