//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIPauseView : YBaseView
{
	public Button Resume;
	public Button Restart;
	public Button ReturnToMainMenu;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		Resume = viewItemList[0].Target.GetComponent<Button>();
		Restart = viewItemList[1].Target.GetComponent<Button>();
		ReturnToMainMenu = viewItemList[2].Target.GetComponent<Button>();
	}
}