//This File Is Auto Generated By Process Control
using UnityEngine;

public class UIPauseControl : YViewControl
{
	private UIPauseView m_View;

	public static EResType GetResType()
	{
		return EResType.UIPause;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIPauseView>();
		m_View.Resume.onClick.AddListener(OnResumeClick);
		m_View.Restart.onClick.AddListener(OnRestartClick);
		m_View.ReturnToMainMenu.onClick.AddListener(OnReturnToMainMenuClick);
	}

	void OnResumeClick()
	{
		gameObject.SetActive(false);
	}

	void OnRestartClick()
	{
		JoeyGameControl.Instance.EnterBattleStart();
		gameObject.SetActive(false);
	}

	void OnReturnToMainMenuClick()
	{
		JoeyGameControl.Instance.ReturnToMainMenu();
		gameObject.SetActive(false);
	}

	public void SetData()
	{
		;
	}

	protected override void OnReturn()
	{
		gameObject.SetActive(false);
	}
}