//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIRelicView : YBaseView
{
	public Image ImgRelic;
	public Text TxtName;
	public Button BtnRelic;
	public EventTriggerListener Trigger;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		ImgRelic = viewItemList[0].Target.GetComponent<Image>();
		TxtName = viewItemList[1].Target.GetComponent<Text>();
		BtnRelic = viewItemList[2].Target.GetComponent<Button>();
		Trigger = viewItemList[2].Target.GetComponent<EventTriggerListener>();
	}
}