//This File Is Auto Generated By Process Control
using UnityEngine;

public class UIRelicControl : YViewControl
{
	private UIRelicView m_View;
	private RelicInfo m_RelicInfo;
	public Transform CacheTrans;
	private Vector3 m_OriginalScale;
	private UIDescExtControl m_DescExtControl;

	public RelicInfo RelicData => m_RelicInfo;
	public System.Action<UIRelicControl> SelectClickHandler;
	public Transform ImgRelicTransform => m_View.RelicImage.transform;

	public static EResType GetResType()
	{
		return EResType.UIRelic;
	}

	protected override void OnInit()
	{
		base.OnInit();
		CacheTrans = transform;
		m_View = CreateView<UIRelicView>();
		m_View.BtnRelic.onClick.AddListener(OnBtnRelicClick);

		if (m_View.Trigger != null)
		{
			m_View.Trigger.onEnter = OnPointerEnter;
			m_View.Trigger.onExit = OnPointerExit;
		}
	}

	void OnBtnRelicClick()
	{
		if (SelectClickHandler != null)
		{
			SelectClickHandler(this);
		}
	}

	private void OnPointerEnter(GameObject go, UnityEngine.EventSystems.PointerEventData eventData)
	{
		m_OriginalScale = CacheTrans.localScale;
		CacheTrans.localScale = m_OriginalScale * 1.1f;

		if (m_RelicInfo != null && !string.IsNullOrEmpty(m_RelicInfo.description))
		{
			m_DescExtControl = Asset.OpenUI<UIDescExtControl>(Asset.UIRoot);
			m_DescExtControl.SetData(m_RelicInfo.description);
			RectTransform relicRect = CacheTrans as RectTransform;
			if (relicRect != null)
			{
				m_DescExtControl.SetPositionRelativeTo(relicRect);
			}
		}
	}

	private void OnPointerExit(GameObject go, UnityEngine.EventSystems.PointerEventData eventData)
	{
		CacheTrans.localScale = m_OriginalScale;

		if (m_DescExtControl != null)
		{
			m_DescExtControl.Close();
			m_DescExtControl = null;
		}
	}

	public void SetData(RelicInfo relicInfo)
	{
		m_RelicInfo = relicInfo;
		if (m_RelicInfo != null)
		{
			m_View.RelicImage.sprite = LoadSprite(m_RelicInfo.cardImage);
			m_View.IconImage.sprite = LoadSprite(m_RelicInfo.iconImage);
			m_View.TxtName.text = m_RelicInfo.name;
			m_View.Tombstone.sprite = LoadSprite(m_RelicInfo.tombstoneImage);
		}
	}

	public void SetGameData(RelicInfo relicInfo)
	{
		m_RelicInfo = relicInfo;
		if (m_RelicInfo != null)
		{
			m_View.RelicImage.sprite = LoadSprite(m_RelicInfo.cardImage);
			m_View.IconImage.sprite = LoadSprite(m_RelicInfo.iconImage);
			m_View.CardItem.SetActive(false);
			m_View.TxtName.gameObject.SetActive(false);
		}
	}

	private Sprite LoadSprite(string path)
	{
		return Resources.Load<Sprite>(path);
	}

	public void CleanupDescExt()
	{
		if (m_DescExtControl != null)
		{
			m_DescExtControl.Close();
			m_DescExtControl = null;
		}
	}

	protected override void OnReturn()
	{
		if (m_DescExtControl != null)
		{
			m_DescExtControl.Close();
			m_DescExtControl = null;
		}
		SelectClickHandler = null;
		m_RelicInfo = null;
		base.OnReturn();
	}
}