//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UISelectView : YBaseView
{
	public Button BtnSkip;
	public RectTransform Content;
	public RectTransform ContentRelic;
	public Text TxtCardNum;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		BtnSkip = viewItemList[0].Target.GetComponent<Button>();
		Content = viewItemList[1].Target.GetComponent<RectTransform>();
		ContentRelic = viewItemList[2].Target.GetComponent<RectTransform>();
		TxtCardNum = viewItemList[3].Target.GetComponent<Text>();
	}
}