//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class UISelectControl : YViewControl
{
	private UISelectView m_View;
	private List<UISelectCardControl> m_CardList = new List<UISelectCardControl>();
	private List<Card> m_CurrentSelectCards = new List<Card>();
	private DataJoeyPlayer m_PlayerData;
	private const int SELECT_CARD_COUNT = 3;
	public System.Action OnSelectComplete;

	public static EResType GetResType()
	{
		return EResType.UISelect;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UISelectView>();
		m_View.BtnSkip.onClick.AddListener(OnBtnSkipClick);
		m_PlayerData = DataSystem.Instance.GetDataJoeyPlayer();
	}

	public void SetData()
	{
		GenerateSelectCards();
		RefreshSelectDisplay();
	}

	void OnBtnSkipClick()
	{
		Close();
		if (OnSelectComplete != null)
		{
			OnSelectComplete();
		}
	}

	void GenerateSelectCards()
	{
		m_CurrentSelectCards.Clear();

		List<Card> allCards = GData.Instance.CardDict.Values.ToList();
		List<Card> availableCards = allCards.Where(c =>
		{
			ECardType cardType = c.GetCardType();
			return cardType == ECardType.attack ||
				cardType == ECardType.defence ||
				cardType == ECardType.skill ||
				cardType == ECardType.item;
		}).ToList();

		List<Card> shuffledCards = availableCards.OrderBy(x => Random.value).ToList();

		for (int i = 0; i < SELECT_CARD_COUNT && i < shuffledCards.Count; i++)
		{
			Card card = shuffledCards[i];
			m_CurrentSelectCards.Add(card);
		}
	}

	void RefreshSelectDisplay()
	{
		while (m_CardList.Count < SELECT_CARD_COUNT)
		{
			UISelectCardControl cardControl = Asset.OpenUI<UISelectCardControl>(null);
			cardControl.CacheTrans.SetParent(m_View.Content);
			cardControl.CacheTrans.localScale = Vector3.one;
			cardControl.CacheTrans.localPosition = Vector3.zero;
			cardControl.CacheTrans.localEulerAngles = Vector3.zero;
			m_CardList.Add(cardControl);
		}

		float cardSpacing = 300f;
		float startX = -(SELECT_CARD_COUNT - 1) * cardSpacing * 0.5f;

		for (int i = 0; i < m_CardList.Count; i++)
		{
			UISelectCardControl control = m_CardList[i];
			if (i < m_CurrentSelectCards.Count)
			{
				Card card = m_CurrentSelectCards[i];
				control.gameObject.SetActive(true);
				control.SetData(card);
				control.SelectClickHandler = OnSelectCardClick;

				RectTransform rectTransform = control.CacheTrans as RectTransform;
				if (rectTransform != null)
				{
					rectTransform.localPosition = new Vector3(startX + i * cardSpacing, 0, 0);
				}
			}
			else
			{
				control.gameObject.SetActive(false);
				control.SelectClickHandler = null;
			}
		}
	}

	void OnSelectCardClick(UISelectCardControl cardControl)
	{
		if (cardControl.CardData == null)
		{
			return;
		}

		Card selectedCard = cardControl.CardData;
		Card newCard = DataSystem.Instance.CreateCard(selectedCard.id);
		YActionSystem.Instance.DispatchAction(EActionId.AddCardToBagFromSelect, newCard);

		DataSystem.Instance.SaveDataJoeyPlayer();
		Close();
		if (OnSelectComplete != null)
		{
			OnSelectComplete();
		}
	}

	protected override void OnReturn()
	{
		for (int i = 0; i < m_CardList.Count; i++)
		{
			if (m_CardList[i] != null)
			{
				m_CardList[i].SelectClickHandler = null;
			}
		}
		m_CardList.Clear();
		m_CurrentSelectCards.Clear();
		OnSelectComplete = null;
		base.OnReturn();
	}
}
