//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class UISelectControl : YViewControl
{
	private UISelectView m_View;
	private List<UISelectCardControl> m_CardList = new List<UISelectCardControl>();
	private List<Card> m_CurrentSelectCards = new List<Card>();
	private List<UIRelicControl> m_RelicList = new List<UIRelicControl>();
	private List<RelicInfo> m_CurrentSelectRelics = new List<RelicInfo>();
	private DataJoeyPlayer m_PlayerData;
	private const int SELECT_CARD_COUNT = 3;
	public System.Action OnSelectComplete;
	private StageReward m_CurrentStageReward;

	public static EResType GetResType()
	{
		return EResType.UISelect;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UISelectView>();
		m_View.BtnSkip.onClick.AddListener(OnBtnSkipClick);
		m_PlayerData = DataSystem.Instance.GetDataJoeyPlayer();
	}

	public void SetData()
	{
		m_CurrentStageReward = null;
		GenerateSelectCards();
		RefreshSelectDisplay();
	}

	public void SetData(StageReward stageReward)
	{
		m_CurrentStageReward = stageReward;
		GenerateSelectCards();
		RefreshSelectDisplay();
	}

	void OnBtnSkipClick()
	{
		DataSystem.Instance.AddCoin(10);
		DataSystem.Instance.SaveDataJoeyPlayer();
		Close();
		if (OnSelectComplete != null)
		{
			OnSelectComplete();
		}
	}

	void GenerateSelectCards()
	{
		m_CurrentSelectCards.Clear();

		List<Card> allCards = GData.Instance.CardDict.Values.ToList();
		List<Card> availableCards = allCards.Where(c =>
		{
			ECardType cardType = c.GetCardType();
			return (cardType == ECardType.attack ||
				cardType == ECardType.defence ||
				cardType == ECardType.skill ||
				cardType == ECardType.item) &&
			c.price > 0;

		}).ToList();

		// If stage reward has star rates configured, filter cards by star level
		if (m_CurrentStageReward != null && m_CurrentStageReward.cardStarRates.Count > 0)
		{
			for (int i = 0; i < SELECT_CARD_COUNT; i++)
			{
				int targetStar = m_CurrentStageReward.GetRandomStarLevel();
				List<Card> starFilteredCards = availableCards.Where(c => c.stars == targetStar).ToList();
				
				// If no cards available for this star level, fallback to any available card
				if (starFilteredCards.Count == 0)
				{
					starFilteredCards = availableCards;
				}

				// Remove already selected cards
				starFilteredCards = starFilteredCards.Where(c => !m_CurrentSelectCards.Contains(c)).ToList();
				
				if (starFilteredCards.Count > 0)
				{
					Card selectedCard = starFilteredCards[Random.Range(0, starFilteredCards.Count)];
					m_CurrentSelectCards.Add(selectedCard);
				}
			}
		}
		else
		{
			// Default behavior: random selection without star rate filtering
			List<Card> shuffledCards = availableCards.OrderBy(x => Random.value).ToList();

			for (int i = 0; i < SELECT_CARD_COUNT && i < shuffledCards.Count; i++)
			{
				Card card = shuffledCards[i];
				m_CurrentSelectCards.Add(card);
			}
		}
	}

	void RefreshSelectDisplay()
	{
		while (m_CardList.Count < SELECT_CARD_COUNT)
		{
			UISelectCardControl cardControl = Asset.OpenUI<UISelectCardControl>(m_View.Content);

			m_CardList.Add(cardControl);
		}

		float cardSpacing = 300f;
		float startX = -(SELECT_CARD_COUNT - 1) * cardSpacing * 0.5f;

		for (int i = 0; i < m_CardList.Count; i++)
		{
			UISelectCardControl control = m_CardList[i];
			if (i < m_CurrentSelectCards.Count)
			{
				Card card = m_CurrentSelectCards[i];
				control.gameObject.SetActive(true);
				control.SetData(card);
				control.SelectClickHandler = OnSelectCardClick;

				RectTransform rectTransform = control.CacheTrans as RectTransform;
				if (rectTransform != null)
				{
					rectTransform.localPosition = new Vector3(startX + i * cardSpacing, 0, 0);
				}
			}
			else
			{
				control.gameObject.SetActive(false);
				control.SelectClickHandler = null;
			}
		}
	}

	void OnSelectCardClick(UISelectCardControl cardControl)
	{
		if (cardControl.CardData == null)
		{
			return;
		}

		Card selectedCard = cardControl.CardData;

		if (JoeyGameControl.Instance != null && JoeyGameControl.Instance.GameMode == EGameMode.Env)
		{
			m_PlayerData.AddEnvCardPoolData(selectedCard.id);
			DataSystem.Instance.SaveDataJoeyPlayer();
			YActionSystem.Instance.DispatchAction(EActionId.RefreshCardLimitDebuff);
			Debug.Log($"Env mode: Added card {selectedCard.id} to EnvCardPool");
		}
		else
		{
			Card newCard = DataSystem.Instance.CreateCard(selectedCard.id);
			bool success = DataSystem.Instance.AddCardToDataJoeyPlayer(newCard);
			if (success)
			{
				YActionSystem.Instance.DispatchAction(EActionId.AddCardToBagFromSelect, newCard);
			}
			DataSystem.Instance.SaveDataJoeyPlayer();
		}

		Close();
		if (OnSelectComplete != null)
		{
			OnSelectComplete();
		}
	}

	public void SetRelicData()
	{
		GenerateSelectRelics();
		RefreshRelicDisplay();
	}

	void GenerateSelectRelics()
	{
		m_CurrentSelectRelics.Clear();

		List<RelicInfo> allRelics = GData.Instance.RelicInfoDict.Values.ToList();
		List<RelicInfo> availableRelics = allRelics.Where(r =>
		{
			// Exclude CardLimitDebuff from selection pool
			if (r.id == (int)ERelicType.CardLimitDebuff)
			{
				return false;
			}
			return m_PlayerData != null && m_PlayerData.RelicList != null && !m_PlayerData.RelicList.Contains(r.id);
		}).ToList();

		List<RelicInfo> shuffledRelics = availableRelics.OrderBy(x => Random.value).ToList();

		for (int i = 0; i < SELECT_CARD_COUNT && i < shuffledRelics.Count; i++)
		{
			RelicInfo relic = shuffledRelics[i];
			m_CurrentSelectRelics.Add(relic);
		}
	}

	void RefreshRelicDisplay()
	{
		while (m_RelicList.Count < SELECT_CARD_COUNT)
		{
			UIRelicControl relicControl = Asset.OpenUI<UIRelicControl>(m_View.ContentRelic);

			m_RelicList.Add(relicControl);
		}

		float relicSpacing = 300f;
		float startX = -(SELECT_CARD_COUNT - 1) * relicSpacing * 0.5f;

		for (int i = 0; i < m_RelicList.Count; i++)
		{
			UIRelicControl control = m_RelicList[i];
			if (i < m_CurrentSelectRelics.Count)
			{
				RelicInfo relic = m_CurrentSelectRelics[i];
				control.gameObject.SetActive(true);
				control.SetData(relic);
				control.SelectClickHandler = OnSelectRelicClick;

				RectTransform rectTransform = control.CacheTrans as RectTransform;
				if (rectTransform != null)
				{
					rectTransform.localPosition = new Vector3(startX + i * relicSpacing, 0, 0);
				}
			}
			else
			{
				control.gameObject.SetActive(false);
				control.SelectClickHandler = null;
			}
		}
	}

	void OnSelectRelicClick(UIRelicControl relicControl)
	{
		if (relicControl.RelicData == null)
		{
			return;
		}

		ERelicType relicType = (ERelicType)relicControl.RelicData.id;
		DataSystem.Instance.AddRelic(relicType);

		// 桃遗物效果：增加10生命上限
		if (relicType == ERelicType.Peach)
		{
			DataJoeyPlayer playerData = DataSystem.Instance.GetDataJoeyPlayer();
			playerData.playerMaxHealth += 10;
			// playerData.playerHealth += 10; // 同时增加当前生命值
			YActionSystem.Instance.DispatchAction(EActionId.AppHp, 10);
		}

		// 手牌上限+2
		if (relicType == ERelicType.HandLimitIncrease)
		{
			RoguelikeCharacter characterData = GData.Instance.GetRoguelikeCharacter();
			if (characterData != null)
			{
				characterData.envCardLimit += 2;
				YActionSystem.Instance.DispatchAction(EActionId.RefreshCardLimitDebuff);
			}
		}

		// Boxing Gloves relic: Replace all Bare Hands cards with Boxing Gloves
		if (relicType == ERelicType.BareHandsMaster)
		{
			DataJoeyPlayer playerData = DataSystem.Instance.GetDataJoeyPlayer();
			Card boxingGlovesTemplate = GData.Instance.GetCardConfigById("1019");
			
			// Replace all Bare Hands cards in player's card dictionary
			foreach (var kvp in playerData.SelfCardDict)
			{
				Card card = kvp.Value;
				if (card != null && card.id == "1011")
				{
					// Replace card data while keeping the unique ID
					card.cardImage = boxingGlovesTemplate.cardImage;
					card.cardBackground = boxingGlovesTemplate.cardBackground;
					card.cardName = boxingGlovesTemplate.cardName;
					card.description = boxingGlovesTemplate.description;
					card.id = boxingGlovesTemplate.id;
					card.SetAttack(boxingGlovesTemplate.attack);
					card.effectId = boxingGlovesTemplate.effectId;
				}
			}
		}


		DataSystem.Instance.SaveDataJoeyPlayer();
		YActionSystem.Instance.DispatchAction(EActionId.UpdateRelic, (int)relicType);
		Close();
		if (OnSelectComplete != null)
		{
			OnSelectComplete();
		}
	}

	protected override void OnClose()
	{
		for (int i = 0; i < m_CardList.Count; i++)
		{
			if (m_CardList[i] != null)
			{
				m_CardList[i].SelectClickHandler = null;
				m_CardList[i].CleanupDescExt();
			}
		}
		m_CardList.Clear();
		m_CurrentSelectCards.Clear();

		for (int i = 0; i < m_RelicList.Count; i++)
		{
			if (m_RelicList[i] != null)
			{
				m_RelicList[i].SelectClickHandler = null;
				m_RelicList[i].CleanupDescExt();
			}
		}
		m_RelicList.Clear();
		m_CurrentSelectRelics.Clear();
		base.OnClose();
	}
}
