//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class UISelectControl : YViewControl
{
	private UISelectView m_View;
	private List<UISelectCardControl> m_CardList = new List<UISelectCardControl>();
	private List<Card> m_CurrentSelectCards = new List<Card>();
	private List<UIRelicControl> m_RelicList = new List<UIRelicControl>();
	private List<RelicInfo> m_CurrentSelectRelics = new List<RelicInfo>();
	private DataJoeyPlayer m_PlayerData;
	private const int SELECT_CARD_COUNT = 3;
	public System.Action OnSelectComplete;

	public static EResType GetResType()
	{
		return EResType.UISelect;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UISelectView>();
		m_View.BtnSkip.onClick.AddListener(OnBtnSkipClick);
		m_PlayerData = DataSystem.Instance.GetDataJoeyPlayer();
	}

	public void SetData()
	{
		GenerateSelectCards();
		RefreshSelectDisplay();
	}

	void OnBtnSkipClick()
	{
		Close();
		if (OnSelectComplete != null)
		{
			OnSelectComplete();
		}
	}

	void GenerateSelectCards()
	{
		m_CurrentSelectCards.Clear();

		List<Card> allCards = GData.Instance.CardDict.Values.ToList();
		List<Card> availableCards = allCards.Where(c =>
		{
			ECardType cardType = c.GetCardType();
			return (cardType == ECardType.attack ||
				cardType == ECardType.defence ||
				cardType == ECardType.skill ||
				cardType == ECardType.item) &&
			c.price > 0;

		}).ToList();

		List<Card> shuffledCards = availableCards.OrderBy(x => Random.value).ToList();

		for (int i = 0; i < SELECT_CARD_COUNT && i < shuffledCards.Count; i++)
		{
			Card card = shuffledCards[i];
			m_CurrentSelectCards.Add(card);
		}
	}

	void RefreshSelectDisplay()
	{
		while (m_CardList.Count < SELECT_CARD_COUNT)
		{
			UISelectCardControl cardControl = Asset.OpenUI<UISelectCardControl>(m_View.Content);

			m_CardList.Add(cardControl);
		}

		float cardSpacing = 300f;
		float startX = -(SELECT_CARD_COUNT - 1) * cardSpacing * 0.5f;

		for (int i = 0; i < m_CardList.Count; i++)
		{
			UISelectCardControl control = m_CardList[i];
			if (i < m_CurrentSelectCards.Count)
			{
				Card card = m_CurrentSelectCards[i];
				control.gameObject.SetActive(true);
				control.SetData(card);
				control.SelectClickHandler = OnSelectCardClick;

				RectTransform rectTransform = control.CacheTrans as RectTransform;
				if (rectTransform != null)
				{
					rectTransform.localPosition = new Vector3(startX + i * cardSpacing, 0, 0);
				}
			}
			else
			{
				control.gameObject.SetActive(false);
				control.SelectClickHandler = null;
			}
		}
	}

	void OnSelectCardClick(UISelectCardControl cardControl)
	{
		if (cardControl.CardData == null)
		{
			return;
		}

		Card selectedCard = cardControl.CardData;
		Card newCard = DataSystem.Instance.CreateCard(selectedCard.id);
		bool success = DataSystem.Instance.AddCardToDataJoeyPlayer(newCard);
		if (success)
		{
			YActionSystem.Instance.DispatchAction(EActionId.AddCardToBagFromSelect, newCard);
		}

		DataSystem.Instance.SaveDataJoeyPlayer();
		Close();
		if (OnSelectComplete != null)
		{
			OnSelectComplete();
		}
	}

	public void SetRelicData()
	{
		GenerateSelectRelics();
		RefreshRelicDisplay();
	}

	void GenerateSelectRelics()
	{
		m_CurrentSelectRelics.Clear();

		List<RelicInfo> allRelics = GData.Instance.RelicInfoDict.Values.ToList();
		List<RelicInfo> shuffledRelics = allRelics.OrderBy(x => Random.value).ToList();

		for (int i = 0; i < SELECT_CARD_COUNT && i < shuffledRelics.Count; i++)
		{
			RelicInfo relic = shuffledRelics[i];
			m_CurrentSelectRelics.Add(relic);
		}
	}

	void RefreshRelicDisplay()
	{
		while (m_RelicList.Count < SELECT_CARD_COUNT)
		{
			UIRelicControl relicControl = Asset.OpenUI<UIRelicControl>(m_View.ContentRelic);

			m_RelicList.Add(relicControl);
		}

		float relicSpacing = 300f;
		float startX = -(SELECT_CARD_COUNT - 1) * relicSpacing * 0.5f;

		for (int i = 0; i < m_RelicList.Count; i++)
		{
			UIRelicControl control = m_RelicList[i];
			if (i < m_CurrentSelectRelics.Count)
			{
				RelicInfo relic = m_CurrentSelectRelics[i];
				control.gameObject.SetActive(true);
				control.SetData(relic);
				control.SelectClickHandler = OnSelectRelicClick;

				RectTransform rectTransform = control.CacheTrans as RectTransform;
				if (rectTransform != null)
				{
					rectTransform.localPosition = new Vector3(startX + i * relicSpacing, 0, 0);
				}
			}
			else
			{
				control.gameObject.SetActive(false);
				control.SelectClickHandler = null;
			}
		}
	}

	void OnSelectRelicClick(UIRelicControl relicControl)
	{
		if (relicControl.RelicData == null)
		{
			return;
		}

		ERelicType relicType = (ERelicType)relicControl.RelicData.id;
		DataSystem.Instance.AddRelic(relicType);
		DataSystem.Instance.SaveDataJoeyPlayer();
		YActionSystem.Instance.DispatchAction(EActionId.UpdateRelic, (int)relicType);
		Close();
		if (OnSelectComplete != null)
		{
			OnSelectComplete();
		}
	}

	protected override void OnClose()
	{
		for (int i = 0; i < m_CardList.Count; i++)
		{
			if (m_CardList[i] != null)
			{
				m_CardList[i].SelectClickHandler = null;
				m_CardList[i].CleanupDescExt();
			}
		}
		m_CardList.Clear();
		m_CurrentSelectCards.Clear();

		for (int i = 0; i < m_RelicList.Count; i++)
		{
			if (m_RelicList[i] != null)
			{
				m_RelicList[i].SelectClickHandler = null;
				m_RelicList[i].CleanupDescExt();
			}
		}
		m_RelicList.Clear();
		m_CurrentSelectRelics.Clear();
		base.OnClose();
	}
}
