//This File Is Auto Generated By Process Control
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class UIShopControl : YViewControl
{
	private UIShopView m_View;
	private List<UIShopCardControl> m_ShopCardList = new List<UIShopCardControl>();
	private List<ShopCardData> m_CurrentShopCards = new List<ShopCardData>();
	private DataJoeyPlayer m_PlayerData;
	private int m_RefreshCost = 50;

	// Shop card data structure
	private class ShopCardData
	{
		public Card card;
		public int shopPrice; // Discounted price in shop
		
		public ShopCardData(Card card, int shopPrice)
		{
			this.card = card;
			this.shopPrice = shopPrice;
		}
	}

	public static EResType GetResType()
	{
		return EResType.UIShop;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIShopView>();
		m_View.Control.onClick.AddListener(OnControlClick);
		m_View.BtnClose.onClick.AddListener(OnBtnCloseClick);
		m_View.BtnBuy.onClick.AddListener(OnBtnBuyClick);
		m_View.BtnSale.onClick.AddListener(OnBtnSaleClick);
		m_View.BtnRefresh.onClick.AddListener(OnBtnRefreshClick);
		m_PlayerData = DataSystem.Instance.GetDataJoeyPlayer();
	}

	void OnControlClick()
	{
		Close();
	}

	void OnBtnCloseClick()
	{
		Close();
	}

	void OnBtnBuyClick()
	{
		// Not used, cards are bought by clicking on them
	}

	void OnBtnSaleClick()
	{
		// Sale logic not implemented
	}

	void OnBtnRefreshClick()
	{
		// Check refresh cost
		if (m_PlayerData.Coin < m_RefreshCost)
		{
			Debug.Log("金币不足，无法刷新！需要 " + m_RefreshCost + " 金币");
			return;
		}

		// Deduct refresh cost
		m_PlayerData.Coin -= m_RefreshCost;
		
		// Regenerate shop cards
		GenerateShopCards();
		RefreshShopDisplay();
		
		// Save data
		DataSystem.Instance.SaveDataJoeyPlayer();
	}

	public void SetData()
	{
		GenerateShopCards();
		RefreshShopDisplay();
	}

	// Generate shop cards with random discount (1折 to 10折, i.e., 10% to 100%)
	void GenerateShopCards()
	{
		m_CurrentShopCards.Clear();
		
		// Ensure card data is loaded
		GData.Instance.LoadCards();
		
		// Get all purchasable cards (filter out monster cards, only sell player-usable cards)
		var allCards = GData.Instance.CardDict.Values.ToList();
		var availableCards = allCards.Where(c => 
			(c.type == "attack" || 
			 c.type == "defence" || 
			 c.type == "skill" || 
			 c.type == "item") &&
			c.price > 0 // Must have price to sell
		).ToList();
		
		// Randomly select 8 cards
		int shopCardCount = 8;
		var shuffledCards = availableCards.OrderBy(x => Random.value).ToList();
		
		for (int i = 0; i < shopCardCount && i < shuffledCards.Count; i++)
		{
			Card card = shuffledCards[i];
			
			// Calculate discount price: 1折 to 10折 (10% to 100%)
			// Random.Range(1, 11) generates integer from 1 to 10
			int discount = Random.Range(1, 11); // 1-10折
			int shopPrice = Mathf.RoundToInt(card.price * discount / 10f);
			
			// Ensure price is at least 1
			if (shopPrice < 1)
			{
				shopPrice = 1;
			}
			
			m_CurrentShopCards.Add(new ShopCardData(card, shopPrice));
		}
	}

	// Refresh shop display
	void RefreshShopDisplay()
	{
		// Ensure enough card controls
		while (m_ShopCardList.Count < m_CurrentShopCards.Count)
		{
			UIShopCardControl cardControl = Asset.OpenUI<UIShopCardControl>(null);
			cardControl.CacheTrans.SetParent(m_View.Content);
			cardControl.CacheTrans.localScale = Vector3.one;
			cardControl.CacheTrans.localPosition = Vector3.zero;
			cardControl.CacheTrans.localEulerAngles = Vector3.zero;
			m_ShopCardList.Add(cardControl);
		}
		
		// Update card display
		for (int i = 0; i < m_ShopCardList.Count; i++)
		{
			var control = m_ShopCardList[i];
			if (i < m_CurrentShopCards.Count)
			{
				ShopCardData shopCardData = m_CurrentShopCards[i];
				control.gameObject.SetActive(true);
				control.SetData(shopCardData.card, shopCardData.shopPrice);
				control.ShopClickHandler = OnShopCardClick;
			}
			else
			{
				control.gameObject.SetActive(false);
				control.ShopClickHandler = null;
			}
		}
	}

	// Click shop card to buy
	void OnShopCardClick(UIShopCardControl cardControl)
	{
		// Find corresponding shop card data
		ShopCardData shopCardData = null;
		foreach (var data in m_CurrentShopCards)
		{
			if (data.card.id == cardControl.CardData.id)
			{
				shopCardData = data;
				break;
			}
		}
		
		if (shopCardData == null)
		{
			Debug.LogWarning("找不到对应的商店卡牌数据！");
			return;
		}
		
		int price = shopCardData.shopPrice;
		
		// Check if player has enough coins
		if (m_PlayerData.Coin < price)
		{
			Debug.Log("金币不足！需要 " + price + " 金币，当前只有 " + m_PlayerData.Coin + " 金币");
			return;
		}
		
		// Deduct coins
		m_PlayerData.Coin -= price;
		
		// Create card instance and add to player's card library
		Card newCard = DataSystem.Instance.CreateCard(shopCardData.card.id);
		m_PlayerData.AddSelfCardDictData(newCard);
		
		// Remove card from shop
		m_CurrentShopCards.Remove(shopCardData);
		
		// Save data
		DataSystem.Instance.SaveDataJoeyPlayer();
		
		// Refresh display
		RefreshShopDisplay();
		
		Debug.Log("购买成功！花费 " + price + " 金币购买了 " + newCard.cardName);
	}

	protected override void OnReturn()
	{
		// Clear card control list
		m_ShopCardList.Clear();
		m_CurrentShopCards.Clear();
		base.OnReturn();
	}
}