//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIShopView : YBaseView
{
	public Button Control;
	public RectTransform Content;
	public Button BtnRefresh;
	public Text TxtCoin;
	public Button BtnClose;
	public RectTransform BuildRoot;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		Control = viewItemList[0].Target.GetComponent<Button>();
		Content = viewItemList[1].Target.GetComponent<RectTransform>();
		BtnRefresh = viewItemList[2].Target.GetComponent<Button>();
		TxtCoin = viewItemList[3].Target.GetComponent<Text>();
		BtnClose = viewItemList[4].Target.GetComponent<Button>();
		BuildRoot = viewItemList[5].Target.GetComponent<RectTransform>();
	}
}