//This File Is Auto Generated By Process Control
using UnityEngine;

public class UIShopControl : YViewControl
{
	private UIShopView m_View;

	public static EResType GetResType()
	{
		return EResType.UIShop;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIShopView>();
		m_View.Control.onClick.AddListener(OnControlClick);
		m_View.BtnClose.onClick.AddListener(OnBtnCloseClick);
		m_View.BtnBuy.onClick.AddListener(OnBtnBuyClick);
		m_View.BtnSale.onClick.AddListener(OnBtnSaleClick);
		m_View.BtnRefresh.onClick.AddListener(OnBtnRefreshClick);
	}

	void OnControlClick()
	{
	}

	void OnBtnCloseClick()
	{
	}

	void OnBtnBuyClick()
	{
	}

	void OnBtnSaleClick()
	{
	}

	void OnBtnRefreshClick()
	{
	}

	public void SetData()
	{
		;
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}