//This File Is Auto Generated By Process Control
using UnityEngine;

public class UIStartControl : YViewControl
{
	private UIStartView m_View;

	public static EResType GetResType()
	{
		return EResType.UIStart;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIStartView>();
		m_View.BtnStart.onClick.AddListener(OnBtnStartClick);
		m_View.BtnRoguelike.onClick.AddListener(OnBtnRoguelikeClick);
	}

	void OnBtnStartClick()
	{
		SceneLoader.Instance.LoadScene("battle");
	}

	void OnBtnRoguelikeClick()
	{
	}

	public void SetData()
	{
		;
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}