//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIStartView : YBaseView
{
	public Button BtnEnv;
	public EventTriggerListener EnvTrigger;
	public Button BtnOver;
	public EventTriggerListener OverTrigger;
	public Button BtnGuide;
	public EventTriggerListener GuideTrigger;
	public Button BtnStart;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		BtnEnv = viewItemList[0].Target.GetComponent<Button>();
		EnvTrigger = viewItemList[0].Target.GetComponent<EventTriggerListener>();
		BtnOver = viewItemList[1].Target.GetComponent<Button>();
		OverTrigger = viewItemList[1].Target.GetComponent<EventTriggerListener>();
		BtnGuide = viewItemList[2].Target.GetComponent<Button>();
		GuideTrigger = viewItemList[2].Target.GetComponent<EventTriggerListener>();
		BtnStart = viewItemList[3].Target.GetComponent<Button>();
	}
}