//This File Is Auto Generated By Process Control
using UnityEngine;
using Cysharp.Threading.Tasks;

public enum ESceneName
{
	AStar,
	Battle,
	BattleEnv,
	BattleGuide,
	BattleTest,
	BuildNew,
	main,
	main2,
	SceneTest,
	Start,
	Upper
}

public class UIStartControl : YViewControl
{
	private UIStartView m_View;
	private float m_ShakeTimer = 0f;
	private const float SHAKE_INTERVAL = 2f;

	public static EResType GetResType()
	{
		return EResType.UIStart;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIStartView>();
		m_View.BtnStart.onClick.AddListener(OnBtnStartClick);
		m_View.BtnRoguelike.onClick.AddListener(OnBtnRoguelikeClick);
		m_View.BtnGuide.onClick.AddListener(OnBtnGuideClick);
		m_View.BtnOver.onClick.AddListener(OnBtnOverClick);
	}

	private void Update()
	{
		if (DataSystem.Instance.isFinishGame)
		{
			m_ShakeTimer += Time.deltaTime;
			if (m_ShakeTimer >= SHAKE_INTERVAL)
			{
				m_ShakeTimer = 0f;
				ShakeTransform().Forget();
			}
		}
	}

	private async UniTaskVoid ShakeTransform()
	{
		RectTransform rectTransform = transform as RectTransform;
		Vector2 originalPosition = rectTransform.anchoredPosition;
		float duration = 0.2f;
		float intensity = 20f;
		float elapsed = 0f;

		while (elapsed < duration)
		{
			float progress = elapsed / duration;
			float currentIntensity = intensity * (1f - progress);
			Vector2 randomOffset = Random.insideUnitCircle * currentIntensity;
			rectTransform.anchoredPosition = originalPosition + randomOffset;

			elapsed += Time.deltaTime;
			await UniTask.Yield();
		}

		rectTransform.anchoredPosition = originalPosition;
	}

	void OnBtnStartClick()
	{
		ClearPlayerData();
		SceneLoader.Instance.LoadScene(ESceneName.Battle.ToString());
	}

	void OnBtnRoguelikeClick()
	{
		ClearPlayerData();
		SceneLoader.Instance.LoadScene(ESceneName.BattleEnv.ToString());
	}

	void OnBtnGuideClick()
	{
		ClearPlayerData();
		SceneLoader.Instance.LoadScene(ESceneName.BattleGuide.ToString());
	}

	void OnBtnOverClick()
	{
		Application.Quit();
#if UNITY_EDITOR
		UnityEditor.EditorApplication.isPlaying = false;
#endif
	}

	private void ClearPlayerData()
	{
		DataSystem.Instance.ResetDataJoeyPlayer();
	}

	public void SetData()
	{
		;
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}