//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIStartView : YBaseView
{
	public Button BtnRoguelike;
	public Button BtnOver;
	public Button BtnGuide;
	public Button BtnStart;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		BtnRoguelike = viewItemList[0].Target.GetComponent<Button>();
		BtnOver = viewItemList[1].Target.GetComponent<Button>();
		BtnGuide = viewItemList[2].Target.GetComponent<Button>();
		BtnStart = viewItemList[3].Target.GetComponent<Button>();
	}
}