//This File Is Auto Generated By Process Config
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

public class DataJoeyPlayer : IData
{
	public int lastPlayerHealth;
	public int playerHealth;
	public int playerMaxHealth;
	public int playerAttack;
	public int playerDefence;
	public int currentLevel;
	public int Coin;
	public List<int> RelicList = new List<int>();
	public Dictionary<int, Card> SelfCardDict = new Dictionary<int, Card>();
	public List<int> BuildList = new List<int>();
	public int UniqueIdGen;
	public List<int> EquipedAttackList = new List<int>();
	public List<int> EquipedDefenceList = new List<int>();
	public List<int> EquipedItemList = new List<int>();
	public List<int> EquipedSkillList = new List<int>();
	public void LoadFromJson(JObject jobject)
	{
		lastPlayerHealth = (int)jobject["lastPlayerHealth"];
		playerHealth = (int)jobject["playerHealth"];
		playerMaxHealth = (int)jobject["playerMaxHealth"];
		playerAttack = (int)jobject["playerAttack"];
		playerDefence = (int)jobject["playerDefence"];
		currentLevel = (int)jobject["currentLevel"];
		Coin = (int)jobject["Coin"];
		JsonUtil.ToList(jobject, "RelicList", ref RelicList);
		var SelfCardList = new List<Card>();
		JsonUtil.ToList(jobject, "SelfCardList", ref SelfCardList);
		foreach (var item in SelfCardList)
		{
			SelfCardDict[item.UniqueId] = item;
		}
		JsonUtil.ToList(jobject, "BuildList", ref BuildList);
		UniqueIdGen = (int)jobject["UniqueIdGen"];
		JsonUtil.ToList(jobject, "EquipedAttackList", ref EquipedAttackList);
		JsonUtil.ToList(jobject, "EquipedDefenceList", ref EquipedDefenceList);
		JsonUtil.ToList(jobject, "EquipedItemList", ref EquipedItemList);
		JsonUtil.ToList(jobject, "EquipedSkillList", ref EquipedSkillList);
	}
	public void SaveToJson(JObject jobject)
	{
		jobject.Add("lastPlayerHealth", lastPlayerHealth);
		jobject.Add("playerHealth", playerHealth);
		jobject.Add("playerMaxHealth", playerMaxHealth);
		jobject.Add("playerAttack", playerAttack);
		jobject.Add("playerDefence", playerDefence);
		jobject.Add("currentLevel", currentLevel);
		jobject.Add("Coin", Coin);
		jobject.Add("RelicList", JsonUtil.ToJArray(RelicList));
		var SelfCardList = SelfCardDict.Values.ToList();
		jobject.Add("SelfCardList", JsonUtil.ToJArray(SelfCardList));
		jobject.Add("BuildList", JsonUtil.ToJArray(BuildList));
		jobject.Add("UniqueIdGen", UniqueIdGen);
		jobject.Add("EquipedAttackList", JsonUtil.ToJArray(EquipedAttackList));
		jobject.Add("EquipedDefenceList", JsonUtil.ToJArray(EquipedDefenceList));
		jobject.Add("EquipedItemList", JsonUtil.ToJArray(EquipedItemList));
		jobject.Add("EquipedSkillList", JsonUtil.ToJArray(EquipedSkillList));
	}
	public void AddRelicListData(int data)
	{
		RelicList.Add(data);
	}
	public void RemoveRelicListData(int data)
	{
		RelicList.Remove(data);
	}
	public int GetRelicListData(int dataIndex)
	{
		return RelicList[dataIndex];
	}
	public void AddSelfCardDictData(Card item)
	{
		SelfCardDict[item.UniqueId] = item;
	}
	public void RemoveSelfCardDictData(int dataId)
	{
		SelfCardDict.Remove(dataId);
	}
	public Card GetSelfCardDictData(int dataId)
	{
		Card result = null;
		SelfCardDict.TryGetValue(dataId, out result);
		return result;
	}
	public void AddBuildListData(int data)
	{
		BuildList.Add(data);
	}
	public void RemoveBuildListData(int data)
	{
		BuildList.Remove(data);
	}
	public int GetBuildListData(int dataIndex)
	{
		return BuildList[dataIndex];
	}
	public void AddEquipedAttackListData(int data)
	{
		EquipedAttackList.Add(data);
	}
	public void RemoveEquipedAttackListData(int data)
	{
		EquipedAttackList.Remove(data);
	}
	public int GetEquipedAttackListData(int dataIndex)
	{
		return EquipedAttackList[dataIndex];
	}
	public void AddEquipedDefenceListData(int data)
	{
		EquipedDefenceList.Add(data);
	}
	public void RemoveEquipedDefenceListData(int data)
	{
		EquipedDefenceList.Remove(data);
	}
	public int GetEquipedDefenceListData(int dataIndex)
	{
		return EquipedDefenceList[dataIndex];
	}
	public void AddEquipedItemListData(int data)
	{
		EquipedItemList.Add(data);
	}
	public void RemoveEquipedItemListData(int data)
	{
		EquipedItemList.Remove(data);
	}
	public int GetEquipedItemListData(int dataIndex)
	{
		return EquipedItemList[dataIndex];
	}
	public void AddEquipedSkillListData(int data)
	{
		EquipedSkillList.Add(data);
	}
	public void RemoveEquipedSkillListData(int data)
	{
		EquipedSkillList.Remove(data);
	}
	public int GetEquipedSkillListData(int dataIndex)
	{
		return EquipedSkillList[dataIndex];
	}
}
public partial class DataSystem
{
	DataJoeyPlayer m_DataJoeyPlayer;

	public DataJoeyPlayer GetDataJoeyPlayer()
	{
		if (m_DataJoeyPlayer == null)
		{
			m_DataJoeyPlayer = new DataJoeyPlayer();
		}
		return m_DataJoeyPlayer;
	}

	public void SaveDataJoeyPlayer()
	{
		SaveJsonFile("Data_JoeyPlayer", m_DataJoeyPlayer);
	}
	public void LoadDataJoeyPlayer()
	{
		LoadJsonFile("Data_JoeyPlayer", ref m_DataJoeyPlayer);
	}
}