//This File Is Auto Generated By Process Config
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

public class DataCardProgress : IData
{
	public Dictionary<string, int> CardIdDict = new Dictionary<string, int>();
	public void LoadFromJson(JObject jobject)
	{
		var CardIdKey = new List<string>();
		JsonUtil.ToList(jobject, "CardIdKey", ref CardIdKey);
		var CardIdValue = new List<int>();
		JsonUtil.ToList(jobject, "CardIdValue", ref CardIdValue);
		for(int i = 0; i < CardIdKey.Count; i++)
		{
			CardIdDict[CardIdKey[i]] = CardIdValue[i];
		}
	}
	public void SaveToJson(JObject jobject)
	{
		var CardIdKey = CardIdDict.Keys.ToList();
		jobject.Add("CardIdKey", JsonUtil.ToJArray(CardIdKey));
		var CardIdValue = CardIdDict.Values.ToList();
		jobject.Add("CardIdValue", JsonUtil.ToJArray(CardIdValue));
	}
	public void AddCardIdDictData(string dataKey, int value)
	{
		CardIdDict[dataKey] = GetCardIdDictData(dataKey) + value;
	}
	public void RemoveCardIdDictData(string dataKey)
	{
		CardIdDict.Remove(dataKey);
	}
	public int GetCardIdDictData(string dataKey)
	{
		int result = 0;
		CardIdDict.TryGetValue(dataKey, out result);
		return result;
	}
}
public partial class DataSystem
{
	DataCardProgress m_DataCardProgress;

	public DataCardProgress GetDataCardProgress()
	{
		if (m_DataCardProgress == null)
		{
			m_DataCardProgress = new DataCardProgress();
		}
		return m_DataCardProgress;
	}

	public void SaveDataCardProgress()
	{
		SaveJsonFile("Data_CardProgress", m_DataCardProgress);
	}
	public void LoadDataCardProgress()
	{
		LoadJsonFile("Data_CardProgress", ref m_DataCardProgress);
	}
}