//This File Is Auto Generated By Process Config
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

public class DataJoeyPlayer : IData
{
	public int lastPlayerHealth;
	public int playerHealth;
	public int playerMaxHealth;
	public int playerAttack;
	public int playerDefence;
	public int currentLevel;
	public int Coin;
	public List<int> RelicList = new List<int>();
	public Dictionary<int, Card> SelfCardDict = new Dictionary<int, Card>();
	public int UniqueIdGen;
	public List<int> EquipedAttackList = new List<int>();
	public List<int> EquipedDefenceList = new List<int>();
	public List<int> EquipedItemList = new List<int>();
	public List<int> EquipedSkillList = new List<int>();
	public List<int> TempAttackList = new List<int>();
	public List<int> TempDefenceList = new List<int>();
	public List<int> TempItemList = new List<int>();
	public List<int> TempSkillList = new List<int>();
	public int MaxEquipedAttackNum;
	public int MaxEquipedDefenceNum;
	public int MaxEquipedItemNum;
	public int MaxEquipedSkillNum;
	public int StageId;
	public int levelRandomSeed;
	public int giftBoxUseCounter;
	public int envRandomSeed;
	public List<string> EnvCardPool = new List<string>();
	public Dictionary<string, Card> EnvCardDict = new Dictionary<string, Card>();
	public void LoadFromJson(JObject jobject)
	{
		lastPlayerHealth = (int)jobject["lastPlayerHealth"];
		playerHealth = (int)jobject["playerHealth"];
		playerMaxHealth = (int)jobject["playerMaxHealth"];
		playerAttack = (int)jobject["playerAttack"];
		playerDefence = (int)jobject["playerDefence"];
		currentLevel = (int)jobject["currentLevel"];
		Coin = (int)jobject["Coin"];
		JsonUtil.ToList(jobject, "RelicList", ref RelicList);
		var SelfCardList = new List<Card>();
		JsonUtil.ToList(jobject, "SelfCardList", ref SelfCardList);
		foreach(var item in SelfCardList)
		{
			SelfCardDict[item.UniqueId] = item;
		}
		UniqueIdGen = (int)jobject["UniqueIdGen"];
		JsonUtil.ToList(jobject, "EquipedAttackList", ref EquipedAttackList);
		JsonUtil.ToList(jobject, "EquipedDefenceList", ref EquipedDefenceList);
		JsonUtil.ToList(jobject, "EquipedItemList", ref EquipedItemList);
		JsonUtil.ToList(jobject, "EquipedSkillList", ref EquipedSkillList);
		JsonUtil.ToList(jobject, "TempAttackList", ref TempAttackList);
		JsonUtil.ToList(jobject, "TempDefenceList", ref TempDefenceList);
		JsonUtil.ToList(jobject, "TempItemList", ref TempItemList);
		JsonUtil.ToList(jobject, "TempSkillList", ref TempSkillList);
		MaxEquipedAttackNum = (int)jobject["MaxEquipedAttackNum"];
		MaxEquipedDefenceNum = (int)jobject["MaxEquipedDefenceNum"];
		MaxEquipedItemNum = (int)jobject["MaxEquipedItemNum"];
		MaxEquipedSkillNum = (int)jobject["MaxEquipedSkillNum"];
		StageId = (int)jobject["StageId"];
		levelRandomSeed = jobject.ContainsKey("levelRandomSeed") ? (int)jobject["levelRandomSeed"] : 0;
		giftBoxUseCounter = jobject.ContainsKey("giftBoxUseCounter") ? (int)jobject["giftBoxUseCounter"] : 0;
		envRandomSeed = jobject.ContainsKey("envRandomSeed") ? (int)jobject["envRandomSeed"] : 0;
		JsonUtil.ToList(jobject, "EnvCardPool", ref EnvCardPool);
		var EnvCardList = new List<Card>();
		JsonUtil.ToList(jobject, "EnvCardList", ref EnvCardList);
		foreach(var item in EnvCardList)
		{
			EnvCardDict[item.id] = item;
		}
	}
	public void SaveToJson(JObject jobject)
	{
		jobject.Add("lastPlayerHealth", lastPlayerHealth);
		jobject.Add("playerHealth", playerHealth);
		jobject.Add("playerMaxHealth", playerMaxHealth);
		jobject.Add("playerAttack", playerAttack);
		jobject.Add("playerDefence", playerDefence);
		jobject.Add("currentLevel", currentLevel);
		jobject.Add("Coin", Coin);
		jobject.Add("RelicList", JsonUtil.ToJArray(RelicList));
		var SelfCardList = SelfCardDict.Values.ToList();
		jobject.Add("SelfCardList", JsonUtil.ToJArray(SelfCardList));
		jobject.Add("UniqueIdGen", UniqueIdGen);
		jobject.Add("EquipedAttackList", JsonUtil.ToJArray(EquipedAttackList));
		jobject.Add("EquipedDefenceList", JsonUtil.ToJArray(EquipedDefenceList));
		jobject.Add("EquipedItemList", JsonUtil.ToJArray(EquipedItemList));
		jobject.Add("EquipedSkillList", JsonUtil.ToJArray(EquipedSkillList));
		jobject.Add("TempAttackList", JsonUtil.ToJArray(TempAttackList));
		jobject.Add("TempDefenceList", JsonUtil.ToJArray(TempDefenceList));
		jobject.Add("TempItemList", JsonUtil.ToJArray(TempItemList));
		jobject.Add("TempSkillList", JsonUtil.ToJArray(TempSkillList));
		jobject.Add("MaxEquipedAttackNum", MaxEquipedAttackNum);
		jobject.Add("MaxEquipedDefenceNum", MaxEquipedDefenceNum);
		jobject.Add("MaxEquipedItemNum", MaxEquipedItemNum);
		jobject.Add("MaxEquipedSkillNum", MaxEquipedSkillNum);
		jobject.Add("StageId", StageId);
		jobject.Add("levelRandomSeed", levelRandomSeed);
		jobject.Add("giftBoxUseCounter", giftBoxUseCounter);
		jobject.Add("envRandomSeed", envRandomSeed);
		jobject.Add("EnvCardPool", JsonUtil.ToJArray(EnvCardPool));
		var EnvCardList = EnvCardDict.Values.ToList();
		jobject.Add("EnvCardList", JsonUtil.ToJArray(EnvCardList));
	}
	public void AddRelicListData(int data)
	{
		RelicList.Add(data);
	}
	public void RemoveRelicListData(int data)
	{
		RelicList.Remove(data);
	}
	public int GetRelicListData(int dataIndex)
	{
		return RelicList[dataIndex];
	}
	public void AddSelfCardDictData(Card item)
	{
		SelfCardDict[item.UniqueId] = item;
	}
	public void RemoveSelfCardDictData(int dataId)
	{
		SelfCardDict.Remove(dataId);
	}
	public Card GetSelfCardDictData(int dataId)
	{
		Card result = null;
		SelfCardDict.TryGetValue(dataId, out result);
		return result;
	}
	public void AddEquipedAttackListData(int data)
	{
		EquipedAttackList.Add(data);
	}
	public void RemoveEquipedAttackListData(int data)
	{
		EquipedAttackList.Remove(data);
	}
	public int GetEquipedAttackListData(int dataIndex)
	{
		return EquipedAttackList[dataIndex];
	}
	public void AddEquipedDefenceListData(int data)
	{
		EquipedDefenceList.Add(data);
	}
	public void RemoveEquipedDefenceListData(int data)
	{
		EquipedDefenceList.Remove(data);
	}
	public int GetEquipedDefenceListData(int dataIndex)
	{
		return EquipedDefenceList[dataIndex];
	}
	public void AddEquipedItemListData(int data)
	{
		EquipedItemList.Add(data);
	}
	public void RemoveEquipedItemListData(int data)
	{
		EquipedItemList.Remove(data);
	}
	public int GetEquipedItemListData(int dataIndex)
	{
		return EquipedItemList[dataIndex];
	}
	public void AddEquipedSkillListData(int data)
	{
		EquipedSkillList.Add(data);
	}
	public void RemoveEquipedSkillListData(int data)
	{
		EquipedSkillList.Remove(data);
	}
	public int GetEquipedSkillListData(int dataIndex)
	{
		return EquipedSkillList[dataIndex];
	}
	public void AddTempAttackListData(int data)
	{
		TempAttackList.Add(data);
	}
	public void RemoveTempAttackListData(int data)
	{
		TempAttackList.Remove(data);
	}
	public int GetTempAttackListData(int dataIndex)
	{
		return TempAttackList[dataIndex];
	}
	public void AddTempDefenceListData(int data)
	{
		TempDefenceList.Add(data);
	}
	public void RemoveTempDefenceListData(int data)
	{
		TempDefenceList.Remove(data);
	}
	public int GetTempDefenceListData(int dataIndex)
	{
		return TempDefenceList[dataIndex];
	}
	public void AddTempItemListData(int data)
	{
		TempItemList.Add(data);
	}
	public void RemoveTempItemListData(int data)
	{
		TempItemList.Remove(data);
	}
	public int GetTempItemListData(int dataIndex)
	{
		return TempItemList[dataIndex];
	}
	public void AddTempSkillListData(int data)
	{
		TempSkillList.Add(data);
	}
	public void RemoveTempSkillListData(int data)
	{
		TempSkillList.Remove(data);
	}
	public int GetTempSkillListData(int dataIndex)
	{
		return TempSkillList[dataIndex];
	}
	public void AddEnvCardPoolData(string data)
	{
		EnvCardPool.Add(data);
	}
	public void RemoveEnvCardPoolData(string data)
	{
		EnvCardPool.Remove(data);
	}
	public string GetEnvCardPoolData(int dataIndex)
	{
		return EnvCardPool[dataIndex];
	}
	public void AddEnvCardDictData(string id,Card item)
	{
		EnvCardDict[id] = item;
	}
	public void RemoveEnvCardDictData(string id)
	{
		EnvCardDict.Remove(id);
	}
	public Card GetEnvCardDictData(string dataId)
	{
		Card result = null;
		EnvCardDict.TryGetValue(dataId, out result);
		return result;
	}
}
public partial class DataSystem
{
	DataJoeyPlayer m_DataJoeyPlayer;

	public DataJoeyPlayer GetDataJoeyPlayer()
	{
		if (m_DataJoeyPlayer == null)
		{
			m_DataJoeyPlayer = new DataJoeyPlayer();
		}
		return m_DataJoeyPlayer;
	}

	public void SaveDataJoeyPlayer()
	{
		SaveJsonFile("Data_JoeyPlayer", m_DataJoeyPlayer);
	}
	public void LoadDataJoeyPlayer()
	{
		LoadJsonFile("Data_JoeyPlayer", ref m_DataJoeyPlayer);
	}
}