//This File Is Auto Generated By Process Config
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

public class DataJoeyPlayer : IData
{
	public int lastPlayerHealth;
	public int playerHealth;
	public int playerMaxHealth;
	public int playerAttack;
	public int playerDefence;
	public int currentLevel;
	public int Coin;
	public List<int> RelicList = new List<int>();
	public Dictionary<int, Card> SelfCardDict = new Dictionary<int, Card>();
	public int UniqueIdGen;
	public void LoadFromJson(JObject jobject)
	{
		lastPlayerHealth = (int)jobject["lastPlayerHealth"];
		playerHealth = (int)jobject["playerHealth"];
		playerMaxHealth = (int)jobject["playerMaxHealth"];
		playerAttack = (int)jobject["playerAttack"];
		playerDefence = (int)jobject["playerDefence"];
		currentLevel = (int)jobject["currentLevel"];
		Coin = (int)jobject["Coin"];
		JsonUtil.ToList(jobject, "BuffRelicList", ref RelicList);
		var SelfCardList = new List<Card>();
		JsonUtil.ToList(jobject, "SelfCardList", ref SelfCardList);
		foreach (var item in SelfCardList)
		{
			SelfCardDict[item.UniqueId] = item;
		}
		UniqueIdGen = (int)jobject["UniqueIdGen"];
	}
	public void SaveToJson(JObject jobject)
	{
		jobject.Add("lastPlayerHealth", lastPlayerHealth);
		jobject.Add("playerHealth", playerHealth);
		jobject.Add("playerMaxHealth", playerMaxHealth);
		jobject.Add("playerAttack", playerAttack);
		jobject.Add("playerDefence", playerDefence);
		jobject.Add("currentLevel", currentLevel);
		jobject.Add("Coin", Coin);
		jobject.Add("BuffRelicList", JsonUtil.ToJArray(RelicList));
		var SelfCardList = SelfCardDict.Values.ToList();
		jobject.Add("SelfCardList", JsonUtil.ToJArray(SelfCardList));
		jobject.Add("UniqueIdGen", UniqueIdGen);
	}
	public void AddRelicListData(int data)
	{
		RelicList.Add(data);
	}
	public void RemoveRelicListData(int data)
	{
		RelicList.Remove(data);
	}
	public int GetRelicListData(int dataIndex)
	{
		return RelicList[dataIndex];
	}
	public void AddSelfCardDictData(Card item)
	{
		SelfCardDict[item.UniqueId] = item;
	}
	public void RemoveSelfCardDictData(int dataId)
	{
		SelfCardDict.Remove(dataId);
	}
	public Card GetSelfCardDictData(int dataId)
	{
		Card result = null;
		SelfCardDict.TryGetValue(dataId, out result);
		return result;
	}
}
public partial class DataSystem
{
	DataJoeyPlayer m_DataJoeyPlayer;

	public DataJoeyPlayer GetDataJoeyPlayer()
	{
		if (m_DataJoeyPlayer == null)
		{
			m_DataJoeyPlayer = new DataJoeyPlayer();
		}
		return m_DataJoeyPlayer;
	}

	public void SaveDataJoeyPlayer()
	{
		SaveJsonFile("Data_JoeyPlayer", m_DataJoeyPlayer);
	}
	public void LoadDataJoeyPlayer()
	{
		LoadJsonFile("Data_JoeyPlayer", ref m_DataJoeyPlayer);
	}
}