//This File Is Auto Generated By Process Config
using Newtonsoft.Json.Linq;

public class DataAchievement : IData
{
	public int MaxDamageNum;
	public int MaxCoinNum;
	public int MaxTakeDamageNum;
	public int DeadNum;
	public int PassGameNum;
	public int KillMonsterNum;
	public int FistUseNum;
	public void LoadFromJson(JObject jobject)
	{
		MaxDamageNum = (int)jobject["MaxDamageNum"];
		MaxCoinNum = (int)jobject["MaxCoinNum"];
		MaxTakeDamageNum = (int)jobject["MaxTakeDamageNum"];
		DeadNum = (int)jobject["DeadNum"];
		PassGameNum = (int)jobject["PassGameNum"];
		KillMonsterNum = (int)jobject["KillMonsterNum"];
		FistUseNum = (int)jobject["FistUseNum"];
	}
	public void SaveToJson(JObject jobject)
	{
		jobject.Add("MaxDamageNum", MaxDamageNum);
		jobject.Add("MaxCoinNum", MaxCoinNum);
		jobject.Add("MaxTakeDamageNum", MaxTakeDamageNum);
		jobject.Add("DeadNum", DeadNum);
		jobject.Add("PassGameNum", PassGameNum);
		jobject.Add("KillMonsterNum", KillMonsterNum);
		jobject.Add("FistUseNum", FistUseNum);
	}
}
public partial class DataSystem
{
	DataAchievement m_DataAchievement;

	public DataAchievement GetDataAchievement()
	{
		if (m_DataAchievement == null)
		{
			m_DataAchievement = new DataAchievement();
		}
		return m_DataAchievement;
	}

	public void SaveDataAchievement()
	{
		SaveJsonFile("Data_Achievement", m_DataAchievement);
	}
	public void LoadDataAchievement()
	{
		LoadJsonFile("Data_Achievement", ref m_DataAchievement);
	}
}